### DISCUSSION TITLE
Using the sub_button function doesn't work.

### DISCUSSION THREAD

**Discussion by ShmilyStar** [Clooos/Bubble-Card#1008] [Questions about config, custom styles and templates]
I want to use the call-service function of sub_button to close the curtain after clicking the button, but it doesn't work. Here is my code. Please help me.

```yaml
type: custom:bubble-card
card_type: button
button_type: slider
scrolling_effect: true
show_icon: true
force_icon: true
show_state: true
show_last_changed: false
show_attribute: true
show_name: true
sub_button:
  - entity: cover.ci_wo_chuang_lian_curtain
    show_name: false
    show_icon: true
    state_background: true
    show_background: true
    icon: mdi:account
    tap_action:
      action: call-service
      service: cover.close_cover
      target:
        entity_id: entity
entity: cover.ci_wo_chuang_lian_curtain
```
