### DISCUSSION TITLE
Horizonal button card not loading images

### DISCUSSION THREAD

**Discussion by Daniel-dev22** [Clooos/Bubble-Card#1017] [Questions about config, custom styles and templates]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

I tried to follow the readme for using background images on a horizontal button. My path is correct I triple checked that and I use the same path for mushroom card images with no issues.

Am I doing something wrong?

**To Reproduce**  

**Expected behavior**  

A background image to appear for each sub button

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: horizontal-buttons-stack
    1_link: "#ansible_traefik_routers"
    1_name: Traefik Routers
    styles: |-
      .bubble-sub-button-1 {
        background-image: url("/local/icons/custom_icons/traefik_proxy.png");
        background-size: cover;
      }
      .bubble-sub-button-2 {
        background-image: url("/local/icons/custom_icons/traefik_proxy.png");
        background-size: cover;
      }
    hide_gradient: true
    2_name: Traefik Entrypoints
    2_link: "#ansible"

```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻

**Comment by MrBearPresident** [comment]
@Daniel-dev22 
Did you already solve this?

**Comment by Daniel-dev22** [comment]
> @Daniel-dev22 
> Did you already solve this?

I did not

**Comment by MrBearPresident** [comment]
This works for me:

![image](https://github.com/user-attachments/assets/1252616c-6efc-438f-8fc7-d868f93abbca)


```
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_link: "#top"
1_icon: no-icon
2_link: "#bottom"
2_icon: no-icon
styles: |-
  .bubble-button .bubble-background-color{
    display: block !important;    
    background-size: cover;   
    width: 50px;
  }

  .bubble-button-1 .bubble-background-color{
    background-image: url("https://community.home-assistant.io/user_avatar/community.home-assistant.io/mrbearpresident/48/585054_2.png") !important;
  }

  .bubble-button-2 .bubble-background-color{
    background-image: url("https://avatars.githubusercontent.com/u/47092714?s=64&v=4") !important;
  }

  .bubble-background{
    display: none !important;
  }

```

---

<sup>If this solves your issue, please mark this as solved and close it.</sup>

**Reply by kev-chun** [reply]
```yaml
type: horizontal-stack
cards:
  - type: custom:bubble-card
    card_type: button
    button_type: name
    show_icon: false
    scrolling_effect: false
    show_name: true
    name: Feeding Time
    tap_action:
      action: navigate
      navigation_path: "#feeding-time"
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#feeding-time"
    styles: |2+
        .bubble-name {
             text-align: center !Important
      }
        * { 
          font-size: 16px !important;
      }

      }

      .highlight .bubble-button-1 .bubble-background-color{ 
        background-image: url("https://community.home-assistant.io/user_avatar/community.home-assistant.io/mrbearpresident/48/585054_2.png") !important;
      }

    icon: ""
    sub_button: []
  - type: custom:bubble-card
    card_type: button
    button_type: name
  - type: custom:bubble-card
    card_type: button
    button_type: name
```



Doesnt seem to work for my code? any iedas?
