### DISCUSSION TITLE
Buttons for light entities greyed out

### DISCUSSION THREAD

**Discussion by jimmy-ly** [Clooos/Bubble-Card#1022] [Questions about config, custom styles and templates] [answered]
Hi, I'm trying to reproduce the buttons in the screenshots in the README but without success. Adding buttons for my lights (switch/slider) results in a button that is always greyed out, regardless of the state or brightness of the light. The button functions as expected, but is missing the styling. This is the case for all of my lights (Hue, Shelly).  What am I missing? Does the theme have to be applied somehow?

Simple example and screenshot:
```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: light.bar_light
show_state: true
slider_live_update: false
```

![image](https://github.com/user-attachments/assets/4db7065d-24fa-4967-ba21-a78096fde514)
