### DISCUSSION TITLE
Issue with using PopUp inside picture-elements

### DISCUSSION THREAD

**Discussion by Menelao147** [Clooos/Bubble-Card#1027] [Questions about config, custom styles and templates]
Hi, I’m opening this topic following a [discussion](https://community.home-assistant.io/t/bubble-card-a-minimalist-card-collection-for-home-assistant-with-a-nice-pop-up-touch/609678/2028?u=menelao) on the Home Assistant community forum.
I’m encountering an issue when using the Bubble Card pop-up feature inside a picture-elements card. The pop-up card needs to be placed inside a vertical-stack, but vertical-stack cannot be used directly within picture-elements. Some users suggest using custom:hui-element, but when I try to add the pop-up inside the hui-element, it seems that Bubble Card stops working.

**Steps to reproduce the issue:**
1. With `vertical-stack`, the pop-up works as expected.
![image](https://github.com/user-attachments/assets/d82eaec4-e283-47fd-a238-27de7791a844)

2.  Using `custom:hui-element`, Bubble Card also works as expected:
![image](https://github.com/user-attachments/assets/08b8949b-b24b-431e-9708-b78ad972c4b4)

3. However, adding the pop-up inside `hui-element` breaks the configuration:
![image](https://github.com/user-attachments/assets/588ea554-c809-4f42-aa2a-74ced8371a18)

**Goal**
I would like to use the Bubble Card pop-up inside a picture-elements card with custom:hui-element as shown below:
```
type: picture-elements
image: /local/Floorplan/Sera.webp
elements:
  - type: custom:mushroom-entity-card
    style:
      left: 60%
      top: 70%
    entity: sensor.wall_connector_assorbimento_kw
    tap_action:
      action: navigate
      navigation_path: "#Test"
    hold_action:
      action: navigate
      navigation_path: "#Test"
    double_tap_action:
      action: navigate
      navigation_path: "#Test"
    icon: tsl:water-percent-absolute
    icon_color: disabled
  - type: custom:hui-element
    card_type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        hash: "#Test"
        button_type: name
        name: TEST1
        icon: mdi:air-conditioner
        scrolling_effect: true
        show_icon: true
        show_name: true
      - type: entities
        entities:
          - light.cottura
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.tesla_battery_level
        card_layout: large
```

**Actual behavior:**
When I click the pop-up, the screen becomes blurred, but nothing is shown in the popup.
Here’s a short video demonstrating the issue:

https://github.com/user-attachments/assets/1b390a72-2ae7-4871-a4bc-bd755af33382
