### DISCUSSION TITLE
Sub Button Icon State Color

### DISCUSSION THREAD

**Discussion by StaleLoafOfBread** [Clooos/Bubble-Card#1037] [Questions about config, custom styles and templates] [answered]
Today we can color the background when the entity is considered `on`. This  makes it a gold/yellow (at least on my theme). I am suggesting a feature where instead it will:

1) color the icon itself, not the background
2) make the color match var(--state-icon-color) for that sub buttons entity 

For my purposes, a singular toggle for `Use state color for icon` would be perfect.
 

I have tried to accomplish this via style to color my phone battery icon but instead it's coloring based on the main person entity. I am not well versed in CSS nor JS so it's perhaps possible this way and I just do not yet know it. 

``` yaml
type: custom:bubble-card
card_type: button
button_type: state
show_attribute: false
sub_button:
  - entity: sensor.phone_battery_level
    show_background: false
    show_attribute: false
    show_state: true
show_state: false
styles: |-

  .bubble-sub-button-1 {
      color: var(--state-icon-color) !important;
  }
entity: person.me
```

This is effectively the `State color` feature of the headings card under appearance for it's entities. 

``` yaml
type: heading
icon: ""
heading_style: title
badges:
  - type: entity
    show_state: true
    show_icon: true
    entity: sensor.phone_battery_level
    color: state
```

Now that I'm comparing the two, I think copying the `appearance` functionality  in whole would be awesome as that adds icon customization and the ability to show multiple attributes, including the state.
