### DISCUSSION TITLE
How can I change both the text AND icon of a sub-button

### DISCUSSION THREAD

**Discussion by Juggler00** [Clooos/Bubble-Card#1049] [Questions about config, custom styles and templates] [answered]
I'd like to be able to change both the icon and text of a sub-button. With the styles section below, the "innerText" part always overrides the "icon" attribute. 

```
type: custom:bubble-card
card_type: button
entity: switch.esphome_web_1111b4_pool_pump
name: Pump
icon: mdi:pump
show_icon: true
sub_button:
  - entity: sensor.esphome_web_1111b4_pool_temperature
    show_state: true
    show_icon: true
    state_background: false
    show_background: false
    name: pool
    show_name: true
  - entity: sensor.co2click_temperature
    name: air
    show_background: false
    show_name: true
    show_state: false
    show_icon: true
    show_attribute: false
    show_last_changed: false
card_layout: large-2-rows
styles: >
  ${card.querySelector('.bubble-sub-button-2').innerText = "Air " +
  parseFloat(hass.states["sensor.co2click_temperature"].state).toFixed(1) + " ºC"}
  ${card.querySelector('.bubble-sub-button-2').icon.setAttribute("icon", 'mdi:alert')}
scrolling_effect: false
show_name: true
```

**Comment by MrBearPresident** [comment, marked as answer]
You have to use `.bubble-sub-button-2 .bubble-sub-button-name-container`



```
type: custom:bubble-card
card_type: button
entity: switch.esphome_web_1111b4_pool_pump
name: Pump
icon: mdi:pump
show_icon: true
sub_button:
  - entity: sensor.esphome_web_1111b4_pool_temperature
    show_state: true
    show_icon: true
    state_background: false
    show_background: false
    name: pool
    show_name: true
  - entity: sensor.co2click_temperature
    name: air
    show_background: false
    show_name: true
    show_state: false
    show_icon: true
    show_attribute: false
    show_last_changed: false
card_layout: large-2-rows
styles: >
  ${card.querySelector('.bubble-sub-button-2 .bubble-sub-button-name-container').innerText = "Air " +
  parseFloat(hass.states["sensor.co2click_temperature"].state).toFixed(1) + " ºC"}
  ${card.querySelector('.bubble-sub-button-2').icon.setAttribute("icon", 'mdi:alert')}
scrolling_effect: false
show_name: true
```

---

<sub>If this solves you question mark this as solved and close the discussion.</sub>
