### DISCUSSION TITLE
Pop up live video feed triggered by motion.

### DISCUSSION THREAD

**Discussion by UserWally** [Clooos/Bubble-Card#1055] [General]
I set up pop up and video entity cards with the pop up triggered by motion. Works fine but as soon as the motion clears the pop up video goes away. Is there any way I can set it to stay open for 30 seconds after motion clears? I have spent hours and tried just about anything I can think of to make it stick around awhile, but no joy. I find it irritating that the window comes and goes so quickly. Any help would be appreciated.

**Comment by michaelroper** [comment]
I do this on my dashboard with an automation that is triggered by my camera motion sensors, which turns on an input boolean helper, waits 30 seconds, and turns it off. I then use that input boolean being true to trigger my camera view popup, so it is open for that 30 seconds after it a camera sees motion...

![image](https://github.com/user-attachments/assets/48961067-46d3-4789-90c3-7f73829c0625)

```
alias: Camera Card Visibility
description: ""
mode: single
triggers:
  - entity_id:
      - binary_sensor.front_cameras_person
      - binary_sensor.front_cameras_vehicle
    to: "on"
    trigger: state
conditions: []
actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.front_cameras_motion
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.front_cameras_motion
```
