### DISCUSSION TITLE
Pop-up card from another "Page" - can't close

### DISCUSSION THREAD

**Discussion by Balooforever** [Clooos/Bubble-Card#1057] [Questions about config, custom styles and templates] [answered]
Hi all,

It's a very specific issue, i use "popup" for create a menu of all of my page (for mobile view).

In all page, i have a "button" who call the popup of my home page.

The bug : if i call the popup of my home page from another page, i can't close it, the "X" doesn't work.

How i can do ?

Thank you! 🍻

**Comment by MrBearPresident** [comment]
Please follow the form. 

On what version are you?
V2.3.0? Or higher?

**Comment by Balooforever** [comment]
2.3.2 :)
I don’t know if i’m clear

**Comment by MrBearPresident** [comment]
Due to some issues identified in the latest releases (v2.3.1, v2.3.2, v2.3.3), I have decided to mark them as pre-release versions. These updates may not be fully stable and could cause unexpected behavior. I strongly recommend rolling back to the latest stable release, v2.3.0, until further notice. This version has been thoroughly tested and provides a reliable experience. Thank you for your understanding and patience as we work to ensure a future updates that meets the highest standards of quality.

Please report back if the issue persist on v2.3.0.

---

- How to rollback
- Click on the integration in HACS.
- Click on the three dots icon top right of the page.
- Select Redownload.
- Choose the version you want from the dropdown list.
- Click Download.

**Comment by Balooforever** [comment]
Sorry, same with 2.3.0. Do you want help for reproduce ?

**Comment by Balooforever** [comment]
For reproduce, in a page, a button who link a popup in another page : 
```
type: custom:bubble-card
card_type: button
entity: switch.prise_seche_linge
show_attribute: false
show_state: false
attribute: friendly_name
sub_button: []
name: RDC
card_layout: large
grid_options:
  columns: 6
  rows: 1
button_action:
  tap_action:
    action: navigate
    navigation_path: /home/#RDC
  hold_action:
    action: toggle
icon: mdi:home-floor-0
button_type: name
tap_action:
  action: navigate
  navigation_path: /home/#RDC
```

Navigation work but i can't close the popup with the "X" or clic in another zone.
