### DISCUSSION TITLE
Alarm / Alarmo turn_off not found...

### DISCUSSION THREAD

**Discussion by jq-yeraz** [Clooos/Bubble-Card#1060] [Questions about config, custom styles and templates]
Cloos your work on bubblecard is amazing. I love this card ! I have a little issue when using Alarmo with a "button" card type and a "switch" button type. When calling the default "toggle" action, I get the following error :

Action alarm_control_panel.turn_off not found

Just another question do you think it's possible to swap between protected area with the current button or do you think you need to create an "alarm" card type instead ?

Jerome

**Comment by MrBearPresident** [comment]
The alarm_control_panel does not have a turn_on/turn_off. ([source](https://www.home-assistant.io/integrations/alarm_control_panel/#actions))
You instead have to use: 

```
tap_action:
  action: call-service
  target:
    entity_id: alarm_control_panel.alarmo
  service: alarm_control_panel.alarm_disarm
```

![image](https://github.com/user-attachments/assets/af28df50-eb93-4306-8081-a1be44434157)

---
<sup>If this solves your problem mark this as the solution and close the discussion. </sup>
