### DISCUSSION TITLE
Popup close_action should allow templating

### DISCUSSION THREAD

**Discussion by svb91** [Clooos/Bubble-Card#1064] [Feature requests]
Hey Cloos,

hope you are doing fine!
I was wondering if it would be possible to use templating in the close_action of the popup card.

I'd like to archive something like this:

```
close_action:
    action: navigate
    navigation_path: >
        [[[ return window.history.back(); ]]]
```

I use my popups in different scenarios and sometimes a popup opens a new one. Therefore a history.back() method would be great to return to the previous popup.

Hope that this could be implemented in your cool tool as well :-)
