### DISCUSSION TITLE
Cover Tilt on button slider

### DISCUSSION THREAD

**Discussion by Morcegolas** [Clooos/Bubble-Card#1072] [Questions about config, custom styles and templates]
Hello, I'm trying to add a cover card, but the default don't have tilt position option, is it possible to use the Button card with Slider type and use the slider to control the tilt_position? I already searched but tilt_position is not an atribute, if anybody can help me I'll be thankful.

**Comment by MrBearPresident** [comment]
So you want the ability to just slide a bit and then it should close completely?

**Comment by Morcegolas** [comment]
As you can see I have two sliders to control my blinds, one for up/down and other to tilt the blinds. I want to use the sub buttons to up/down and the slider to tilt the blinds.

<img width="1005" alt="1" src="https://github.com/user-attachments/assets/ffa7d711-9a23-465e-bea6-6a151e74c04f" />
<img width="1005" alt="2" src="https://github.com/user-attachments/assets/5696a97c-237d-4ad4-b180-5c1a80ef47dd" />
<img width="667" alt="3" src="https://github.com/user-attachments/assets/da1af384-2086-433a-bccc-c3c10082b2af" />

**Comment by MrBearPresident** [comment]
(I don't have covers/blinds let alone blinds with tilt function.)

So you just need the sub-buttons to place on top of your slider card? 
based on my answer here https://github.com/Clooos/Bubble-Card/discussions/1066#discussioncomment-11629963

code for sub-buttons:
```
sub_button:
  - entity: cover.test_cover_cover
    show_icon: true
    icon: mdi:arrow-down
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.test_cover_cover
      service: cover.close_cover
  - entity: cover.test_cover_cover
    icon: mdi:square-outline
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.test_cover_cover
      service: cover.stop_cover
  - entity: cover.test_cover_cover
    icon: mdi:arrow-up
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.test_cover_cover
      service: cover.open_cover
```

---

<sup>If this solves your question, mark this as the solution and close the discussion.</sup>

**Reply by Morcegolas** [reply]
Your sub-buttons work, the problem is that the slider is also controlling the up/down instead of tilt_position, so my slider and sub-buttons are doing the same thing. 

This is my code:

```
type: custom:bubble-card
card_type: button
button_type: slider
name: Janela
entity: cover.quarto_principal_estore_quarto_p_24
icon: mdi:blinds-horizontal
show_last_updated: true
sub_button:
  - entity: cover.quarto_principal_estore_quarto_p_24
    show_icon: true
    icon: mdi:arrow-down
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.quarto_principal_estore_quarto_p_24
      service: cover.close_cover
  - entity: cover.test_cover_cover
    icon: mdi:square-outline
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.quarto_principal_estore_quarto_p_24
      service: cover.stop_cover
  - entity: cover.test_cover_cover
    icon: mdi:arrow-up
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.quarto_principal_estore_quarto_p_24
      service: cover.open_cover
```

This is a script I use to put the blinds in the middle position so light can pass through, where the tilt_position is used:

```
alias: Abrir Persianas Todas
sequence:
  - data:
      tilt_position: 50
    action: cover.set_cover_tilt_position
    target:
      entity_id:
        - cover.escritorio_janela_180
        - cover.quarto_francisca_janela_francisca_172
        - cover.quarto_principal_estore_quarto_p_24
        - cover.sala_portas_sala_varanda_15
        - cover.lavandaria_janela_lavandaria_17
  - data:
      tilt_position: 70
    action: cover.set_cover_tilt_position
    target:
      entity_id:
        - cover.quarto_visitas_janela_q_brinquedos_390
mode: single
description: ""
icon: mdi:blinds-horizontal
```

**Reply by MrBearPresident** [reply]
Can you send me a printscreen of the device page?

**Reply by Morcegolas** [reply]
Sure, on logbook on the right you can see it uses Set position. On the device control sliders I have two, one for up/down, the other for tilt position.

<img width="999" alt="1" src="https://github.com/user-attachments/assets/3091e0b2-03d3-406d-b09e-bf833fd97e59" />
<img width="593" alt="2" src="https://github.com/user-attachments/assets/13fdc719-b8ce-49db-b53a-4a5eb553c9a5" />

**Comment by MrBearPresident** [comment]
I guess we will have to look into this. 

For now you can do this with an input_number helper 

and have an automation like this:

```
alias: New automationdcs
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_number.help_house_testnumbe
conditions: []
actions:
  - data:
      tilt_position:
        "[object Object]": null
    action: cover.set_cover_tilt_position
    target:
      entity_id:
        - cover.quarto_visitas_janela_q_brinquedos_390
mode: single

```
