### DISCUSSION TITLE
Ignore state for button background color

### DISCUSSION THREAD

**Discussion by derousse** [Clooos/Bubble-Card#1080] [Questions about config, custom styles and templates] [answered]
### Goal

How can I make a bubble button NOT change it's background color when the state of the entity changes?  For example, in the following buttons:
![image](https://github.com/user-attachments/assets/673ab21e-ed85-4219-9e32-f109ceb33c0d)

I would like only the icon highlighting to be affected by the state of the entity.

### Source Yaml

```yaml
type: horizontal-stack
cards:
  - type: custom:bubble-card
    card_type: button
    entity: light.lamp1_light
    name: Living Room
    icon: mdi:sofa
    tap_action:
      action: navigate
      navigation_path: "#pop-up-living-room"
    use_accent_color: true
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#pop-up-living-room"
    grid_options:
      columns: 6
      rows: 1
    button_type: switch
    styles: ""
    show_state: false
  - type: custom:bubble-card
    card_type: button
    entity: light.dining_room_lights
    name: Dining Room / Kitchen
    icon: mdi:table-furniture
    tap_action:
      action: navigate
      navigation_path: "#pop-up-dining-room-kitchen"
    use_accent_color: true
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#pop-up-dining-room-kitchen"
    grid_options:
      columns: 6
      rows: 1
    styles: ""
```
