### DISCUSSION TITLE
[Example] Adaptive design between large and large-2-rows layouts

### DISCUSSION THREAD

**Discussion by MrBearPresident** [Clooos/Bubble-Card#1094] [Share your custom styles, templates and dashboards]
![image](https://github.com/user-attachments/assets/8134673c-4d9f-4d4e-a27c-6abd4f4f3762)
![image](https://github.com/user-attachments/assets/a4ca96b9-f70d-433f-ab63-f5cda6d37edf)

Because of #684 I made this example where the design switches between large and large-2-rows layouts. *

```
type: custom:bubble-card
card_type: button
button_type: state
entity: sun.sun
sub_button:
  - entity: sun.sun
  - entity: sun.sun
  - entity: sun.sun
  - entity: sun.sun
grid_options:
  columns: full
styles: "${(() => {if(window.innerWidth < 450){card.classList.add('rows-2')}})()}"
card_layout: large
```
