### DISCUSSION TITLE
[FR] Add a Numeric Input card with "+" and "-" buttons

### DISCUSSION THREAD

**Discussion by Menelao147** [Clooos/Bubble-Card#1103] [Feature requests]
Currently, Bubble Card uses a slider for numeric inputs.
It would be great to have an alternate option that allows you to increment or decrement the value using "+" and "-" buttons, similar to what is available for the climate entities (see below).

![image](https://github.com/user-attachments/assets/44996023-ca10-4bdb-bf77-b77986db0d0e)

Sliders are a useful tool for making quick adjustments, but they can lack precision, particularly on smaller screens.
Adding "+" and "-" buttons would allow users to increase or decrease values with more accuracy, making the interface more usable in scenarios where precision is crucial.

**Comment by Ladida1** [comment]
<img width="392" alt="image" src="https://github.com/user-attachments/assets/cca34b52-8c5b-4f9b-b864-10a2020deeea" />

This is a workaround. It uses a script for +  and - operations.
Side note: Reason for passing the climate entity to to the script is to read the set temperature steps.

```
  - type: custom:bubble-card
    card_type: button
    button_type: state
    entity: input_number.biorum_temperatur_komfort
    sub_button:
      - icon: mdi:minus-thick
        tap_action:
          action: call-service
          target: {}
          service: script.varme_installning_minska
          service_data:
            temperatur_entity_id: input_number.biorum_temperatur_komfort
            climate_entity_id: climate.biorum_element_2
      - entity: input_number.biorum_temperatur_komfort
        show_state: true
        state_background: false
      - icon: mdi:plus-thick
        tap_action:
          action: call-service
          target: {}
          service: script.varme_installning_oka
          service_data:
            temperatur_entity_id: input_number.biorum_temperatur_komfort
            climate_entity_id: climate.biorum_element_2
    name: Komfort

```
