### DISCUSSION TITLE
Select Button | input_boolean(s) ?

### DISCUSSION THREAD

**Discussion by Symbiot78** [Clooos/Bubble-Card#1108] [Questions about config, custom styles and templates]
hi

is it possible to create a select button but with input_booleans.. 
it looks like I can only use input_select and similar.. but not helpers.

am i missing some clever way of doing this?

**Comment by Symbiot78** [comment]
Like - i have an input_select from alarmo which.. when I use it.. gives me a nice drop down of the states I can choose between and when I tap one it is selected.

I'd like the same but with a few input_booleans I have for vacation mode...

If I create a sub-button I can select the input_boolean but I still need to select an entity but there is none.. so to speak.

**Comment by MrBearPresident** [comment]
I think this should be solved with an automation.

**Comment by Symbiot78** [comment]
can you give an example of this?
I'm not quite sure how an automation would solve this?

maybe I am not explaining it properly

but i want a button which is named "home state"
when i click it I want it to show a drop down menu of different states I can select.
these states are all input_booleans.

**Comment by MrBearPresident** [comment]
Yes I recently learned this can also go through a template select helper. 
But I did similar stuff through an automation in the past. 

So what you need to do: 

1. Label all the input Booleans you want to belong to the dropdown to one specific label. _(I chose `TestBooleans`)_
2. Go to Helpers and create a new template helper.
  a. This should be 'Template a select'
3. In the Helper set following values: 

State template 
``` jinja2
{% set activeElements = states.input_boolean 
    | selectattr('state','equalto','on')
    | selectattr('entity_id', 'in', label_entities('TestBooleans'))
    | sort(reverse=true, attribute='last_changed')
    | map(attribute='name')
    | list
%}

{% if activeElements | length == 0 %}
  Off
{% else %}
  {{activeElements|first}}
{% endif %}
```

Available options

``` jinja2
{{(states.input_boolean 
    | selectattr('entity_id', 'in', label_entities('TestBooleans'))
    | map(attribute='name')
    | list
    | sort) + ['Off']
}}
```

Actions on select:

``` yaml
sequence:
  - if:
      - condition: template
        value_template: "{{ option != 'Off' }}"
    then:
      - action: homeassistant.turn_on
        target:
          entity_id: |
            {{
              states.input_boolean      
                | selectattr('name', 'eq', option)
                | map(attribute='entity_id')
                | first
            }}
  - action: homeassistant.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: >-
        {{(states.input_boolean  | selectattr('entity_id', 'in',
        label_entities('TestBooleans'))   | rejectattr('name','match', option) |
        map(attribute='entity_id') | list) }}

```

![Screen Recording 2025-01-11 171853](https://github.com/user-attachments/assets/31aec809-a3ca-477a-b5f4-9ca63b2afa5e)
