### DISCUSSION TITLE
How do I move Name/State to bottom of card to stop it from being covered in my person card?

### DISCUSSION THREAD

**Discussion by StaleLoafOfBread** [Clooos/Bubble-Card#1114] [Questions about config, custom styles and templates]
### Goal

Ultimately I want to create a person card. In that pursuit I have something I am somewhat happy with but on mobile, the main Name/State text gets covered. I am looking for ideas on how to address this. I am open to pretty much any solution that allows the info to still be presented. 

I think my ideal solution would be to lower the text to the bottom of the card, separate all pieces of data with a `•`, and enable scrolling for the text when its longer than the card. 

My person card is very complicated and messy so I made a simple example that shows the issue at hand.

![image](https://github.com/user-attachments/assets/ab675d0f-abbb-4f6e-8bf6-4b59a41ef1b7)

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: binary_sensor.test
name: Long Text To Show
show_last_changed: false
force_icon: true
sub_button:
  - entity: binary_sensor.test
    show_name: true
    show_state: true
    show_attribute: false
    name: aaaaaaaaaaaa
  - entity: binary_sensor.test
    show_name: true
    show_state: true
    show_attribute: false
styles: |+
  .bubble-name-container {
     transform: translateY(40px); 
     width: 100px !important;
  }

  .bubble-button-card-container {
    position: relative;
    height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
  }

rows: 2
show_state: false
show_attribute: true
```

### Which step did you already try?

```yaml
.bubble-name-container {
   transform: translateY(40px); 
   width: 100% !important;
}

.bubble-button-card-container {
  position: relative;
  height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
}
```

### Problem

1. The text is covered by sub buttons
2. The text does not span the entire card

In addition to `translateY` I've tried adding margins or padding. I think maybe new divs need be created? 

I realize with this code the text won't scroll but I believe I solved that issue in https://github.com/Clooos/Bubble-Card/discussions/857#discussioncomment-11731543

### Read the documentation

- [X] I have read the documentation
