### DISCUSSION TITLE
Switch Name and State on an Entity-Card

### DISCUSSION THREAD

**Discussion by darki79** [Clooos/Bubble-Card#1115] [Questions about config, custom styles and templates]
### Goal

Hey,

is it possible - and if yes, how - to change switch the Name and the State on an entity card?

For example, I have many cards displaying temperature and humidity for different rooms:
<img width="240" alt="image" src="https://github.com/user-attachments/assets/f9f468ba-5dc3-4de0-be93-28d692693e39" />

If I could switch both it would be better readable, but I also need the name on the card (no heading etc.).

Thanks!

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.temp_kammer_temperature
name: Kammer
show_state: true
show_attribute: false
show_name: true
card_layout: large
grid_options:
  columns: 6
  rows: 1
show_icon: true
force_icon: false
show_last_changed: false
```

### Read the documentation

- [ ] I have read the documentation

**Comment by MrBearPresident** [comment]
Is it not easier to add following to your custom style: 
![image](https://github.com/user-attachments/assets/daba370d-2301-4942-9092-1e63b600b619)

```css
.bubble-name-container {
  .bubble-name{
    font-size: 12px !important;
    font-weight: normal !important;
    opacity: 0.7 !important;
  }
  .bubble-state{
    font-size: 13px !important;
    font-weight: 600 !important;
    opacity: 1 !important;
  }
}
```
