### DISCUSSION TITLE
Curly braces in templates

### DISCUSSION THREAD

**Discussion by bux** [Clooos/Bubble-Card#1117] [Questions about config, custom styles and templates]
### Goal

I would like to use the Intl.DateTimeFormat function inside a style template.
I'm pretty new to home assistant, bubble card and templates in general.

How does one escape curly braces inside the javascript literal?

### Source Yaml

```yaml
styles: >-
  ${card.querySelector('.bubble-sub-button-1').innerText = new Intl.DateTimeFormat("en-US", {weekday: 'long'}).format(new Date()) }
```

### Which step did you already try?

* Double curly braces `{{ }}`
* trying to escape by using a backslash `\{ \}`

### Problem

The options object that needs to be passed to the DateTimeFormat constructor has curly braces. Those need to be escaped for to be able to save the yaml.

### Read the documentation

- [X] I have read the documentation

**Comment by MrBearPresident** [comment]
The code you provided works for me;

![image](https://github.com/user-attachments/assets/30c6758b-ca89-4d2f-ac45-4bfe669d50d0)


```
type: custom:bubble-card
card_type: button
button_type: state
entity: sun.sun
styles: >-
  ${card.querySelector('.bubble-sub-button-1').innerText = new Intl.DateTimeFormat("en-US", {weekday: 'long'}).format(new Date()) }
sub_button:
  - entity: sun.sun
  - entity: sun.sun
```
