### DISCUSSION TITLE
Popup Header/Title and Separator Text Centering

### DISCUSSION THREAD

**Discussion by poolguard** [Clooos/Bubble-Card#1119] [Questions about config, custom styles and templates] [answered]
### Goal

Is there a way have text centered and enlarged in the header WITHOUT the button outline or background? Kind of like a title for the popup?  I would even like to hide the close button if possible.

Also is there a way to center the text in a Separator and have the separator lines both to the left and right of the text?

### Source Yaml

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#KitchenMusic"
    show_header: true
    name: Music
    scrolling_effect: false
    show_icon: false
    styles: |-
      .bubble-name-container {
        align-items: center;
        
      }
```

### Read the documentation

- [X] I have read the documentation

**Comment by MrBearPresident** [comment, marked as answer]
Something like: 
```css
.bubble-header .bubble-name-container {
  align-items: center;
}
.bubble-header{
  .bubble-button-background,.bubble-button-card-container{
    background: #11118800 !important;
  }
}
```

---

<sup>If this solves your problem, mark this as the solution and close the discussion. </sup>
