### DISCUSSION TITLE
Is there a way to modify a sub button action via JS in the style tag?

### DISCUSSION THREAD

**Discussion by ee4lif3** [Clooos/Bubble-Card#1123] [Questions about config, custom styles and templates]
### Goal

Ultimately I'm trying to modify the path for a URL action in a sub button. I have a wled controller and I want a sub button that I can tap that will navigate me to the IP of the controller. 

At this point I could hard code the current IP, but Ive become hyper focused on seeing if I can figure this out. 

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: light.wled
tap_action:
  action: toggle
show_attribute: false
show_last_changed: false
show_state: true
force_icon: false
slider_live_update: true
sub_button:
  - entity: light.wled
    show_attribute: true
    attribute: brightness
    show_background: false
    show_icon: false
    name: Brightness
    icon: mdi:brightness-percent
  - entity: light.wled
    select_attribute: effect_list
    show_name: false
    show_state: false
    show_attribute: true
    attribute: effect
    state_background: false
    show_background: false
    name: Mode
    show_arrow: false
  - entity: select.wled1_color_palette
    select_attribute: effect_list
    show_attribute: false
    show_arrow: false
    show_name: false
    show_state: true
    icon: mdi:palette
    show_last_changed: false
    show_background: false
    show_icon: true
    name: Palette
  - entity: sensor.wled_ip
    icon: mdi:ip-network
    show_background: false
    show_state: false
    show_name: false
    name: IP Address
    tap_action:
      action: url
      navigation_path: ${ states("sensor.wled_ip") }
      url_path: sensor.wled1_ip
attribute: brightness
double_tap_action:
  action: none
hold_action:
  action: more-info
visibility:
  - condition: state
    entity: switch.sonoff_100205f05c
    state: "on"
name: WLED
icon: mdi:led-strip-variant
card_layout: large
```

### Which step did you already try?

```yaml
Tried every templating format I can think of. The FAQ says templates aren't directly supported, but that it might be possible via JS in the style tag.
```

### Read the documentation

- [X] I have read the documentation
