### DISCUSSION TITLE
Right justify content in sub-buttons?

### DISCUSSION THREAD

**Discussion by sjcrossley** [Clooos/Bubble-Card#1176] [Questions about config, custom styles and templates] [answered]
### Goal

Is there a way to right-justify the content of sub-buttons when using the 2-row layout?  If not, I think it would be a nice feature to have.

### Source Yaml

```yaml
- type: custom:bubble-card
    card_type: button
    button_type: state
    entity: sensor.XXXXXXXX
    name: Account
    card_layout: large-2-rows
    sub_button:
      - name: Change Value
        attribute: marketChangeDisplay
        show_attribute: true
        show_background: false
        show_icon: false
      - name: Cash Value
        attribute: cash
        show_state: false
        show_icon: false
        state_background: false
        show_background: false
        show_attribute: true
    styles: |
      .bubble-icon-container,
      .bubble-button-card-container {
        background-color: transparent !important;
      }
      .bubble-sub-button-container {
        padding-right: 0px !important;
      }
      .bubble-icon,
      .bubble-sub-button {
        color: ${hass.states[entity].attributes.iconColor} !important;
      }
      .bubble-sub-button {
        font-sizeX: 14px !important;
        font-weight: 600 !important;
      }
      .bubble-sub-button-2,
      .bubble-sub-button-4 {
        color: var(--info-color) !important;
      }
```

### Read the documentation

- [X] I have read the documentation
