### DISCUSSION TITLE
problem on background

### DISCUSSION THREAD

**Discussion by platini76** [Clooos/Bubble-Card#1177] [Questions about config, custom styles and templates] [answered]
### Goal

my goal is to have no yellow background on my lock card

<img width="550" alt="Screenshot 2025-01-23 alle 14 27 30" src="https://github.com/user-attachments/assets/24d11795-c8b9-4d2f-b962-348a31512b84" />

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: switch
entity: lock.nuki_porta_fronte_bocchio
name: Porta Ingresso
card_layout: large
sub_button:
  - entity: sensor.nuki_porta_fronte_bocchio_batteria
    show_state: true
    show_attribute: true
    show_icon: true
    show_background: true
    state_background: true
styles: >

  .bubble-icon {
    color: ${hass.states['lock.nuki_porta_fronte_bocchio'].state === 'locked' ? 'red' : 'green'} !important;
  }  

  .bubble-icon-container {
    background-color: ${hass.states['lock.nuki_porta_fronte_bocchio'].state === 'locked' ? 'rgba(255, 0, 0, 0.2)' : 'rgba(0, 255, 0, 0.2)'} !important;
  } 

  .bubble-sub-button-1 > ha-icon {
    color: 
      ${hass.states['sensor.nuki_porta_fronte_bocchio_batteria'].state < 10 ? 'red' :
       hass.states['sensor.nuki_porta_fronte_bocchio_batteria'].state <= 20 ? 'yellow' :
       'green'} !important;
  } 

  .bubble-sub-button-1 {
    background-color: rgba(86, 86, 85, 0.6) !important;
  }

  ${icon.setAttribute("icon",
  hass.states['lock.nuki_porta_fronte_bocchio'].state === 'locked' ? 'mdi:lock'
  : 'mdi:lock-open')}
show_state: true
force_icon: false
show_last_changed: false
show_attribute: false
show_name: true
show_icon: true
scrolling_effect: true
```

### Problem

how I must correct the code?

### Read the documentation

- [X] I have read the documentation

**Comment by Menelao147** [comment, marked as answer]
Something like this?
![image](https://github.com/user-attachments/assets/eae4adb9-6b0a-4bd9-ad86-a662f8fcb15d)

`.bubble-button-background { background: transparent !important; }`

```yaml
type: custom:bubble-card
card_type: button
button_type: switch
entity: lock.nuki_porta_fronte_bocchio
name: Porta Ingresso
card_layout: large
sub_button:
  - entity: sensor.nuki_porta_fronte_bocchio_batteria
    show_state: true
    show_attribute: true
    show_icon: true
    show_background: true
    state_background: true
styles: |
  .bubble-button-background { background: transparent !important; }

  .bubble-icon {
    color: ${hass.states['lock.nuki_porta_fronte_bocchio'].state === 'locked' ? 'red' : 'green'} !important;
  }  

  .bubble-icon-container {
    background-color: ${hass.states['lock.nuki_porta_fronte_bocchio'].state === 'locked' ? 'rgba(255, 0, 0, 0.2)' : 'rgba(0, 255, 0, 0.2)'} !important;
  } 

  .bubble-sub-button-1 > ha-icon {
    color: 
      ${hass.states['sensor.nuki_porta_fronte_bocchio_batteria'].state < 10 ? 'red' :
       hass.states['sensor.nuki_porta_fronte_bocchio_batteria'].state <= 20 ? 'yellow' :
       'green'} !important;
  } 

  .bubble-sub-button-1 {
    background-color: rgba(86, 86, 85, 0.6) !important;
  }

  ${icon.setAttribute("icon",
  hass.states['lock.nuki_porta_fronte_bocchio'].state === 'locked' ? 'mdi:lock'
  : 'mdi:lock-open')}
show_state: true
force_icon: false
show_last_changed: false
show_attribute: false
show_name: true
show_icon: true
scrolling_effect: true
```
