### DISCUSSION TITLE
Horizontal buttons stack bubble card width

### DISCUSSION THREAD

**Discussion by flth1968** [Clooos/Bubble-Card#1195] [Questions about config, custom styles and templates] [answered]
### Goal

Bubble cards in a horizontal button stack with different widths, card 1 70% and card 2 30% of the width

### Source Yaml

```yaml
type: horizontal-stack
cards:
  - type: custom:bubble-card
    card_type: select
    card_layout: large-2-rows
    entity: input_select.modes
    sub_button:
      - entity: device_tracker.flemming_iphone
        show_state: false
        show_icon: true
        name: ""
        icon: mdi:human-male
        show_name: false
      - entity: device_tracker.heidi_iphone
        icon: mdi:human-female
        show_arrow: false
        show_icon: true
    show_icon: false
    show_name: false
    show_state: true
  - type: custom:bubble-card
    card_type: button
    button_type: state
    entity: sensor.energi_data_service
    card_layout: large-2-rows
```

### Which step did you already try?

```yaml
type: horizontal-stack
cards:
  - type: custom:mod-card
    card:
      type: custom:bubble-card
      entity: sensor.temperature
      name: Temperatur
    style: |
      ha-card {
        width: 70%;
      }

  - type: custom:mod-card
    card:
      type: custom:bubble-card
      entity: sensor.humidity
      name: Fugtighed
    style: |
      ha-card {
        width: 30%;
      }
```

### Read the documentation

- [X] I have read the documentation
