### DISCUSSION TITLE
Bubbel Card slider show % on slider when adjusting.

### DISCUSSION THREAD

**Discussion by flth1968** [Clooos/Bubble-Card#1197] [Questions about config, custom styles and templates]
### Goal

Is it possible to make a button slider where you can see % when adjusting, can see % when the curtain is stopped, but would like to be able to see where I set the slider, as in the picture.
![IMG_1367](https://github.com/user-attachments/assets/86ca3436-19a5-48e0-88af-588a6ec88c4e)
Missing %
![IMG_1366](https://github.com/user-attachments/assets/78feb65c-e711-4ba4-b10f-92486d5712ac)

### Source Yaml

```yaml
- type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: cover.stue1
    show_last_changed: false
    show_attribute: true
    show_state: true
    scrolling_effect: false
    show_icon: false
    show_name: true
    attribute: current_position
    styles: |
      .bubble-range-fill { 
        background: rgba(77, 154, 169, 5) !important;
        opacity: 1 !important;
      }
    force_icon: false
    slider_live_update: true
    card_layout: normal
```

### Read the documentation

- [X] I have read the documentation
