### DISCUSSION TITLE
Select card, blurred select menu

### DISCUSSION THREAD

**Discussion by KNicholson-VII** [Clooos/Bubble-Card#1198] [Questions about config, custom styles and templates]
### Goal

A blurred drop down menu with the items still visible and the borders solid. I can change the background with ha-select.
<img width="505" alt="Screenshot 2025-01-30 at 14 06 49" src="https://github.com/user-attachments/assets/8d906832-5fcd-47db-a8b9-5ee36acf7726" />

### Source Yaml

```yaml
ha-select {
  --mdc-theme-surface: rgb(255,255,255,0.2);
}

ha-select::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: inherit;
  filter: blur(20px);
  z-index: -1;
}
```

### Which step did you already try?

The above

### Problem

it seems I cannot make the :before work with the select ha-select menu and I do not know of another way to achieve this, help!

Thanks

### Read the documentation

- [X] I have read the documentation
