### DISCUSSION TITLE
Change background based on numerical entity

### DISCUSSION THREAD

**Discussion by azsaleem** [Clooos/Bubble-Card#1217] [Questions about config, custom styles and templates]
### Goal

I want to change the color of the background based on temperature of the water. So when it is at temperature (ie >45 deg) it should be red, when it is 38-44, it should be yellow and below that should be blue. I'm not able to get even the first first. I've tried a few of the elements based in the docs, see below.

### Source Yaml

```yaml
style: |
  .bubble-button-background {
    opacity: 1 !important;
    background-color: ${state === '>45' ? 'red' : 'yellow'} !important;
      }
```

### Which step did you already try?

```yaml
style: |
  .bubble-button-background {
    opacity: 1 !important;
    background-color: ${hass.states['sensor.mitsubishi_ecodan_tank_temperature'].state === '> 45' ?  'red' : 'yellow'} !important;
  }
```

### Problem

None of the above work, is there a way to make this happen. I can make it happen based on entities being on or off but is there a way to do it based on the numerical value of an entity?

### Read the documentation

- [X] I have read the documentation
