### DISCUSSION TITLE
[Showcase] Sharing a Few Dashboard Sections!

### DISCUSSION THREAD

**Discussion by garoevans** [Clooos/Bubble-Card#1224] [Share your custom styles, templates and dashboards]
**TTLock with IP restricted cloudflare tunnel**
All Locked
<img width="520" alt="Screenshot 2025-02-11 at 09 07 27" src="https://github.com/user-attachments/assets/1980e6ec-74b9-491a-971f-a0e8ddb83ce9" />

Door Unlocking/Unlocked
<img width="520" alt="Screenshot 2025-02-11 at 09 07 47" src="https://github.com/user-attachments/assets/9e7aa65e-9680-4029-83bf-683b332daa59" />

Double click lock icon to unlock with a few custom styles added. 3 sub buttons on each separator, one for last state change, one for lock icon when locked (hidden on other states), one with additional info when state is not locked. Conditional style for the battery icon color. Precise width settings.
```css
.bubble-sub-button-3 {
  background-color: red !important;
}
.bubble-icon {
  color: ${state > 70 ? 'green' : state < 30 ? 'red' : 'orange'} !important;
}
```

**Full screen dashboard for docked Pixel 8 Pro**

- House icon is person detection from a combination of security camera person detection (30 min motion detection to deactivate)
- Inside temp is average from 5 rointe radiators
- Target temp is average from 5 rointe radiators
- Office Temp card is target and actual for all radiators
- EV Charger connected triggers screenshot from security camera so I can see who's charging (via popup)
- Bottom right office card is UPS status (2hr runtime and 8% load)
- Spotify includes 3 cards - media, state, and slider to handle media, source, and volume independently - all with blurred media background image

<img width="520" alt="Screenshot 2025-02-11 at 09 16 29" src="https://github.com/user-attachments/assets/cabf3618-f1df-4248-8f48-6d03d4573b31" />

Clicking the office temp icon triggers a popup:
- Mini graph used to track 24 hours temp and target (average) and outside temp (right axis)

<img width="560" alt="Screenshot 2025-02-11 at 09 24 51" src="https://github.com/user-attachments/assets/a32179e1-8d6a-4963-b509-fcc1be5d513a" />

In edit mode...
- Lock badge when the office door is unlocked
- Camera icon when I'm on a work call (triggered via MQTT with bash script from macbook when webcam active)

<img width="520" alt="Screenshot 2025-02-11 at 09 21 24" src="https://github.com/user-attachments/assets/406681d1-61a7-455a-9161-309543c32a5d" />

Using Caule Black Purple Theme with following alterations:
```css
bubble-main-background-color: var(--ha-card-background)
state-sensor-background-color: var(--ha-card-background)
ha-card-border-radius: 32px
ha-card-border-width: 0px
```

Tweaks to EV Charger Colors:
```css
ha-card {
  --bubble-main-background-color: ${hass.states['sensor.myenergi_zappi_unit_18_plug_status'].state === 'Charging' ? 'var(--accent-color)' : 'inherit'} !important;
}

.bubble-icon {
  color: ${hass.states['sensor.myenergi_zappi_unit_18_plug_status'].state === 'Charging' ? 'var(--accent-color)' : 'inherit'} !important;
}
```

Media/State/Slide Combo Styles:
```css
/* Media card style */
.large .bubble-media-player-container {
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}

/* State card style */
.large .bubble-button-card-container {
  border-radius: 0;
}
.bubble-button-background {
    display: flex;
    position: absolute;
    height: 100%;
    width: 100%;
    background-size: cover;
    background-position: 50% !important;
    filter: blur(50px);
    opacity: 0.5;
    background: url("${hass.hassUrl(hass.states['media_player.spotifyplus_garoevans'].attributes.entity_picture)}");
}

/* Slider card style */
.large .bubble-button-card-container, .bubble-range-slider {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
.bubble-button-background {
    display: flex;
    position: absolute;
    height: 100%;
    width: 100%;
    background-size: cover;
    background-position: 50% !important;
    filter: blur(50px);
    opacity: 0.5;
    background: url("${hass.hassUrl(hass.states['media_player.spotifyplus_garoevans'].attributes.entity_picture)}");
}
```

Haven't managed to close the gaps between the media/state/slider cards. I'd like to do this to achieves 3 cards looking like one. Few other tweaks planned, but super happy with this!

**Comment by garoevans** [comment]
Fun update to the 3x media related cards:
<img width="524" alt="Screenshot 2025-02-11 at 11 27 33" src="https://github.com/user-attachments/assets/a5bdff95-201c-4442-8ecf-ac3a1cdc74a0" />

```css
/* media card */
.large .bubble-media-player-container {
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
.bubble-cover-background {
  filter: blur(0);
  background-position: 0 0px
}

/* state card */
.large .bubble-button-card-container {
  border-radius: 0;
  height: 264px;
}
.bubble-button-background {
  display: flex;
  position: absolute;
  height: 100%;
  width: 100%;
  background-size: cover !important;
  background-position: 0 -56px !important;
  border-radius: 0;
  opacity: 0.5;
  background: url("${hass.hassUrl(hass.states['media_player.spotifyplus_garoevans'].attributes.entity_picture)}");
}
ha-card {
  margin-top: -8px;
}

/* slider card */
.large .bubble-button-card-container, .bubble-range-slider {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
.bubble-button-background {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  display: flex;
  position: absolute;
  height: 100%;
  width: 100%;
  background-size: cover !important;
  background-position: 0 -320px !important;
  opacity: 0.5;
  background: url("${hass.hassUrl(hass.states['media_player.spotifyplus_garoevans'].attributes.entity_picture)}");
}
```

**Comment by garoevans** [comment]
And a couple more tweaks, last post on this, just sharing...

**3 card media player**
<img width="524" alt="Screenshot 2025-02-13 at 09 40 53" src="https://github.com/user-attachments/assets/b7a6796e-2f98-449d-88e6-71dfd73c679f" />

**door lock**
<img width="524" alt="Screenshot 2025-02-13 at 09 41 45" src="https://github.com/user-attachments/assets/f68832eb-4a9b-4eca-ab1e-8d4d18375f6a" />
<img width="524" alt="Screenshot 2025-02-13 at 09 42 07" src="https://github.com/user-attachments/assets/d4076f7e-0a7c-4965-b739-fd347a7db144" />

**Comment by schumi2309** [comment]
@garoevans 
Great card.
Can you give me the full code for your first card (door lock) as well as the Spotify 3-in-1 card (the latest model)?
thanks...

**Reply by schumi2309** [reply]
@garoevans 
Possible ??
![Capture d’écran 2025-04-09 à 12 55 39](https://github.com/user-attachments/assets/485b4754-a133-4c4b-ab5a-12d5954dddf0)

![Capture d’écran 2025-04-09 à 12 55 49](https://github.com/user-attachments/assets/7457e8f5-5a7a-490b-8994-33f83da66bd8)

Merci a toi.

**Reply by garoevans** [reply]
Hey @schumi2309, sorry for the slow reply - notifications not coming through. Here we go:

Door Card:
```
  - type: sections
    max_columns: 1
    title: Locks
    path: locks
    icon: mdi:lock-smart
    sections:
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Main Door
            icon: mdi:door-closed-lock
            card_layout: large
            sub_button:
              - entity: lock.main_door_external
                show_background: false
                show_icon: false
                show_attribute: false
                show_last_changed: true
              - entity: lock.main_door_external
                show_name: false
                show_state: false
                show_last_changed: false
                show_attribute: false
                visibility:
                  - condition: state
                    entity: lock.main_door_external
                    state: locked
                double_tap_action:
                  action: toggle
                state_background: true
                show_background: true
              - entity: lock.main_door_external
                show_state: true
                show_last_changed: false
                visibility:
                  - condition: state
                    entity: lock.main_door_external
                    state_not: locked
                icon: mdi:lock-open-variant
                show_background: true
            styles: >-
              .bubble-sub-button-2 {
                background-color: var(--success-color) !important;
              }

              .bubble-sub-button-3 {
                background-color: var(--info-color) !important;
              }

              .bubble-sub-button-2, .bubble-sub-button-3 {
                color: var(--text-primary-color) !important;
              }

              ${icon.setAttribute("icon",
              hass.states['lock.main_door_external'].state === 'locked' ?
              'mdi:door-closed-lock' : 'mdi:door-open')}
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.main_door_external_battery
            show_attribute: false
            show_name: false
            grid_options:
              columns: 3
              rows: 1
            card_layout: large
            styles: |-
              .bubble-icon {
                color: ${state > 30 ? 'green' : state < 10 ? 'red' : 'orange'} !important;
              }
            show_state: true
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.main_door_external_last_operator
            name: Last Operator
            icon: mdi:shield-account-outline
            grid_options:
              columns: 5
              rows: 1
            card_layout: large
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.main_door_external_last_trigger
            icon: mdi:cursor-default-click-outline
            name: Last Trigger
            grid_options:
              columns: 4
              rows: 1
            card_layout: large
          - type: custom:bubble-card
            card_type: separator
            name: Warehouse Door
            icon: mdi:door-closed-lock
            card_layout: large
            sub_button:
              - entity: lock.warehouse_door
                show_background: false
                show_icon: false
                show_last_changed: true
              - entity: lock.warehouse_door
                show_name: false
                show_attribute: false
                show_last_changed: false
                show_state: false
                visibility:
                  - condition: state
                    entity: lock.warehouse_door
                    state: locked
                double_tap_action:
                  action: toggle
              - entity: lock.warehouse_door
                show_state: true
                show_last_changed: false
                visibility:
                  - condition: state
                    entity: lock.warehouse_door
                    state_not: locked
                icon: mdi:lock-open-variant
            styles: >-
              .bubble-sub-button-2 {
                background-color: var(--success-color) !important;
              }

              .bubble-sub-button-3 {
                background-color: var(--info-color) !important;
              }

              .bubble-sub-button-2, .bubble-sub-button-3 {
                color: var(--text-primary-color) !important;
              }

              ${icon.setAttribute("icon",
              hass.states['lock.warehouse_door'].state ===
                'locked' ? 'mdi:door-closed-lock' : 'mdi:door-open')}
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.warehouse_door_battery
            show_attribute: false
            show_name: false
            grid_options:
              columns: 3
              rows: 1
            card_layout: large
            styles: |-
              .bubble-icon {
                color: ${state > 30 ? 'green' : state < 10 ? 'red' : 'orange'} !important;
              }
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.warehouse_door_last_operator
            name: Last Operator
            icon: mdi:shield-account-outline
            grid_options:
              columns: 5
              rows: 1
            card_layout: large
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.warehouse_door_last_trigger
            icon: mdi:cursor-default-click-outline
            name: Last Trigger
            grid_options:
              columns: 4
              rows: 1
            card_layout: large
```

Spotify Card:
```
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Spotify
            icon: mdi:spotify
            card_layout: large
            sub_button: []
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.spotifyplus_garoevans
            show_name: false
            show_state: false
            show_attribute: false
            hide:
              power_button: true
              previous_button: true
              next_button: true
              volume_button: true
              play_pause_button: true
            card_layout: large
            cover_background: true
            sub_button:
              - entity: media_player.spotifyplus_garoevans
                select_attribute: source_list
                state_background: true
                show_name: false
                show_state: false
                show_attribute: true
                attribute: source
            show_icon: true
            force_icon: false
            show_last_changed: false
            scrolling_effect: true
            styles: |-
              .large .bubble-media-player-container {
                border-bottom-left-radius: 0;
                border-bottom-right-radius: 0;
              }
              .bubble-cover-background {
                filter: blur(0);
                background-position: 0 0px
              }
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: media_player.spotifyplus_garoevans
            icon: mdi:volume-high
            force_icon: true
            show_state: false
            show_name: false
            show_attribute: false
            attribute: volume_level
            card_layout: large
            styles: |-
              .large .bubble-button-card-container {
                border-radius: 0;
                height: calc(var(--row-gap)*5 + var(--row-height)*5)
              }
              .bubble-button-background {
                display: flex;
                position: absolute;
                height: 100%;
                width: 100%;
                background-size: cover !important;
                background-position: 0 calc(var(--row-height)*-1) !important;
                border-radius: 0;
                opacity: 0.5;
                background: url("${hass.hassUrl(hass.states['media_player.spotifyplus_garoevans'].attributes.entity_picture)}");
              }
              ha-card {
                margin-top: calc(var(--row-gap) * -1);
              }
            show_icon: false
            scrolling_effect: false
            sub_button: []
            grid_options:
              columns: 12
              rows: 5
            rows: 3
            visibility:
              - condition: or
                conditions:
                  - condition: state
                    entity: media_player.spotifyplus_garoevans
                    state: playing
                  - condition: state
                    entity: media_player.spotifyplus_garoevans
                    state: paused
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: media_player.spotifyplus_garoevans
            icon: mdi:volume-high
            force_icon: true
            show_state: false
            show_name: false
            show_attribute: true
            attribute: volume_level
            card_layout: large
            styles: |-
              .large .bubble-button-card-container, .bubble-range-slider {
                border-top-left-radius: 0;
                border-top-right-radius: 0;
              }
              .bubble-button-background {
                border-top-left-radius: 0;
                border-top-right-radius: 0;
                display: flex;
                position: absolute;
                height: 100%;
                width: 100%;
                background-size: cover !important;
                background-position: 0 calc((var(--row-gap)*5 + var(--row-height)*6) * -1) !important;
                opacity: 0.5;
                background: url("${hass.hassUrl(hass.states['media_player.spotifyplus_garoevans'].attributes.entity_picture)}");
              }
              ha-card {
                margin-top: calc(var(--row-gap) * -1);
              }
            sub_button:
              - entity: media_player.spotifyplus_garoevans
                tap_action:
                  action: perform-action
                  perform_action: spotifyplus.player_media_skip_next
                  target: {}
                  data:
                    entity_id: media_player.spotifyplus_garoevans
                icon: mdi:skip-next
                state_background: false
                show_background: false
              - entity: media_player.spotifyplus_garoevans
                tap_action:
                  action: perform-action
                  target: {}
                  perform_action: spotifyplus.player_media_pause
                  data:
                    entity_id: media_player.spotifyplus_garoevans
                icon: mdi:pause
                visibility:
                  - condition: state
                    entity: media_player.spotifyplus_garoevans
                    state: playing
              - entity: media_player.spotifyplus_garoevans
                icon: mdi:play
                state_background: true
                show_background: false
                tap_action:
                  action: perform-action
                  perform_action: spotifyplus.player_media_resume
                  target: {}
                  data:
                    entity_id: media_player.spotifyplus_garoevans
                visibility:
                  - condition: state
                    entity: media_player.spotifyplus_garoevans
                    state_not: playing
        visibility:
          - condition: or
            conditions:
              - condition: state
                entity: media_player.spotifyplus_garoevans
                state: playing
              - condition: state
                entity: media_player.spotifyplus_garoevans
                state: paused
```

**Reply by Daniel75** [reply]
Hello
I would like to make the media player window always visible. Is there a way to display a placeholder or an image of my choice?

Deutsch:
Hallo
Ich würde gern das Mediaplayer Fenster immer sichtbar machen. Gibt es vielleicht eine Möglichkeit, das er das ein Platzhalter oder ein von mir gewähltes Bild anzeigt?

**Reply by garoevans** [reply]
Remove any of the visibility conditions:

```
        visibility:
          - condition: or
            conditions:
              - condition: state
                entity: media_player.spotifyplus_garoevans
                state: playing
              - condition: state
                entity: media_player.spotifyplus_garoevans
                state: paused
```

There's 3 or 4 of them
