### DISCUSSION TITLE
[JS+Editor Module] Customize the icon container color

### DISCUSSION THREAD

**Discussion by Clooos** [Clooos/Bubble-Card#1231] [Share your Modules]
# Customize the icon container color

**Version:** v1.2  
**Creator:** [Clooos](https://github.com/Clooos/)  

> [!IMPORTANT] 
> **Unsupported cards:**
>  - Horizontal buttons stack
>  - Separator

A list of predefined colors to customize the icon container color.
Configure this module via the editor or in YAML, for example:

```yaml
icon_container_color: 
    color: light-blue
```

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply copy and paste the following configuration into your `/www/bubble/bubble-modules.yaml` file.

```yaml
icon_container_color:
  name: 'Example: Customize the icon container color'
  version: v1.2
  creator: Clooos
  supported:
    - calendar
    - pop-up
    - cover
    - button
    - media-player
    - climate
    - select
  description: |
    A list of predefined colors to customize the icon container color.
    Configure this module via the editor or in YAML, for example:
    <br><br>
    <code-block><pre>
    icon_container_color: 
        color: light-blue
    </pre></code-block>
  code: |
    .bubble-icon-container,
    .bubble-day-chip {
      opacity: 1 !important;
      --bubble-icon-background-color: var(--${this.config.icon_container_color?.color}-color) !important;
    }
  editor:
    - name: color
      label: Color
      selector:
        ui_color:
          include_none: true
```

</details>

---

### Screenshot:

<img width="997" alt="image" src="https://github.com/user-attachments/assets/1d602bbc-e040-4beb-b1c9-66ca7443c3b3" />
