### DISCUSSION TITLE
Ping Effect when garage door is open

### DISCUSSION THREAD

**Discussion by Zerosignal84** [Clooos/Bubble-Card#1238] [Questions about config, custom styles and templates] [answered]
### Goal

I am trying to produce a ping effect like shown in the image below when my garage door is open. I was able to produce this with a mushroom card using the following code for our front door lock.

    mushroom-shape-icon$: |
      .shape {
        {{ '--shape-animation: ping 2s infinite;' if is_state('lock.front_door', 'unlocked') }}
      }
      @keyframes ping {
          0% {box-shadow: 0 0 0 0 rgba(var(--rgb-red), .7);}
          70% {box-shadow: 0 0 0 12px transparent;}
          100% {box-shadow: 0 0 0 0 transparent;}
      }

![image](https://github.com/user-attachments/assets/c7db1ebe-a8bc-4fa1-b820-91f711ec306d)

### Source Yaml

```yaml
type: custom:bubble-card
entity: cover.smart_garage_door_2106157753936436101748e1e97278fb_garage
card_layout: large
grid_options:
  columns: 6
  rows: 1
card_type: button
icon: mdi:garage-variant
name: Garage Door
tap_action:
  action: toggle
double_tap_action:
  action: none
hold_action:
  action: none
button_action:
  double_tap_action:
    action: none
  hold_action:
    action: more-info
style_templates:
  - home-assistant-default
show_last_changed: false
show_state: true
force_icon: false
styles: ".bubble-icon-container {\n  animation: ${hass.states['cover.smart_garage_door_2106157753936436101748e1e97278fb_garage'].state === 'open' ? 'ping 2s infinite' : ''};  \n}\n  @keyframes ping {\n     0% {box-shadow: 0 0 0 0 rgba(var(--rgb-red), .7);}\n     70% {box-shadow: 0 0 0 12px transparent;}\n\t 100% {box-shadow: 0 0 0 0 transparent;}\n  }"
```

### Which step did you already try?

```yaml
I've tried using this code following the example on how to rotate a fan on the main page.

.bubble-icon-container {
  animation: ${hass.states['cover.smart_garage_door_2106157753936436101748e1e97278fb_garage'].state === 'open' ? 'ping 2s infinite' : ''};  
}
  @keyframes ping {
     0% {box-shadow: 0 0 0 0 rgba(var(--rgb-red), .7);}
     70% {box-shadow: 0 0 0 12px transparent;}
     100% {box-shadow: 0 0 0 0 transparent;}
  }
```

### Problem

I cannot seem to the animation to work, I would appreciate some help where I am going wrong with this.

### Read the documentation

- [X] I have read the documentation
