### DISCUSSION TITLE
CSS  styling for hacked 2x height climate card

### DISCUSSION THREAD

**Discussion by deergitseason** [Clooos/Bubble-Card#1242] [Questions about config, custom styles and templates]
### Goal

I hacked together 2 climate cards with custom CSS to make it look like they're one double-height card, by extending the margins of the top card down, and turning off corner rounding on the respective corners of the top and bottom cards.

It all works great except when the HVAC is heating/cooling, the active color doesn't extend downward, leaving a gap in between.

Any ideas on this, while we all excitedly wait for this feature to be implemented :)?

Off:
![Screenshot 2025-02-15 at 10 26 17 AM](https://github.com/user-attachments/assets/e46e0ebc-3fc6-4482-be94-23ce44c3bb88)

On:
![Screenshot 2025-02-15 at 8 20 43 AM](https://github.com/user-attachments/assets/c6adcba8-686d-4391-9fe0-ec80525dc09e)

### Source Yaml

```yaml
.bubble-climate-container,
.bubble-button-background,
.bubble-color-background {
    border-radius: 15px 15px 0 0 !important;
    position: relative; /* Ensure the element is positioned relative for pseudo-elements or offsets */
    overflow: visible;
}

.bubble-climate-container::after,
.bubble-button-background::after,
.bubble-color-background::after {
    content: '';
    position: absolute;
    bottom: -8px; /* Extend downwards by 8px */
    left: 0;
    right: 0;
    height: 8px;
    background-color: inherit;
}

.bubble-climate {
    position: absolute;
    top: 0; /* Aligns it to the top of the container */
    left: 0; /* Aligns it to the left of the container */
    z-index: 1; /* Places it above other elements */
}

    .rows-2 .bubble-sub-button-container > * {
    justify-self: end; /* Right-justify each grid item */
    margin-right: -20px;
    padding-top: 10px;
}

    .bubble-sub-button-container {
  padding: 0px !important;

    }

    .bubble-target-temperature-container {
    display: flex;
    flex-direction: column; /* Stack children vertically */
    align-items: center;   /* Center-align the containers horizontally */
    gap: 0px;             /* Optional: Add space between the containers */
}

.bubble-low-temp-container,
.bubble-high-temp-container {
    background: none;
    display: flex;
    justify-content: center; /* Optional: Center-align content inside */
    align-items: center;     /* Optional: Vertically align content */
    width: 100%;             /* Optional: Adjust as needed */
}

.bubble-climate-minus-button, .bubble-climate-plus-button {
    height: 24px;
    }
```

### Read the documentation

- [X] I have read the documentation

**Comment by Menelao147** [comment]
Have you try to use `.bubble-climate-container::before` instead of `.bubble-climate-container::after`?

**Comment by deergitseason** [comment]
I realized I was overthinking this and just made a single card's css 2x height. I'm sure the CSS here is super messy but it works:

```
.bubble-climate-container,
.bubble-button-background,
.bubble-color-background {
    border-radius: 15px !important;
    height: 120px !important;
}

.bubble-climate {
  display: grid;
  grid-template-columns: auto auto;
  grid-template-rows: auto auto;
  align-items: start;
}

/* Place the icon in the first row, first column */
.bubble-icon-container {
  grid-column: 1;
  grid-row: 1;
  margin-top: 15px;
  margin-bottom: 0px;
  margin-left: 20px !important;
}

/* Place the name below the icon in the first column */
.bubble-name-container {
  grid-column: 1;
  grid-row: 2;
  margin-top: -10px;
  margin-left: 20px;
}

/* Place the button container in the second column, spanning both rows */
.bubble-button-container {
  grid-column: 2;
  grid-row: 1 / span 2;
  margin-top: -5px !important;
  align-self: center; /* vertically center the button container */
}


.bubble-button-container {
    display: flex;
    flex-direction: column; /* Stack elements vertically */
    align-items: center; /* Center-align contents horizontally */
    gap: 8px; /* Adjust spacing between child elements */
}


    .rows-2 .bubble-sub-button-container > * {
    justify-self: end; /* Right-justify each grid item */
    margin-right: -20px;
    padding-top: 10px;
}

    .bubble-sub-button-container {
  padding: 0px !important;
  margin-right: 12px;

    }

    .bubble-target-temperature-container {
    display: flex;
    flex-direction: column; /* Stack children vertically */
    align-items: center;   /* Center-align the containers horizontally */
    gap: 0px;             /* Optional: Add space between the containers */
}

.bubble-low-temp-container,
.bubble-high-temp-container {
    background: none;
    display: flex;
    justify-content: center; /* Optional: Center-align content inside */
    align-items: center;     /* Optional: Vertically align content */
    width: 100%;             /* Optional: Adjust as needed */
}

.bubble-climate-minus-button, .bubble-climate-plus-button {
    height: 24px;
    }
```

**Comment by MrBearPresident** [comment]
Hey Maybe you could use #1291 on the newest beta?

**Comment by garoevans** [comment]
I did something similar in a 3x card media player

https://github.com/Clooos/Bubble-Card/discussions/1224#discussioncomment-12139739

To take it a little further instead of hard coding the margins and height I used (eventually):

```css
.large .bubble-button-card-container {
  border-radius: 0;
  height: calc(var(--row-gap)*5 + var(--row-height)*5)
}
.bubble-button-background {
  display: flex;
  position: absolute;
  height: 100%;
  width: 100%;
  background-size: cover !important;
  background-position: 0 calc(var(--row-height)*-1) !important;
  border-radius: 0;
  opacity: 0.5;
  background: url("${hass.hassUrl(hass.states['media_player.spotifyplus'].attributes.entity_picture)}");
}
ha-card {
  margin-top: calc(var(--row-gap) * -1);
}
```

and

```css
.large .bubble-button-card-container, .bubble-range-slider {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
.bubble-button-background {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  display: flex;
  position: absolute;
  height: 100%;
  width: 100%;
  background-size: cover !important;
  background-position: 0 calc((var(--row-gap)*5 + var(--row-height)*6) * -1) !important;
  opacity: 0.5;
  background: url("${hass.hassUrl(hass.states['media_player.spotifyplus'].attributes.entity_picture)}");
}
ha-card {
  margin-top: calc(var(--row-gap) * -1);
}
```

There's also some background image css in there too
