### DISCUSSION TITLE
Arrange icon and text

### DISCUSSION THREAD

**Discussion by Martin650523** [Clooos/Bubble-Card#1261] [Questions about config, custom styles and templates]
### Goal

Is it possible to arrange the icon and the text like the picture show below?
![螢幕擷取畫面 2025-02-20 093106](https://github.com/user-attachments/assets/8acc5bba-ff66-40b9-b8d1-e96a39db2400)

### Source Yaml

```yaml
- type: custom:bubble-card
    card_type: button
    entity: switch.sonoff_e51669_2
    card_layout: large-2-rows
    icon: mdi:lightbulb
    show_state: true
    styles: |-
      * { 
        font-size: 20px !important;
      }
      .bubble-name {
        height: 25px
      }
```

### Read the documentation

- [ ] I have read the documentation
