### DISCUSSION TITLE
[Styling Module] Sub-buttons below

### DISCUSSION THREAD

**Discussion by MrBearPresident** [Clooos/Bubble-Card#1291] [Share your Modules]
# Sub-buttons below

**Version:** v2025.10.01  
**Creator:** MrBearPresident

> [!IMPORTANT] 
> **Supported cards:**
>  - Button
>  - Calendar
>  - Climate
>  - Cover
>  - Media Player
>  - Select
>  - Separator

This module adds all the necessary css to move the subbuttons below and make full use of the witdh. In meantime give the main feature and title the room to use that witdh. Only applicable when multirow sections are used.
Configure this module via the editor or in YAML, for example:

```yaml
  type: custom:bubble-card
  card_type: button
  modules:
    - subbutton_below
  card_layout: large-sub-buttons-grid
  grid_options:
    rows: 3
  sub_button:
    - entity: sun.sun
      icon: mdi:numeric-0
    - entity: sun.sun
      icon: mdi:numeric-1
    - entity: sun.sun
      icon: mdi:numeric-2
    - entity: sun.sun
      icon: mdi:numeric-3
  button_type: state
  entity: sun.sun
```

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply install it from the Module Store (from the editor of any card > Modules), or copy and paste the following configuration into your `/www/bubble/bubble-modules.yaml` file.

```yaml
subbutton_below:
    name: "Sub-button below"
    version: "v2025.10.01"
    creator: "MrBearPresident"
    link: "https://github.com/Clooos/Bubble-Card/discussions/1291"

    supported:
        - button
        - calendar
        - climate
        - cover
        - media-player
        - select
        - separator

    description: |
        This module adds all the necessary css to move the subbuttons below and make full use of the witdh. In meantime give the main feature and title the room to use that witdh. Only applicable when multirow sections are used.
        <br><br>
        <code-block><pre>
        subbutton_below: 
            # Your configuration here
        </pre></code-block>

    code: |
        :host{
          --row-size-copy: var(--row-size,1);
        }
        
        .bubble-button-container{
          --row-size-copy: var(--row-size,1);
        }
        
        .large .bubble-wrapper {
          position: relative;
          display: grid;
          grid-template-areas:
          'i n a' 'b b b' !important;
          grid-template-columns: auto 1fr auto;
          grid-template-rows: var(--row-height,56px) 1fr;
          justify-self: start;
          justify-items: start;
          align-self: center;
          align-items: center;
          width: 100%;
          gap: 0px;
        }
        .large .bubble-content-container {
          justify-content: flex-start;
          grid-area: n;
          overflow: hidden;
          max-width: calc(100% - 2 * var(--gap-to-edge,7px));
        }
        .large .bubble-sub-button-container {
          --row-size: calc( var(--row-size-copy) - 1);
          max-width: calc(100% - 20px);
          max-height: calc(100% - 20px);
          grid-area: b;
          justify-self: center;
          align-self: center;
          justify-content: center;
          align-content: start;
          justify-items: center;
          margin: 0;
          left: 0;
          right: 0;
        }
        .large .bubble-buttons-container{
          grid-area: a;
        }

```

</details>

---

### Screenshot:
![image](https://github.com/user-attachments/assets/c0cbd46f-32c0-444b-9e81-3b4cf1f16b4c)

**Comment by MrBearPresident** [comment]
@HyperCriSiS & @ddkedr: Here you go.

**Reply by HyperCriSiS** [reply]
Would it also be possible to additionally still use the first line? :sweat_smile:
Especially for the the normal slider card, to really get use of the whole space.
Makes much difference on mobile view.

**Reply by MrBearPresident** [reply]
not easily....
I use the css grid to easily separate the items and give them a position. 
So in short the card is build like this: 
![image](https://github.com/user-attachments/assets/8289ea46-1539-4ca7-aa76-393d12892d48)

To use also the top would mean a grid design like this: 
![image](https://github.com/user-attachments/assets/fc6bdcb7-6c60-4f4f-a250-e129ab91e544)
But this is not possible. 

So that would mean in a redesign of this module and for the sub-buttons as well. 
Because these are also ordered in grid structure.

**Reply by HyperCriSiS** [reply]
Thank you for the explanation!
Regarding the button and slider card, I thought they have no card specific feature area or is the card specific are normally the sub-button area? Without the module...

**Reply by MrBearPresident** [reply]
Indeed, the button and slider don't have a card-specific feature so that space would be empty but because the width of that space is defined on auto it goes to '0' when there is nothing in it.

**Reply by HyperCriSiS** [reply]
OK thanks 👍 maybe it can be realised in a future version

**Comment by ddkedr** [comment]
@MrBearPresident thanks a ton, man! That's exactly what I was looking for.

Just to clarity, am I correct that there is no easy way to put a state in a separate grid-area? 
I'm thinking about experimenting with this layout:

```
ICON | NAME | STATE | ACTION
-----------------------------
SUB-BUTTONS
```

I feel that with this layout we'll use the empty space between `name/state` and `feature action` more effectively. 
Of course this will only make sense for longer buttons that use 100% of screen width. For half-width cards your current layout with `state` under the `name` is more effective.
What do you think?

**Comment by HenryJIII** [comment]
Is it possible to adjust the container height of the sub-buttons, so those would be bigger? I feel like there is some unsused space between the name/state and the sub-buttons, that could be filled by making the sub-buttons bigger. Both in large and large with 2 rows mode.
![image](https://github.com/user-attachments/assets/564dd4ad-db76-41a2-a934-46cb884125dd)

**Comment by HyperCriSiS** [comment]
Also it would be cool if it could be used with normal layout instead of large.

**Reply by Clooos** [reply]
I was thinking to make the large layout the default in v2.5.0, I already tried on my side and I think that the difference is not disturbing, this also make more sense with the section view that's is getting more and more in popularity. What do you think?

**Reply by HyperCriSiS** [reply]
oh no :sweat_smile:
I think the majority of people uses HA on smart phones, at least that's my assumption. 
I only use it on PC for configuration. And I have no tablet.
My target is always to have as much as possible visible on one screen, while still maintaining usability.
So I prefer always compact layouts and it also bothers me if I can't use some space because it is just not possible.

Edit:
Maybe ur right, in one row layouts it does not make a real difference. Just in this special case with this modification here.
This is why I created the alternative with normal layout.
So, as long as you do not remove it, everything cool. :laughing:


I really love your bubble-cards, it is an awesome concept and the thing with the modules is really great!
But they are imo also still to static. When I imagine a certain layout, I would like to be able to place everything just there where I want to have it, without limitations.
So I wonder, if it would be possible to divide the cards into a fine raster which enables to put any button, any element just where you want it, in any size, while having a card with as much lines you like.
And the possibility to drag and drop the elements in the editor within the raster. :sweat_smile:
That would ne the endgame of card configuration for Home Assistant. :grin:

This here is also interesting and would be a nice addition if directly integrated:
https://github.com/Nemuritor01/css-swipe-card

**Reply by Clooos** [reply]
The drag and drop thing is an incredible idea, even if it would be probably incredibly difficult to put in place, also my current build has a smoother editor, but not smooth enough to my liking, so a feature like that could make it even worth 😅 

Maybe one day, but you're right, everything is a bit too static, that's why I'm planning to work a lot more on some new layouts, but in the meantime with the new modules, it will be easy to add new layouts and to share them (damn I like this new possibility).

**Reply by HyperCriSiS** [reply]
> The drag and drop thing is an incredible idea, even if it would be probably incredibly difficult to put in place, also my current build has a smoother editor, but not smooth enough to my liking, so a feature like that could make it even worth 😅
> 
> Maybe one day, but you're right, everything is a bit too static, that's why I'm planning to work a lot more on some new layouts, but in the meantime with the new modules, it will be easy to add new layouts and to share them (damn I like this new possibility).

That is a general HA issue and also issues like that with many other projects.
The Devs have a kind of a tunnel view and very often absolutely no fucking idea what the fucking hell usability is. :joy:
Did you see the latest additions to the tile card? At general very nice, BUT, so damn dumb integrated, that I could not believe my eyes.
They literally just made the majority of the new possibilities not work, because it seems they just wanted to do but did not even think a bit. :expressionless:
And that's the general thing with HA. Much done here and there and yes they maybe have a kinda clear roadmap, but IMO they concentrate on the wrong things since long time.
Main issue with HA still is, that it is damn fucking complicated, as soon as you want something 0.1% away from the default, lol.

YAML is just a damn abomination. Whoever decided using this, did not think a bit. :joy:

Ok, enough rant, for now :joy:

Did you see the module that I have added? I am ready for an update soon, with colour gradient option.
I am so proud how awesome it got.

**Reply by HyperCriSiS** [reply]
And regarding drag+drop, I think this is the only true way.
There is no other possibility if you want to achieve top notch usability.

**Reply by Clooos** [reply]
I have maybe something else in mind, but I always put usability first (and I hope everything is clear), that's why everything is editable in the editor.

For your drag and drop idea, what use case do you have in mind?

**Reply by HyperCriSiS** [reply]
I have no idea if this is even possible with a card addon or would have need a change in HA.
My idea is that there is no specific layout, only templates.
You create a raster card, with a certain size and x.y rasters.
Then you have an item editor where you can select from different buttons, style elements or whatever and you drop them into the raster and configure them there.
Or you just create placeholders directly in the raster, when you click on them a menu opens where you can select what it should be.
You could define virtual areas within the raster. Drop custom JS code onto it. Apply custom CSS Styles. Or you can add some kind of module, like you have it now. People could create whole Dashboard templates. You could realize automatic resizing to different screen sizes.

Also maybe as plugin system. I like software with plugins very much. It is an elegant way to keep things modular and exchangeable, easily extendible, and accessible. Anyone can contribute without the need of pull requests. I even would only make the real core functions non plugin.
That makes it much easier to adapt to whatever comes. 
You exchange the plugin, bam, done.

Of course that would need a PC or at least a tablet for proper configuration experience, but it is not much different now.
Configuring HA on mobile phone is a pain in the ass.

Sure, this would be a mammoth project in the beginning, but I could imagine that in the long run it is better.

This was just a quick'n dirty brainstorm. :sweat_smile:

**Reply by Clooos** [reply]
That's a lot more complex explained like that 🫠

**Reply by HyperCriSiS** [reply]
@Clooos 
Do you think you can make it possible to use full space with sub-buttons?
To span them from first line over second below the main icon?
This would be interesting especially for section view on mobile to have no space left as blank unused space.

**Reply by Clooos** [reply]
This will come at some point 🙂 This is probably already possible with some custom styles.

**Comment by Clooos** [comment]
I updated his module to fully support v3.0.0. He wanted to update it himself, but I have no news from him anymore. I hope he's doing well.

I will not update everyone's modules (🫠), I just used his module as a test when I worked on the new structure, and updated it in the meantime.

**Comment by a-bianucci** [comment]
Where do you update the module at?   Checking, depsite having bubble-card installed, I'm not seeing a www/bubble that contains the file mentioned

**Reply by Clooos** [reply]
Hi! The module feature is from [v3.0.0-beta](https://github.com/Clooos/Bubble-Card/releases), this version is really stable and should be the last beta, I'm just waiting a bit before the stable release just to be sure 🙂

**Comment by Christinxa** [comment]
Hi, on desktop the card looks great, but in the Android app everything is shifted up (main icon, title, sub-buttons get cut off). Any ideas why?
Using bubble card beta v3.0.0-beta.5, btw. Thanks! 😊
Desktop: ![image](https://github.com/user-attachments/assets/7d955140-d41b-4784-84c3-b0e92fa32359) Mobile: ![image](https://github.com/user-attachments/assets/55fe396f-a3e1-4c56-a35f-1710eec11d7a)

Edit: Seems to be related to Android WebView? Switching to Canary 138.0.7164.0 fixed it, but reverting to the stable version brings the issue right back.

**Reply by Christinxa** [reply]
> Hi, on desktop the card looks great, but in the Android app everything is shifted up (main icon, title, sub-buttons get cut off). Any ideas why? Using bubble card beta v3.0.0-beta.5, btw. Thanks! 😊 Desktop: ![image](https://private-user-images.githubusercontent.com/200943698/440787717-7d955140-d41b-4784-84c3-b0e92fa32359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY2OTE5NDMsIm5iZiI6MTc0NjY5MTY0MywicGF0aCI6Ii8yMDA5NDM2OTgvNDQwNzg3NzE3LTdkOTU1MTQwLWQ0MWItNDc4NC04NGMzLWIwZTkyZmEzMjM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUwOFQwODA3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjNmNTJiZjVmODRkODBlNDBkZmZiMDE0ZTgzM2FlZjY4ZTJiODAyNzM1ODg3MWQwOTk5ZmZhZGQzYTllNDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DyzrxABUWw2dPmDmxNuOr1tAM3YjYwjfBcdkdrMPl1c) Mobile: ![image](https://private-user-images.githubusercontent.com/200943698/440787839-55fe396f-a3e1-4c56-a35f-1710eec11d7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY2OTE5NDMsIm5iZiI6MTc0NjY5MTY0MywicGF0aCI6Ii8yMDA5NDM2OTgvNDQwNzg3ODM5LTU1ZmUzOTZmLWEzZTEtNGM1Ni1hMzVmLTE3MTBlZWMxMWQ3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUwOFQwODA3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTdlNjEzYmQwNDc3NTAwYTQzNDhhMDU2NGFmNWY2M2Y0MDQzMGJkOGQ2NDUzN2ZiZWZhNDgxODUxMDM3YzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7I5S4FyRSglU5L6tZlh2D3pIBcr5gzZ8jHhJGxbEZ4s)
> 
> Edit: Seems to be related to Android WebView? Switching to Canary 138.0.7164.0 fixed it, but reverting to the stable version brings the issue right back.

Okay, the problem's back again with Android 15, even though I'm using the latest Android System WebView. It only occurs with this specific module.

**Reply by AlkaDragos** [reply]
Hi, i have the same problem 😞 and, yes, it's specific to this module as others works just fine. As suggested, i updated my WebView app to Canary, fixed it for 2 days, now it's back to be broken. I think it's something related to grid view, but i can't find any recent changes  that may break this code. I'd like to know the potential solution too as i would like to use this 😃

**Reply by 0tto0o** [reply]
I have this issue as well since yesterday. It is just on my phone, on my Android tablet it is as it should.

**Reply by mattague** [reply]
This is happening with me as well on my desktop system

**Reply by berrywhite96** [reply]
Seems like they fixed a positioning bug within the rendering engine. Or it was a bug and they fixed it? I got it first on my phone, then updated my browser and the same issue appeared there. The code just needs a little update, @MrBearPresident just add the `position: relative;` attribute at the wrapper selector.

```
subbutton_below:
    name: Sub-button below
    version: "v2025.04.0"
    creator: "MrBearPresident"
    link: "https://github.com/Clooos/Bubble-Card/discussions/1291"
    description: This module adds all the necessary css to move the subbuttons below and make full use of the witdh. In meantime give the main feature and title the room to use that witdh. Only applicable when multirow sections are used. 
    unsupported:
      - horizontal-buttons-stack
      - pop-up
      - empty-column
  code: |-
    :host{
      --row-size-copy: var(--row-size,1);
    }

    .large .bubble-wrapper {
      position: relative;
      display: grid;
      grid-template-areas:
      'i n a' 'b b b' !important;
      grid-template-columns: auto 1fr auto;
      grid-template-rows: var(--row-height,56px) 1fr;
      justify-self: start;
      justify-items: start;
      align-self: center;
      align-items: center;
      width: 100%;
      gap: 0px;
    }
    .large .bubble-content-container {
      justify-content: flex-start;
      grid-area: n;
      overflow: hidden;
      max-width: calc(100% - 2 * var(--gap-to-edge,7px));
    }
    .large .bubble-sub-button-container {
      --row-size: calc( var(--row-size-copy) - 1);
      max-width: calc(100% - 20px);
      max-height: calc(100% - 20px);
      grid-area: b;
      justify-self: center;
      align-self: center;
      justify-content: center;
      align-content: start;
      justify-items: center;
      margin: 0;
      left: 0;
      right: 0;
    }
    .large .bubble-buttons-container{
      grid-area: a;
    }
    .bubble-media-info-container, .bubble-name-container {
      width: 100%;
    }

```

**Reply by gboldt** [reply]
> Seems like they fixed a positioning bug within the rendering engine. Or it was a bug and they fixed it? I got it first on my phone, then updated my browser and the same issue appeared there. The code just needs a little update, @MrBearPresident just add the `position: relative;` attribute at the wrapper selector.
> 
> ```
> subbutton_below:
>     name: Sub-button below
>     version: "v2025.04.0"
>     creator: "MrBearPresident"
>     link: "https://github.com/Clooos/Bubble-Card/discussions/1291"
>     description: This module adds all the necessary css to move the subbuttons below and make full use of the witdh. In meantime give the main feature and title the room to use that witdh. Only applicable when multirow sections are used. 
>     unsupported:
>       - horizontal-buttons-stack
>       - pop-up
>       - empty-column
>   code: |
>     :host{
>       --row-size-copy: var(--row-size,1);
>     }
> 
>     .large .bubble-wrapper {
>       position: relative; /* UPDATE HERE*/
>       display: grid;
>       grid-template-areas:
>       'i n a' 'b b b' !important;
>       grid-template-columns: auto 1fr auto;
>       grid-template-rows: var(--row-height,56px) 1fr;
>       justify-self: start;
>       justify-items: start;
>       align-self: center;
>       align-items: center;
>       width: 100%;
>       gap: 0px;
>     }
>     .large .bubble-content-container {
>       justify-content: flex-start;
>       grid-area: n;
>       overflow: hidden;
>       max-width: calc(100% - 2 * var(--gap-to-edge,7px));
>     }
>     .large .bubble-sub-button-container {
>       --row-size: calc( var(--row-size-copy) - 1);
>       max-width: calc(100% - 20px);
>       max-height: calc(100% - 20px);
>       grid-area: b;
>       justify-self: center;
>       align-self: center;
>       justify-content: center;
>       align-content: start;
>       justify-items: center;
>       margin: 0;
>       left: 0;
>       right: 0;
>     }
>     .large .bubble-buttons-container{
>       grid-area: a;
>     }
> 
> 
> ```

This fixed it for me, thank you very much

**Reply by Clooos** [reply]
@berrywhite96 I've updated his module with your YAML, since we have no news from him anymore. Thank you for your help!

**Reply by berrywhite96** [reply]
> @berrywhite96 I've updated his module with your YAML, since we have no news from him anymore. Thank you for your help!

No problem at all. I updated the YAML code again which fixes the broken scrolling of too long text next to icon.

I really like the modules system, thinking of building my own module also related to sub buttons. I think there are a lot of possibilities regarding multiple rows and positioning of those buttons.

**Reply by Clooos** [reply]
Great! Would be nice to have the same option as this module in yours as well, since this one isn't maintained anymore. 

Can't wait to see what you will create 😄

**Reply by berrywhite96** [reply]
> Great! Would be nice to have the same option as this module in yours as well, since this one isn't maintained anymore.
> 
> Can't wait to see what you will create 😄

I will try to create something useful when I find the time 😁

**Comment by einfall** [comment]
Hello,
I use the lastest beta.
How can i setup 2 or more rows?
THX

![image](https://github.com/user-attachments/assets/788444d5-99b1-4619-9373-fdf3d4bb91f6)
![image](https://github.com/user-attachments/assets/acef5917-fd56-4f78-a839-14638eaa6a1f)

**Reply by idominiki** [reply]
I would also like to know if it is possible to display sub-buttons in two rows.

**Reply by AllanonBrooks** [reply]
Had the same issue. Fixed by adjusting the layout of the card itself. 

<img width="1195" height="607" alt="image" src="https://github.com/user-attachments/assets/7ca24f05-6d7b-417c-a0ce-f659e98c94af" />

<img width="1271" height="642" alt="image" src="https://github.com/user-attachments/assets/06184128-8006-4198-858b-95ea8de4a55b" />

**Comment by Velo1901** [comment]
<img width="584" alt="Screenshot 2025-05-07 at 15 01 30" src="https://github.com/user-attachments/assets/c3815596-4d45-4bfe-9f7b-551e164854b1" />

Is there a way to remove the icons inside the pictures?

**Reply by einfall** [reply]
disable icon? how you set the speaker in the right corner on top? which module?

**Reply by Velo1901** [reply]
Disable the icon also removed the image. The right speaker is the volume option of the media player settings.

<img width="547" alt="Screenshot 2025-05-07 at 19 41 12" src="https://github.com/user-attachments/assets/f7203a3e-e317-4993-8cdb-c07f5b425a78" />

**Reply by Velo1901** [reply]
> disable icon? how you set the speaker in the right corner on top? which module?

I think you're right, but every time I clicked on 'Show Icon' it removed the picture also. But after I try again it removed the icon of the first button, but removing the second icon gives me the same problem of removing the picture.

<img width="507" alt="Screenshot 2025-05-07 at 19 45 16" src="https://github.com/user-attachments/assets/19b1c8cc-0180-4d0e-9a31-0a4ca573f2b1" />

**Reply by Velo1901** [reply]
It getting stranger. If I first choose the button and click on visibility and start with entitiestatus and delete the if then etc. Go back to icon and click on not to show icon it removes the icon. I use version 3 beta 5, maybe it's the beta or safari on my MacBook. Happy with the layout. Thanks [Mr. BearPresident](https://github.com/MrBearPresident)

<img width="484" alt="Screenshot 2025-05-07 at 19 54 36" src="https://github.com/user-attachments/assets/25cc1e22-a5ba-482c-b4ff-3f93794fd536" />

**Reply by Soukyuu** [reply]
@Velo1901: how do you choose which image to display? Separate entity?

**Comment by tclayson** [comment]
Hello! This is great, thank you so much.

I was wondering if there was any way to get the buttons to stretch to fill the width of the button at all? A bit like the Mushroom Media Player card works (see pic below).

I would be happy if all the buttons just stretched equally to fill the width. I can't figure it out myself!

![image](https://github.com/user-attachments/assets/3facccaa-6bb4-45d5-9570-6eb5a4afc9e0)

Thanks!

**Comment by HafizSarkawi** [comment]
![image](https://github.com/user-attachments/assets/86d917e1-573f-4ef3-88fb-505d1d37f353)


https://github.com/user-attachments/assets/63053345-033d-4bf4-a578-fdfb2b533fc1


Hi, need some help. Why is my card showing like this? The whole content seemed to be shifted to the top outside of the card.
Appreciate your help.

```
type: custom:bubble-card
card_type: button
button_type: switch
name: Office
entity: light.gaming_room
icon: mdi:desk
tap_action:
  action: none
button_action:
  tap_action:
    action: navigate
    navigation_path: /bubble-office
card_layout: large-sub-buttons-grid
rows: "2"
grid_options:
  columns: 6
  rows: "2"
sub_button:
  - entity: light.gaming_room
    icon: mdi:lightbulb
    state_background: true
    show_background: true
  - entity: binary_sensor.office_door
    show_background: true
    state_background: false
  - entity: media_player.office_display
    state_background: false
    visibility:
      - condition: state
        entity: media_player.office_display
        state_not: "off"
    show_state: false
    show_name: false
    show_background: true
  - entity: binary_sensor.office_motion_iaszone
    state_background: false
    visibility:
      - condition: state
        entity: binary_sensor.office_motion_iaszone
        state: "on"
  - entity: binary_sensor.game_room_ac_sensor_ias_zone
    icon: mdi:air-conditioner
    state_background: true
    visibility:
      - condition: state
        entity: climate.game_room_ac
        state: cool
  - entity: fan.office_fan
    icon: mdi:ceiling-fan
    state_background: false
    visibility:
      - condition: state
        entity: fan.office_fan
        state: "on"
modules:
  - subbutton_below
  - "!default"
```

**Reply by Clooos** [reply]
Hi, just refresh the Module Store, then install this module's update.

**Comment by burnt-past** [comment]
This doesn't seem to work with casting to a Google Home Hub.

**Comment by Soukyuu** [comment]
Something broke with 3.0.0 for me. I tried refreshing the module store, and it displays the version of the module as 2025.07. I then click "install" and get a "successfully installed" message. Attempting to enable the module for a media player card makes the module disappear. If I edit the module before enabling it, it looks weird:

![image](https://github.com/user-attachments/assets/3d51eaf8-8d39-4cc0-a06c-d4d3952aab14)

**Reply by Soukyuu** [reply]
Nice, refreshing the module store now says "no modules found".

**Reply by crypticSlave** [reply]
I'm having the same problem. My whole dashboard is ruined as it relied on this module for the layout.

**Reply by MrBearPresident** [reply]
If you installed/updated this through the Module store a weird bug appeared. 
I've made a new update and it should work fine now

**Reply by Soukyuu** [reply]
Working for me now, thanks!

**Comment by systems-monitor** [comment]
When I load in the new Module Store this is being stepped on by https://github.com/Clooos/Bubble-Card/discussions/1315
It is loading that one instead, assumedly because of identical names uniqueness.

**Comment by azilberbaum** [comment]
Not working for me?

![IMG_7084](https://github.com/user-attachments/assets/f7a5f4f3-93ba-4076-b59f-6f8ea475af04)

**Comment by systems-monitor** [comment]
Multiline sub buttons do not seem to be working as the pics in the doc above shows. 
Does it work for anyone else? is it something theme or browser?
<img width="348" height="176" alt="image" src="https://github.com/user-attachments/assets/90180eba-56b5-4cb8-9cfd-8c197c077439" />
clipped buttons right and left

I stripped it down to the simple demo yaml and still have the same.
<img width="330" height="179" alt="image" src="https://github.com/user-attachments/assets/6901f60c-a33d-4274-ab55-e7acb90aba60" />


```
type: custom:bubble-card
card_type: button
modules:
  - subbutton_below
card_layout: large
grid_options:
  rows: 3
sub_button:
  - entity: sun.sun
    icon: mdi:numeric-0
  - entity: sun.sun
    icon: mdi:numeric-1
  - entity: sun.sun
    icon: mdi:numeric-2
  - entity: sun.sun
    icon: mdi:numeric-4
  - entity: sun.sun
    icon: mdi:numeric-3
  - entity: sun.sun
    icon: mdi:account
  - entity: sun.sun
    icon: mdi:air-conditioner
  - entity: sun.sun
    icon: mdi:battery
  - entity: sun.sun
    icon: mdi:air-purifier
  - entity: sun.sun
    icon: mdi:balcony
button_type: state
entity: sun.sun

```

**Reply by MrBearPresident** [reply]
Please use: 


```
card_layout: large-sub-buttons-grid
```

**Reply by firmlyundecided** [reply]
I'm having the same issue, and confirmed that I have the large-sub-buttons-grid enabled. The entire card is horizontal scrollable, but clipped.

```
type: custom:bubble-card
card_type: button
button_type: name
entity: vacuum.q5_max_2
name: Vacuum
modules:
  - subbutton_below
card_layout: large-sub-buttons-grid
rows: 3
sub_button:
  - entity: vacuum.q5_max_2
    name: All Rooms
    show_state: false
    show_name: true
    tap_action:
      action: perform-action
      perform_action: vacuum.send_command
      target:
        device_id: fbf52cc7394a91421dbc3f7ee209bd13
      data:
        command: app_segment_clean
        params:
          segments:
            - 16
            - 17
            - 18
            - 19
            - 20
            - 21
            - 22
            - 23
    show_icon: true
    icon: mdi:home
  - entity: vacuum.q5_max_2
    name: Living Room
    show_name: true
    tap_action:
      action: perform-action
      perform_action: vacuum.send_command
      target:
        device_id: fbf52cc7394a91421dbc3f7ee209bd13
      data:
        command: app_segment_clean
        params:
          segments:
            - 22
    show_icon: true
    icon: mdi:sofa
  - entity: vacuum.q5_max_2
    name: Dining Room
    show_name: true
    tap_action:
      action: perform-action
      perform_action: vacuum.send_command
      target:
        device_id: fbf52cc7394a91421dbc3f7ee209bd13
      data:
        command: app_segment_clean
        params:
          segments:
            - 23
    show_icon: true
    icon: mdi:table-furniture
  - entity: vacuum.q5_max_2
    name: Kitchen
    show_name: true
    tap_action:
      action: perform-action
      perform_action: vacuum.send_command
      target:
        device_id: fbf52cc7394a91421dbc3f7ee209bd13
      data:
        command: app_segment_clean
        params:
          segments:
            - 21
    show_icon: true
    icon: mdi:silverware-fork-knife
  - entity: vacuum.q5_max_2
    name: Bedroom
    show_name: true
    tap_action:
      action: perform-action
      perform_action: vacuum.send_command
      target:
        device_id: fbf52cc7394a91421dbc3f7ee209bd13
      data:
        command: app_segment_clean
        params:
          segments:
            - 16
            - 17
    show_icon: true
    icon: mdi:bed-double
  - entity: vacuum.q5_max_2
    name: Second Bathroom
    show_name: true
    tap_action:
      action: perform-action
      perform_action: vacuum.send_command
      target:
        device_id: fbf52cc7394a91421dbc3f7ee209bd13
      data:
        command: app_segment_clean
        params:
          segments:
            - 19
    show_icon: true
    icon: mdi:paper-roll
  - entity: vacuum.q5_max_2
    name: Hallway
    show_name: true
    tap_action:
      action: perform-action
      perform_action: vacuum.send_command
      target:
        device_id: fbf52cc7394a91421dbc3f7ee209bd13
      data:
        command: app_segment_clean
        params:
          segments:
            - 18
            - 20
    show_icon: true
    icon: mdi:door-open
show_icon: false
show_name: true
tap_action:
  action: none
button_action:
  tap_action:
    action: none
```
![IMG_4282](https://github.com/user-attachments/assets/f085ad4d-b5cb-4c68-b886-9ccd92f19487)
