### DISCUSSION TITLE
[JS+Editor Module] Change Font

### DISCUSSION THREAD

**Discussion by will-fezz** [Clooos/Bubble-Card#1292] [Share your Modules]
# Change Font

**Version:** v1.2
**Creator:** will_fezz (https://github.com/will-fezz)

> [!IMPORTANT] 
> **Unsupported cards:**
>  - Horizontal buttons stack

A very simple module to change the font on the bubble cards. Now you can also change the letter spacing, font style and font size. Important that you add your font via the resources page first:

<a href="https://my.home-assistant.io/redirect/lovelace_resources/" target="_blank" rel="noreferrer noopener"><img src="https://my.home-assistant.io/badges/lovelace_resources.svg" alt="Open your Home Assistant instance and show your dashboard resources." /></a>

```yaml
font_change:
  font_type:
    font: Quicksand
  fine_control:
    lspacing: 6
    fstyle: oblique
    name_font_size: 25
    state_font_size: 15
```

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply copy and paste the following configuration into your `/www/bubble/bubble-modules.yaml` file.

```yaml
font_change:
    name: "Change Font"
    version: "v1.2"
    creator: "Will_Fezz"
    link: "https://github.com/Clooos/Bubble-Card/discussions/1292"    

    unsupported:
        - horizontal-buttons-stack    

    description: |
        A very simple module to change the font on the bubble cards. Now you can also change the letter spacing, font style and font size. Important that you add your font via the resources page first:
        <a href="https://my.home-assistant.io/redirect/lovelace_resources/" target="_blank" rel="noreferrer noopener"><img src="https://my.home-assistant.io/badges/lovelace_resources.svg" alt="Open your Home Assistant instance and show your dashboard resources." /></a>        

    code: |

      ${(() => {
      let fontCard = card.querySelector(".bubble-name, .bubble-name-container, .bubble-button-card-container, .bubble-select-card-container, .bubble-climate-container, .bubble-media-player-container, mwc-list-item, .bubble-separator, .bubble-cover-card-container");
      let fontName = card.querySelector(".bubble-name");
      let fontState = card.querySelector(".bubble-state");

      if(fontCard && this.config.font_change.font_type) { 
        if(!!this.config.font_change.font_type.font) {
          fontCard.style.fontFamily = this.config.font_change.font_type.font;
      }
        }
      if(fontCard && this.config.font_change.fine_control) { 
        if(!!this.config.font_change.fine_control.letter_spacing) {
          fontCard.style.letterSpacing = this.config.font_change.fine_control.letter_spacing + 'px';
      }
        }
      if(fontCard && this.config.font_change.fine_control) { 
        if(!!this.config.font_change.fine_control.font_style) {
          fontCard.style.fontStyle = this.config.font_change.fine_control.font_style;
      }
        }
      if(fontName && this.config.font_change.fine_control) { 
        if(!!this.config.font_change.fine_control.name_font_size) {
          fontName.style.fontSize = this.config.font_change.fine_control.name_font_size  + 'px';
      }
        }
      if(fontState && this.config.font_change.fine_control) { 
        if(!!this.config.font_change.fine_control.state_font_size) {
          fontState.style.fontSize = this.config.font_change.fine_control.state_font_size  + 'px';
      }
        }


      })()}
     
    editor:
      - name: font_type
        type: expandable
        title: "Font"
        icon: "mdi:format-font"
        schema:
            - label: "Font"
              name: "font"
              selector:
                text: "{}"
      - name: fine_control
        type: expandable
        title: "Fine Control"
        icon: "mdi:format-font"
        schema:
            - name: "letter_spacing"
              label: "Letter Spacing"
              selector:
                number:
                  min: -20
                  max: 50
                  step: 1
                  mode: slider
            - label: "Font Style"
              name: "font_style"
              selector:
                select:
                  options:
                    - normal
                    - italic
                    - oblique
                  mode: dropdown
            - name: "name_font_size"
              label: "Name Font Size"
              selector:
                number:
                  min: 1
                  max: 25
                  step: 1
                  mode: slider
            - name: "state_font_size"
              label: "State Font Size"
              selector:
                number:
                  min: 1
                  max: 15
                  step: 1
                  mode: slider
```

</details>

---

### Screenshot:

<img width="517" alt="Screenshot 2025-02-24 at 11 01 58" src="https://github.com/user-attachments/assets/d35bb717-47cc-4b74-be7f-7d96e0ec2bf9" />
<img width="476" alt="Screenshot 2025-02-24 at 11 02 45" src="https://github.com/user-attachments/assets/89fbdedd-5686-4081-930c-0065bca3e644" />
<img width="1576" alt="Screenshot 2025-02-24 at 11 03 10" src="https://github.com/user-attachments/assets/cddf9488-4024-43fd-8244-1b3354fd4c63" />
