### DISCUSSION TITLE
Sub Button Color on state

### DISCUSSION THREAD

**Discussion by panic-Patrick** [Clooos/Bubble-Card#1298] [Questions about config, custom styles and templates]
### Goal

I want to set a color for my sub button when the state is off.

### Source Yaml

```yaml
type: custom:bubble-card
card_type: separator
name: Draußen
sub_button:
  - entity: input_boolean.automation_toggle
    show_name: true
    icon: mdi:toggle-switch
    tap_action:
      action: toggle
    state_background: true
grid_options:
  columns: 12
  rows: 1
card_layout: large
```

### Read the documentation

- [ ] I have read the documentation
