### DISCUSSION TITLE
Switch colors differ from Slider colors despite same color HEX CODE

### DISCUSSION THREAD

**Discussion by StormFusion** [Clooos/Bubble-Card#1304] [Questions about config, custom styles and templates]
### Goal

![buts](https://github.com/user-attachments/assets/2718a54e-b0c8-4414-95bc-3c57f8002eaa)

Living Room is a Slider, Dining room is a switch, why is the SWITCH color lighter than the Living Room, despite attempting different color settings in the YAML it reminds lighter than the slider buttons, is there a way to fix?

### Source Yaml

```yaml
`type: custom:bubble-card
card_type: button
entity: light.dining_room
use_accent_color: false
show_state: true
show_last_changed: false
show_attribute: false
card_layout: normal
button_type: switch
slider_live_update: false
hold_action:
  action: more-info
double_tap_action:
  action: none
scrolling_effect: false
show_icon: true
icon: mdi:lightbulb
tap_action:
  action: toggle
grid_options:
  columns: 12
  rows: 1
styles: >-
  .bubble-icon { color: ${state === 'on' ?  '#FFFFFF' : '#4C4C4C'} !important;

  }

  .switch-button { background-color: ${state === 'on' ? '#546373' : '#2C2C2C'}
  !important; }
sub_button:
  - tap_action:
      action: none
    hold_action:
      action: none
    icon: mdi:motion-sensor
    entity: switch.hue_motion_sensor_9_motion_sensor_enabled
    double_tap_action:
      action: toggle`
```

### Which step did you already try?

```yaml
Tried a ton of color changing code, even though some changed the colors, none of them made it the same as the slider colors.
```

### Problem

Living Room is a Slider, Dining room is a switch, why is the SWITCH color lighter than the Living Room, despite attempting different color settings in the YAML it reminds lighter than the slider buttons, is there a way to fix?

### Read the documentation

- [X] I have read the documentation
