### DISCUSSION TITLE
[JS+Editor Module] Conditional Subbutton Colors

### DISCUSSION THREAD

**Discussion by HenryJIII** [Clooos/Bubble-Card#1311] [Share your Modules]
# Conditional Subbutton Colors

**Version:** v1.0  
**Creator:** [HenryJIII](https://github.com/HenryJIII)

> [!IMPORTANT] 
> **Unsupported cards:**
>  - Horizontal buttons stack
>  - Pop-up

Add conditional subbutton coloring to up to 6 subbuttons. Chose a color from the dropdown menu and optionally a condition for when it should be active.
Configure this module via the editor or in YAML, for example: 

```yaml
subbutton_colors:
  subbutton1:
    color: red
    condition:
      - condition: state
        entity_id: sensor.your_entity
        state: "your_state"
  subbutton2:
    color: green
```

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply copy and paste the following configuration into your `/www/bubble/bubble-modules.yaml` file.

```yaml
subbutton_colors:
  name: Subbutton Colors
  version: "v1.0"
  creator: "HenryJIII"
  link: "https://github.com/Clooos/Bubble-Card/discussions/1311"
  description: This module adds the ability to customize background colors for subbuttons conditionally.

  unsupported:
    - horizontal-buttons-stack
    - pop-up
    - empty-column

  editor:
    - type: expandable
      name: subbutton1
      title: "Subbutton 1"
      icon: "mdi:list-box-outline"
      schema:
        - name: color
          label: "Background Color"
          selector:
            ui_color:
              include_none: true
        - name: condition
          label: "Color is always applied if no condition is defined. Otherwise, it will be shown when ALL below conditions are fulfilled."
          selector:
            condition: {}

    - type: expandable
      name: subbutton2
      title: "Subbutton 2"
      icon: "mdi:list-box-outline"
      schema:
        - name: color
          label: "Background Color"
          selector:
            ui_color:
              include_none: true
        - name: condition
          label: "Color is always applied if no condition is defined. Otherwise, it will be shown when ALL below conditions are fulfilled."
          selector:
            condition: {}

    - type: expandable
      name: subbutton3
      title: "Subbutton 3"
      icon: "mdi:list-box-outline"
      schema:
        - name: color
          label: "Background Color"
          selector:
            ui_color:
              include_none: true
        - name: condition
          label: "Color is always applied if no condition is defined. Otherwise, it will be shown when ALL below conditions are fulfilled."
          selector:
            condition: {}

    - type: expandable
      name: subbutton4
      title: "Subbutton 4"
      icon: "mdi:list-box-outline"
      schema:
        - name: color
          label: "Background Color"
          selector:
            ui_color:
              include_none: true
        - name: condition
          label: "Color is always applied if no condition is defined. Otherwise, it will be shown when ALL below conditions are fulfilled."
          selector:
            condition: {}

    - type: expandable
      name: subbutton5
      title: "Subbutton 5"
      icon: "mdi:list-box-outline"
      schema:
        - name: color
          label: "Background Color"
          selector:
            ui_color:
              include_none: true
        - name: condition
          label: "Color is always applied if no condition is defined. Otherwise, it will be shown when ALL below conditions are fulfilled."
          selector:
            condition: {}

    - type: expandable
      name: subbutton6
      title: "Subbutton 6"
      icon: "mdi:list-box-outline"
      schema:
        - name: color
          label: "Background Color"
          selector:
            ui_color:
              include_none: true
        - name: condition
          label: "Color is always applied if no condition is defined. Otherwise, it will be shown when ALL below conditions are fulfilled."
          selector:
            condition: {}

  code: |
    ${(() => {
        const config = this.config.subbutton_colors || {};

        const hasColor = (subbuttonConfig) => {
            return !!subbuttonConfig?.color;
        };

        const applyColor = (containerSelector, subbuttonConfig) => {
          if (!hasColor(subbuttonConfig)) {
            return;
          }

          const subbutton = card.querySelector(containerSelector);
          if (!subbutton) return;

          if (!subbuttonConfig?.condition || (subbuttonConfig?.condition && checkConditionsMet([].concat(subbuttonConfig.condition), hass))) {
            subbutton.style.backgroundColor = `var(--${subbuttonConfig.color}-color)`;
          } else {
            subbutton.style.backgroundColor = "";
          }
        };

        Object.values(config).forEach((c, index) => {
          let subbuttonNumber = Number(Object.keys(config)[index].replace("subbutton", ""));
          applyColor(`.bubble-sub-button-${subbuttonNumber}`, c);
        });
        })()}
```

</details>

---

### Screenshot:

![image](https://github.com/user-attachments/assets/581bef7f-4bed-4c6d-90ce-0783aeb6864c)

**Comment by codenzonderschrijven** [comment]
Just what I needed! I can't get this working for some reason. The module won't appear between all the other added modules.

**Reply by HenryJIII** [reply]
Nice to hear that, I would like to help you get this working but its hard to tell without knowing your config. Have you checked your indentations maybe?

**Reply by codenzonderschrijven** [reply]
Thanks for offering your help! I have checked the indentations and also swapped positions of this module between others. I have included my bubble-modules.yaml file.
[bubble-modules.zip](https://github.com/user-attachments/files/19158403/bubble-modules.zip)

**Reply by HenryJIII** [reply]
Your config works for me if I replace mine with yours, so I see nothing wrong with it really.  And it's just my module that doesn't work for you? Maybe start with an empty config and go step by step and adding one module at a time again to see where it fails. And just to be sure to have mentioned it, refresh your browser cache everytime you change your config

**Reply by HenryJIII** [reply]
Also, which beta are you on? The color selector only works on v2.5.0-beta6 and upwards as far as I know

**Reply by codenzonderschrijven** [reply]
It was the cache that needed to be cleared! It can't remember if I've cleared the cache the other times... (I think not). Thanks for your assistance ;)

**Reply by jamessimpson007** [reply]
Hiya, thanks for creating this module. It's fantastic!

Quick query  - I have got the conditional sub-button colors working with state conditions, but I can't get it working with numeric_state or template conditions. Although when I create one of these conditions and test them (using the test button in the dropdown box  which confirms that the condition passes), it doesn't seem to be applied in the card. Is this a bug please? 

Thanks for your help

**Reply by HenryJIII** [reply]
I cannot get it to work right now either. I will have look at why in the coming days.

**Reply by HenryJIII** [reply]
Looks like template conditions are not supported. Numeric conditions should theoretically be working but so far I haven't found a module here where it works. Do you have a module by chance where numerical_state conditions are working?

**Reply by Clooos** [reply]
> Numeric conditions should theoretically be working

This issue is probably on my side, I will check that for the next beta 👌

**Comment by jamessimpson007** [comment]
thank you.
________________________________

**Comment by genesisforlive** [comment]
thx for this,
is it bossible to make this?

if on than green
if off than blue

**Reply by HenryJIII** [reply]
Unfortunately not entirely. You could however define the color in the module for one of the states and then additionally set your default color in the styles section

Something like this 

```
subbutton_colors:
  subbutton1:
    color: deep-orange
    condition:
      - condition: state
        entity_id: light.buro
        state: "on"
styles: |-
  .bubble-sub-button-1 {
    background-color: blue;
  }

```

**Reply by viatro** [reply]
But if custom styles section is used, then it is much simplier to make a solution completely in it, without a module at all:
```css
styles: |-
  .bubble-sub-button-1 {
    background-color: ${hass.states['light.buro'].state === "on" ? "green" : "blue"};
  }
```
@HenryJIII It looks like a room for improvement of your module

**Reply by genesisforlive** [reply]
> But if custom styles section is used, then it is much simplier to make a solution completely in it, without a module at all:
> 
> ```css
> styles: |-
>   .bubble-sub-button-1 {
>     background-color: ${hass.states['light.buro'].state === "on" ? "green" : "blue"};
>   }
> ```
> 
> @HenryJIII It looks like a room for improvement of your module

thix works nice, i hope it comes to a module so its klicky :)

it is possible to use more colores? when i user blue-gray it wont work, or is there i list for the native working colores?

**Reply by viatro** [reply]
> is there i list for the native working colores?

There is a [list of color keywords](https://www.w3.org/TR/css-color-3/#svg-color).
But you can use any color by its [hex-code](https://www.w3schools.com/css/css_colors_hex.asp), or by using [rgb](https://www.w3schools.com/colors/colors_rgb.asp) / [hsl](https://www.w3schools.com/colors/colors_hsl.asp) functions

**Comment by colinhuliselan** [comment]
Hi!

Love the module! I’m running into an issue with a conditional button color where "not" conditions don’t seem to work as expected. In the example below (in which both conditions are equal, obviously), the condition doesn’t trigger the color change (it seems to evaluate to False). However, if I comment out the "not" block, the color works as expected:
```
subbutton_colors:
  subbutton1:
    color: primary
    condition:
      - condition: state
        entity_id: light.all_lights
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: light.all_lights
            state: "off"
```
New to HA, so I might be missing something obvious! Any guidance would be appreciated!
