### DISCUSSION TITLE
Looking to change background Color of Sub-Button based on State (Temperature)

### DISCUSSION THREAD

**Discussion by MarqBarq** [Clooos/Bubble-Card#1316] [Questions about config, custom styles and templates]
### Goal

Working on a dashboard for some devices rack mounted in my basement. In this case a Synology NAS.

 I'm wanting to change the color of the background of a sub-bubble based on the temperature of the server.  

I found the code I am using on another example here and trying to modify it. I will be honest, I'm very new to this. 

Want to change the background Green under 110 and Red over 155 and orange between the two. 

<img width="800" alt="Screenshot 2025-03-07 170348" src="https://github.com/user-attachments/assets/f3429622-34b1-4d44-958b-dba28c82c978" />

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: state
name: CPU
icon: mdi:cpu-64-bit
sub_button:
  - entity: sensor.XX_basement_volume_1_used_space
    show_state: true
    state_background: false
    icon: mdi:file
  - entity: sensor.XX_basement_volume_1_total_size
    name: Total
    icon: mdi:harddisk-plus
    show_last_changed: false
    show_icon: true
    show_state: true
    state_background: false
  - show_state: true
    show_icon: false
    show_background: true
    state_background: false
    entity: sensor.XX_basement_volume_1_volume_used
    name: "Used "
    show_name: true
  - entity: sensor.XX_basement_memory_available_real
    show_name: false
    show_state: true
    state_background: false
    icon: mdi:memory
  - entity: sensor.XX_basement_temperature
    show_state: true
    state_background: false
  - entity: update.XX_basement_dsm_update
    show_state: true
    icon: mdi:update
grid_options:
  columns: full
entity: sensor.XX_basement_cpu_utilization_total
scrolling_effect: false
show_attribute: false
attribute: state_class
styles: |-
  .bubble-sub-button-5 {
    background-color: ${state > 155 ? 'red' : state < 110 ? 'green' : 'orange'} !important;
  }
```

### Which step did you already try?

```yaml
About everything. It is random. This is what I cobbled together based on another example. 

.bubble-sub-button-5 {
    background-color: ${state > 155 ? 'red' : state < 110 ? 'green' : 'orange'} !important;
  }
```

### Problem

It does not work. Any help would be grateful. I want to solve this before I go and add it to the disks. 

### Read the documentation

- [X] I have read the documentation
