### DISCUSSION TITLE
Make the popup appear as an actual popup

### DISCUSSION THREAD

**Discussion by frozenhellguard** [Clooos/Bubble-Card#1359] [Questions about config, custom styles and templates]
### Goal

As can be seen in a few screenshots here, for example: https://github.com/Clooos/Bubble-Card/discussions/305

Loving the card and I use the popups as is on my mobile with a set height, works wonders! I'm trying to incorporate them in my new tablet dashboard now, but I feel that the current function of the popups is not what I'm looking for. Hence why I'm using browser_mod popups for now, but I'd love to use Bubble Card instead!

I'm trying to get the popup to not be attached to the bottom of the screen for my tablet dashboard. I want them to appear in the middle of the screen instead and either set the height to fit the content or set the height manually. Is this possible at all? Didn't get any of the code snippets from the other topic to work, might be due to outdated code, etc.

Thanks in advance! 

### Source Yaml

```yaml
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        hash: "#media"
        icon: fas:computer
        styles: |
          #root.pop-up.is-popup-opened {
            transform: scale(1) translate(0, -50%);
            display: flex;
          }

          #root.pop-up {
            top: calc(50% + var(--header-height));
            transform: scale(0) translate(0, 50%);
            display: none;
            max-height: 100%
          }
        show_header: false
        button_type: slider
        entity: media_player.hall_2
        show_icon: true
        show_state: false
        show_last_changed: false
        show_attribute: false
        card_layout: normal
      - type: custom:bubble-card
        card_type: media-player
        entity: media_player.hall_2
        button_type: slider
      - type: custom:bubble-card
        card_type: media-player
        entity: media_player.kontor_2
        show_state: false
        show_attribute: false
      - type: custom:bubble-card
        card_type: media-player
        entity: media_player.kok_2
```

### Which step did you already try?

```yaml
#root.pop-up.is-popup-opened {
  transform: scale(1) translate(0, -50%);
  display: flex;
}

#root.pop-up {
  top: calc(50% + var(--header-height));
  transform: scale(0) translate(0, 50%);
  display: none;
  max-height: 100%
}
```

### Read the documentation

- [X] I have read the documentation
