### DISCUSSION TITLE
Sub button change colour when certain entities are on

### DISCUSSION THREAD

**Discussion by davelegg83** [Clooos/Bubble-Card#1360] [Questions about config, custom styles and templates]
### Goal

I've got a bubble card called Garden.
![garden](https://github.com/user-attachments/assets/c4e25e3e-08be-4b30-8682-af9f9c7aa766)
When this is clicked, it turns on evrything except my flood lights and porch light.
![lights](https://github.com/user-attachments/assets/cb13d1fc-080c-43d2-a4b6-8494777e7430)

However is there a way if all the lights are off, except the Flood Lights or Porch Light that the ... icon will change colour so I know something is switched on outside?

### Source Yaml

```yaml
      - type: custom:bubble-card
        card_type: button
        entity: light.outside_lights
        sub_button:
          - entity: light.garden_floods
            icon: mdi:dots-horizontal
            tap_action:
              action: navigate
              navigation_path: "#outside"
            visibility: []
        name: Garden
    columns: 2
columns: 1
```

### Read the documentation

- [X] I have read the documentation
