### DISCUSSION TITLE
[Example] Auto-Entity Battery Card with Sliders

### DISCUSSION THREAD

**Discussion by Zerosignal84** [Clooos/Bubble-Card#1368] [Share your custom styles, templates and dashboards]
With the new slider update now showing battery states as a percentage of the bar I decided to switch my old auto populated battery card over to bubble!

Cards & Integrations used:

1. The excellent Battery Notes integration - https://github.com/andrew-codechimp/HA-Battery-Notes
2. Lovelace auto entities card - https://github.com/thomasloven/lovelace-auto-entities
3. Bubblecard 2.5 Beta 9

This is what the current auto population looks like, I might play around with the styling some more or maybe event take some advice from the gurus here.

Hope somebody finds this useful!

![image](https://github.com/user-attachments/assets/3180e990-c244-49c9-a858-e476d1a38739)

```
type: custom:auto-entities
card:
  square: false
  type: grid
  columns: 1
card_param: cards
filter:
  include:
    - entity_id: sensor.*battery_plus*
      options:
        type: custom:bubble-card
        card_type: button
        button_type: slider
        show_last_changed: true
        show_state: true
        read_only_slider: true
        scrolling_effect: false
        sub_button:
          - show_state: false
            show_icon: false
            state_background: false
            show_background: false
            show_attribute: true
            attribute: battery_type_and_quantity
        modules:
          - default
  exclude: []
sort:
  method: state
  numeric: true
  reverse: false
show_empty: true
```

**Comment by MetalOnes** [comment]
I like this, thanks!  
I added conditional backgrounds by adding this style to the cards. Adjust the thresholds and RGB values as desired.
```
.bubble-range-fill {  
  background-color: rgba(${state > 50.0 ?  '39, 174, 96' : state > 20.0 ? '243, 156, 18' : '192, 57, 43'}, 0.4) !important;
}
```
![image](https://github.com/user-attachments/assets/ef1d3d1a-baf0-415f-9d07-0c64bf9bd138)

**Comment by viatro** [comment]
For those who want to automatically get rid of 'Battery+' part of entity name, here is template filter version:
```yaml
type: custom:auto-entities
card:
  type: vertical-stack
card_param: cards
filter:
  template: >-
    {% for state in states.sensor if "battery_plus" in state.entity_id -%}
      {{
        {
          "type": "custom:bubble-card",
          "card_type": "button",
          "button_type": "slider",
          "entity": state.entity_id,
          "name": state.attributes.friendly_name.split(' Battery')[0],
          "show_last_changed": true,
          "show_state": true,
          "read_only_slider": true,
          "scrolling_effect": false,
          "sub_button": [
            {
              "show_state": false,
              "show_icon": false,
              "state_background": false,
              "show_background": false,
              "show_attribute": true,
              "attribute": "battery_type_and_quantity"
            }
          ],
          "modules": [
            "default"
          ]
        }
      }},
    {%- endfor %}
sort:
  method: state
  numeric: true
  reverse: false
show_empty: true
```

**Reply by Soukyuu** [reply]
I got to almost what I want to have, but I can't seem to be able to do a 
`"entity": state.entity_id.replace('plus', 'replaced'),`
for the second button in that syntax you used. I'd like the second subbutton to issue a click on the corresponding _replaced button. Do you have an idea?

```
type: custom:auto-entities
card:
  square: false
  type: grid
  columns: 1
card_param: cards
filter:
  template: |-
    {%- for state in states.sensor if "battery_plus" in state.entity_id -%}
      {{
        {
          "entity": state.entity_id,
          "name": state.attributes.friendly_name.split(' Batterie')[0],
          "type": "custom:bubble-card",
          "card_type": "button",
          "button_type": "slider",
          "show_last_changed": true,
          "show_state": true,
          "read_only_slider": true,
          "scrolling_effect": false,
          "styles": ".bubble-range-fill {  \n  background-color: rgba(${state > 50.0 ?  '39, 174, 96' : state > 20.0 ? '243, 156, 18' : '192, 57, 43'}, 0.4) !important;\n}\n${(() => {\n  let date = new Date(hass.states[entity].attributes['battery_last_replaced']);\n  let options = {\n    weekday: \"short\",\n    year: \"numeric\",\n    month: \"short\",\n    day: \"numeric\",  \n  }\n  card.querySelector('.bubble-sub-button-2').innerText = hass.states[entity].attributes['battery_last_replaced'] == null ?\n  \"Never replaced\" : date.toLocaleDateString(undefined, options);\n  })()\n}",
          "sub_button": [
              {
                  "show_state": false,
                  "show_icon": false,
                  "state_background": false,
                  "show_background": false,
                  "show_attribute": true,
                  "attribute": "battery_type_and_quantity"
              },
              {
                  "show_name": true,
                  "show_state": false,
                  "show_icon": false,
                  "state_background": false,
                  "show_background": false,
                  "tap_action": {
                      "action": "toggle"
                  }
              }
          ],
          "modules": [
              "home-assistant-default"
          ]
        }
      }},
    {%- endfor -%}
sort:
  method: state
  numeric: true
  reverse: false
  ip: false
  ignore_case: false
show_empty: true
visibility:
  - condition: state
    state_not: ""

```

So far this shows up like this:
![image](https://github.com/user-attachments/assets/c85ad18d-417a-4b41-8620-0bbb067f93d0)

**Reply by Soukyuu** [reply]
Finally got a working "replace" sub-button:
```
type: custom:auto-entities
card:
  square: false
  type: grid
  columns: 1
card_param: cards
filter:
  template: |-
    {%- for state in states.sensor if "battery_plus" in state.entity_id -%}
      {{
        {
          "entity": state.entity_id,
          "name": state.attributes.friendly_name.split(' Batterie')[0],
          "type": "custom:bubble-card",
          "card_type": "button",
          "button_type": "slider",
          "show_last_changed": true,
          "show_state": true,
          "read_only_slider": true,
          "scrolling_effect": false,
          "styles": ".bubble-range-fill {  \n  background-color: rgba(${state > 50.0 ?  '39, 174, 96' : state > 20.0 ? '243, 156, 18' : '192, 57, 43'}, 0.4) !important;\n}\n${(() => {\n  let date = new Date(hass.states[entity].attributes['battery_last_replaced']);\n  let options = {\n    weekday: \"short\",\n    year: \"numeric\",\n    month: \"short\",\n    day: \"numeric\",  \n  }\n  card.querySelector('.bubble-state').innerText = hass.states[entity].state + '% - ersetzt: ' + (hass.states[entity].attributes['battery_last_replaced'] == null ?\n  \"nie\" : date.toLocaleDateString(undefined, options));\n  })()\n}",
          "sub_button": [
              {
                  "show_state": false,
                  "show_icon": false,
                  "state_background": false,
                  "show_background": false,
                  "show_attribute": true,
                  "attribute": "battery_type_and_quantity"
              },
              {
                  "show_name": true,
                  "show_state": false,
                  "show_icon": false,
                  "state_background": true,
                  "show_background": true,
                  "tap_action": {
                      "action": "perform-action",
                      "perform_action": "button.press",
                      "target": {
                        "entity_id": state.entity_id | replace('sensor.', 'button.') | replace('_plus', '_replaced')
                        }  
                  },
                  "name": "Ersetzen"
              }
          ],
          "modules": [
              "home-assistant-default"
          ]
        }
      }},
    {%- endfor -%}
sort:
  method: state
  numeric: true
  reverse: false
  ip: false
  ignore_case: false
show_empty: true
visibility:
  - condition: state
    state_not: ""
```
![image](https://github.com/user-attachments/assets/e810a441-034e-4489-850c-2e4aa660f18f)

**Reply by fbloemhof** [reply]
Awesome, did some small adjustments on this one to make it a little more flexible for other languages:
- filter > 75% out
- use the name of the replace entity button instead of hard coded name
- splitted the friendly name based on the last word instead of hard coded name
- Removed the "ersetzt:"

Only "never" remains, not sure yet how to change that.

```
type: custom:auto-entities
card:
  square: false
  type: grid
  columns: 1
card_param: cards
filter:
  template: |-
    {%- for state in states.sensor if "battery_plus" in state.entity_id and (state.state | float(100)) < 75 -%}
      {{
        {
          "entity": state.entity_id,
          "name": state.attributes.friendly_name.rsplit(' ', 1)[0],
          "type": "custom:bubble-card",
          "card_type": "button",
          "button_type": "slider",
          "show_last_changed": true,
          "show_state": true,
          "read_only_slider": true,
          "scrolling_effect": false,
          "styles": ".bubble-range-fill {  \n  background-color: rgba(${state > 50.0 ?  '39, 174, 96' : state > 20.0 ? '243, 156, 18' : '192, 57, 43'}, 0.4) !important;\n}\n${(() => {\n  let date = new Date(hass.states[entity].attributes['battery_last_replaced']);\n  let options = {\n    weekday: \"short\",\n    year: \"numeric\",\n    month: \"short\",\n    day: \"numeric\",  \n  }\n  card.querySelector('.bubble-state').innerText = hass.states[entity].state + '% - ' + (hass.states[entity].attributes['battery_last_replaced'] == null ?\n  \"never\" : date.toLocaleDateString(undefined, options));\n  })()\n}",
          "sub_button": [
              {
                  "show_state": false,
                  "show_icon": false,
                  "state_background": false,
                  "show_background": false,
                  "show_attribute": true,
                  "attribute": "battery_type_and_quantity"
              },
              {
                  "show_name": true,
                  "show_state": false,
                  "show_icon": false,
                  "state_background": true,
                  "show_background": true,
                  "tap_action": {
                      "action": "perform-action",
                      "perform_action": "button.press",
                      "target": {
                        "entity_id": state.entity_id | replace('sensor.', 'button.') | replace('_plus', '_replaced')
                        }  
                  },
                  "name": states[state.entity_id | replace('sensor.', 'button.') | replace('_plus', '_replaced')].attributes.friendly_name.rsplit(' ', 2)[-2] ~ ' ' ~ states[state.entity_id | replace('sensor.', 'button.') | replace('_plus', '_replaced')].attributes.friendly_name.rsplit(' ', 2)[-1]
              }
          ],
          "modules": [
              "home-assistant-default"
          ]
        }
      }},
    {%- endfor -%}
sort:
  method: state
  numeric: true
  reverse: false
  ip: false
  ignore_case: false
show_empty: true
visibility:
  - condition: state
    state_not: ""
```

![image](https://github.com/user-attachments/assets/faadb591-d359-4e32-a0b1-bb925a11045d)

**Reply by Soukyuu** [reply]
The "ersetzt:" (replaced) part was to signify it's the date the battery was replaced on instead of last changed date as in original.

The "nie" (never) part is just to signify it was, well, never replaced instead of showing null, maybe there is a home assistant function to localize that, I'm not sure.

**Comment by palhaca** [comment]
i had some trouble so i leave my version for those that had the same problem:


```
type: custom:auto-entities
card:
  square: false
  type: grid
  columns: 1
card_param: cards
filter:
  include:
    - entity_id: sensor.*battery*
      options:
        type: custom:bubble-card
        card_type: button
        button_type: slider
        show_last_changed: true
        show_state: true
        read_only_slider: true
        scrolling_effect: false
        styles: |-
          .bubble-range-fill {  
            background-color: rgba(${state > 50.0 ?  '39, 174, 96' : state > 20.0 ? '243, 156, 18' : '192, 57, 43'}, 0.4) !important;
          }
        sub_button:
          - show_state: false
            show_icon: false
            state_background: false
            show_background: false
            show_attribute: true
            attribute: battery_type_and_quantity
        modules:
          - default
  exclude: []
sort:
  method: state
  numeric: true
  reverse: false
  ip: false
  ignore_case: false
show_empty: true
visibility:
  - condition: state
    state_not: ""
```
