### DISCUSSION TITLE
[Styling Module] Pop-Up Box

### DISCUSSION THREAD

**Discussion by octoTurnip** [Clooos/Bubble-Card#1376] [Share your Modules]
# Pop-Up Box

**Version:** v1.6
**Creator:** [octoTurnip](https://github.com/octoTurnip)

> [!IMPORTANT] 
> **Supported cards:**
>  - Pop-up

My module styles your Bubble-Pop-Up card to look like the Home Assistant's more-info dialogue Pop-Up box.
Enable this module via the editor.

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply copy and paste the following configuration into your `/www/bubble/bubble-modules.yaml` file.

```yaml
more_info_popup:
  name: "Pop-Up Box"
  version: "v1.6"
  creator: "octoTurnip"
  link: "https://github.com/Clooos/Bubble-Card/discussions/1376"

  supported:
    - pop-up

  description: |
    This will style the pop-up to look like a more-info style pop-up.

  code: |
    #root:not(.editor) {
      top: ${this.config.more_info_popup?.center ? 'auto' : this.config.more_info_popup?.top || '40px'} !important;
      margin-left: auto !important;
      margin-right: auto !important;
      bottom: ${this.config.more_info_popup?.bottom || 'auto'} !important;
      height: auto !important;
      max-height: ${this.config.more_info_popup?.max_height || 'calc(100% - 72px)'} !important;
      width: 96%;
      --desktop-width: ${this.config.more_info_popup?.dt_width || '60vw'} !important;
      align-self: ${this.config.more_info_popup?.center ? 'anchor-center' : 'none'};
      transition: ${this.config.more_info_popup?.window_speed || 'all 0.4s ease'} !important;
    }
    .bubble-pop-up-container {
      padding: 20px !important;
      mask-image: none !important;
      overflow: scroll;
      grid-gap: 7px;
    }
    .bubble-pop-up-background {
      border-radius: ${this.config.more_info_popup?.b_radius || '20px'} !important;
      border: ${this.config.more_info_popup?.border || 'solid 1px var(--primary-color)'} !important;
    }
    .bubble-backdrop {
      background-color: ${this.config.more_info_popup?.bg_color || 'rgba(0, 0, 0, 0.2)'} !important;
      backdrop-filter: ${this.config.more_info_popup?.bd_filter || 'blur(10px)'} !important;
      transition-delay: 0 !important;
      transition: opacity 0.2s !important;
    }
    .bubble-backdrop.is-visible {
      opacity: 0.7 !important;
    }
    .is-popup-closed:not(.editor) { 
      transform: ${this.config.more_info_popup?.window_ani === 'customUserInput' ? this.config.more_info_popup?.customInput : this.config.more_info_popup?.window_ani || 'scale(0.1)'} !important;
      opacity: ${this.config.more_info_popup?.window_ani === 'scale(0.1)' ? '0.1' : 'null'} !important;
      transition: opacity 0.4s ease !important;
    }
    .is-popup-opened {
      opacity: 1 !important;
      transition: opacity 0.4s ease !important;
    }
  editor:
    - name: center
      label: Place box in the center?
      selector:
        boolean: {}
    - type: expandable
      title: Position & Box Settings
      expanded: false
      schema:
        - name: top
          label: Distance from the top of the screen
          selector:
            text: {}
          default: 40px
        - name: bottom
          label: How big the Pop-Up box will be
          selector:
            text: {}
          default: auto
        - name: max_height
          label: Max length the box can grow to
          selector:
            text: {}
          default: calc(100% - 72px)
        - name: dt_width
          label: Width of the desktop Pop-Up
          selector:
            text: {}
          default: 60vw
        - name: b_radius
          label: Border radius
          selector:
            text: {}
          default: 20px
        - name: border
          label: Border Style
          selector:
            text: {}
          default: solid 1px var(--primary-color)
    - type: expandable
      title: Extra fun settings
      expanded: false
      schema:
        - name: bg_color
          label: Background Color
          selector:
            text: {}
          default: rgba(0, 0, 0, 0.2)
        - name: bd_filter
          label: Backdrop Filter
          selector:
            text: {}
          default: blur(10px)
        - name: window_speed
          label: Window Speed
          selector:
            text: {}
          default: all 0.4s ease
        - name: window_ani
          label: Window animation style
          selector:
            select:
              options:
                - label: HA Style
                  value: scale(0.1)
                - label: Bubble Style (bottom to top)
                  value: translateY(150%)
                - label: Right to left
                  value: translateX(150%)
                - label: Twirl
                  value: rotate(360deg) translateY(150%)
                - label: Lean
                  value: skewX(90deg)
                - label: Custom
                  value: customUserInput
              multiple: false
              custom_value: false
              mode: list
        - name: customInput
          label: Your Custom CSS
          selector:
            text: {}
```

</details>

---

### Screenshot:

**Desktop** _(v1.4)_: 
![v1_4_desktop](https://github.com/user-attachments/assets/a85967cb-875c-40f0-a056-72167b486ba0)

**Mobile** _(v1.4)_: 
<img src="https://github.com/user-attachments/assets/8dc3f537-cb04-4e55-8e36-449f11ed88f9" width="50%" height="50%">

## Quick notes:
Per Home Assistant Frontend style:
- The max-height for desktop should be `calc(100% - 72px)` but I cannot get the module to style the height differently for mobile and desktop <sub>(maybe i can get help)</sub>.
    - Instead I've changed it to `70vh` that way the bottom will still wrap if you don't have too many cards in it.
- The desktop width should be `90vw` but i changed it to `60vw` because I think it makes the Bubble Pop-Up look better.
    - One thing I've tried to solve this was to make it look like a "Grid-layout" but, it can look weird depending on what cards you are using in the Pop-up. If you'd like to try it, use the following code in your styles: 
    ```
    .bubble-pop-up-container{
      display: grid;
      grid: auto auto / auto auto;
      grid-gap: 10px;
      align-items: start;
    }
    ```
- There is no outlines on regular Pop-up's. But on mine I added `border: solid 1px var(--primary-color);`.
    - This is so you can tell it apart from the others.
    - It also uses your primary color as the outline: `var(--primary-color)`
- Home Assistant's default way of showing Pop-Up's make it "pop" up (lol). So that is reflected in this module as the default option over the normal "Bubble" card way you're used to. 
  - you can change this in the config editor settings. 

### Editor Settings

| Setting | Default | Description | Example Inputs |
|:-:|:-:|:-:|:-:|
| Place box in the center? | off | Places the pop-up in the center of the screen. **Please read the warning below!** | N/A |
| Distance from the top of the screen | `40px` | Sets the top of the pop-up to this y-level of the screen | `0px` , `10vh` |
| How big the Pop-Up box will be | `auto` | How big do you want the pop-up container to always be | `100%` , `20vh` |
| Max length the box can grow to | `calc(100% - 72px)` | Sets the maximum length a pop-up box can be | `100%` , `100vh` |
| Width of the desktop Pop-Up | `60vw` | Changes how wide the pop-up will be on desktop only | `210px` , `100%` |
| Border radius | `20px` | Changes the corner shape of the pop-up box | `15px 50px` , `15px 50px 30px 5px` |
| Border Style | `solid 1px var(--primary-color)` | How the border up the pop-up box looks like | `none` , `dotted 5px red` |
| v | EXTRA | SETTINGS | v |
| Background Color | `rgba(0, 0, 0, 0.2)` | Change what color *BEHIND* the pop-up is | `red` , `rgba(from var(--primary-color) r g b / 0.2)` |
| Backdrop Filter | `blur(10px)` | How you want the background *BEHIND* the pop-up to be | `none` , `saturate(7)` |
| Window Speed | `all 0.4s ease` | Sets the animation speed for opening & closing the pop-up | `all 2s ease` , `all 0.4s width` |
| Window animation style | HA Style `scale(0.1)` | Select from the options on how you want the pop-up animation to look like when opening & closing | N/A |

**Recommendations & Warnings**
- `Place box in the center?` **PLEASE BE AWARE** as of this update (v1.4) Safari on iPhone has not updated their CSS library to make this work.
  - iPhone may show a blank screen
  - This works perfectly fine on Android devices!
- `How big the Pop-Up box will be` will make the container always be that size unless kept at `auto`
- `Width of the desktop Pop-Up` streches the pop-up and its items and may not look the best if set too high
  - Keep a lookout for future updates because I may have something fun planned for this!
- `Border radius` set too high will overlap with the bubble-header
- `Window Speed` is HARD CODED to be `0.3s` and anything set over that will not chow when closing the pop-up!

**Extra Settings**
- Change the background color and effect to add some personalization to your pop-ups.
- You can also change the speed and animation style of when the pop-up comes on screen.
How they look:

| HA Style | Bubble Style | Right to Left | Twirl | Lean |
|:-:|:-:|:-:|:-:|:-:|
| <video src="https://github.com/user-attachments/assets/b8a3d14a-7727-4624-b8cd-406983849893" width="50%" height="50%" controls></video> | <video src="https://github.com/user-attachments/assets/d8cb1055-3f8a-4907-8fd8-c14193bdb5c0" width="50%" height="50%" controls></video> | <video src="https://github.com/user-attachments/assets/02663a49-8a05-4ce7-bdf8-a111d5c32fe1" width="50%" height="50%" controls></video> | <video src="https://github.com/user-attachments/assets/52471160-b827-4c55-9666-cee7c4633984" width="50%" height="50%" controls></video> | <video src="https://github.com/user-attachments/assets/6b5bd2b7-0a7d-4192-be44-28db94c4ba11" width="50%" height="50%" controls></video> |

Use [w3schools](https://www.w3schools.com/) website to learn all the amazing things you can do with CSS.

### v1.6
- removed my development variables with the correct ones 🫠
- added videos of the new window animations
- spelling, spacing, and grammer

### v1.5
- fixed animation speed not working due to my bad coding lol
- added `Swirl` and `Lean` to pop-up animations to pick from
- you can now add your own custom animations by choosing `Custom` from the list, then inputing the CSS code below it
  - please make sure to read the warnings before asking me for help :)

### v1.4
**\*\*PLEASE RE-READ THE DESCRIPTION\*\***
- center screen pop-up's are back baby!
  - <img src="https://github.com/user-attachments/assets/c7e4cfa9-8013-4e9d-974c-2b185636e126" width="50%" height="50%">
  - use the config editor to enable the option
- added more styling options
- fixed stutters in the animations
- fixed open/close animations

Thank you everyone for your inputs and feedback! as always, please let me know if you'd like to see anything else!

### v1.3
- due `align-self: anchor-center` being incompatible with Safari and iOS, I have changed the position of the pop-up box. It now follows the style of Home Assistant Frontend and puts it at the top. 
  - On a personal note: I actually enjoy it being in the center of the screen so until I can find a way where it will fit all devices, this will be the norm.
- **GOOD NEWS!** I figured out how to use the editor and so now you have that option too! Options at this release are for the outline border and sizing of the pop-up box. If you don't like the options I have set, you now have the ability to change it to what you like. Please let me know if there are more options you would like to see changed.

### v1.2
- added `overflow: scroll;` to the container in case there are sizing issues. That way you wont lose any card details.
- fixed dropdown boxes. They used to look like this: 
<img src="https://github.com/user-attachments/assets/97376a8b-2d76-4c8a-9829-73863f34e66c" width="30%" height="30%">

### v1.1
- pop-up box now automatically resizes depending on how many cards there are
- changed the desktop width so cards don't look so stretched out

### v1.0
- *Initial release*

**Comment by octoTurnip** [comment]
Updated to v1.1 :)
- pop-up box now automatically resizes depending on how many cards there are
- changed the desktop width so cards don't look so stretched out

~~_(I will upload updated photos later)_~~

**Comment by cwrau** [comment]
Hey, sounds like a great module, but I couldn't find out how to use it? 😅

**Reply by octoTurnip** [reply]
I guess I don't understand. Are you having problems with all modules working or just mine? 

Maybe if you post your yaml I can see what's wrong.

**Reply by Clooos** [reply]
Have you installed Bubble Card v3.0.0-beta? The module feature is only available in this version.

**Reply by cwrau** [reply]
@Clooos Yes! That's what I was missing! Thank you 🙏

The module works perfectly, thanks @octoTurnip!

**Comment by octoTurnip** [comment]
Updated to v1.2 !!!
- added `overflow: scroll;` to the container in case there are sizing issues. That way you wont lose any card details.
- fixed dropdown boxes.

Let me know if there are any styling changes or other features you would like to see!

**Reply by Arbujl** [reply]
Hello, seems this module does not work anymore, maybe since new HAOS version. Not sure....
HAOS: 2025.5.3
Bubble Card: 3.0.0-beta.7
Pop-up Box module: 1.2

type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#lights"
    button_type: name
    name: Toutes les Lampes
    icon: mdi:lightbulb-group-outline
    width_desktop: 550px
    margin_top_mobile: calc(100vh - 700px)
    margin_top_desktop: calc(100vh - 700px)
    styles: |
      #root {
          border-radius: 14px;
          border: solid 1px var(--primary-color);
      }
      .bubble-button-card-container {
          background: rgba(100,140,180,0.7) !important;
      }
    auto_close: "25000"
    modules:
      - more_info_popup
    show_header: true
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - options:
            type: custom:bubble-card
            card_type: button
            button_type: switch
            show_last_changed: true
            show_state: true
            read_only_slider: false
            scrolling_effect: false
          group: light.lights_all_house
      exclude: []
    sort:
      method: state
      numeric: false
      reverse: true
    show_empty: true

**Reply by octoTurnip** [reply]
I'm sorry to hear that! Are you able to share a screenshot and a little more detail of your problem? Like:

- is it loading at all
- what does it look like
- are you using iPhone or Android 
- are any of the other modules working

Thank you for the feedback! I hope we can solve this😊

**Reply by Arbujl** [reply]
Thanks for your prompt reply.
The other modules I'm using are OK.
When I remove "more_info_popup" the popup can be launched. 
like this...
<img width="835" alt="Capture d’écran 2025-05-24 à 15 01 53" src="https://github.com/user-attachments/assets/d7219345-3ea9-4878-985e-b84b2c88773a" />
when "more_info_popup" is activated, the background darkens but the popup does not open... or is not visible...
<img width="639" alt="Capture d’écran 2025-05-24 à 15 06 27" src="https://github.com/user-attachments/assets/0157980a-f90e-4283-b80b-6f113016be76" />

**Reply by octoTurnip** [reply]
I tried to recreate your problem on my setup but haven't gotten the same results as you. If you haven't already, here are some troubleshooting tips I would suggest: 

- start off by deleting your frontend cashe
- restart home assistant 
- copy and paste my module code into your "styles" section of your pop-up and dissect it piece by piece to see what the problem might be. 

Unfortunately it can be a multitude of things, but because I've been unable to get the same error you're having, I can only suggest those tips. It could be a beta bug or just that one device... Anyways.

But please let me know if you do find or do something! You never know what we can solve together. Look forward to hearing from you! Cheers

**Reply by Arbujl** [reply]
Ok thanks for your reply...
Did some tests with Google chrome under apple, all good 👍 
under Safari, it's not OK. 
Cache cleared, HA reboot done, same issue.
Will check on my different screens (mainly Edge) when I will come back from traveling 
Thanks for your support

**Reply by Arbujl** [reply]
Hello @octoTurnip, On Edge all good, but same issue on IOS.
Too bad, I liked the simplicity.

**Reply by Clooos** [reply]
Have you checked in the Bubble Card editor, at the bottom if you have the correct version on iOS?

**Reply by Arbujl** [reply]
On IOS I have v3.0.0-beta.7 for Bubble Card and v1.2 pour the module.
Not sure to understand where can I found what you said ….

**Reply by dragonlee429** [reply]
I have the exact same issue, works on chrome with window laptop, but when tested on iphone it shows nothing.

**Reply by Clooos** [reply]
> On IOS I have v3.0.0-beta.7 for Bubble Card and v1.2 pour the module. Not sure to understand where can I found what you said ….

Forget what I said, I have this issue as well on Safari Mac and on iOS.

**Reply by octoTurnip** [reply]
Hey y'all. Sorry for getting back late but I've been on vacation. 

I think it might be a bug with iPhone/Apple. I used my wife's phone and she has the same problem. 

What I've done is
- removed the module from the popup
- hard refreshed 
- restarted home assistant 

But none of that has worked. I'm not a programmer and all of what I've made for this module has been stuff I've just picked up over the years. 

Switching from translate/transform to just transform gave better results. But I will continue to work on this. 

Maybe it's not a bug with iPhone, and it was just my recent update. I'll update when I get back from vacation! Thank you all for holding out!

**Reply by dragonlee429** [reply]
Hello! Thank you for your feedback. I am really looking forward to this module, it's a last piece that will finish my dashboard. :) I will also look for the solution myself as well. Cheers

**Reply by octoTurnip** [reply]
So I'm back working on it and did a little research. Apparently in the CSS `align-self: anchor-center` the "anchor-center" part is incompatible with Safari and iOS. My only problem tho is that the code I used before `transform: translate(0, -50%) !important` worked **but** whenever you needed to use a dropdown menu, it was always off. 

Does anyone have an idea to help solve this (or why Safari is lagging behind)? I mean I can always just manually put variables in to set the box, but it wont look as clean.

Current code (not working on Safari/iOS):
```
#root:not(.editor){
  top: auto !important;
  height: auto !important;
  max-height: 70vh !important;
  width: 97%;
  --desktop-width: 60vw !important;
  margin-left: auto !important;
  margin-right: auto !important;
  bottom: auto !important;
  align-self: anchor-center;
}
```

Old code (that _kinda_ worked):
```
#root:not(.editor){
  top: 50% !important;
  transform: translate(0, -50%) !important;
  height: auto !important;
  max-height: 70vh !important;
  width: 97%;
  --desktop-width: 60vw !important;
  margin-left: auto !important;
  margin-right: auto !important;
  bottom: auto !important;
}
```

**Reply by octoTurnip** [reply]
@Clooos I know you're probably busy but I wanted to test something out before i updated my module again. Do you happen to have an apple device? if so, do you think you can replace the `#root` portion of the code with the following:
```yaml
#root:not(.editor){
  top: auto !important;
  height: auto !important;
  max-height: 70vh !important;
  width: 97%;
  --desktop-width: 60vw !important;
  margin-left: auto !important;
  margin-right: auto !important;
  bottom: auto !important;
  align-self: anchor-center;
}
```
It seems like safari was updated and that my old code might work again, but don't have any way to test it at the moment. Thanks in advance!

**Comment by octoTurnip** [comment]
Updated to v1.3!!!
- due `align-self: anchor-center` being incompatible with Safari and iOS, I have changed the position of the pop-up box. It now follows the style of Home Assistant Frontend and puts it at the top. 
  - On a personal note: I actually enjoy it being in the center of the screen so until I can find a way where it will fit all devices, this will be the norm.
- **GOOD NEWS!** I figured out how to use the editor and so now you have that option too! Options at this release are for the outline border and sizing of the pop-up box. If you don't like the options I have set, you now have the ability to change it to what you like. Please let me know if there are more options you would like to see changed.

**Comment by TimBeekman** [comment]
Great module—this is exactly what I needed! Keep up the awesome work.

I did notice a small issue: when closing the pop-up, it still seems to try running the animation, which causes a bit of a glitchy effect. Just wondering—has anyone else reported this?

**Reply by octoTurnip** [reply]
Wow you're right! I don't know how I never really noticed this before 😅 

Thanks for pointing it out! I'll have an update soon hopefully.

**Reply by octoTurnip** [reply]
@TimBeekman So i should have it fixed now but wanted to test something out before i updated it. Do you happen to have an apple device? if so, do you think you can replace the `#root` portion of the code with the following:
```yaml
#root:not(.editor){
  top: auto !important;
  height: auto !important;
  max-height: 70vh !important;
  width: 97%;
  --desktop-width: 60vw !important;
  margin-left: auto !important;
  margin-right: auto !important;
  bottom: auto !important;
  align-self: anchor-center;
}
```
It seems like safari was updated and that my old code might work again, but don't have any way to test it at the moment. Thanks in advance!

**Reply by octoTurnip** [reply]
Module updated and fixed this issue. Also included some nice extra animations to give a whirl if you want. Hope you enjoy!

**Comment by cwrau** [comment]
I'm a bit confused, is it possible to make it appear in the middle of the screen? 🤔

**Reply by TimBeekman** [reply]
Yes, with help of the module written by @octoTurnip

**Reply by cwrau** [reply]
Nice, but which one? I can only see this one: `Pop-Up Box`.

I'm already using that, but the pop-ups appear at the top of the screen.

**Reply by octoTurnip** [reply]
> Nice, but which one? I can only see this one: `Pop-Up Box`.
> 
> I'm already using that, but the pop-ups appear at the top of the screen.

Hello, I made an update 2 months ago fixing an issue where some of the code was incompatible with Apple devices. I think it might be fixed now but I need to get my hands on one or have someone test it to see if my new proposed code will work. 

In the meantime, you can edit my module in the settings and paste the following code to make the pop-ups appear in the middle of the screen:

```yaml
#root:not(.editor) {
  top: auto !important;
  height: auto !important;
  max-height: 70vh !important;
  width: 97%;
  --desktop-width: 60vw !important;
  margin-left: auto !important;
  margin-right: auto !important;
  bottom: auto !important;
  align-self: anchor-center;
}
```

Just replace the `#root` section with the above code. Hopefully there will be an update soon! 😊

**Reply by cwrau** [reply]
> but I need to get my hands on one or have someone test it to see if my new proposed code will work.

My wife still has an iPhone, I can test for you 😁

The same snippet you just sent?

**Reply by octoTurnip** [reply]
Yes sir🫡

**Reply by cwrau** [reply]
<img width="738" height="1600" alt="image" src="https://github.com/user-attachments/assets/7d576a42-9d86-47b2-b6b9-7d7d4bf3de0e" />

It's not broken, but it doesn't seem to work. Worked perfectly on my android tho

**Reply by octoTurnip** [reply]
Just to be clear, the module config looks like this right:

```yaml
more_info_popup:
  name: "Pop-Up Box"
  version: "v1.3"
  creator: "octoTurnip"
  link: "https://github.com/Clooos/Bubble-Card/discussions/1376"

  unsupported:
    - button
    - cover
    - climate
    - horizontal-buttons-stack
    - media-player
    - select
    - separator
    - calendar

  description: |
    This will style the pop-up to look like a more-info style pop-up.

  code: |
    #root:not(.editor){
      top: auto !important;
      margin-left: auto !important;
      margin-right: auto !important;
      bottom: auto !important;
      height: auto !important;
      max-height: calc(100% - 72px) !important;
      width: 97%;
      --desktop-width: 60vw !important;
      align-self: anchor-center;
    }
    .bubble-pop-up-container{
      padding: 20px !important;
      mask-image: none !important;
    }
    .bubble-pop-up-background{
      border-radius: 20px !important;
      border: solid 1px var(--primary-color);
    }
    .bubble-backdrop{
      transition-delay: 0 !important;
      transition: opacity 0.2s !important;
      background-color: null !important;
    }
    .is-popup-closed { 
      opacity: 0;
      transition: opacity 0.4s !important;
    }
    .is-popup-opened, .is-popup-closed.editor {
      opacity: 1;
      transition: opacity 0.2s !important;
    }
```

I changed a few things I think, so maybe just try this one. Make sure to update the version number so something different so it'll update the backend. 

Also make sure to clear any cashe, close the app, and restart it. 

Thanks a million for the help btw😇👏

**Reply by cwrau** [reply]
Mh, how do I use this?

I tried to put this in the `bubble-modules.yaml` with version `v2` but that didn't seem to work, in the frontend I still have `v1.3`

**Reply by octoTurnip** [reply]
- Start off by editing your dashboard 

- Make or edit a bubble card pop up

- go to the modules section and press the edit icon

  - ![Screenshot_20250808_081714_Home Assistant.jpg](https://github.com/user-attachments/assets/8fb0fc9b-f7ab-400b-8d06-097de4e68c81)

- Change the version and update the code to the one posted before 
  - ![Screenshot_20250808_081914_Home Assistant.jpg](https://github.com/user-attachments/assets/66429273-3ba5-48db-96be-20f768721d52)

- then save and try


Optionally, you can try making a new module for testing:

- go back to edit the bubble pop-up

- open the modules section and press create new module 

  - ![Screenshot_20250808_081950_Home Assistant.jpg](https://github.com/user-attachments/assets/63f526a6-105e-48e4-9047-f34e0e55de31)

- then paste the above code into the css/js code area

  - ![Screenshot_20250808_082019_Home Assistant.jpg](https://github.com/user-attachments/assets/12d7fd74-ceb0-4aa5-97ae-3f61c48a82b2)


Let me know if this helps😎

**Reply by cwrau** [reply]
Ah, the first one worked.

But now it doesn't show up anymore at all, it just puts a dark transparent overlay on top

**Reply by octoTurnip** [reply]
> Ah, the first one worked.
> 
> But now it doesn't show up anymore at all, it just puts a dark transparent overlay on top

Yeah I just verified with a friends iPhone😔. Unfortunately, Apple still haven't updated Safari on iPhone with current CSS code (I think that's what it is) so we can use the function where it puts the box in the middle. 

I'm releasing an update soon and hopefully I'll have a workaround or option to toggle this, if a user wants this. Stay tuned!

**Reply by octoTurnip** [reply]
I just updated the module and included a conditional option to allow the pop-up to be on the center of the screen if you want. Check it out 😎

**Comment by maisun** [comment]
Hi, thanks for sharing the module! It works great but looks like it doesn't respect the width_desktop style. Is there any way that I can change the max-width of the card? It looks strange on desktop but on mobile works perfectly. thank you!

**Reply by octoTurnip** [reply]
Right now, I haven't set that ability to change it. BUT look out for the next update coming soon! It'll be an option then 😊

**Reply by maisun** [reply]
> Right now, I haven't set that ability to change it. BUT look out for the next update coming soon! It'll be an option then 😊

Thank you and look forward!

**Reply by octoTurnip** [reply]
I just updated the module to include the feature you requested! Enjoy!

**Comment by maisun** [comment]
Hi @octoTurnip : sorry I have another question hope you don't mind: looks like the pop-up currently shows in the middle of the screen. Is there any way to make it to show in the middle of a picture element card? I ask because my picture element card has max-width so on desktop it doesn't always scale to the full screen. I know the max width so would like to find a way to show the middle by min(screen_width, card_max_width). Thank you in advance!

**Reply by octoTurnip** [reply]
If I understand you correctly: you have one card and you're trying to get the bubble pop up in the middle of that card? If so, then I don't think so. Due to how the bubble card is coded. That also doesn't fit into the scope of this module. 

Now you might be able to do some card-mod magic or something with another card. I don't know off the top of my head but maybe what you're looking for (to Google) is a "picture in a picture". 

Hope this helps!

**Reply by maisun** [reply]
> If I understand you correctly: you have one card and you're trying to get the bubble pop up in the middle of that card? If so, then I don't think so. Due to how the bubble card is coded. That also doesn't fit into the scope of this module.
> 
> Now you might be able to do some card-mod magic or something with another card. I don't know off the top of my head but maybe what you're looking for (to Google) is a "picture in a picture".
> 
> Hope this helps!

Thank you for your reply! Will ask in bubble card discussion and see if anybody know a good solution.

**Comment by octoTurnip** [comment]
Updated to v1.4 !!

**\*\*PLEASE RE-READ THE DESCRIPTION\*\***
- center screen pop-up's are back baby!
  - <img src="https://github.com/user-attachments/assets/c7e4cfa9-8013-4e9d-974c-2b185636e126" width="50%" height="50%">
  - use the config editor to enable the option
- added more styling options
- fixed stutters in the animations
- fixed open/close animations

Thank you everyone for your inputs and feedback! as always, please let me know if you'd like to see anything else!

**Comment by maisun** [comment]
Hi @octoTurnip :
Thanks for the update and I can confirm the desktop-width works great with configuration option!
However would like to report center on screen doesn’t seem to work for me on Safari iOS, when click the pop-up doesn’t show.
Another question: is it correct to delete and reimport the yaml code to update the module or there is a better way I missed?
Once again thanks for the great effort!

**Reply by octoTurnip** [reply]
Yeah, I wish Apple would update their browsers to support that stuff😭

To update the module, just edit a Bubble card and go to the modules section. There should be a tab that says "Module Store". Click on that and find my module. There then should be an update button you can press, then boom! Updated module 😇 reopen the app and it should show the updated settings.

**Comment by zanix** [comment]
The window speed configuration option doesn't work. I took a look at the code and it looks like it applies only to the close button.

```css
    .bubble-close-button {
      transition: ${this.config.more_info_popup?.window_speed || 'all 0.4s ease'} !important;
    }
```

I moved this to the root element and now the config works.

```css
    #root:not(.editor) {
      top: ${this.config.more_info_popup?.center ? 'auto' : this.config.more_info_popup?.top || '40px'} !important;
      ...
      align-self: ${this.config.more_info_popup?.center ? 'anchor-center' : 'none'};
      /*transition: transform 0.4s ease !important; hard coded transition */
      transition: ${this.config.more_info_popup?.window_speed || 'all 0.4s ease'} !important;
    }
```

**Reply by octoTurnip** [reply]
Sorry for the late reply. I just got back from vacation. And thank you for pointing this out!

I'll check it out soon and get back to you with an update.

**Reply by octoTurnip** [reply]
@zanix sorry for taking forever! I just got back from deployment, but I'm working on it now. 

I ran into trouble with this because hard codded into the pop-up card removes the window after 300ms (0.3s) whether we change the animation speed to longer or not. 

I'm currently looking for a workaround, but it's not looking to good. I'll probably keep the animation speed in there in case someone wants to make it faster. 

Thank you for waiting, and stand by for an update this week😇

**Reply by zanix** [reply]
No worries and welcome back!

My change does fix the configuration of the opening speed, but I do see that the closing speed is always short. It looks like the entire dom structure is just removed after a certain amount of time. It looks like this is coded into the popups directly like you said.

Where `popupState.animationDuration` is defined
https://github.com/Clooos/Bubble-Card/blob/main/src/cards/pop-up/helpers.js#L11

Time is used in `setTimeout` in the `closePopup` function around line 408-416.
https://github.com/Clooos/Bubble-Card/blob/main/src/cards/pop-up/helpers.js#L416
I don't think there is a way around this unless the `animationDuration` variable is configurable.

**Reply by octoTurnip** [reply]
Updated

**Comment by octoTurnip** [comment]
Updated to v1.5!!!

- fixed animation speed not working due to my bad coding lol
- added `Swirl` and `Lean` to pop-up animations to pick from
- you can now add your own custom animations by choosing `Custom` from the list, then inputing the CSS code below it
  - please make sure to read the warnings before asking me for help :)

**Reply by zanix** [reply]
I think you left in a development variable in the css:

```css
 transition: ${this.config.more_info_popdev?.window_speed || 'all 0.4s ease'} !important;
```

Should `this.config.more_info_popdev` be `this.config.more_info_popup`?

**Reply by t-pc** [reply]
The different animations didn't work until I changed `transform` to this:
```css
transform: ${this.config.more_info_popup?.window_ani === 'customUserInput' ? this.config.more_info_popup?.customInput : this.config.more_info_popup?.window_ani || 'scale(0.1)'} !important;```

**Reply by octoTurnip** [reply]
Wow I really did copy over the wrong code😅 sorry fellas! It looks like @t-pc is correct and that's what it should be. 

I'll hopefully have the fix out tonight.

**Reply by octoTurnip** [reply]
fixed in v1.6

**Comment by maisun** [comment]
Sorry for a stupid question: how can I upgrade in yaml mode?

**Reply by maisun** [reply]
Anybody can help with my question? Cannot edit the in ui as I switched to yaml model , many thanks

**Reply by octoTurnip** [reply]
> Anybody can help with my question? Cannot edit the in ui as I switched to yaml model , many thanks

hmmm good question. im too weak to go full yaml mode, but i would assume that you have to copy and paste the updated code into your defaults bubble module yaml then set the options in your dashboard.

or what i just thought is that is=f another dashboard is not yaml mode, update it there, then it should reflects on the yaml only dashboard!

i hope this helps :)

**Comment by octoTurnip** [comment]
Updated to v1.6!!!

- removed my development variables with the correct ones 🫠
- added videos of the new window animations 
- spelling, spacing, and grammer

**Reply by Clooos** [reply]
Hi! I've updated your module, there was a typo in your YAML that was blocking it from being updated from the store. I also updated the version at the top of the post, it was still showing v1.5.

Always export it from the Bubble Card editor (at least just the YAML) to avoid this kind of issue 🙂 

Edit: I also changed it to use the `supported:` key, since your module is only working with the pop-up card. This way it is not shown as compatible with the new "Sub-buttons only" card in v3.1.0.

**Comment by MackoMici** [comment]
Why is it that when I reload the page and then open a pop-up, it never opens in the set mode the first time? There is no problem when I open it a second time.

```
        modules:
          - more_info_popup
        more_info_popup:
          window_ani: scale(0.1)
```
