### DISCUSSION TITLE
How to show the time remaining of a timer in a sub-button ?

### DISCUSSION THREAD

**Discussion by MilesTEG1** [Clooos/Bubble-Card#1385] [Questions about config, custom styles and templates]
### Goal

I want to show in a sub-button the time remaining of a timer launched by a script when clicking on a button from another bubble card.

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
modules:
  - default
button_type: state
entity: timer.boost_timer_vtherm_sdb
styles: |

  .bubble-icon {
    color:  rgba(126, 104, 143, 1) !important;
  }

  .bubble-button-card-container {
    background: rgba(55,55,55,0.8) !important;
  }

  .bubble-range-fill { 
    background: rgba(79, 69, 87, 1) !important;
    opacity: 1 !important;
  }

  .bubble-sub-button-1 {
    background-color: rgba(0, 148, 255, 0.5) !important;
    opacity: 1 !important;
    height: 30px !important;
    min-width: 80px !important;
    font-size: 14px !important;
    font-weight: bold !important;
  }

  .bubble-sub-button-2 {
    background-color: rgba(0, 148, 255, 0.5) !important;
    opacity: 1 !important;
    height: 30px !important;
    min-width: 80px !important;
    font-size: 14px !important;
    font-weight: bold !important;
  }
force_icon: false
show_state: false
sub_button:
  - entity: timer.boost_timer_vtherm_sdb
    show_background: true
    show_name: false
    show_icon: false
    show_state: true
    show_attribute: false
    visibility:
      - condition: state
        entity: timer.boost_timer_vtherm_sdb
        state: idle
  - entity: timer.boost_timer_vtherm_sdb
    show_icon: false
    show_last_changed: false
    show_state: false
    show_attribute: true
    attribute: remaining
    visibility:
      - condition: state
        entity: timer.boost_timer_vtherm_sdb
        state: active
scrolling_effect: false
```

### Which step did you already try?

```yaml
X
```

### Problem

The sub-button as I set it up doesn't show the time remaining, but only the time I set with another card :
![image](https://github.com/user-attachments/assets/db142452-8747-4e73-bc1a-fb426b010708)
- First card: setting the timer with a bubble card (yaml code at the bottom of this message).
- Second card: the lovelace card showing the timer.
- Third: the bubble-card i want to show the time remaining when the timer is on and its time decreasing.

Code for the first card:
```yaml
type: custom:bubble-card
card_type: button
entity: input_number.boost_duration_vtherm_sdb
button_type: slider
name: Durée Boost SdB
sub_button:
  - entity: input_number.boost_duration_vtherm_sdb
    show_icon: false
    show_state: true
    show_attribute: false
    attribute: mode
    tap_action:
      action: none
    state_background: true
    show_background: true
    name: Durée
  - name: Start
    icon: mdi:play
    state_background: true
    show_background: true
    tap_action:
      action: call-service
      service: script.timer_boost_sdb_start_script_ui
      target: {}
  - name: Stop
    icon: mdi:stop
    tap_action:
      action: call-service
      target: {}
      service: script.timer_boost_sdb_stop_script_ui
grid_options:
  columns: 12
  rows: 1
tap_action:
  action: call-service
  service: script.timer_boost_sdb_start_script_ui
  target: {}
styles: |-

  .bubble-icon {
    color:  rgba(126, 104, 143, 1) !important;
  }

  .bubble-button-card-container {
    background: rgba(55,55,55,0.8) !important;
  }

  .bubble-range-fill { 
    background: rgba(79, 69, 87, 1) !important;
    opacity: 1 !important;
  }

  .bubble-sub-button-1 {
    background-color: rgba(0, 148, 255, 0.5) !important;
    opacity: 1 !important;
    height: 30px !important;
    min-width: 80px !important;
    font-size: 14px !important;
    font-weight: bold !important;
  }

  .bubble-sub-button-2 {
    background-color: rgba(0, 255, 0, 0.75) !important;
    opacity: 1 !important;
    height: 30px !important;
    width: 50px !important;
    font-size: 14px !important;
    font-weight: bold !important;
  }

  .bubble-sub-button-2 > ha-icon {
    color: rgba(0, 0, 0, 1) !important;
  }
  .bubble-sub-button-3 > ha-icon {
    color: rgba(0, 0, 0, 1) !important;
  }

  .bubble-sub-button-icon {
    --mdc-icon-size: 26px !important;
  }

  .bubble-sub-button-3 {
    background-color: rgba(255, 0, 0, 0.75) !important;
    opacity: 1 !important;
    height: 30px !important;
    width: 50px !important;
    font-size: 14px !important;
    font-weight: bold !important;
  }
modules:
  - default
```

And if someone need it, here the start script for the timer:
```yaml
alias: Timer Boost SdB - Start - Script UI
sequence:
  - action: timer.start
    data:
      duration: "{{ states('input_number.boost_duration_vtherm_sdb') | int(0) * 60 }}"
    target:
      entity_id: timer.boost_timer_vtherm_sdb
  - if:
      - condition: device
        device_id: b6657a47c9412a2407b8bb0572eb18dc
        domain: climate
        entity_id: 50f7de9aef9aee7afd8920e9e1755502
        type: is_hvac_mode
        hvac_mode: "off"
    then:
      - device_id: b6657a47c9412a2407b8bb0572eb18dc
        domain: climate
        entity_id: 50f7de9aef9aee7afd8920e9e1755502
        type: set_hvac_mode
        hvac_mode: heat
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: climate.vtherm_salle_de_bains
            attribute: preset_mode
            state: boost
    then:
      - device_id: b6657a47c9412a2407b8bb0572eb18dc
        domain: climate
        entity_id: 50f7de9aef9aee7afd8920e9e1755502
        type: set_preset_mode
        preset_mode: boost
description: ""
icon: mdi:timer-play-outline

```

Of course, I have a timer set up, but it's duration is determined by the slider of the first bubble-card.

Thanks for your help 

### Read the documentation

- [X] I have read the documentation
