### DISCUSSION TITLE
Color outline of the card

### DISCUSSION THREAD

**Discussion by schumi2309** [Clooos/Bubble-Card#1387] [Questions about config, custom styles and templates]
### Goal

Hello,
I'd like to know how to draw just the outline of the card (the border) with a specific color, and how to adjust the line thickness.
Does anyone have a solution?
Thanks

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: switch
entity: light.entree
icon: mdi:hanger
card_layout: large
show_state: true
show_last_changed: false
sub_button:
  - entity: binary_sensor.porte_hall
    visibility:
      - condition: state
        entity: binary_sensor.porte_hall
        state: "on"
  - entity: binary_sensor.detecteur_hall
    icon: mdi:motion-sensor
    visibility:
      - condition: state
        entity: binary_sensor.detecteur_hall
        state: "on"
  - entity: binary_sensor.aarlo_motion_sonnette
    icon: mdi:home-automation
    visibility:
      - condition: state
        entity: script.alarme_sonnette_armee
        state: "on"
styles: >-

  .bubble-sub-button-1 {
    background-color: 
      ${hass.states['binary_sensor.porte_hall'].state === 'on' 
        ? 'var(--accent-color)'               
        : 'var(--card-background-color)'};
  } .bubble-sub-button-2 {
    background-color: 
      ${hass.states['binary_sensor.detecteur_hall'].state === 'on' 
        ? 'var(--accent-color)'               
        : 'var(--card-background-color)'};
  .bubble-sub-button-3 {
    background-color: 
      ${hass.states['binary_sensor.aarlo_motion_sonnette'].state === 'on' 
        ? 'var(--accent-color)'               
        : 'var(--card-background-color)'};

  } ${card.querySelector('.bubble-state').innerText =
  parseFloat(hass.states['sensor.hall_temperature'].state).toFixed(1) + '°C'}

button_action:
  tap_action:
    action: navigate
    navigation_path: /dashboard-bubble/Entrée
  double_tap_action:
    action: toggle
name: "Entrée "
scrolling_effect: false
show_icon: true
show_name: true
modules:
  - default
```

### Read the documentation

- [X] I have read the documentation

**Comment by viatro** [comment]
Try this:
```css
styles: |-
  .bubble-button-card-container {
    border-style: solid;
    border-width: 1px;
    border-color: rgb(...);
  }
```
