### DISCUSSION TITLE
Prevent scrolling inside bubble card when icon larger than card

### DISCUSSION THREAD

**Discussion by CV8R** [Clooos/Bubble-Card#1391] [Questions about config, custom styles and templates]
### Goal

Trying to stop the card contents scrolling vertically when an icon is set to a size that makes it larger than the card.

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
modules:
  - default
entity: light.office_light
styles: |-
  .bubble-icon {
    --mdc-icon-size: 126px !important;
  }
```

### Which step did you already try?

```yaml
Tried various overflow: hidden; overflow-block: but I am out of my depth.
```

### Problem

When forcing the icon outside the card and scrolling the dashboard, scrolling from within the card scrolls the card contents and not the dashboard page. Particularly an issue on mobile but can be replicated on desktop with the mouse.

### Read the documentation

- [X] I have read the documentation
