### DISCUSSION TITLE
Device centric cards / with Auto-Entities (multiple entities per bubble)

### DISCUSSION THREAD

**Discussion by saethone** [Clooos/Bubble-Card#1413] [Questions about config, custom styles and templates]
### Goal

Has anybody done any work to try and get a bubble card to be centered around a device instead of an entity? For example, I'm using https://github.com/natekspencer/hacs-planta integration to bring plant data into HA, and it creates devices with several entities - an image entity, timestamp sensors for the date of next actions, and buttons to press to say an action was done (like watering), etc

![image](https://github.com/user-attachments/assets/1acad4d6-0ed2-4d25-b263-433020ac7998)
![image](https://github.com/user-attachments/assets/66107dfa-f3f5-49ed-b381-a58694945059)

I'm wanting to use auto-entities to fill out a list of these cards, but having trouble because the different sensors are all separate entities. I was thinking this.entity_id  would be a string replace but because the base name is an image even if that were to be the case, its image.plant_name and all the sensors i need are sensor.plant_name_whatever. Im thinking I either need to template helper all of these sensors into attributes of a single entity, or set a template in the auto-entities card to figure out the names of the entities for the sensors... I'm not really sure

Has anybody done anything along these lines?

### Source Yaml

```yaml
type: custom:auto-entities
filter:
  include:
    - integration: planta
      domain: image
      options:
        type: custom:bubble-card
        card_type: button
        modules:
          - default
          - flat_style
        button_type: state
        entity: this.entity_id
        show_state: false
        sub_button:
          - entity: this.entity_id_scheduled_watering
            show_state: true
            show_icon: true
            icon: mdi:water
          - entity: this.entity_id_scheduled_misting
            icon: mdi:spray
            show_state: true
            show_background: true
          - entity: this.entity_id_scheduled_fertilizing
            icon: mdi:food-apple
            show_state: true
          - entity: this.entity_id_scheduled_repotting
            icon: mdi:shovel
            show_state: true
        card_layout: large-2-rows
        flat_style:
          card_styles:
            prime_color:
              - 0
              - 128
              - 0
  exclude: []
show_empty: true
card_param: cards
card:
  type: vertical-stack
```

### Read the documentation

- [X] I have read the documentation

**Comment by saethone** [comment]
Ok Ya'll, I've been hammering away at this all week and I think i have a solution.

![image](https://github.com/user-attachments/assets/657d95c5-9e56-4b6b-8a8e-43d0c3352c8c)


 Warning: its pretty wild

You need the easy time, auto entities, expander card, and decluttering templates all from HACS

Then, for each plant, add a template sensor with the following code - named in line with your entities _issues, and update the entities in the set command (ie, named common_ivy_issues, and sensor.common_ivy_scheduled_watering etc)

```yaml
{%- set SENSORS = [
              "sensor._scheduled_watering",
              "sensor._scheduled_misting",
              "sensor._scheduled_fertilizing",
              "sensor._scheduled_cleaning",
              "sensor._scheduled_repotting",
              "sensor._scheduled_progress_update"
            ] -%}
            
  {{ states.sensor | selectattr('entity_id', 'in', SENSORS) | selectattr('state', '<', utcnow().isoformat()) | list | count }}
```

Then, in your lovelace.yaml add a template:

```yaml
decluttering_templates:
  planta_bubble_card_test:
    card:
      type: custom:expander-card
      title-card:
        type: custom:bubble-card
        card_type: button
        button_type: switch
        modules:
          - default
          - flat_style
          - badgy-condition-helper
        entity: '[[image_entity]]'
        show_attribute: true
        sub_button:
          - entity: issues_entity
            show_state: true
            icon: mdi:alert-circle
            name: Issues
            show_name: true
            visibility:
              - condition: numeric_state
                entity: '[[issues_entity]]'
                above: 0
        flat_style:
          card_styles:
            prime_color:
              - 0
              - 128
              - 0
        badgy-condition-helper:
          sub_buttons_background:
            "0":
              type: solid
              color: red
              opacity: 1
        visual_styling_center:
          custom_subicon_color:
            - 255
            - 255
            - 255
          custom_subbutton_background_color:
            - 255
            - 0
            - 0
          hide_subbutton_background: false
          hide_icon_background: false
      cards:
        - type: custom:bubble-card
          card_type: button
          button_type: state
          modules:
            - default
          entity: '[[health_entity]]'
          name: Health
          sub_button:
            - entity: '[[last_progress_update_string]]'
              show_background: false
              icon: mdi:camera-timer
              show_state: true
            - entity: '[[progress_update_entity]]'
              show_name: true
              show_state: false
              show_icon: false
              name: Update Due '[[progress_update_value]]'
        - type: custom:bubble-card
          card_type: button
          button_type: switch
          modules:
            - default
          entity: '[[watering_entity]]'
          show_state: true
          show_name: true
          icon: mdi:water
          show_attribute: false
          name: Watering Due [[watering_value]]
          sub_button:
            - entity: '[[last_watering_entity]]'
              show_state: true
              icon: mdi:camera-timer
              show_background: false
            - entity: '[[press_watering]]'
              icon: mdi:check-circle
              name: Complete
              show_name: true
              state_background: true
              show_background: true
        - type: custom:bubble-card
          card_type: button
          button_type: switch
          modules:
            - default
          entity: '[[misting_entity]]'
          show_state: true
          show_name: true
          icon: mdi:spray-bottle
          show_attribute: false
          name: Misting Due [[misting_value]]
          sub_button:
            - entity: '[[last_misting_entity]]'
              show_state: true
              icon: mdi:camera-timer
              show_background: false
            - entity: '[[press_misting]]'
              icon: mdi:check-circle
              name: Complete
              show_name: true
              state_background: true
              show_background: true
        - type: custom:bubble-card
          card_type: button
          button_type: switch
          modules:
            - default
          entity: '[[fertilizing_entity]]'
          show_state: true
          show_name: true
          icon: mdi:flower-tulip-outline
          show_attribute: false
          name: Fertilizing Due [[fertilizing_value]]
          sub_button:
            - entity: '[[last_fertilizing_entity]]'
              show_state: true
              icon: mdi:camera-timer
              show_background: false
            - entity: '[[press_fertilizing]]'
              icon: mdi:check-circle
              name: Complete
              show_name: true
              state_background: true
              show_background: true
        - type: custom:bubble-card
          card_type: button
          button_type: switch
          modules:
            - default
          entity: '[[cleaning_entity]]'
          show_state: true
          show_name: true
          icon: mdi:broom
          show_attribute: false
          name: Cleaning Due [[cleaning_value]]
          sub_button:
            - entity: '[[last_cleaning_entity]]'
              show_state: true
              icon: mdi:camera-timer
              show_background: false
            - entity: [[press_cleaning]]'
              icon: mdi:check-circle
              name: Complete
              show_name: true
              state_background: true
              show_background: true
        - type: custom:bubble-card
          card_type: button
          button_type: switch
          modules:
            - default
          entity: '[[repotting_entity]]'
          show_state: true
          show_name: true
          icon: mdi:sprout
          show_attribute: false
          name: Repotting Due [[repotting_value]]
          sub_button:
            - entity: '[[last_repotting_entity]]'
              show_state: true
              icon: mdi:camera-timer
              show_background: false
```

and here's the bubble stack - 

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    modules:
      - default
    hash: "#plants"
    button_type: name
  - type: custom:auto-entities
    card:
      type: vertical-stack
    card_param: cards
    filter:
      template: >-
        {% from 'easy_time.jinja' import easy_relative_time %} {%- set STATES =
        states.image | selectattr('entity_id', 'in',
        integration_entities('planta')) | list  -%}

        {%- for STATE in STATES -%}

        {%- set watering_string = "sensor." ~ STATE.entity_id.split("image.")[1]
        ~ "_scheduled_watering" -%} {%- set watering =
        easy_relative_time(states(watering_string)) -%} {%- set misting_string =
        "sensor." ~ STATE.entity_id.split("image.")[1] ~ "_scheduled_misting"
        -%} {%- set misting = easy_relative_time(states(misting_string)) -%} {%-
        set fertilizing_string = "sensor." ~ STATE.entity_id.split("image.")[1]
        ~ "_scheduled_fertilizing" -%} {%- set fertilizing =
        easy_relative_time(states(fertilizing_string)) -%} {%- set
        repotting_string = "sensor." ~ STATE.entity_id.split("image.")[1] ~
        "_scheduled_repotting" -%} {%- set repotting =
        easy_relative_time(states(repotting_string)) -%} {%- set
        progress_update_string = "sensor." ~ STATE.entity_id.split("image.")[1]
        ~ "_scheduled_progress_update" -%} {%- set progress_update =
        easy_relative_time(states(progress_update_string)) -%} {%- set
        cleaning_string = "sensor." ~ STATE.entity_id.split("image.")[1] ~
        "_scheduled_cleaning" -%} {%- set cleaning =
        easy_relative_time(states(cleaning_string)) -%} {%- set issues_string =
        "sensor." ~ STATE.entity_id.split("image.")[1] ~ "_issues" -%} {%- set
        last_watering_string = "sensor." ~ STATE.entity_id.split("image.")[1] ~
        "_time_since_last_watering" -%} {%- set last_misting_string = "sensor."
        ~ STATE.entity_id.split("image.")[1] ~ "_time_since_last_misting" -%}
        {%- set last_fertilizing_string = "sensor." ~
        STATE.entity_id.split("image.")[1] ~ "_time_since_last_fertilizing" -%}
        {%- set last_repotting_string = "sensor." ~
        STATE.entity_id.split("image.")[1] ~ "_time_since_last_repotting" -%}
        {%- set last_progress_update_string = "sensor." ~
        STATE.entity_id.split("image.")[1] ~ "_time_since_last_progress_update"
        -%} {%- set last_cleaning_string = "sensor." ~
        STATE.entity_id.split("image.")[1] ~ "_time_since_last_cleaning" -%} {%-
        set health_string = "sensor." ~ STATE.entity_id.split("image.")[1] ~
        "_health" -%} {%- set press_cleaning_string = "button." ~
        STATE.entity_id.split("image.")[1] ~ "_complete_cleaning" -%} {%- set
        press_fertilizing_string = "button." ~
        STATE.entity_id.split("image.")[1] ~ "_complete_fertilizing" -%} {%- set
        press_misting_string = "button." ~ STATE.entity_id.split("image.")[1] ~
        "_complete_misting" -%} {%- set press_watering_string = "button." ~
        STATE.entity_id.split("image.")[1] ~ "_complete_watering" -%} {%- set
        area_string = area_name(STATE.entity_id) -%}



        {%- set VARIABLES = [] -%} {%- set VARIABLES= VARIABLES +
        [{'image_entity': STATE.entity_id}] -%} {%- set VARIABLES= VARIABLES +
        [{'watering_value': watering}] -%} {%- set VARIABLES= VARIABLES +
        [{'watering_entity': watering_string}] -%} {%- set VARIABLES= VARIABLES
        + [{'misting_value': misting}] -%} {%- set VARIABLES= VARIABLES +
        [{'misting_entity': misting_string}] -%} {%- set VARIABLES= VARIABLES +
        [{'fertilizing_value': fertilizing}] -%} {%- set VARIABLES= VARIABLES +
        [{'fertilizing_entity': fertilizing_string}] -%} {%- set VARIABLES=
        VARIABLES + [{'cleaning_value': cleaning}] -%} {%- set VARIABLES=
        VARIABLES + [{'cleaning_entity': cleaning_string}] -%} {%- set
        VARIABLES= VARIABLES + [{'repotting_value': repotting}] -%} {%- set
        VARIABLES= VARIABLES + [{'repotting_entity': repotting_string}] -%} {%-
        set VARIABLES= VARIABLES + [{'progress_update_value': progress_update}]
        -%} {%- set VARIABLES= VARIABLES + [{'progress_update_entity':
        progress_update_string}] -%} {%- set VARIABLES= VARIABLES +
        [{'issues_entity': issues_string}] -%} {%- set VARIABLES= VARIABLES +
        [{'last_watering_entity': last_watering_string}] -%} {%- set VARIABLES=
        VARIABLES + [{'last_misting_entity': last_misting_string}] -%} {%- set
        VARIABLES= VARIABLES + [{'last_fertilizing_entity':
        last_fertilizing_string}] -%} {%- set VARIABLES= VARIABLES +
        [{'last_repotting_entity': last_repotting_string}] -%} {%- set
        VARIABLES= VARIABLES + [{'last_cleaning_entity': last_cleaning_string}]
        -%} {%- set VARIABLES= VARIABLES + [{'last_progress_update_entity':
        last_progress_update_string}] -%} {%- set VARIABLES= VARIABLES +
        [{'press_cleaning': press_cleaning_string}] -%} {%- set VARIABLES=
        VARIABLES + [{'press_watering': press_watering_string}] -%} {%- set
        VARIABLES= VARIABLES + [{'press_misting': press_misting_string}] -%} {%-
        set VARIABLES= VARIABLES + [{'press_fertilizing':
        press_fertilizing_string}] -%} {%- set VARIABLES= VARIABLES +
        [{'health_entity': health_string}] -%} {%- set VARIABLES= VARIABLES +
        [{'area_value': area_string}] -%}
          {{
            { 
              'type': "custom:decluttering-card",
              'template': "planta_bubble_card",
              'variables': VARIABLES,
              }
            }},

          {%- endfor -%}
```


Improvements I'd still like to make:
- Color the background of the sensor that's past due dynamically
- Sort the plants by # of issues

Let me know what ya'll think!
