### DISCUSSION TITLE
Cover Card action buttons location

### DISCUSSION THREAD

**Discussion by tonyramin** [Clooos/Bubble-Card#1425] [Questions about config, custom styles and templates]
### Goal

I am trying to move the buttons for this cover entity - my garage door - to be on one row instead of two.

![Garage Cover](https://github.com/user-attachments/assets/a919b7a8-12b2-4c08-a7a3-b0ac19354fae)

### Source Yaml

```yaml
- type: custom:bubble-card
    card_type: cover
    entity: cover.right_2
    show_last_changed: true
    show_state: true
    name: Right Garage Door
```

### Which step did you already try?

```yaml
I have not had any luck with trying to use the rows attribute or css styles.  

rows: 1
```

### Problem

Currently the buttons are huge and are taking up a lot of screen real-estate.
I do not see an option make them smaller and on one row but hoping other have found out how to accomplish this.

### Read the documentation

- [X] I have read the documentation
