### DISCUSSION TITLE
v3 beta3 Modules from store disappear

### DISCUSSION THREAD

**Discussion by Tschumlo** [Clooos/Bubble-Card#1428] [Questions about config, custom styles and templates] [answered]
### Goal

Hi everybody,

I installed v3 beta 3 and wanted to give modules a try for the first time, as we have the fancy new module store now 😄 
Unfortunately there is a strange issue, where an installed module will just disappear after 1-2 seconds after activating it.
Further description below.

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: switch
modules:
  - default
  - subbutton_below
entity: device_tracker.jphone
show_state: true
show_last_updated: false
show_last_changed: true
sub_button:
  - entity: sensor.jphone_battery_level
    show_state: true
grid_options:
  columns: 6
  rows: 2
show_icon: true
scrolling_effect: false
```

### Problem

I followed the instructions in the editor by adding the code below to my configuration.yaml.

```
template:
  - trigger:
      - trigger: event
        event_type: bubble_card_update_modules

  - sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        icon: "mdi:puzzle"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"
```

It seems that part was fine since i can browse the modules and install one.
But i cannot use it.

For example i have this card as a test (yaml above):
![Bildschirmfoto 2025-04-25 um 20 57 25](https://github.com/user-attachments/assets/878de5dc-f3fa-4d08-a039-1286b292e03f)

I installed the module "Sub-button below". I got a short pop-up at the bottom of the screen and the module was installed:
![Bildschirmfoto 2025-04-25 um 20 59 17](https://github.com/user-attachments/assets/eb77f2de-4696-44a4-adea-75b9fa49e3f9)

Once I activate the module under "My Modules" the card is changed accordingly:
![Bildschirmfoto 2025-04-25 um 21 00 41](https://github.com/user-attachments/assets/e15936b3-dab6-454f-be1d-a90ceb0af81b)

BUT! After approx. 1 second the "sub-button below" module under "My Modules" disappears as well as the changes for the card itself and it jumps back to the state before downloading and activating the module.

I tried to explain what i did the best i can so hopefully it is understandable.
I did not want to create any issue as i used modules for the first time and did not know if the issue is on my end.

Does anybody have any hints?

Thank you so much in advance!

### Read the documentation

- [X] I have read the documentation
