### DISCUSSION TITLE
Dropdown select box in wrong position

### DISCUSSION THREAD

**Discussion by octoTurnip** [Clooos/Bubble-Card#1442] [Questions about config, custom styles and templates]
### Goal

Move the drop-down from the incorrect location:
![image](https://github.com/user-attachments/assets/5f64a08d-bfde-498e-8ca0-2e649fff8573)

To a drop-box to show up normally:
![image](https://github.com/user-attachments/assets/7e56bcf7-f771-4a4c-9d44-3adbc93c3d10)

### Source Yaml

```yaml
code: |
    #root:not(.editor){
      top: 50% !important;
      transform: translate(0, -50%) !important;
      height: auto;
      max-height: 70vh !important;
      width: 97%;
      --desktop-width: 60vw !important;
      margin-left: auto !important;
      margin-right: auto !important;
      bottom: auto !important;
    }
    .bubble-pop-up-container{
      padding: 20px !important;
      mask-image: none !important;
    }
    .bubble-pop-up-background{
      border-radius: 20px !important;
      border: solid 1px var(--primary-color);
    }
    .bubble-backdrop{
      transition-delay: 0 !important;
      transition: opacity 0.2s !important;
      background-color: null !important;
    }
    .is-popup-closed { 
      opacity: 0;
      transition: opacity 0.4s !important;
    }
    .is-popup-opened, .is-popup-closed.editor {
      opacity: 1;
      transition: opacity 0.2s !important;
    }
```

### Which step did you already try?

```yaml
- I have attempted to copy (and also move) code from #root to .bubble-pop-up-container.
- If I remove "height", "max-height", "top", and "transform" the problem goes away.
```

### Problem

I assume this problem stems shaping the pop-up into another sized container. But am not knowledgeable enough to know how to move the dropdown select options to their proper position.

Thanks in advance for any help!

### Read the documentation

- [X] I have read the documentation
