### DISCUSSION TITLE
Struggling to inverse the colors of a switch tied to a lock

### DISCUSSION THREAD

**Discussion by rcdailey** [Clooos/Bubble-Card#1454] [Questions about config, custom styles and templates] [answered]
### Goal

I want to invert the color behavior of my lock button in Bubble Card. Currently when the lock is locked, the icon is blue (active). When unlocked, it shows as gray (inactive). I want this reversed since unlocked is the "concerning state" that should grab attention. I'd like to use red for the unlocked state and the standard gray/inactive color for the locked state.

![image](https://github.com/user-attachments/assets/3bfce28a-6675-4cce-b392-ec5993d45ace)

The screenshot shows my current configuration where the locked state (which should be gray/inactive) is still showing as blue.

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
card_layout: large
entity: lock.front_door
button_type: switch
show_state: true
show_attribute: false
styles: >
  .bubble-button-background {
    opacity: 1 !important;
    background-color: ${state === 'unlocked' ? 'rgba(180,20,60,0.5)' : 'var(--bubble-main-background-color)'} !important;
  }

  .bubble-icon {
    color: ${state === 'unlocked' ? 'rgba(180,20,60,1)' : 'var(--bubble-icon-color)'} !important;
  }

  ${icon.setAttribute("icon", state === 'unlocked' ? 'mdi:lock-open-variant' :
  'mdi:lock')};
sub_button:
  - entity: sensor.front_lock_battery_level
    show_state: true
    show_name: false
    show_attribute: false
    show_last_changed: false
    state_background: false
    show_background: false
    tap_action:
      action: none
modules:
  - default
```

### Which step did you already try?

I've tried setting custom CSS for both the background and the icon colors based on the state, as shown in my code. I'm specifically targeting the `.bubble-icon` class to try and override the icon color, but it doesn't seem to be working for the locked state.

```css
.bubble-icon {
  color: ${state === 'unlocked' ? 'rgba(180,20,60,1)' : 'var(--bubble-icon-color)'} !important;
}
```

I'm using v3.0.0-beta.5 of Bubble Card.

### Problem

I cannot get the lock icon to display as gray (inactive) when in the locked state. Despite my CSS for the `.bubble-icon` class, it still appears blue when locked. I'd like to know:

1. How to simplify the setup to get the desired effect (locked=gray, unlocked=red)
2. What's the proper way to swap the inactive/active themes for a lock button
3. How to specify the standard gray inactive color in CSS that most buttons use when inactive

Although the project readme shows many examples, most of them deal in setting *explicit* colors like "red" or "blue", but it does not show dynamic usage of variables or ways to utilize colors already in play (e.g. inactive and active color states). So this has been especially challenging.

## Feedback
I find simple customizations like changing colors of icons and backgrounds very frustrating because they require CSS knowledge. I think there should be simple input fields for things like icon color, icon type, background color, active and inactive colors. CSS should be reserved for "advanced" modifications, not these basic customizations that most users would want to do. This requirement ruins the user experience and ease of use for those who aren't web developers.

### Read the documentation

- [X] I have read the documentation

**Comment by viatro** [comment]
Chrome dev tools show me that icon color for turned on state is declared as
```css
color: var(--bubble-icon-color, var(--bubble-accent-color, var(--bubble-default-color)));
```
and that `--bubble-icon-color` and `--bubble-accent-color` are not defined. So icon-color fallbacks to accent-color, which then fallbacks to default-color, and default-color is defined as that blue `rgb(5, 107, 184)`.
When you use just `var(--bubble-icon-color)` without fallbacks, browser can't show undefined nothingness, and automatically fallbacks to previous declaration (from the beginning), returning blue.

The same for turned off state is
`color: inherit;`
with parent's declaration
`color: var(--primary-text-color);`
Try to use one of these two instead of your `var(--bubble-icon-color)`

**Reply by rcdailey** [reply]
I did inspect a icon that had the color I wanted. I already tried primary text color but it doesn't change the color. I don't know why.

**Reply by viatro** [reply, marked as answer]
Try these (one after the other):
1. Make sure you have not forgotten the `!important` part:
```css
.bubble-icon {
  color: ${state === 'unlocked' ? 'rgba(180,20,60,1)' : 'var(--primary-text-color)'} !important;
}
```
2. Try some basic color keyword to see if there is a problem with `--primary-text-color`:
```css
.bubble-icon {
  color: ${state === 'unlocked' ? 'red' : 'gray'} !important;
}
```
This line must work, or there is some deeper problem.
3. More complicated variant of "single-line" solution for icon color is
```css
.is-off .bubble-icon {
  color: red !important;
}
.is-on .bubble-icon {
  color: gray !important;
}
```
If this work, try to change `gray` to `var(--primary-text-color)` or `inherit` again.
4. In my theme (default dark Home Assistant theme) I see the following declarations:
```css
--primary-text-color: #e1e1e1;
--secondary-text-color: #9b9b9b;
--disabled-text-color: #6f6f6f;
```
Try to use these hex-codes written manually instead of `gray` to see if one of them is the the same as the color for disabled icon in your theme.
