### DISCUSSION TITLE
sub button, drop down, not dropping down

### DISCUSSION THREAD

**Discussion by poolguard** [Clooos/Bubble-Card#1496] [Questions about config, custom styles and templates]
### Goal

This was working a little while ago, but it stopped working and I can't figure out what I'm doing wrong. I have a sub button that is tied to a list that I used to control states of lights in my house. I used to be able to click the sub button and see the full list of items, but it is no longer dropping down. My YAML is below. I have a number of these cards and none of them are working anymore.

### Source Yaml

```yaml
type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                entity: light.group_home_theater_lights
                name: Lights
                tap_action:
                  action: perform-action
                  perform_action: script.scene_toggle
                  target: {}
                  data:
                    select_entity: input_select.hone_theater_scenes
                    scene: Daylight
                    off_scene: 'Off'
                double_tap_action:
                  action: none
                hold_action:
                  action: none
                button_action:
                  tap_action:
                    action: perform-action
                    perform_action: script.scene_toggle
                    target: {}
                    data:
                      select_entity: input_select.hone_theater_scenes
                      scene: Daylight
                      off_scene: 'Off'
                  double_tap_action:
                    action: none
                  hold_action:
                    action: none
                sub_button:
                  - entity: input_select.hone_theater_scenes
                    show_state: true
                    show_arrow: true
```

### Which step did you already try?

```yaml
I have tried re-creating them, as well as tried using it on a number of different computers and browsers. Nothing seems to work.
```

### Problem

When I click on the sub button, there is no pop-up, allowing me to select one of the options

### Read the documentation

- [ ] I have read the documentation
