### DISCUSSION TITLE
[Styling Module, JS Module, JS+Editor Module] Customize icon color and background color

### DISCUSSION THREAD

**Discussion by Dimi27** [Clooos/Bubble-Card#1514] [Share your Modules]
# Customize the icon color and the icon backgrond color

**Version:** 1.20  
**Creator:** Dimi27

> [!IMPORTANT] 
> **Supported cards:**
>  - Button
>  - Climate
>  - Media Player
>  - Select
>  - Cover

Customize the icon color and the icon background color.
Colors can be a theme color or a hex value.
<br><br>
<code-block><pre>
icon_color:
    icon:
        color: red
    background:
        use_hex: true
        color_hex: '#0000ff33'
</pre></code-block>

Configure this module via the editor or in YAML, for example:

```yaml
icon_color: 
```

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply install it from the Module Store (from the editor of any card > Modules), or copy and paste the following configuration into a `/www/bubble/modules/icon_color.yaml` file.

```yaml
icon_color:
    name: "Customize the icon color and the icon backgrond color"
    version: "1.20"
    creator: "Dimi27"
    link: "https://github.com/Clooos/Bubble-Card/discussions/XXXX"

    supported:
        - button
        - climate
        - media-player
        - select
        - cover

    description: |
        Customize the icon color and the icon background color.
        Colors can be a theme color or a hex value.
        <br><br>
        <code-block><pre>
        icon_color:
            icon:
                color: red
            background:
                use_hex: true
                color_hex: '#0000ff33'
        </pre></code-block>
        
        <br><br>
        <code-block><pre>
        icon_color: 
            # Your configuration here
        </pre></code-block>

    code: |
        ${(() => {
        const cfg = this.config.icon_color || {};
        
        const icon = cfg.icon ?? {
          use_hex: cfg.use_hex,
          color: cfg.color,
          color_hex: cfg.color_hex
        };
        const bg = cfg.background ?? {
          use_hex: cfg.bg_use_hex,
          color: cfg.bg_color,
          color_hex: cfg.bg_color_hex
        };
        
        const resolveColor = (c) => {
          if (c.use_hex) return c.color_hex || null;
          if (c.color) return `var(--${c.color}-color)`;
          return null;
        };
        
        const iconColor = resolveColor(icon);
        const bgColor = resolveColor(bg);
        
        const css = [];
        
        if (iconColor) {
          css.push(`.bubble-icon { color: ${iconColor} !important; }`);
        }
        
        if (bgColor) {
          css.push(`.bubble-icon-container { background-color: ${bgColor} !important; }`);
        }
        
        return css.join('\n');
        })()}
        

    editor:
      - type: expandable
        title: Icon
        icon: mdi:palette
        schema:
          - name: icon
            label: Color
            selector:
              object:
                fields:
                  color:
                    label: Theme color
                    visible_if: '!item.use_hex'
                    selector:
                      ui_color:
                        include_none: true
                  color_hex:
                    label: Hex color
                    default: '#ff6600'
                    visible_if: '!!item.use_hex'
                    selector:
                      text: {}
                  use_hex:
                    label: Use hex instead?
                    selector:
                      boolean: {}
      - type: expandable
        title: Icon background
        icon: mdi:circle-opacity
        schema:
          - name: background
            label: Color
            selector:
              object:
                fields:
                  color_hex:
                    label: Hex color
                    default: '#ff660033'
                    visible_if: '!!item.use_hex'
                    selector:
                      text: {}
                  color:
                    label: Theme color
                    visible_if: '!item.use_hex'
                    selector:
                      ui_color:
                        include_none: true
                  use_hex:
                    label: Use hex instead?
                    selector:
                      boolean: {}
      
```

</details>

---

### Screenshot:

<img width="395" height="615" alt="image" src="https://github.com/user-attachments/assets/b8cd04e5-7bbf-492f-8202-d09188e2bb85" />
