### DISCUSSION TITLE
For media player sub-buttons, why doesn't it show the dynamic "Now playing" icon? Regular button icon does.

### DISCUSSION THREAD

**Discussion by deergitseason** [Clooos/Bubble-Card#1515] [Questions about config, custom styles and templates]
### Goal

I want to add a media player as a sub-button and have the icon show what's currently playing, like how it works for the Button Icon.

### Source Yaml

```yaml
- type: custom:bubble-card
    card_type: button
    button_type: state
    entity: media_player.bedroom_roku
    columns: 1
    show_state: true
    show_attribute: true
    attribute: percentage
    tap_action:
      action: toggle
    modules:
      - default
    sub_button:
      - entity: media_player.bedroom_roku
        show_state: false
        show_attribute: true
        attribute: app_name
```

### Problem

When adding a media player entity as a Button (or Media Player), the icon will display whatever's currently playing. 4

For my Roku player it will show the current app/channel as the icon:

![Screenshot 2025-05-17 at 8 30 41 AM](https://github.com/user-attachments/assets/243aafc9-8c31-4a78-bb83-0b7a299110fa)

However when I add the same entity as a sub-button, it only shows the mdi-icon:

![Screenshot 2025-05-17 at 8 33 09 AM](https://github.com/user-attachments/assets/7e523f07-96b4-4465-a162-3f941a177d52)

Ideally I'd like the sub-button to only show the icon, but also show what's currently playing.

Any thoughts?

### Read the documentation

- [X] I have read the documentation
