### DISCUSSION TITLE
Is there a way to have animated backgrounds?

### DISCUSSION THREAD

**Discussion by geozza123** [Clooos/Bubble-Card#1517] [Questions about config, custom styles and templates]
### Goal

I would like to add an animated background (footsteps) if there is motion detected, and have this still show if the colour of the background changes.

I have setup a border to apply with motion, but I think this would be a nice addition. I don't know where to start.

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: light.kitchen_lights
sub_button:
  - entity: sensor.kitchen_temperature_sensor
    state_background: false
    show_background: false
    show_icon: false
    show_state: true
  - entity: sensor.kitchen_humidity_sensor
    show_state: true
    show_icon: false
    show_background: false
card_layout: large-2-rows
button_action:
  tap_action:
    action: navigate
    navigation_path: "#kitchen-popup"
tap_action:
  action: navigate
  navigation_path: "#kitchen-popup"
show_icon: true
use_accent_color: false
show_state: false
force_icon: false
grid_options:
  columns: 6
  rows: 1
styles: |-
  .bubble-button-background {
    background-color: ${hass.states['light.kitchen_lights'].state === 'on' ? 'rgba(255,152,0)' : ''} !important;
    }
  .bubble-button-card-container { 
      border-style: solid;
      border-width: 2px;
      border-color: ${
      (hass.states['binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone'].state === 'on' ||
      hass.states['binary_sensor.kitchen_sink_motion_sensor_iaszone'].state === 'on')
      ? 'var(--primary-color)'
      : 'transparent'
    } !important;
    }      
name: Kitchen
icon: mdi:fridge
modules:
  - default
dynamic_lighting:
  light_entity: light.kitchen_lights
  illuminance_sensor: sensor.lumi_lumi_sensor_motion_aq2_illuminance
```

### Read the documentation

- [X] I have read the documentation
