### DISCUSSION TITLE
How to change popup top margin dynamically

### DISCUSSION THREAD

**Discussion by dragonlee429** [Clooos/Bubble-Card#1521] [Questions about config, custom styles and templates]
### Goal

Hello! I made it so that when music plays, a media player card appears at the bottome of the popup as shown in video. I want to adjust the 'margin_top_mobile' value based on whether the music is playing or not to perfectly match the height. For example, music off : margin_top_mobile: calc(100vh - 490px) / music on: margin_top_mobile: calc(100vh - 530px). How could I achieve this? 

https://github.com/user-attachments/assets/301b4098-e3c2-4b08-8df0-a5c961d5b7ff

### Source Yaml

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#livingroom"
    button_type: name
    modules:
      - default
    bg_color: "#393746"
    bg_opacity: "100"
    margin_top_mobile: calc(100vh - 490px)
    bg_blur: "0"
    show_header: false
    backdrop_blur: ""
    hide_backdrop: false
    shadow_opacity: "100"
    card_mod:
      style: |
        :host {
          {% if is_state('media.player_', 'playing') %}
            margin-top: calc(100vh - 530px) !important;
          {% else %}
            margin-top: calc(100vh - 490px) !important;
          {% endif %}
        }
```

### Read the documentation

- [X] I have read the documentation
