### DISCUSSION TITLE
Template for icons in separator

### DISCUSSION THREAD

**Discussion by gouthamravee** [Clooos/Bubble-Card#1527] [Questions about config, custom styles and templates] [answered]
### Goal

I want to have logic control what icons show up on the buttons in the separator. 

### Source Yaml

```yaml
type: custom:bubble-card
card_type: separator
name: Bedroom
sub_button:
  - entity: sensor.bedroom_weather_temperature
    show_state: true
    show_name: false
    show_icon: true
    show_background: false
    show_last_changed: false
    show_attribute: false
  - entity: sensor.bedroom_weather_humidity
    show_state: true
    show_background: false
    show_icon: true
  - entity: sensor.bedroom_occupancy
    show_last_changed: false
    show_state: false
    state_background: true
    show_icon: true
    show_background: true
    show_attribute: false
  - entity: binary_sensor.bedroom_door_contact
  - entity: binary_sensor.bed_sensor_g
    icon: mdi:bed
    show_name: true
    name: G
    show_state: false
  - entity: binary_sensor.bed_sensor_n
    icon: mdi:bed
    show_name: true
    name: "N"
    show_state: false
card_layout: large-2-rows
grid_options:
  columns: full
```

### Which step did you already try?

```yaml
type: custom:bubble-card
card_type: separator
name: Bedroom
sub_button:
  - entity: sensor.bedroom_weather_temperature
    show_state: true
    show_name: false
    show_icon: true
    show_background: false
    show_last_changed: false
    show_attribute: false
  - entity: sensor.bedroom_weather_humidity
    show_state: true
    show_background: false
    show_icon: true
  - entity: sensor.bedroom_occupancy
    show_last_changed: false
    show_state: false
    state_background: true
    show_icon: true
    show_background: true
    show_attribute: false
  - entity: binary_sensor.bedroom_door_contact
  - entity: binary_sensor.bed_sensor_g
    icon: mdi:bed
    show_name: true
    name: G
    show_state: false
  - entity: binary_sensor.bed_sensor_n
    icon: |
      {% if true %}
        mdi:bed
      {% endif %}
    show_name: true
    name: "N"
    show_state: false
card_layout: large-2-rows
grid_options:
  columns: full
```

### Problem

The template above is just a test to see if templating would work, but doesn't seem like it supports templates at all. I feel like the only other option here is card_mod, but before I do that wanted to see if there's a better way I'm missing. 

### Read the documentation

- [X] I have read the documentation
