### DISCUSSION TITLE
edit .mdc-select is not working

### DISCUSSION THREAD

**Discussion by Jonsonmon** [Clooos/Bubble-Card#1534] [Questions about config, custom styles and templates]
### Goal

Im trying to edit .mdc-select but it's not working... Is this a child div or something?

### Source Yaml

```yaml
.mdc-select {
    color: transparent !important;
    width: 100px !important; /* for example */
    position: absolute !important;
    pointer-events: none;
    right: var(--right-value, 46px);
    top: -28px;
}
```

### Read the documentation

- [ ] I have read the documentation
