### DISCUSSION TITLE
[Styling Module] Card Text Styling

### DISCUSSION THREAD

**Discussion by navypixel** [Clooos/Bubble-Card#1556] [Share your Modules]
### Module post template

# Card Text Styling

**Version:** v1.0  
**Creator:** NavyPixel

> [!IMPORTANT] 
> **Supported cards:**
>  - Button
>  - Calendar
>  - Climate
>  - Cover
>  - Media Player
>  - Pop Up
>  - Select

Customize only the text styling for .bubble-name and .bubble-state.
Includes color, font size, font weight, and opacity for each.

Configure this module via the editor or in YAML, for example:

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply install it from the Module Store (from the editor of any card > Modules), or copy and paste the following configuration into your `/www/bubble/bubble-modules.yaml` file.

```yaml
card_text_style:
    name: "Card Text Styling"
    version: "v1.0"
    creator: "NavyPixel"
    link: "https://github.com/Clooos/Bubble-Card/discussions/1556"

    supported:
        - button
        - calendar
        - climate
        - cover
        - media-player
        - pop-up
        - select

    description: |
        Customize only the text styling for .bubble-name and .bubble-state.
        Includes color, font size, font weight, and opacity for each.
        
        <br><br>
        <code-block><pre>
        card_text_style: 
            name: YOUR_VALUE
        </pre></code-block>

    code: |
        ${(() => {
          // .bubble-name Styling
          let bubbleName = card.querySelector(".bubble-name");
          if (bubbleName && this.config.card_text_style.name) {
            const nameCfg = this.config.card_text_style.name;
            if (nameCfg.color) bubbleName.style.setProperty("color", `var(--${nameCfg.color}-color)`, "important");
            if (nameCfg.font_size) bubbleName.style.setProperty("font-size", nameCfg.font_size, "important");
            if (nameCfg.font_weight) bubbleName.style.setProperty("font-weight", nameCfg.font_weight, "important");
            if (nameCfg.opacity !== undefined) bubbleName.style.setProperty("opacity", nameCfg.opacity, "important");
          }
        
          // .bubble-state Styling
          let bubbleState = card.querySelector(".bubble-state");
          if (bubbleState && this.config.card_text_style.state) {
            const stateCfg = this.config.card_text_style.state;
            if (stateCfg.color) bubbleState.style.setProperty("color", `var(--${stateCfg.color}-color)`, "important");
            if (stateCfg.font_size) bubbleState.style.setProperty("font-size", stateCfg.font_size, "important");
            if (stateCfg.font_weight) bubbleState.style.setProperty("font-weight", stateCfg.font_weight, "important");
            if (stateCfg.opacity !== undefined) bubbleState.style.setProperty("opacity", stateCfg.opacity, "important");
          }
        })()}
        

    editor:
      - name: name
        type: expandable
        title: Name Text Adjustments
        icon: mdi:format-font
        schema:
          - name: color
            label: Text Color
            selector:
              ui_color: {}
          - name: font_size
            label: Font Size (e.g. 16px)
            selector:
              text: {}
          - name: font_weight
            label: Font Weight (e.g. normal, bold, 600)
            selector:
              text: {}
          - name: opacity
            label: Text Opacity
            selector:
              number:
                min: 0
                max: 1
                step: 0.1
                mode: slider
      - name: state
        type: expandable
        title: State Text Adjustments
        icon: mdi:format-size
        schema:
          - name: color
            label: Text Color
            selector:
              ui_color: {}
          - name: font_size
            label: Font Size (e.g. 14px)
            selector:
              text: {}
          - name: font_weight
            label: Font Weight (e.g. normal, bold, 400)
            selector:
              text: {}
          - name: opacity
            label: Text Opacity
            selector:
              number:
                min: 0
                max: 1
                step: 0.1
                mode: slider
      
```

</details>

---

### Screenshot:

![card style edit](https://github.com/user-attachments/assets/b7e596f8-e5ad-45af-94d7-361fb6cd6b8b)

### Before posting your module

- [X] I've replaced all lines starting with ->
- [X] I've updated the unsupported cards above the description and under the `unsupported` property
- [X] I've added a screenshot
- [X] I've chosen a unique `your_module_key`
- [X] I really enjoyed working on this module ❤️
