### DISCUSSION TITLE
[Styling Module] Restore previous accent color

### DISCUSSION THREAD

**Discussion by Clooos** [Clooos/Bubble-Card#1558] [Share your Modules]
# Restore previous accent color

**Version:** 1.0  
**Creator:** Clooos

> [!IMPORTANT] 
> **Supported cards:**
>  - Button
>  - Calendar
>  - Climate
>  - Cover
>  - Horizontal Buttons Stack
>  - Media Player
>  - Pop Up
>  - Select
>  - Separator

Restores the pre–Bubble Card 3 accent color. Not a fan of the new contrast-friendly blue? This module brings back the original accent color.

Just toggle the "All cards" button in the module configuration.

---

<details>

<summary><b>🧩 Get this Module</b></summary>

<br>

> To use this module, simply install it from the Module Store (from the editor of any card > Modules), or copy and paste the following configuration into your `/www/bubble/bubble-modules.yaml` file.

```yaml
previous_accent_color:
    name: "Restore previous accent color"
    version: "1.0"
    creator: "Clooos"
    link: "https://github.com/Clooos/Bubble-Card/discussions/1558"

    supported:
        - button
        - calendar
        - climate
        - cover
        - horizontal-buttons-stack
        - media-player
        - pop-up
        - select
        - separator

    description: |
        Restores the pre–Bubble Card 3 accent color. Not a fan of the new contrast-friendly blue? This module brings back the original accent color.

    code: |
        * {
            --bubble-accent-color: var(--accent-color);
            --bubble-button-accent-color: var(--accent-color);
        }

```

</details>

---

### Screenshot:

![previous-accent-color-module](https://github.com/user-attachments/assets/8195e1e1-c3ea-475a-b0d6-985ffe4e43c0)
