### DISCUSSION TITLE
Close popup on action

### DISCUSSION THREAD

**Discussion by jamesbull** [Clooos/Bubble-Card#1561] [Questions about config, custom styles and templates]
### Goal

I've used Bubble Card to create a room selector pop-up. Clicking a link in the popup reveals specific room-based cards in the dashboard, no dashboard or view switching, it's all using visibility conditions based on a room selector input select helper. The link in the popup just sets the input select state to the room and the dashboard reveals the right cards. It's nice and slick. Once the room is selected, I want the popup to close.

### Source Yaml

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#rooms"
    name: Rooms
    icon: mdi:menu
    show_icon: true
    show_name: true
    show_header: true
    show_state: false
    scrolling_effect: false
    force_icon: false
    close_on_click: true
    card_layout: normal
    styles: |-
      /*.bubble-button-card-container {
        background: none !important;
      }
      .bubble-name-container {
        margin-left: 8px !important;
      }
      .bubble-name{
        font-size: 20px !important;
      }*/
    bg_opacity: "88"
    bg_blur: "10"
    margin_top_mobile: 50px
    margin_top_desktop: 50px
    bg_color: "#000"
  - type: custom:mushroom-template-card
    primary: Arcade
    icon: mdi:controller
    secondary: ""
    layout: horizontal
    fill_container: true
    multiline_secondary: false
    tap_action:
      action: perform-action
      perform_action: input_select.select_option
      target:
        entity_id: input_select.room_selector
      data:
        option: Arcade
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: custom:mushroom-template-card
    primary: Primary Bedroom
    icon: mdi:bed
    secondary: ""
    layout: horizontal
    fill_container: true
    tap_action:
      action: perform-action
      perform_action: input_select.select_option
      target:
        entity_id: input_select.room_selector
      data:
        option: Primary Bedroom
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: custom:mushroom-template-card
    primary: Theatre
    icon: mdi:theater
    secondary: ""
    fill_container: true
    layout: horizontal
    tap_action:
      action: perform-action
      perform_action: input_select.select_option
      target:
        entity_id: input_select.room_selector
      data:
        option: Theatre
    hold_action:
      action: none
    double_tap_action:
      action: none
title: "#rooms"
```

### Problem

I can't find a way to close the popup after I select a room. I would have thought the "Close the pop-up after any click or tap" would do that, but it doesn't. It seems to be disabled when clicking/tapping an item in the popup, but it does close when clicking on any empty space in the popup.

How can I achieve my desired behaviour?

### Read the documentation

- [X] I have read the documentation
