### DISCUSSION TITLE
Can't get bubble card background blur enabled to work

### DISCUSSION THREAD

**Discussion by Vib1240n** [Clooos/Bubble-Card#1573] [Questions about config, custom styles and templates]
**Describe the bug**  
I have bubble card popup in my dashboard and I have an image as the popup background. The cards inside the popup are transparent but the backdrop-filter property isn't blurring the cards. 

**To Reproduce**  
1. Copy paste yaml code for popup
2. Set this image as background 
![image](https://github.com/user-attachments/assets/72faf504-f6ef-475b-b655-61f759cb88bd)
3. Adjust entities and save. 

**Expected behavior**  
Have the cards inside the popup have a blurred background, giving a glassmorphic effect. 

**Screenshots**  
![image](https://github.com/user-attachments/assets/836082d4-673d-4205-837d-5ba09aaed0b8)
**YAML**  
If applicable, add any relevant YAML code.

```yaml

type: custom:bubble-card
            card_type: pop-up
            hash: "#laundry-room-popup"
            button_type: name
            modules:
              - default
            name: Laundry Room
            button_action:
              tap_action:
                action: perform-action
                perform_action: light.turn_off
                target:
                  area_id: main_bedroom
            close_on_click: true
            backdrop_blur: "10"
            margin_top_mobile: 300px
            bg_color: "#ffffff"
            bg_opacity: "1"
            bg_blur: "10"
            card_layout: normal
            icon: mdi:washing-machine
            styles: |-
              .bubble-pop-up-background {
                background-image: url("/local/image/laundryroomblue.jpeg");
                background-repeat: no-repeat;
                background-size: cover;
                background-position-y: center;
              }
              .bubble-button-card-container {
                background: transparent;
                backdrop-filter: blur(20px) !important;
                color: black;
              }
              .bubble-icon-container{
                background: transparent;
              }
              .bubble-close-button {
                background: rgba(200,0,0,0.3);
                backdrop-filter: blur(20px) !important;
                border: 1px solid rgba(200,0,0,0.2);
              }
            margin: 7px
            shadow_opacity: "10"
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: state
                modules:
                  - default
                  - subbutton_below
                entity: switch.dryer
                sub_button:
                  - show_name: false
                    show_state: true
                    entity: sensor.washer_completion_time
                    show_attribute: false
                    attribute: friendly_name
                    show_background: false
                  - entity: sensor.washer_washer_machine_state
                    show_name: false
                    name: State
                    icon: mdi:tumble-dryer
                    show_state: true
                    show_last_changed: false
                    show_last_updated: false
                rows: "2"
                show_attribute: false
                styles: |-
                  ha-card {
                    --bubble-main-background-color: rgba(0, 0, 0, 0.39) !important;
                    --bubble-button-border-radius: 16px;
                    --bubble-button-box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1) !important;
                    backdrop-filter: blur(16px) !important;
                    -webkit-backdrop-filter: blur(16px) !important;
                    border: 1px solid rgba(0, 0, 0, 0.51) !important; 
                  }
              - type: custom:bubble-card
                card_type: button
                button_type: state
                modules:
                  - default
                  - subbutton_below
                entity: switch.washer
                sub_button:
                  - show_name: false
                    show_state: true
                    entity: sensor.washer_completion_time
                    show_attribute: false
                    attribute: friendly_name
                    show_background: false
                  - entity: sensor.washer_washer_machine_state
                    show_state: true
                    show_attribute: false
                rows: "2"
                styles: |-
                  ha-card {
                    --bubble-main-background-color: rgba(0, 0, 0, 0.39) !important;
                    --bubble-button-border-radius: 16px;
                    --bubble-button-box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1) !important;
                    backdrop-filter: blur(16px) !important;
                    -webkit-backdrop-filter: blur(16px) !important;
                    border: 1px solid rgba(0, 0, 0, 0.51) !important; 
                  }

```

**Informations (please complete the following information):**  
 - OS: IOS 18.5
 - Browser/App: Home assistant Companion App
 - Bubble Card version: c3.0.0-beta.9
 - Home Assistant version: 2025.5.3

Thank you! 🍻
