### DISCUSSION TITLE
Select Card Type and Select Sub Button Issues

### DISCUSSION THREAD

**Discussion by poolguard** [Clooos/Bubble-Card#1577] [Questions about config, custom styles and templates] [answered]
### Goal

I am trying to get the select card type and select sub button type working 

### Source Yaml

```yaml
type: custom:bubble-card
card_type: select
name: Scene
entity: input_select.home_theater_scenes
show_state: true

and sub button

cards:
  - type: custom:bubble-card
    card_type: separator
    name: Family Room
  - type: custom:bubble-card
    card_type: button
    entity: light.family_room_lights
    name: Lights
    sub_button:
      - entity: input_select.family_room_scenes
        icon: ""
        name: ""
        show_name: true
        show_state: true
    button_action:
      tap_action:
        action: perform-action
        perform_action: script.scene_toggle
        target: {}
        data:
          select_entity: input_select.family_room_scenes
          scene: Daylight
          off_scene: "Off"
      double_tap_action:
        action: none
      hold_action:
        action: none
    tap_action:
      action: perform-action
      perform_action: script.scene_toggle
      target: {}
      data:
        select_entity: input_select.family_room_scenes
        scene: Daylight
        off_scene: "Off"
    double_tap_action:
      action: none
    hold_action:
      action: none
```

### Which step did you already try?

```yaml
Uninstalling, rebooting HA and reinstalling Bubble Card.

clearing Browser and working on a fresh load of windows (never access HA before) in edge, chrome, and firefox
```

### Problem

When I try to setup a select card type in the visual editor at first i see the entity select box in the config but as soon as i click on the box it just disappears making it so i cannot configure the select card with the GUI.

When i try to set up the card in yaml it looks like the card is there and looks correct but when i click on it there is no drop down. i clock the bard shoes the color change with the click but does not show the drop down.

The same thing happens with the sub button example.  i am able to select the input_select using the entity ID in the visual editor but there is never a drop down when i click on it. 

This was working until a few weeks ago. and i do have a number of options in the input_select helper objects.

Any help would be awesome!

### Read the documentation

- [X] I have read the documentation
