### DISCUSSION TITLE
Use Auto-entities card with this bubble card: help needed

### DISCUSSION THREAD

**Discussion by MilesTEG1** [Clooos/Bubble-Card#1591] [Questions about config, custom styles and templates]
Hello,

### Goal

I want to use the [auto-entities card](https://github.com/thomasloven/lovelace-auto-entities) with my bubble card here:

But I can't find a way to have the styles use the entities in use with auto-entities card, nor add `_power` after the name of the current entities to get the power in order to set a custom color for some values.

![image](https://github.com/user-attachments/assets/14a47f55-d28a-4144-a3bc-ddb2898337ae)

### Source Yaml

```yaml
type: custom:bubble-card
card_type: button
button_type: switch
entity: switch.smartplug_bureau
tap_action:
  confirmation:
    text: Allumer/Éteindre la prise ?
  action: toggle
  target:
    entity_id: switch.smartplug_bureau
  show_state: false
button_action:
  tap_action:
    confirmation:
      text: Allumer/Éteindre la prise ?
    action: toggle
    target:
      entity_id: switch.smartplug_bureau
    show_state: false
  double_tap_action:
    action: none
  hold_action:
    action: none
double_tap_action:
  action: none
hold_action:
  action: none
icon: mdi:power-socket-fr
force_icon: false
show_state: true
show_last_changed: true
show_last_updated: false
sub_button:
  - entity: sensor.smartplug_bureau_power
    name: Puissance
    show_name: true
    show_state: true
    show_last_changed: false
    show_attribute: false
    show_background: true
    state_background: false
    visibility:
      - condition: state
        entity: switch.smartplug_bureau
        state: "on"
modules:
  - "!default"
card_layout: large
grid_options:
  rows: auto
  columns: 12
get_state_attribute:
  - entity: sensor.smartplug_bureau_power
flat_style:
  card_styles:
    prime_color:
      - 25
      - 23
      - 140
icon_container_color:
  color: accent
bubble_chips:
  gap: 30
  justify-content: space-evenly
izequbes_custom_colors:
  main_icon:
    background_color: dark-grey
    icon_color: teal
    icon_opacity: 0.9
subbutton_colors:
  subbutton1:
    color: brown
visual_styling_center:
  height_multiplier: 2.1
  inner_padding: 8
  icon_vertical_margin: -4
styles: |
  .bubble-button-background {
    background-color: ${ hass.states['switch.smartplug_bureau'].state === 'on'
        ? 'rgba(0, 255, 255, 0.35)'
        : hass.states['switch.smartplug_bureau'].state === 'off'
          ? 'rgba(30, 30, 30, 0.35)'
          : 'rgba(200, 200, 200, 0.35)'
      } !important;
  }

  .bubble-icon-container{
    opacity: 0.8 !important;
    background-color: rgba(0, 0, 0) !important;
  }

  .bubble-icon {
    color: 
      ${ hass.states['switch.smartplug_bureau'].state === 'on'
        ? 'rgba(0, 255, 255, 0.55)'
        : hass.states['switch.smartplug_bureau'].state === 'off'
          ? 'rgba(30, 30, 30, 0.55)'
          : 'rgba(200, 200, 200, 0.55)'
      } !important;
  }


  .bubble-sub-button-1 > ha-icon {
    color: 
        ${hass.states['sensor.smartplug_bureau_power'].state > 110
          ? 'rgb(255, 0, 212)' 
          : hass.states['sensor.smartplug_bureau_power'].state > 100
          ? 'rgb(255, 0, 0)' 
            : hass.states['sensor.smartplug_bureau_power'].state > 90
            ? 'rgb(252, 152, 3)'
            : hass.states['sensor.smartplug_bureau_power'].state > 80
              ? 'rgb(255, 255, 0)'
              : hass.states['sensor.smartplug_bureau_power'].state > 60
                ? 'rgb(87, 255, 0)'
                : hass.states['sensor.smartplug_bureau_power'].state > 40
                  ? 'rgb(0, 255, 127)'
                  : hass.states['sensor.smartplug_bureau_power'].state > 20
                    ? 'rgb(0, 203, 255)'
                    : hass.states['sensor.smartplug_bureau_power'].state > 10
                      ? 'rgb(0, 77, 255)'
                      : hass.states['sensor.smartplug_bureau_power'].state > 0
                        ? 'rgb(0, 0, 255)'
                        : 'rgb(145, 145, 145)'
        } !important;
  }

  .bubble-sub-button-1 {
    opacity: 0.8 !important;
    background-color: rgb(0, 0, 0) !important;
    font-weight: bold;
    color:
        ${hass.states['sensor.smartplug_bureau_power'].state > 110
          ? 'rgb(255, 0, 212)' 
          : hass.states['sensor.smartplug_bureau_power'].state > 100
          ? 'rgb(255, 0, 0)' 
            : hass.states['sensor.smartplug_bureau_power'].state > 90
            ? 'rgb(252, 152, 3)'
            : hass.states['sensor.smartplug_bureau_power'].state > 80
              ? 'rgb(255, 255, 0)'
              : hass.states['sensor.smartplug_bureau_power'].state > 60
                ? 'rgb(87, 255, 0)'
                : hass.states['sensor.smartplug_bureau_power'].state > 40
                  ? 'rgb(0, 255, 127)'
                  : hass.states['sensor.smartplug_bureau_power'].state > 20
                    ? 'rgb(0, 203, 255)'
                    : hass.states['sensor.smartplug_bureau_power'].state > 10
                      ? 'rgb(0, 77, 255)'
                      : hass.states['sensor.smartplug_bureau_power'].state > 0
                        ? 'rgb(0, 0, 255)'
                        : 'rgb(145, 145, 145)'
        } !important;
  }
``
```

### Which step did you already try?

```yaml
type: custom:auto-entities
filter:
  include:
    - options: {}
      entity_id: ^switch.smartplug_*
  exclude:
    - options: {}
      entity_id: "*wifi*|*child_lock*|*overcharge*"
show_empty: true
card:
  type: custom:bubble-card
  card_type: button
  button_type: switch
```

### Problem

As soon as I choose the Bubble Card in the auto-entities card, I can't have anything:
![image](https://github.com/user-attachments/assets/ccdf0a03-e2bb-42cb-9bbd-622322766305)
![image](https://github.com/user-attachments/assets/148181e8-c288-49b4-add7-4f617b41c32c)

Thanks for the help.

### Read the documentation

- [X] I have read the documentation

**Comment by MilesTEG1** [comment]
Hello,
Some news, not good...
I manage to get a start of Bubble_Card with auto-entities with this:
```yaml
type: custom:auto-entities
filter:
  include:
    - options: {}
      device: ^smartplug_wifi*
  exclude:
    - options: {}
      entity_id: "*child_lock*|*overcharge*"
sort:
  attribute: sensor.smartplug_wifi_*_puissnace
card:
  type: custom:bubble-card
  card_type: button
  button_type: switch
  entity: this.entity_id
  tap_action:
    confirmation:
      text: Allumer/Éteindre la prise ?
    action: toggle
    target:
      entity_id: this.entity_id
    show_state: false
  button_action:
    tap_action:
      confirmation:
        text: Allumer/Éteindre la prise ?
      action: toggle
      target:
        entity_id: this.entity_id
      show_state: false
    double_tap_action:
      action: none
    hold_action:
      action: none
  double_tap_action:
    action: none
  hold_action:
    action: none
  icon: mdi:power-socket-fr
  force_icon: false
  show_state: true
  show_last_changed: true
  show_last_updated: false
  sub_button:
    - entity: sensor.smartplug_wifi_geekom_a7_puissance
      name: Puissance
      show_name: true
      show_state: true
      show_last_changed: false
      show_attribute: false
      show_background: true
      state_background: false
      visibility:
        - condition: state
          entity: switch.smartplug_wifi_geekom_a7
          state: "on"
  modules:
    - "!default"
  card_layout: large
  grid_options:
    rows: auto
    columns: 12
  get_state_attribute:
    - entity: this.entity_id"_puissance"
  flat_style:
    card_styles:
      prime_color:
        - 25
        - 23
        - 140
  icon_container_color:
    color: accent
  bubble_chips:
    gap: 30
    justify-content: space-evenly
  izequbes_custom_colors:
    main_icon:
      background_color: dark-grey
      icon_color: teal
      icon_opacity: 0.9
  subbutton_colors:
    subbutton1:
      color: brown
  visual_styling_center:
    height_multiplier: 2.1
    inner_padding: 8
    icon_vertical_margin: -4
  styles: |
    .bubble-button-background {
      background-color: ${ hass.states['this.entity_id'].state === 'on'
          ? 'rgba(0, 255, 255, 0.35)'
          : hass.states['this.entity_id'].state === 'off'
            ? 'rgba(30, 30, 30, 0.35)'
            : 'rgba(200, 200, 200, 0.35)'
        } !important;
    }

    .bubble-icon-container{
      opacity: 0.8 !important;
      background-color: rgba(0, 0, 0) !important;
    }

    .bubble-icon {
      color: 
        ${ hass.states['this.entity_id'].state === 'on'
          ? 'rgba(0, 255, 255, 0.55)'
          : hass.states['this.entity_id'].state === 'off'
            ? 'rgba(30, 30, 30, 0.55)'
            : 'rgba(200, 200, 200, 0.55)'
        } !important;
    }


    .bubble-sub-button-1 > ha-icon {
      color: 
          ${hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 110
            ? 'rgb(255, 0, 212)' 
            : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 100
            ? 'rgb(255, 0, 0)' 
              : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 90
              ? 'rgb(252, 152, 3)'
              : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 80
                ? 'rgb(255, 255, 0)'
                : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 60
                  ? 'rgb(87, 255, 0)'
                  : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 40
                    ? 'rgb(0, 255, 127)'
                    : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 20
                      ? 'rgb(0, 203, 255)'
                      : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 10
                        ? 'rgb(0, 150, 255)'
                        : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 0
                          ? 'rgb(0, 77, 255)'
                          : 'rgb(145, 145, 145)'
          } !important;
    }

    .bubble-sub-button-1 {
      opacity: 0.8 !important;
      background-color: rgb(0, 0, 0) !important;
      font-weight: bold;
      color:
          ${hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 110
            ? 'rgb(255, 0, 212)' 
            : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 100
            ? 'rgb(255, 0, 0)' 
              : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 90
              ? 'rgb(252, 152, 3)'
              : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 80
                ? 'rgb(255, 255, 0)'
                : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 60
                  ? 'rgb(87, 255, 0)'
                  : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 40
                    ? 'rgb(0, 255, 127)'
                    : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 20
                      ? 'rgb(0, 203, 255)'
                      : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 10
                        ? 'rgb(0, 150, 255)'
                        : hass.states['sensor.smartplug_wifi_geekom_a7_puissance'].state > 0
                          ? 'rgb(0, 77, 255)'
                          : 'rgb(145, 145, 145)'
          } !important;
    }
```
![image](https://github.com/user-attachments/assets/19d0e8ee-ae67-4acd-9a80-60be7d25be8f)

My problem is that I want to get a bubble-card for each `switch.smartplug_wifi*` I have, and that I want the card to show another entities value, the power, with `sensor.smartplug_wifi_blabla_puissance`. (blabla is a generic name, replaced by actual plug name, like geekom_a7, or other). The styles I want are based on the puissance used, so `sensor.smartplug_wifi_blabla_puissance`.

Is it possible to get somting functional?

Thanks in advance.
