### DISCUSSION TITLE
Trying to make a module

### DISCUSSION THREAD

**Discussion by krajani786** [Clooos/Bubble-Card#1594] [Questions about config, custom styles and templates]
### Goal

i want to be able to change the radius of the borders in the card, slider and button for a cohesive look. 

### Source Yaml

```yaml
border-radius-controller:
  name: "Border Radius Controller"
  version: "1.8"
  creator: ""
  description: "A simple and reliable module to override the theme by setting a custom border radius on the card container, the card itself, and the slider."
  code: |
    .bubble-button-card-container,
    .bubble-button-card,
    .bubble-range-slider {
      border-radius: var(--bubble-border-radius) !important;
    }

    ${(() => {
      try {
        const config = this.config['border-radius-controller'] || {};

        const radiusValue = (typeof config.radius === 'number') ? config.radius : 12;
        
        card.style.setProperty('--bubble-border-radius', `${radiusValue}px`);

      } catch (e) {
        console.error("Error in Border Radius Controller module:", e);
      }
      return '';
    })()}
  editor:
    - type: "grid"
      name: "radius_options"
      schema:
        - name: "radius"
          label: "Border Radius"
          default: 12
          selector:
            number:
              min: 0
              max: 50
              step: 1
              mode: slider
              unit_of_measurement: "px"
```

### Problem

This changes it how i want. but i can't modify it on the fly. 

### Read the documentation

- [X] I have read the documentation
