### DISCUSSION TITLE
Camera motion pop-up

### DISCUSSION THREAD

**Discussion by lapo-gh** [Clooos/Bubble-Card#1604] [Questions about config, custom styles and templates]
### Goal

Hi!
I am trying to have a pop-up open whenever there is motion detected by my Ring Doorbell.
The problem is that the pop-up window open directly when the dashboard loads for the first time.
I have seen the bubble-pop-up-fix in both the dashboard resources and in the configuration.yaml file - it seems to not do anything.
![image](https://github.com/user-attachments/assets/62685635-c72a-45f6-b1ac-6ce6606367a9)
I am not sure if I am doing something wrong...

### Source Yaml

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#ring_camera"
    name: Front Door
    icon: mdi:doorbell-video
    show_header: false
    styles: ""
    button_type: name
    bg_color: blue
    hide_backdrop: false
    trigger:
      - condition: or
        conditions:
          - condition: state
            entity: switch.front_door_motion_detection
            state: "on"
          - condition: state
            entity: binary_sensor.entrance_motion_sensor_motion
            state: "on"
    trigger_close: true
    auto_close: "15000"
  - camera_view: auto
    fit_mode: cover
    type: picture-glance
    title: Front door
    entities:
      - entity: camera.front_door_live_view
    camera_image: camera.front_door_live_view
    tap_action:
      action: none
    hold_action:
      action: none
title: Front door
grid_options:
  rows: auto
```

### Read the documentation

- [X] I have read the documentation
