### DISCUSSION TITLE
Unable to update....

### DISCUSSION THREAD

**Discussion by estley** [Clooos/Bubble-Card#1609] [Questions about config, custom styles and templates]
### Goal

I'm trying to update from 2.4 to 3.0 using HACS, and I get the following:

<img width="1025" alt="Screenshot 2025-06-28 at 5 52 32 PM" src="https://github.com/user-attachments/assets/0ceb17a5-cf98-4899-afef-eed0e3e84ae0" />

Not sure what I'm doing wrong, I've tried removing /hacsfiles/Bubble-Card/ and re-downloading, but it's always the same result, the version installed is 2.4....

### Source Yaml

```yaml
resources:
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
```

### Read the documentation

- [ ] I have read the documentation
