### DISCUSSION TITLE
Cover button request

### DISCUSSION THREAD

**Discussion by ouranos6** [Clooos/Bubble-Card#290] [Feature requests]
Hi,

First of all I want to thank you for this amazing work!! I love it!!!

Where I live we have like venetian blinds so we need the Cover open/close AND the cover tilt.

The best way to use that is to have for example on the UP button short press cover tilt and on the long press cover open
Now I'am using the regular card for covers but I would be amaze if it's possible to make a better one what do you think?

<img width="482" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/20718760/72f494fc-0f39-4628-9b74-380bc38ceddf">

**Comment by realroywalker** [comment]
Along the same line as this initial request, I also notice that the default buttons for open / close in the bubble cover card are always up and down, even when using curtains (in this case they should be horizontal open / close) so it's very hard to know which button does what in the case of curtains.

**Comment by vbtrek** [comment]
I'd also like the ability to customise the up and down icons on the cover buttons, they don't make sense for curtains. Haven't found a way to do it with card-mod or styles. Thanks

**Comment by stomko11** [comment]
I would like to add controls for tilt. Instead of just up-down-stop, it would be nice to get buttons for tilt too.

**Reply by j-kwan** [reply]
Hi

You can tweak the slider card (button) for this.

You have to configure the sub buttons for anything you want like the `cover.open_cover_tilt` of `call-service`

```yaml
      - entity: cover.chambre2_volet_roulant_fenetre
        name: TILT-BOTTOM-RIGHT
        icon: mdi:arrow-bottom-right
        tap_action:
          action: call-service
          target:
            entity_id: entity
          service: cover.open_cover_tilt
```

You can check an example in my styling module :
https://github.com/Clooos/Bubble-Card/discussions/1628
