### DISCUSSION TITLE
Feature Request: "Not equal to" as an option for the "state to open the pop-up" field

### DISCUSSION THREAD

**Discussion by MrTheoW** [Clooos/Bubble-Card#302] [Feature requests]
I am using a conditional card that checks of the trash services are going to pick-up the trash today / tomorrow. (see code below)
It would be awesome if you could create a possibility to use a "not equal to" statement in the "state to open the pop-up" field.
That way it would open up a ton load of new possibilities to use the bubble pop-up card.

```
type: conditional
conditions:
  - entity: sensor.mijnafvalwijzer_morgen
    state_not: geen
  - entity: sensor.mijnafvalwijzer_vandaag
    state_not: geen
card:
  type: custom:auto-entities
  card:
    type: glance
  filter:
    include:
      - entity_id: '*mijnafvalwijzer_vandaag'
        options:
          icon: mdi:trash-can-outline
      - entity_id: '*mijnafvalwijzer_morgen'
        options:
          icon: mdi:trash-can-outline
    exclude:
      - state: Geen
  sort:
    method: none
    reverse: true
  show_empty: false
```
