### DISCUSSION TITLE
Feature Requests: Custom Button Card Like State and Mushroom Chip Card Like Values

### DISCUSSION THREAD

**Discussion by efaden** [Clooos/Bubble-Card#322] [Feature requests]
I love the bubble card, but there are two things that would be neat to add.

Firstly custom button card allows you to define the icon, color, etc based upon the state/value of the an entity (not even the entity the button controls).  So for example I could have a card for my fireplace that has an icon without flames and is grey when on and an icon with a flame that is red when it is on.  It would just be cool to be able to really customize the buttons that way.

My second request would be some sort of a card (could be a button with no action) that allows you to display a state/value.  An example would be the temperature, or an icon that can change color to note motion/occupancy.  So for example I have a popup for controlling the basement lights.  It would be slick to be able to throw an icon in the header or somewhere that shows an icon of a person that changes color depending on state of a motion sensor.

Third request would be able to define another state of the cover.  There are a lot of covers that aren't just open or closed.  I leave my garage door cracked sometimes for the cat.  Currently using custom button card to display 3 possible icons (closed, cracked, open).  Would be cool if there was a way to do something similar.

**Comment by awilliams84** [comment]
I agree on the state or template ability in the popup buttons. Is this possible??

I use mushroom cards for buttons currently at the top that show a color, icon, and content based on states. For example: it counts the number and types of doors and windows open in my house and if I have one door open, the icon will be an open door, color yellow, and content "1".

**Reply by jecrell** [reply]
Same here. Just wanted to say this would be a worthwhile feature. I just want icons to show the current states of my house, such as a flame and red color for when my thermostat is running. Love the look of the cards and want to implement template features.

**Comment by eximo84** [comment]
Was going to post something similar, im using button cards to make a swipe clip which then pops up various things or navigates to other dashboards.  I was playing with bubble card horizontal stack to see if i can replace my custom buttons with that but being you can only put a name on a button means its a bit limited compared to what i have now.

Here is an example:

![hass](https://github.com/Clooos/Bubble-Card/assets/25502878/c656aa32-4006-4e7d-b341-5041dfa5d7c0)

**Reply by nagtegaal** [reply]
Could you share some code of this please?

**Reply by eximo84** [reply]
> Could you share some code of this please?

```
type: custom:button-card
entity: light.all_lights
template:
  - overview_chip
icon: ios:lightbulb-fill
variables:
  active_count: |
    [[[ 
      return (states['sensor.active_lights'].state) 
    ]]]

button_card_templates:
  overview_chip:
    aspect_ratio: 1/0.5
    variables:
      colour: |
        [[[
          if (entity.state == "off") {
              return "var(--secondary-text-color)";
          } else {
              return "var(--primary-color)";
          }
        ]]]
    show_icon: true
    show_units: false
    show_label: false
    show_state: true
    show_name: true
    styles:
      grid:
        - grid-template-areas: '"i n" "i s"'
        - grid-template-columns: 32.5% 67.5%
        - grid-template-rows: 50%
      card:
        - border-radius: 50px
        - scale: 0.95
        - box-shadow: none
      state:
        - justify-self: start
        - font-size: 9pt
        - padding-bottom: 5px
        - text-transform: capitalize
      name:
        - padding-top: 5px
        - justify-self: start
        - font-size: 10pt
        - font-weight: bold
      icon:
        - width: 55%
        - color: |
            [[[ return variables.colour ]]]


```
