### DISCUSSION TITLE
problems adding a pop-up instead of the navigation to a tab

### DISCUSSION THREAD

**Discussion by R0ck3tF** [Clooos/Bubble-Card#328] [Questions about config, custom styles and templates]
Could you help me to add a POP-UP to a kitchen card that used to go to a navigation tab but now it will pop-up directly?

```
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        template:
          - card_esh_room
          - yellow_on
        name: Cocina
        entity: light.luz_cocina
        icon: mdi:knife
        tap_action:
          action: navigate
          navigation_path: 'cocina'
        label: >
          [[[
          return states['sensor.temp_cocina_temperature'].state + '°C'
          ]]]
```
thanks!!

**Comment by MrBearPresident** [comment]
If this is still an issue:

For using pop-up you have to place a `#` before the navigation part.

For example

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: button
    button_type: name
    show_icon: true
    icon: mdi:link
    name: Go To Sun Pop-up
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#Bubble-Test-Sun"
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        hash: "#Bubble-Test-Sun"
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sun.sun

```


---

<sup>If this solves your issue, please mark this as solved and close this discussion. </sup>
