### DISCUSSION TITLE
Hide name on button

### DISCUSSION THREAD

**Discussion by mutasim** [Clooos/Bubble-Card#330] [Questions about config, custom styles and templates] [answered]
Is it possible to have no name and just icon on a button?

**Comment by Clooos** [comment, marked as answer]
Hi! Yes it's possible, try that:
```yaml
type: custom:bubble-card
card_type: button
entity: your.entity
name: []
styles: >
  ha-card {
    width: 50px;
  }
```
