### DISCUSSION TITLE
Call popup from different page/dashboard?

### DISCUSSION THREAD

**Discussion by deanfourie1** [Clooos/Bubble-Card#404] [General]
Is it possible to call popups from a different page or dashboard? I feel like creating all the popups on my main dashboard will make it such a mess, even though you dont see them unless in edit mode, will still make it so hard to navigate.

I plan to create another dashboard all together and place all my popups on that dashboard, then call them from my main dashboard via a button or whatever.

I did try but it doesnt work.

maybe something like dashboard_name/#popup_anchor?

Thanks

**Comment by bocchinofr** [comment]
I want to ask the same options. It's will be very useful to create popup card in other view.

**Comment by Clooos** [comment]
The way the Home Assistant dashboard works makes it impossible due to how the pop-ups interact with the vertical stacks.

I’ve done some research in the past to create a standalone pop-up that could incorporate the cards, but it turned out to be much more complex and difficult to maintain. If it were feasible, it would have allowed for the addition of such a feature.

I might be mistaken, but as of now, it seems impossible… at least with my current skills.

**Comment by andre4715** [comment]
Is it possible to give the Pop-up a Image as background?

**Reply by Clooos** [reply]
Wrong place for asking that but you can add a custom style in YAML to your pop-up.

Here is a working example:

```yaml
type: custom:bubble-card
card_type: pop-up
hash: '#yourpopup'
styles: | 
  .pop-up {
    background: center url("https://img.freepik.com/free-vector/blank-blue-halftone-background_53876-114466.jpg") !important;
    background-size: cover;
  }
```
