### DISCUSSION TITLE
Other color on seperator line and title

### DISCUSSION THREAD

**Discussion by Orionxyy** [Clooos/Bubble-Card#537] [Questions about config, custom styles and templates] [answered]
Is there any way to give the sepeator line or the seperator title an other color?

**Comment by brunosabot** [comment, marked as answer]
Just add the `background-color` you like in the styles.
Example:
```yaml
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: mdi:ceiling-light-multiple
    styles: |
      .bubble-line {
        background-color: red;
      }

```
