### DISCUSSION TITLE
Using with Auto Entities Card

### DISCUSSION THREAD

**Discussion by TScalzott** [Clooos/Bubble-Card#560] [General]
Has anyone figured out how to get Bubble Card working with Auto-Entities (https://github.com/thomasloven/lovelace-auto-entities)?
I've tried several card_param values to no avail.

Thanks!

**Comment by s1mpleman** [comment]
This is what I do, hope it helps

```
  type: custom:auto-entities
  card:
    type: grid
    columns: 1
    square: false
  card_param: cards
  filter:
    include:
      - domain: light
        state: 'on'
        options:
          type: custom:bubble-card
          card_type: button
          button_type: slider
          show_attribute: false
          show_last_changed: true
          show_state: true
    exclude: []
  show_empty: true
```

**Reply by s1mpleman** [reply]
![image](https://github.com/Clooos/Bubble-Card/assets/5730731/0ef5ba3f-d33f-46b2-8b7a-6948ae98d32b)

This is what it looks like inside a bubble pop up

**Reply by TScalzott** [reply]
> This is what I do, hope it helps
> 
> ```
>   type: custom:auto-entities
>   card:
>     type: grid
>     columns: 1
>     square: false
>   card_param: cards
>   filter:
>     include:
>       - domain: light
>         state: 'on'
>         options:
>           type: custom:bubble-card
>           card_type: button
>           button_type: slider
>           show_attribute: false
>           show_last_changed: true
>           show_state: true
>     exclude: []
>   show_empty: true
> ```

Thanks for this. I'll give it a go.

**Reply by micahp2** [reply]
How about an example with styles included? I've tried something like this and only had failure so far:

   - domain: switch
      area: Garage
      state: 'on'
      options:
        type: custom:bubble-card
        card_type: button
        button_type: slider
        show_attribute: false
        show_last_changed: true
        show_state: true
styles: |
  .bubble-button-card-container {
    border-radius: 10px !important;
  .bubble-icon {
    opacity: 1;
    color: white !important;
  }

**Reply by lennon101** [reply]
@s1mpleman Thanks so much for that simple bit of yaml! works perfectly and I can fit and adjust it from there 👍

**Comment by HyperCriSiS** [comment]
Damn, Chatgpt and Claude could not solve this for many hours trying.
How do you put in a Popup? It still gets shown in the dashboard with this code:

type: custom:vertical-stack-in-card
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#clients"
    card_layout: large-2-rows
    name: Clients
    icon: mdi:devices
    scrolling_effect: false
    button_type: name
  - type: custom:auto-entities
    card:
      type: grid
      columns: 1
      square: false
    card_param: cards
    filter:
      include:
        - domain: device_tracker
          options:
            type: custom:bubble-card
            card_type: button
            button_type: state
            show_attribute: false
            show_last_changed: true
            show_state: true
      exclude: []
    show_empty: true
    sort:
      method: friendly_name

Also I can't get two row sub button to work.
Are there some issues with auto entities?
Because when you click on cards in the auto entities section, none is selected.

Thanks
Hyper

**Reply by HyperCriSiS** [reply]
Problem was custom:vertical-stack-in-card
--> vertical-stack

**Comment by andyblac** [comment]
how would I use this with template ? here my current card

```yaml
type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
  state_color: true
  card_mod:
    style:
      .: |
        ha-card: {
          --ha-card-background: none;
          box-shadow: none;
        }
        .card-content {
          padding-top: 0px !important;
          padding-bottom: 0px !important;
        }
      hui-toggle-entity-row:
        $: |
          hui-generic-entity-row {
            height: 25px;
          }
show_empty: false
filter:
  template: |
    {% for entity in state_attr('sensor.number_of_lights_on','entities') %}
      {{ entity.entity_id }}
    {% endfor %}
sort:
  method: friendly_name
```

**Reply by HyperCriSiS** [reply]
Did you try creating a sensor for the template and using this instead?

**Reply by andyblac** [reply]
> Did you try creating a sensor for the template and using this instead?

it is a template sensor with a list of entities that I wants to monitor ( I don't want all lights monitored as some devices have LED indicators, etc), I want the popup to list the lights and let me turn them off etc.
<img width="634" alt="Screenshot 2025-03-02 at 22 45 41" src="https://github.com/user-attachments/assets/3dfeb280-c840-44a4-9505-1a337320fbb4" />

**Reply by HyperCriSiS** [reply]
What I mean is, that you create the template sensor as helper, which creates a sensor entity.
And then you can use the sensor entity for auto-entities.

**Comment by andyblac** [comment]
sorry I don't think you understand what I'm after. this is what I have ATM

<img width="487" alt="Screenshot 2025-03-03 at 10 03 30" src="https://github.com/user-attachments/assets/dbdf9c84-c066-49ac-88f3-7772e8e91843" />

using  this code:
```yaml
type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
  state_color: true
  card_mod:
    style:
      .: |
        ha-card: {
          --ha-card-background: none;
          box-shadow: none;
        }
        .card-content {
          padding-top: 0px !important;
          padding-bottom: 0px !important;
        }
      hui-toggle-entity-row:
        $: |
          hui-generic-entity-row {
            height: 25px;
          }
show_empty: false
filter:
  template: |
    {% for entity in state_attr('sensor.number_of_lights_on','entities') %}
      {{ entity.entity_id }}
    {% endfor %}
sort:
  method: friendly_name
```

what I am after this same but using bubble card buttons, instead of just toggle switch. like this
<img width="449" alt="Screenshot 2025-03-03 at 10 06 20" src="https://github.com/user-attachments/assets/befded76-4785-4126-bd72-ad87ea9394cc" />
with this code:
```yaml
type: custom:auto-entities
card:
  type: grid
  columns: 1
  square: false
card_param: cards
filter:
  include:
    - domain: light
      state: 'on'
      options:
        type: custom:bubble-card
        card_type: button
        button_type: slider
        show_attribute: false
        show_last_changed: true
        show_state: true
sort:
  method: friendly_name
show_empty: true
```

But as you can see it show 2 LED light entities are from my meross socket extension led indicators, I do not want to track, this is why I can't use light domain in auto-entities, and use my own template sensor to keep track of what lights are on.
