### DISCUSSION TITLE
Using Browser_Mod to create a back button in horizontal button stack

### DISCUSSION THREAD

**Discussion by pgale** [Clooos/Bubble-Card#605] [General]
I'm starting to use Bubble Card in more advanced situations and calling new pages/dashboards rather than just using popups. There are several situations where this is a better approach. However, the horizontal button stack doesn't allow a 'back' function I don't think?

Browser_Mod I think allows this (if I have my code correct):

```
tap_action:
  action: call-service
  service: browser_mod.navigate
  service_data:
    navigation_path: 'javascript:history.back()'
```

Is it possible to use this code in a tap_action on a button in the horizontal button stack?

Thanks.
