### DISCUSSION TITLE
Increasing height and padding of horizontal-buttons-stack - Decreasing button spacing

### DISCUSSION THREAD

**Discussion by fcassata** [Clooos/Bubble-Card#615] [Questions about config, custom styles and templates]
Hi, need a little help if anyone has time, trying to give the bottom bar a little more breathing room and tried various methods via styles, but can't get the gradient background to fill out the increased height, so I'm not hitting the right selector or method for this. I've been able to make it look right though, by choosing to hide the gradient, and repeat a whole lot of CSS, that makes me think I'm doing it wrong, is there a way to simplify?

Also looking for a way to change the button spacing :)

<img src="https://github.com/Clooos/Bubble-Card/assets/97367937/63228c4a-01b0-4317-8b1a-100f4f0649c2" width="400"/>

```YAML
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_link: /home
1_icon: mdi:home-assistant
2_link: '#lists'
2_icon: mdi:list-status
3_link: '#ctrl'
3_icon: mdi:cog-outline
highlight_current_view: true
hide_gradient: true
styles: |
  ha-card {
    border-radius: 0px !important;
    padding-top: 20px !important;
    padding-bottom: 80px !important;
    bottom: 0 !important;
    width: calc( 100% + 36px) !important;
    left: 50% !important;
    transform: translateX(-50%) !important;
    background: rgba(0,0,0, .7) !important;
  }
  div.bubble-background-color {
    background-color: #055 !important;
  }
  .home>* {
    border-radius: 10px 0px 0px 10px !important;  
  } 
  .lists>* {
    border-radius: 0px !important;
  }  
  .ctrl>* {
    border-radius: 0px 10px 10px 0px !important;  
  }   
```
