### DISCUSSION TITLE
Pop-up, containing multiple sensors

### DISCUSSION THREAD

**Discussion by SamJongenelen** [Clooos/Bubble-Card#714] [Questions about config, custom styles and templates] [answered]
So, I have a pop-up. Is there a way I can multiple sensors in there I am missing in the Docs? Ive seen some screenshots that work I think

![image](https://github.com/user-attachments/assets/a4ec0e39-9b58-467e-8651-5bb7bc6fa05d)

goals is to give overview of streaming usage, add some network usage etc

**Comment by Mystically11** [comment]
For the second column, you can use sub-buttons to display other entity states.

Not sure what you mean by "2nd 3rd here", but you could add new button cards to show more sensors there

**Comment by SamJongenelen** [comment]
I have currently 1 popup for #jellyfin and that contains 1 button.
I would like to have multiple buttons. I think I am missing something obvious? 


![Screenshot_20240817_225358_Home Assistant](https://github.com/user-attachments/assets/696f37a8-a187-421d-96b0-7103c705d246)

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#test'
    button_type: slider
    entity: light.hanglamp_bulb
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#jellyfin'
    margin_top_mobile: calc(100vh - 400px)
    margin_top_desktop: calc(100vh - 400px)
    name: TV
    show_attribute: true
    attribute: SeriesName
    show_name: true
    show_icon: false
    show_last_changed: true
    icon: ''
    sub_button:
      - entity: sensor.jelly_sam
        name: Sam
        show_name: true
        show_icon: false
      - entity: sensor.jelly_tv
        name: TV
        show_name: true
        show_icon: false
      - entity: sensor.jelly_carlijn
        name: Carlijn
        show_icon: false
        show_name: true
    button_type: state
    card_layout: large-2-rows
```
