### DISCUSSION TITLE
Add a "lock" option to switches.

### DISCUSSION THREAD

**Discussion by hacshacdgacs** [Clooos/Bubble-Card#761] [Feature requests]
Button card has a feature that allows you to lock a card so it can't accidentally be triggered.
https://github.com/custom-cards/button-card#lock-object
Something like this as a toggle would be nice (a similar implementation like theirs of a hold for 3 seconds can disable the lock would work I think). 
I have a couple of PC's in HomeAssistant where the last thing I want is to have them shut down on me because somneone accidentally touches the button on the dashboard.

**Comment by Johnthenerdboss** [comment]
You can do this already in YAML with confirmation. 

```
tap_action:
     confirmation:
          text: Open/Close the Garage?
     action: call-service
     service: cover.toggle
     target:
          entity_id: cover.garage
     show_state: false
```

Like so
