### DISCUSSION TITLE
Possibility to trigger automations

### DISCUSSION THREAD

**Discussion by 80Simo80** [Clooos/Bubble-Card#792] [Feature requests]
Hello,

I've been trying to use the possibility to trigger an automation, but I can't use the bubble card with automations.

is something possible to add?

example:
type: custom:bubble-card
card_type: button
name: Button_Name
icon: mdi:globe-light
tap_action:
  action: perform-action
  perform_action: automation.trigger
  target:
    entity_id: automation.test1
  data:
    skip_condition: true

thanks a lot

**Comment by theharshl** [comment]
I would also really like to see this functionality. I have a number of automations that work like scenes, but are more advanced and I need to trigger them from my dashboard. I would like to have consistency in my button style and use bubble card buttons or something similar to trigger the automations.

Thanks for an awesome card!

**Comment by RichardUUU** [comment]
FWIW, this works: 
```
            tap_action:
              action: call-service
              service: script.family_motion_toggle
              target: {}
```
I haven't tried it with `service: automation.___`. If that doesn't work, perhaps you could use the script to call the automation

**Comment by chiabre** [comment]
try this

```
        tap_action:
          action: call-service
          service: automation.trigger
          target:
            entity_id: automation.fire_tv_off_in_15_mins
```
