### DISCUSSION TITLE
Add a 'auto_close: false' option

### DISCUSSION THREAD

**Discussion by INPoppoRTUNE** [Clooos/Bubble-Card#847] [Feature requests]
I use a `type: custom:bubble-card card_type: pop-up` to hide the player for my IP camera recordings.
I'd like to have the option to disable `auto-close`, as it's quite inconvenient having to continuously re-open the popup every X seconds while paying attention to the recordings.

Here's my snippet:
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#popup-recording"
    button_type: state
    entity: sensor.ipcamera_recordings
    name: Recordings
    show_last_changed: true
    show_attribute: false
    attribute: friendly_name
    auto_close: false           <- what I'm requesting
    width_desktop: 840px
  - type: custom:gallery-card
    entities:
      - path: media-source://media_source/path
        recursive: true
    show_controls: true
    include_images: false
    include_video: true
    autoplay: true
    interval: 5000
    show_reload: true
    preview_video_at: 10
``` 
I'm using this card in combo with [lukelalo/gallery-card](https://github.com/lukelalo/gallery-card) and it's perfect, minus the `auto_close` function.
Thanks for the great work you have put into this card, I hope this request may be an easy implementation.
