### DISCUSSION TITLE
Cannot see the scene list when using a hue room (beta 3)

### DISCUSSION THREAD

**Discussion by ronbruins** [Clooos/Bubble-Card#867] [Questions about config, custom styles and templates]
According the documents I should see the possibility to get a drop down, but I don't see that option.

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/6bff79a0-3fcd-4150-bef0-3acdb9f32c29">

**Comment by Clooos** [comment]
Hi! Have you cleared your browser cache? You can check the version number at the bottom of the Bubble Card editor to be sure.

**Reply by ronbruins** [reply]
<img width="489" alt="image" src="https://github.com/user-attachments/assets/55b3ccf9-16c0-4fd8-af9f-a5ea12fdb754">

I cleared my whole history/cache and even tried a private browser and safari & chrome. no luck :-(

**Reply by ronbruins** [reply]
Have you been able to take a look at this? I'm wondering if I'm doing something wrong or if it is an actual bug.

**Reply by Clooos** [reply]
Can you send me your light informations from the Dev tools?

![Screenshot_2024-11-07-17-49-09-053_io homeassistant companion android](https://github.com/user-attachments/assets/f477e41f-6d97-4045-b125-505268d604a9)

**Reply by ronbruins** [reply]
I am talking about scenes, I see in your example it is the effects. Are we on the same page or am I looking for a feature that doesn't;t exit (yet)? anyway, here is the requested screenshot:

<img width="1064" alt="Screenshot 2024-11-07 at 19 57 47" src="https://github.com/user-attachments/assets/5444da11-1342-439b-94c1-745bd80e723b">

**Reply by ronbruins** [reply]
and as template, to get the raw data:

`<template TemplateState(<state light.eetkamer=on; min_color_temp_kelvin=2000, max_color_temp_kelvin=6535, min_mireds=153, max_mireds=500, supported_color_modes=[<ColorMode.COLOR_TEMP: 'color_temp'>, <ColorMode.XY: 'xy'>], color_mode=color_temp, brightness=235, color_temp_kelvin=2732, color_temp=366, hs_color=(28.327, 64.71), rgb_color=(255, 167, 89), xy_color=(0.524, 0.387), is_hue_group=True, hue_scenes={'Standaard', 'Bright', 'Relax', 'Dimmed'}, hue_type=room, lights={'Eet Kast', 'Eet Midden', 'Eet Rechts', 'Eet Links'}, entity_id={'light.eet_rechts', 'light.eet_midden', 'light.eet_kast', 'light.eet_links'}, dynamics=False, icon=mdi:lightbulb-group, friendly_name=Eetkamer, supported_features=40 @ 2024-11-07T06:07:07.788583+01:00>)>`

**Reply by Clooos** [reply]
Thanks, I haven't added Hue scenes yet, but it shouldn't be too difficult. I will try for the next beta.

**Reply by ronbruins** [reply]
Oh, Well then it makes sense. I assumed it was based on your reply on Reddit, to natively do what I now do with the dynamic template selects to achieve this result. Thanks for all the great work.

**Reply by Clooos** [reply]
Indeed, in fact I was not aware that there are Hue scenes directly available in the lights, I thought that you were using light effects.

I need to manually add each cases, this is why the Hue scenes are not shown at the moment.

**Reply by ronbruins** [reply]
FYI, What I sent you is effectively a group of lights, the scenes are not available in the lights but in the rooms or zones. This is an important thing to take into account. Even though in home assistant the entity gets the light. prefix.

**Reply by Clooos** [reply]
Can you tell me what service you call in YAML for triggering one of these Hue scene? I have Philips Hue as well but I'm unable to find any of these scenes in any of my entities, is this a standard thing?

**Reply by ronbruins** [reply]
To activate the actual scene I use the 'scene turn on' service:

<img width="431" alt="image" src="https://github.com/user-attachments/assets/20918a44-7982-4b5c-8f9d-6daa6a709ff5">

when I select the 'group' then you can see the scenes as attributes:

<img width="578" alt="image" src="https://github.com/user-attachments/assets/e9c69df2-b567-44b0-b402-cff3f1858e51">

**Reply by ronbruins** [reply]
and this from dev tools:
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/68997df1-191d-4b94-b682-68ff76e90239">

**Reply by Clooos** [reply]
The only thing that I don't understand is that:

hue_scenes={'Standaard', 'Bright', 'Relax', 'Dimmed'}

But your scene names don't match that.

**Reply by ronbruins** [reply]
They do... you can see them in the attributes of the room, in this case 'eetkamer'

<img width="531" alt="image" src="https://github.com/user-attachments/assets/85e30cd0-8c1a-4a3a-b973-1634e7a1e769">

**Reply by Clooos** [reply]
Yes I see that, but when I ask how you trigger them you tell me that you use for example Eetkamer Relax, that's that part that I don't understand 😅

**Reply by ronbruins** [reply]
So in hue every room:
<img width="333" alt="image" src="https://github.com/user-attachments/assets/6f44e63b-5a42-4ad7-a5e1-ae1af0ca4569">

Is added as a light group entity in HA. This light group has attributes which are the scenes, so in HA it looks like this:
<img width="483" alt="image" src="https://github.com/user-attachments/assets/779697cc-256e-40c8-8ff4-7e86cf7fb3a5">

The group (room) is eetkamer
the lights which are part of this room are seen and at the bottom you can see the group, to control the whole group(room)
This one has the attributes for the scenes, which can be called by the service 'scene.activate'

**Reply by Clooos** [reply]
Ok, but I don't see how I could use `hue_scenes={'Standaard', 'Bright', 'Relax', 'Dimmed'}` from your group to use it as a list, because there is no way I can automatically match what scenes I need to trigger in my code.

I don't know if this makes sense to you but here is how it works for the effect_list for example:

<img width="691" alt="image" src="https://github.com/user-attachments/assets/693694e1-0b29-4c3b-be5e-4794a96a165f">

**Reply by ronbruins** [reply]
```yaml
- select:
    - name: "Scenes Eetkamer"
      state: "{{ states('input_text.scene_eetkamer') }}"
      options: >
        {{ states.scene
        | selectattr('entity_id', 'search', 'eetkamer')
        | map(attribute='attributes.name') | list }}
      select_option:
        - variables:
            groups: >
              {{ states.scene | selectattr('entity_id', 'search', 'eetkamer') | map(attribute='attributes.group_name') | list }}
            selected_scene: >
              {{ groups[0] + " " + option }}
            entity: >
              {{ states.scene | selectattr('name', 'eq', selected_scene) |map(attribute='entity_id')|join }}
        - service: input_text.set_value
          target:
            entity_id: input_text.scene_eetkamer
          data:
            value: "{{ option }}"
        - service: scene.turn_on
          target:
            entity_id: "{{ entity }}"
```

This is how I do it :-)
