### DISCUSSION TITLE
vacuum card

### DISCUSSION THREAD

**Discussion by bozzio83** [Clooos/Bubble-Card#878] [Questions about config, custom styles and templates] [answered]
Hello.

I'm trying to make a vacuum card with sub buttons.  I can get it to work with a button card but I get error when using bubble card with sub buttons.

```
type: custom:bubble-card
card_type: button
entity: vacuum.george
icon_animation: true
show_state: true
show_last_changed: true
sub_button:
  - entity: vacuum.george
    name: start
    icon: mdi:play
    icon_animation: true
    show_last_changed: false
    show_state: false
    tap_action:
      action: call-service
      service: vacuum.send_command
      target:
        entity_id: vacuum.george
        command: start_pause
  - entity: vacuum.george
    name: stop
    icon: mdi:stop
    icon_animation: true
    show_last_changed: false
    show_state: false
    tap_action:
      action: call-service
      service: vacuum.send_command
      target:
        entity_id: vacuum.george
        command: stop
  - entity: vacuum.george
    name: send home
    icon_animation: true
    show_last_changed: false
    show_state: false
    tap_action:
      action: call-service
      service: vacuum.send_command
      target:
        entity_id: vacuum.george
        command: return_home
    icon: mdi:home-map-marker
  - entity: vacuum.george
    show_last_changed: false
    show_state: false
    tap_action:
      action: call-service
      service: vacuum.send_command
      target:
        entity_id: vacuum.george
        command: start
        params:
          pmap_id: *********************
          regions:
            - region_id: "**"
              type: rid
    name: vacuum kitchen
    icon: mdi:table-chair
  - entity: vacuum.george
    show_last_changed: false
    show_state: false
    name: vacuum bathroom
    tap_action:
      action: call-service
      service: vacuum.send_command
      target:
        entity_id: vacuum.george
        command: start
        params:
          pmap_id: ***********************
          regions:
            - region_id: "**"
              type: rid
    icon: mdi:toilet
button_action:
  tap_action:
    action: more-info
```

This is the error I get

`Failed to perform the action vacuum/send_command. extra keys not allowed @ data['target']['command']. Got 'start_pause'`
