### DISCUSSION TITLE
Covers option to see the satus as a slider

### DISCUSSION THREAD

**Discussion by lonelylupus** [Clooos/Bubble-Card#902] [Questions about config, custom styles and templates]
Hey
is it somehow possible to have not only a button up down and stop for the covers in the card but also a slider in for the status? In the beautiful slim design of the bubble cards?
Thanks in advance for the help

**Comment by MrBearPresident** [comment]
something like? :

![2024-12-20_16-22-12](https://github.com/user-attachments/assets/4b195943-bb2f-419b-84f9-c75c34bc3284)


```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: cover.test_cover_cover
styles: |-
  :host{
      --color-ok: #36A1D3AA ;
      --color-bar: var(--color-ok);
      --color-background: var(--bubble-button-main-background-color, var(--bubble-main-background-color, var(--background-color-2, var(--secondary-background-color))));
  }

  .bubble-button-card-container {
      background: linear-gradient(
    to right, 
    var(--color-bar) 0%, 
    var(--color-bar) ${Math.round(hass.states['cover.test_cover_cover'].attributes.current_position)}%,
    var(--color-background) ${Math.round(hass.states['cover.test_cover_cover'].attributes.current_position)}%,
    var(--color-background) 100%
  ) !important;
  }


  .bubble-sub-button-1{
    border-radius: 32px 0px 0px 32px;
  }
  .bubble-sub-button-2{
    border-radius: 0px;
    margin-left: -10px;
    margin-right:-10px;
  }
  .bubble-sub-button-3{
    border-radius: 0px 32px 32px 0px;
  }    


    
  .bubble-icon {
    color: ${state === 'open' ? 'var(--color-ok)' : ''} !important;
  }
slider_live_update: false
sub_button:
  - entity: cover.lounge_blind
    show_icon: true
    icon: mdi:arrow-down
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.test_cover_cover
      service: cover.close_cover
  - entity: cover.lounge_blind
    icon: mdi:square-outline
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.test_cover_cover
      service: cover.stop_cover
  - entity: cover.lounge_blind
    icon: mdi:arrow-up
    state_background: false
    tap_action:
      action: call-service
      target:
        entity_id: cover.test_cover_cover
      service: cover.open_cover
card_layout: large
show_attribute: true
attribute: current_position

```

---

<sup>If this solves your problem, mark it as solved and close the discussion.</sup>
