### DISCUSSION TITLE
[Example] Progressbar, % bar

### DISCUSSION THREAD

**Discussion by MrBearPresident** [Clooos/Bubble-Card#928] [Share your custom styles, templates and dashboards]
![Screen_Recording_20241116_065523_Home Assistant_1_new](https://github.com/user-attachments/assets/fc34dd45-286e-4007-a934-99c2c30b8dd1)

```
type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.dev_gf_hw_pir_battery
styles: |-
  :host{
      --color-ok-icon: green ;
      --color-warning-icon: orange ;
      --color-alert-icon: red ;
      --color-ok: #85A408AA ;
      --color-warning: #E77910AA ;
      --color-alert: #CA3333AA ;
      --color-bar: ${state > 40 ? 'var(--color-ok)'
                     : state > 20 ? 'var(--color-warning)'
                     : 'var(--color-alert)'} ;
      --color-background: var(--bubble-button-main-background-color, var(--bubble-main-background-color, var(--background-color-2, var(--secondary-background-color))));
      --color-notification-bubble: red;
  }

  ha-icon {
    color: var(${ state > 40 ? '--color-ok-icon':
                  state > 20 ? '--color-warning-icon' :
                              '--color-alert-icon'}) 
              !important; }

  .bubble-button-card-container {
      background: linear-gradient(
    to right, 
    var(--color-bar) 0%, 
    var(--color-bar) ${Math.round(state)}%, 
    var(--color-background) ${Math.round(state)}%,
    var(--color-background) 100%
  ) !important;
  }

  ha-card::after {
    position: absolute;
    top: -10px;
    left: -10px;
    padding: 0 10px;
    border-radius: 999px;
    border: 0px solid black;
    color: #fff;
    content: "${Math.round(state) < 40 ? '!' : ''}";
    background: var(--color-notification-bubble);
    display: block;
  }
icon: ""
name: ""
sub_button: []
layout_options:
  grid_columns: 2
  grid_rows: 1
card_layout: large

```

Extra features: 
- Color change based on percentage
- Notification round on the left to pull attention on alerts

**Comment by falkio8** [comment]
Thank you very much for that code. Looks great but I am struggling to implement it based on a different entity than defined in the bubble-card entity. I tried different options but none of them worked. So is there a way to use a different entity than the variable "state"? Tried it with "states("another_entity")" and so on...


`    var(--color-bar) ${Math.round(**state**)}%, 
    var(--color-background) ${Math.round(**state**)}%,`

**Reply by MrBearPresident** [reply]
I have this working. (see below)
Can you send me your YAML of the complete bubble card + printscreen of the values?

![image](https://github.com/user-attachments/assets/6bcc2ddf-5d23-4d03-b86e-0ae90bd859e3)


```
:host{
    --color-ok: #36A1D3AA ;
    --color-warning: #E77910AA ;
    --color-alert: #CA3333AA ;
    --color-bar: ${hass.states['sensor.nas_volume_3_status'].state === 'normal' ? 'var(--color-ok)'
                   : 'var(--color-alert)'} ;
    --color-background: var(--bubble-button-main-background-color, var(--bubble-main-background-color, var(--background-color-2, var(--secondary-background-color))));
}

.bubble-button-card-container {
    background: linear-gradient(
  to right, 
  var(--color-bar) 0%, 
  var(--color-bar) ${Math.round(hass.states['sensor.nas_volume_3_volume_used'].state)}%,
  var(--color-background) ${Math.round(hass.states['sensor.nas_volume_3_volume_used'].state)}%,
  var(--color-background) 100%
) !important;
}
```

**Reply by falkio8** [reply]
Thanks for the reply, with hass.states I got it working. But unfortunately it seems not to work with bubble-card type: pop-up. The pop-up cards have a bubble card at the top and I wanted to use it there but it doesn´t apply there. Doing it the same way with a single bubble-card type: button its working.

And another question, is there the possibility to access an entity´s attribute for hass.states?

**Reply by killtux** [reply]
wow that looks amazing. would be cool if this could get implemented as a seperate bubble card 😊

**Reply by johndoe0815** [reply]
@MrBearPresident Your code works great for me. In a second step, I'd like to combine that with fading the button/making it gray when the device is offline, as otherwise it is still just displaying the last status.

So instead of your
```
.bubble-button-background {
    background: linear-gradient(
  to right, 
  var(--color-bar) 0%, 
  var(--color-bar) ${Math.round(hass.states['sensor.a1mini_druckfortschritt'].state)}%,
  var(--color-background) ${Math.round(hass.states['sensor.a1mini_druckfortschritt'].state)}%,
  var(--color-background) 100%
) !important;
}
```

I was trying something like 
```
.bubble-button-background {
    background: ${state === 'offline' ? 'rgba(210,210,210,1)' : linear-gradient(
  to right, 
  var(--color-bar) 0%, 
  var(--color-bar) ${Math.round(hass.states['sensor.a1mini_druckfortschritt'].state)}%,
  var(--color-background) ${Math.round(hass.states['sensor.a1mini_druckfortschritt'].state)}%,
  var(--color-background) 100%
) } !important;
}
```

But that does not work. Do you know how to embed this progress bar into some if...then...else?

**Reply by MrBearPresident** [reply]
It would be easier to just set the background color and the active color to the desired color. 

``` css
:host{
    --color-ok: #36A1D3AA ;
    --color-warning: #E77910AA ;
    --color-alert: #CA3333AA ;
    --color-offline: #D2D2D2AA ;
    --color-bar: ${state != 'offline' ? 'var(--color-ok)'
                 : 'var(--color-offline)'} ;
    --color-background-og: var(--bubble-button-main-background-color, var(--bubble-main-background-color, var(--background-color-2, var(--secondary-background-color))));
    --color-background: ${state != 'offline' ? 'var(--color-background-og)'
                 : 'var(--color-offline)'};
}

.bubble-button-card-container {
    background: linear-gradient(
  to right, 
  var(--color-bar) 0%, 
  var(--color-bar) ${Math.round(hass.states['sensor.a1mini_druckfortschritt'].state)}%,
  var(--color-background) ${Math.round(hass.states['sensor.a1mini_druckfortschritt'].state)}%,
  var(--color-background) 100%
) !important;
}
```

**Reply by johndoe0815** [reply]
That is a good idea that did not come to my mind - and as usual perfectly done working out of the box, thanks!
Just one question: What does it actually mean to have those different color variables one after the other in this line:

`--color-background-og: var(--bubble-button-main-background-color, var(--bubble-main-background-color, var(--background-color-2, var(--secondary-background-color))));`

Content-wise so far I do not understand what this is doing compared to just setting one single color.

**Reply by MrBearPresident** [reply]
Ah this is something I didn't know either before starting my adventures with bubble-card. 
A var is a saved variable that flows downstream, so a parent element could have a var, and the child can also use this var. 
For calling the var we use var(`name`, `value`). If the `name` points to a var that does not exist, it will use `value` as the fallback. 
In this way if you cascades this. You get something like this. 
``` 
if var(--bubble-button-main-background-color) exist use that, else ....
  if var(--bubble-main-background-color) exist use that, else ....
     if var(--background-color-2) exist use that, else ....
        if var(--secondary-background-color) exist use that, else ....
```

**Comment by falkio8** [comment]
Here is a small guide to get this to work with a climate card: https://github.com/Clooos/Bubble-Card/discussions/996#discussioncomment-11472032

**Comment by jaaneo** [comment]
Amazing job!

**Comment by John5373** [comment]
Trying to do something similar here, but instead mimic the visual appearance of slider button to show state, but remove the sliding functionality. I can't quite get the CSS right, especially to dynamically adjust with the light color. The top button is a normal slider. The middle button is the one I am trying to match the top button. I assume it is just a matter of using the correct variables, but not sure what they are. For testing purposes I just used static colors (which come back inverted). Using the bubble theme

![image](https://github.com/user-attachments/assets/ca48ae29-661a-4b1d-920a-a92b3a53afa8)

```css
 :host{

    --color-bar: #9933ffAA;
    --color-background: #3333ffAA;
}

.bubble-button-card-container {
    background: linear-gradient(
  to right, 
  var(--color-bar) 0%, 
  var(--color-bar) ${Math.round((hass.states['light.office_lamp_upstairs'].attributes.brightness) / 255 * 100)}%,
  var(--color-background) ${Math.round((hass.states['light.office_lamp_upstairs'].attributes.brightness) / 255 * 100)}%,
  var(--color-background) 100%
) !important;
}
```

Appreciate any help here.

**Reply by MrBearPresident** [reply]
So you need a combination of #1000 and this.
Resulting in something like:

``` css
:host{
    --color-bar:  ${hass.states[entity].attributes.rgb_color ? 'rgba('+hass.states[entity].attributes.rgb_color+`, 0.66)`: '#9933ffAA'};
    --color-background: var(--bubble-button-main-background-color, var(--bubble-main-background-color, var(--background-color-2, var(--secondary-background-color))));
}

.bubble-button-card-container {
  background: linear-gradient(
    to right, 
    var(--color-bar) 0%, 
    var(--color-bar) ${Math.round((hass.states[entity].attributes.brightness) / 255 * 100)}%,
    var(--color-background) ${Math.round((hass.states[entity].attributes.brightness) / 255 * 100)}%,
    var(--color-background) 100%
  ) !important;
}
```
