### DISCUSSION TITLE
Conditionnal card in pop-up

### DISCUSSION THREAD

**Discussion by SylvainDx** [Clooos/Bubble-Card#966] [Questions about config, custom styles and templates] [answered]
Hello,

I'm strugguling with a conditionnal card in a pop-up.
For the context I have lights and plugs and when some are on I have a notification
When i click on this button i call a pop up.

In this pop-up I've got 2 cards.
1 auto-entity for lights
1 bubble separator with sub buttons for plugs because i need to run special action to toggle the plugs.

I can put some conditionnal behavior on the sub-button without issue

But I try to mask the separator.

1st. with a conditionnal card : it works in the preview, but not when calling the pop-up
2nd. with the visibility option on the separator card, it doesn't work at all (maybe the vertical stack prevent to have sub visibility options)

**Comment by Mystically11** [comment]
Can you show your code?

**Comment by SylvainDx** [comment]
With pleasur ! :)
```type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#pop-up-test"
    trigger_close: false
    name: Lumières allumées
    entity: sensor.lights_on
    show_state: true
  - type: custom:bubble-card
    card_type: separator
    sub_button:
      - entity: binary_sensor.nora_piano_2
        icon: mdi:piano
        tap_action:
          action: call-service
          target:
            entity_id: script.piano
          service: homeassistant.turn_on
        name: Piano
      - entity: binary_sensor.nora_pax
        name: Sapin
        icon: mdi:pine-tree-variant-outline
        tap_action:
          action: call-service
          target:
            entity_id: script.s_sapin
          service: homeassistant.turn_on
    styles: |-
      .bubble-sub-button-1 {
        display: ${ hass.states['binary_sensor.nora_piano_2'].state === 'on' ? '' : 'none'} !important;
      }
      .bubble-sub-button-2 {
        display: ${ hass.states['binary_sensor.nora_pax'].state === 'on' ? '' : 'none'} !important;
      }
    name: "Prises : "
  - type: conditional
    conditions:
      - condition: state
        entity: binary_sensor.nora_pax
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity: binary_sensor.nora_piano_2
            state: "on"
    card:
      show_name: true
      show_icon: true
      type: button
      tap_action:
        action: toggle
      name: TOTO 
```

here the screen in edit mode : 
![image](https://github.com/user-attachments/assets/2c77497e-b592-4a98-a4d1-e244aed13625)

and the on in live action : 
![image](https://github.com/user-attachments/assets/57aafcf3-6263-48a8-b4b5-b340f70aab05)

**Comment by SylvainDx** [comment]
the first was with conditionnal card.

And now the code with visibility option 
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#pop-up-test2"
    trigger_close: false
    name: Lumières allumées
    entity: sensor.lights_on
    show_state: true
  - type: custom:bubble-card
    card_type: separator
    sub_button:
      - entity: binary_sensor.nora_piano_2
        icon: mdi:piano
        tap_action:
          action: call-service
          target:
            entity_id: script.piano
          service: homeassistant.turn_on
        name: Piano
      - entity: binary_sensor.nora_pax
        name: Sapin
        icon: mdi:pine-tree-variant-outline
        tap_action:
          action: call-service
          target:
            entity_id: script.s_sapin
          service: homeassistant.turn_on
    styles: |-
      .bubble-sub-button-1 {
        display: ${ hass.states['binary_sensor.nora_piano_2'].state === 'on' ? '' : 'none'} !important;
      }
      .bubble-sub-button-2 {
        display: ${ hass.states['binary_sensor.nora_pax'].state === 'on' ? '' : 'none'} !important;
      }
    name: "Prises : "
  - show_name: true
    show_icon: false
    type: button
    tap_action:
      action: toggle
    name: TOTO
    visibility:
      - condition: state
        entity: binary_sensor.nora_pax
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity: binary_sensor.nora_piano_2
            state: "on"
```

I spare you the screen shot, they are identical 😅

**Comment by Mystically11** [comment]
What I understood from your initial post was that you're trying to hide the separator card, the one which shows the name "Prises". But in your code, you're actually just hiding the "TOTO" default button card.

**Comment by Mystically11** [comment]
If i'm getting this right, you're expecting both the separator and the card below it to disappear. you can do this by creating a conditional card, setting the conditions and then for the card setting, you put a vertical stack and put the cards you want to show or hide depending on if the conditions are met or not inside it, like this:
```
  - type: conditional
    conditions: []
    card:
      type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: separator
          sub_button:
            - entity: binary_sensor.nora_piano_2
              icon: mdi:piano
              tap_action:
                action: call-service
                target:
                  entity_id: script.piano
                service: homeassistant.turn_on
              name: Piano
            - entity: binary_sensor.nora_pax
              name: Sapin
              icon: mdi:pine-tree-variant-outline
              tap_action:
                action: call-service
                target:
                  entity_id: script.s_sapin
                service: homeassistant.turn_on
          styles: |-
            .bubble-sub-button-1 {
              display: ${ hass.states['binary_sensor.nora_piano_2'].state === 'on' ? '' : 'none'} !important;
            }
            .bubble-sub-button-2 {
              display: ${ hass.states['binary_sensor.nora_pax'].state === 'on' ? '' : 'none'} !important;
            }
          name: "Prises : "
        - show_name: true
          show_icon: false
          type: button
          tap_action:
            action: toggle
          name: TOTO
          visibility:
            - condition: state
              entity: binary_sensor.nora_pax
              state: "on"
            - condition: or
              conditions:
                - condition: state
                  entity: binary_sensor.nora_piano_2
                  state: "on"

```
