### DISCUSSION TITLE
How to change theme for global corner radius with default theme?

### DISCUSSION THREAD

**Discussion by makerwolf** [Clooos/Bubble-Card#983] [Questions about config, custom styles and templates] [answered]
Hello! 
I welcome the new change that "makes it easier" to globally change the rounded corners. However, I'm using the default theme, and the line in the release notes that says: "This was achievable with just a few lines added to my theme." leaves me a bit clueless. I'd really like to set my rounded corners globally, but stay on the default theme. 
How would I go to achieve this?
thanks!

**Comment by johndoe0815** [comment]
In my understanding your two statements are contradicting. Either you want to use the default only, or you want to specify your own.
You just create a theme, and only the parameters you provide will be overwritten with the default, all the rest remains. And this theme you then set as the default.

You find many examples on the internet. In the configuration.yaml, you put
```
frontend:
  themes: !include themes.yaml
```

You then create a themes.yaml, and in there you put e.g.

````
Classic:
  bubble-border-radius: "8px" 
  bubble-icon-border-radius: "200px" #circle icons
  bubble-sub-button-border-radius: "200px" #circle sub-buttons
````

And then I have an automation which puts this theme as default once Home Assistant starts:
```
alias: X - Bei Start Classic Theme einstellen
description: ""
mode: single
triggers:
  - event: start
    trigger: homeassistant
conditions: []
actions:
  - data:
      name: Classic
    action: frontend.set_theme
```

I have this in place already for a long time, so honestly I do not remember if without this automation you cannot set it as a default. I think I maybe did that to make sure that for every user this is applied.

**Comment by SylvainDx** [comment, marked as answer]
a little warning, if you use dark mode, you may want to dooble the informations like this :
```
    Classic:
      modes:
        light:
          bubble-border-radius: "8px" 
          bubble-icon-border-radius: "200px" #circle icons
          bubble-sub-button-border-radius: "200px" #circle sub-buttons
        dark:
          bubble-border-radius: "8px" 
          bubble-icon-border-radius: "200px" #circle icons
          bubble-sub-button-border-radius: "200px" #circle sub-buttons
```
This will allow you to switch from one to the other without more trouble
