### DISCUSSION TITLE
Is it possible to format (e.g decimal places) an entity?

### DISCUSSION THREAD

**Discussion by Juggler00** [Clooos/Bubble-Card#986] [Questions about config, custom styles and templates] [answered]
One of my sensors reports a ridiculous number of decimal places to HA. I would like to include its value as a sub-button, however I'm trying to figure out how to format the number of decimal places. 

Looking through the documentation, I think there is a way with some CSS styles. I have the following, but cannot figure out how to format the number of decimal places reported `sensor.co2click_temperature`. Is what I'm trying to achieve possible?

```
 - type: custom:bubble-card
    card_type: pop-up
    hash: "#pool"
  - type: custom:bubble-card
    card_type: button
    entity: switch.esphome_web_1111b4_pool_pump
    name: Pump
    icon: mdi:pump
    show_icon: true
    sub_button:
      - entity: sensor.esphome_web_1111b4_pool_temperature
        show_state: true
        show_icon: true
        state_background: false
        show_background: false
        name: pool
        show_name: true
      - entity: sensor.co2click_temperature
        name: air
        show_background: false
        show_name: true
        show_state: false
        show_icon: false
    card_layout: large-2-rows
    styles: >
      ${card.querySelector('.bubble-sub-button-2').innerText =
      hass.states['sensor.co2click_temperature'].state}
    scrolling_effect: false
```
