### DISCUSSION TITLE
Possibility to show multiple attributes in main part?

### DISCUSSION THREAD

**Discussion by mrgrlscz** [Clooos/Bubble-Card#989] [Feature requests]
Could be great, maybe like this:
```
type: custom:bubble-card
card_type: climate
entity: climate.heat
show_attribute: true
attributes:
  - current_temperature
  - target_temperature
```

**Comment by SylvainDx** [comment]
it's build in ;) adding only show attribute current_temperature

```
  - type: custom:bubble-card
    card_type: climate
    entity: climate.salon_heating
    sub_button:
      - name: HVAC modes menu
        select_attribute: preset_modes
        state_background: true
        show_arrow: true
        show_icon: true
        show_attribute: false
    force_icon: false
    state_color: true
    show_attribute: true
    show_state: false
    name: Salon
    attribute: current_temperature
```
![image](https://github.com/user-attachments/assets/b70e5422-1aa6-4366-9353-209909d22bb8)
