### ISSUE TITLE
Bubble card titles shown on dashboard

### ISSUE THREAD

**Issue by SneakieGargamel** [Clooos/Bubble-Card#1003]
**Describe the bug**  
When I open my dashboard on ios, I see the titles of bubble cards on my dashboard. Downgrading to 2.2.4 fixes it for now. The bug is only when first opening the app. Title disappears when you open a bubble card.

Also (2nd mini title bug) when you open a bubble card you can for a quick second see the title appear on the dashboard. Title on dashboard disappears again after closing bubble card.

**To Reproduce**  
1. Add a bubble card on a dashboard
2. Close ios app and open app again
3. See titles of bubble cards on dashboard

**Expected behavior**  
Not seeing titles of bubble cards

**Screenshots**  
![image](https://github.com/user-attachments/assets/528383fd-2004-46e2-aa44-22668b612738)
![image](https://github.com/user-attachments/assets/f1f6bff3-7026-434c-a817-76dad6910746)

**YAML**  
If applicable, add any relevant YAML code.

```yaml

type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#pop-up-afval"
    close_on_click: false
    name: Afval
    icon: mdi:trash-can
    show_icon: true
  - initial_view: listWeek
    type: calendar
    entities:
      - calendar.afvalbeheer_cyclus
title: Afval

```

**Informations (please complete the following information):**  
 - OS: ios
 - Browser/App: App
 - Bubble Card version: e.g. 2.3.0
 - Home Assistant version: 2024.12.1

**Additional context**  

Thank you! 🍻
