### ISSUE TITLE
bubble-secondary-background-color not can be applied

### ISSUE THREAD

**Issue by 1iverea9er** [Clooos/Bubble-Card#1021]
**Describe the bug**  
`bubble-secondary-background-color` not can be applied while `bubble-pop-up-main-background-color` applied in themes

**To Reproduce**  
I just use the code from the example for release 2.3.0

**Expected behavior**  
I'm expecting to apply a color from exaple (rgb(0,70,90)) to the background of main entity card in pop-up

**Screenshots**  
![image](https://github.com/user-attachments/assets/b397c395-c182-49e9-bad6-49de4411b7b6)

**YAML**  

```yaml
Bubble:  
  bubble-secondary-background-color: "rgb(0,70,90)"
  bubble-pop-up-main-background-color: "rgba(200,200,200,0.5)"

```

**Informations (please complete the following information):**  
 - Browser/App: chrome
 - Bubble Card version: 2.3.0
 - Home Assistant version: 2024.12.1

**Additional context**  
I think `bubble-pop-up-main-background-color` has an advantage over `bubble-secondary-background-color`  because if I delete the row `bubble-pop-up-main-background-color`, the color is applied
![image](https://github.com/user-attachments/assets/61161ba4-5a6a-43da-9a11-8d9f0836be97)

Thank you! 🍻
