### ISSUE TITLE
[v2.3.2] Popup doesnt close on home page

### ISSUE THREAD

**Issue by Dimi27** [Clooos/Bubble-Card#1036]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
I use the popup card on many of my views, 
however if I open a popup on my homescreen I can't close them anymore. 
I have to click back in my browser (or back on my android buttons) to let the popup close.
On all the other views of my dashboard everything works normal.

I tried to convert my dashboard from the old masonry or grid view to the new sections one but that didn't help eighter.
I also tried to give my homepage a url for navigational purposes but without succes.

**To Reproduce**  
1. Go to first view when selecting a dashboard (the first one that opens up)
2. Click on new card, select vertical stack, then bubble card, then popup with hash ex: #popup
3. Go back to first view when selecting a dashboard (the first one that opens up)
4. Create a button with navigation function to  ex: /homescreen#popup
5. See error

**Expected behavior**  
If i click or tap on the close icon in the top right of the popup card, the popup should close

**Screenshots**  
![image](https://github.com/user-attachments/assets/8e4a83a9-f4f4-483c-8227-4a0d33fdf42f)

**YAML**  
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#popup"
    name: Weer
    ...etc

**Informations (please complete the following information):**  
 - OS: Android 13 and Windows 11
 - Browser/App: Opera browser & Home Assistant android app
 - Bubble Card version: 2.3.2
 - Core   2024.12.1
   Supervisor   2024.11.4
   Operating System   14.0
   Frontend    20241127.6

**Additional context**  

Thank you! 🍻

**Comment by MrBearPresident** [comment]
Hi

Due to some issues identified in the latest releases (v2.3.1, v2.3.2, v2.3.3), I have decided to mark them as pre-release versions. These updates may not be fully stable and could cause unexpected behavior. I strongly recommend rolling back to the latest stable release, **v2.3.0**, until further notice. This version has been thoroughly tested and provides a reliable experience. Thank you for your understanding and patience as we work to ensure a future updates that meets the highest standards of quality.

---

[u]**How to rollback**[/u]
1. Click on the integration  in HACS.
2. Click on the three dots icon top right of the page.
3. Select Redownload.
4. Choose the version you want from the dropdown list.
5. Click Download.

**Comment by MrBearPresident** [comment]
Can you try the newest bèta version and report back if your issue is solved?

**Comment by Dimi27** [comment]
I tried it with the 2.3.4 beta one version but the problem remains.

Thx for trying to solve it, and many thanks for all the work already done!



Met vriendelijke groeten,


Dimitri Daelman
________________________________

**Comment by MrBearPresident** [comment]
Could you share more of your yaml/setup because I cannot reproduce this on my home screen. 


To test this place this code on your homescreen (this works with mine): 
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: button
    button_type: name
    show_icon: true
    icon: mdi:link
    name: Go To Sun Pop-up
    tap_action:
      navigation_path: "#Bubble-Test-Sun"
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#Bubble-Test-Sun"
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        hash: "#Bubble-Test-Sun"
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sun.sun
```
