### ISSUE TITLE
Box shadow variable also changes cover sub-buttons

### ISSUE THREAD

**Issue by johndoe0815** [Clooos/Bubble-Card#1039]
**Describe the bug**  
When using the new theme variable bubble-box-shadow, the settings are also applied to the sub-buttons on the cover-card, which should not be the case, it looks awkward.

**To Reproduce**  
Put something like
`bubble-box-shadow: rgba(0, 0, 0, 0.4) 0px 1px 3px`
in your custom theme.

**Expected behavior**  
Box shadow should only be applied to the outside containers, not to buttons inside the container. Like this:
![grafik](https://github.com/user-attachments/assets/2de3c7ed-1250-4a6c-9fab-d498edc23f6c)

**Screenshots**  
This is how it looks when using the theme variable:
![grafik](https://github.com/user-attachments/assets/5ae48405-4673-422e-ab78-921a95a368ff)

**YAML**  
```
type: custom:bubble-card
card_type: cover
entity: cover.rolladen
show_last_changed: true
show_state: true
force_icon: false
card_layout: large
grid_options:
  columns: 12
  rows: 1
icon_open: mdi:window-shutter-open
icon_close: mdi:window-shutter
icon_down: mdi:arrow-down-circle-outline
icon_up: mdi:arrow-up-circle-outline
```

**Informations (please complete the following information):**  
 - OS: Windows & iOS
 - Browser/App: Firefox, Companion App
 - Bubble Card version: 2.3.2
 - Home Assistant version: 2024.12.2
