### ISSUE TITLE
Select Card options show in default language instead of translation

### ISSUE THREAD

**Issue by pcr-coding** [Clooos/Bubble-Card#1040]
**Describe the bug**  
The select menu does not show the options in the correct language, while the state in the card indeed does show it correctly by default.
I can select "sweeping and mopping" and then the state shows automatically "Saugen und Wischen" (in German, which is the language I use in Home Assistant). So the state is shown correctly but the options not.

**To Reproduce**  
Choose some entity where the options you can select have some translated options and create a bubble card.
This happens with any entity that has translations.

**Expected behavior**  
I expect the options to show the translated version instead of the default language, as well as it does in the state.

**Screenshots**  
![Screenshot 2024-12-13 103349](https://github.com/user-attachments/assets/506bacb3-59aa-4365-aab0-7d3cd13a8621)

**YAML**  
YAML code of the card I used.

```yaml
type: custom:bubble-card
card_type: select
entity: select.x40_ultra_complete_cleaning_mode
show_state: true
show_last_changed: false
show_attribute: false
force_icon: false
show_icon: true
scrolling_effect: true
name: Cleaning Mode
columns: 2
card_layout: normal
```

**Informations (please complete the following information):**  
 - Bubble Card version: 2.3.2
 - Home Assistant version: 2024.12.2

Thank you! 🍻
