### ISSUE TITLE
Visibility option on main button versus just sub-buttons

### ISSUE THREAD

**Issue by CykloneFij** [Clooos/Bubble-Card#1050]
Standard HA visibility option only works for sub buttons and not main button?  Is this by design or am I missing something?

`        
-  
          visibility:
            - condition: state
              -  entity: '[[media_player]]'
              -  state: media_player.android_tv_192_168_1_60
`
This works on a sub-button but not on main button

**Comment by Clooos** [comment]
Hi! What do you mean by main button? If it's about the whole card, there is a Visibility tab at the top of the editor.

**Comment by MrBearPresident** [comment]
All is fine for me....?

![Screen Recording 2024-12-15 201605](https://github.com/user-attachments/assets/e0e1c1c2-74c1-404b-ae0e-d51823c7febd)


```
type: custom:bubble-card
card_type: button
entity: input_boolean.help_house_testboolean3
sub_button:
  - entity: input_boolean.help_house_testboolean3
    icon: mdi:numeric-3
    visibility:
      - condition: state
        entity: input_boolean.help_house_testboolean2
        state: "on"
    name: Only Show when 2=on
    show_name: true
icon: mdi:numeric-3
name: Only show when 1=on
visibility:
  - condition: state
    entity: input_boolean.help_house_testboolean
    state: "on"

```
