### ISSUE TITLE
[Compatibility other HACS] Custom-template-card and auto entities

### ISSUE THREAD

**Issue by OpenGrowBox** [Clooos/Bubble-Card#1056]
Hello dear Team,
I noticed that the bubble card not work with Templates as far as i noticed. 

If I want to build a card with 3 custom components. 

1. custom config-template-card (selects from a select sensor the current Room creates a var)
2. auto-entitys( with includes area - ${room) for all entity in that room ) 
3. bubble-card  ( if you use here the Room as String, it works. )

Like this one works with String as Area: 

```yaml
type: custom:config-template-card
variables:
  - ogb_room: states['select.ogb_rooms'].state
entities:
  - select.ogb_rooms
card:
  type: custom:auto-entities
  card:
    type: grid
    columns: 1
    square: false
  card_param: cards
  filter:
    include:
      - area: "FlowerTent"
        domain: light
        options:
          type: custom:bubble-card
          card_type: button
          button_type: button
          show_attribute: false
          show_last_changed: true
          icon: mdi:light-switch
          show_state: true
    exclude: []
  sort:
    method: state
    reverse: true
  show_empty: true

```
![image](https://github.com/user-attachments/assets/f570ee5e-3c4a-482b-af3a-069e3be726eb)

```yaml
type: custom:config-template-card
variables:
  - ogb_room: states['select.ogb_rooms'].state
entities:
  - select.ogb_rooms
card:
  type: custom:auto-entities
  card:
    type: grid
    columns: 1
    square: false
  card_param: cards
  filter:
    include:
      - area: ${ogb_room}
        domain: light
        options:
          type: custom:bubble-card
          card_type: button
          button_type: button
          show_attribute: false
          show_last_changed: true
          icon: mdi:light-switch
          show_state: true
    exclude: []
  sort:
    method: state
    reverse: true
  show_empty: true

```
![image](https://github.com/user-attachments/assets/45ff9be2-ac86-4222-b44f-516daabf4a82)

If you need a room sensor for current all rooms to select, you can use the opengrowbox-ha integration for no need to itself. 

Also, if try to get that over templates in auto-enties I also don't get any result. 

Looks like it's relating to the template engine 

Or is the problem related to my YAML ? Maybe someone have an idea. 

Working on Debian 11 HA Supervised
- OS: MacOS
- Browser: Brave
- Bubble Card Version: v2.3.2
- Home Assistant Service versions
![image](https://github.com/user-attachments/assets/f68f72e0-493f-48e6-ad56-11053bdbdbe2)

Thank you! 🍻

**Comment by MrBearPresident** [comment]
Combining 3 custom-components, that is some challenging stuff. 
I can't follow completely why do you assume this is a bubble-card problem?

**Comment by OpenGrowBox** [comment]
Hello, 

If I use normal entity card as example, it works fine. 

See here 
![image](https://github.com/user-attachments/assets/f7488015-df43-4b42-b64a-b09074b340bb)
```yaml
type: custom:tabbed-card
tabs:
  - card:
      type: custom:config-template-card
      variables:
        ogb_room: states['select.ogb_rooms'].state
      entities:
        - select.ogb_rooms
      card:
        type: vertical-stack
        cards:
          - type: custom:auto-entities
            card:
              type: entities
              name: Other Options
              title: |
                Room Optionen
            filter:
              include:
                - area: ${ogb_room}
                  domain: select
              exclude:
                - name: "*Select*"
                - name: "*Own*"
                - name: "*GLS*"
                - name: "*Light*"
    attributes:
      label: Modes
      icon: mdi:auto-mode
layout_options:
  grid_columns: 4
  grid_rows: auto
```

What I think is that the card can't work with hat array/list of entities if they are from a var.

I just want to get the list / array of entities dynamic with in the bubble card. 

Tried many things, what I found is that problem is with $vars. As I work with "Strings" and tell the "area" as String 

Bubble card can display me the entities but not from the var. 

Hope that helps to understand what I mean. 

Thanks
