### ISSUE TITLE
Call Service Action does not support floor_id target

### ISSUE THREAD

**Issue by mal2856** [Clooos/Bubble-Card#1068]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
If you add a service call action and try to target a floor, the configuration isn't saved properly and it doesn't work.

**To Reproduce**  
Add an action that targets a specfic floor, e.g.

```
    tap_action:
      action: call-service
      service: light.turn_off
      target:
        floor_id: top
```
**Expected behavior**  
Configuration is saved and service call runs as normal.

Thank you! 🍻
