### ISSUE TITLE
Pop-up of button_type "name" does not use icon / name of provided entity

### ISSUE THREAD

**Issue by svb91** [Clooos/Bubble-Card#1070]
**Describe the bug**  
If changing the button_type to "name" the entity attributes were not used in the header section.

**Screenshots**  
![image](https://github.com/user-attachments/assets/be6146df-b247-423f-bd6a-17b4ea57dd9f)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
      - type: custom:bubble-card
        card_type: pop-up
        button_type: name
        entity: light.og_as_l_decke
```
