### ISSUE TITLE
Templating texts (like name or state) for `.bubble-name` doesn't work

### ISSUE THREAD

**Issue by MilesTEG1** [Clooos/Bubble-Card#1078]
**Describe the bug**  
I want to change the text displayed by a button, so I use [the template for Templating texts (like name or state)](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#templates) 

```yaml
    styles: >
      ${card.querySelector('.bubble-name').innerText = "Aujourd'hui :" + "  " 
        + hass.states['sensor.rte_tempo_couleur_actuelle_visuel'].state
        + " " + hass.states['sensor.rte_tempo_couleur_actuelle'].state
      }
```
But, the name of the button isn't changed at all:

![CleanShot 2024-12-23 at 10 45 59@2x](https://github.com/user-attachments/assets/5dcdf84c-39b9-4d1e-b59c-5aec1a6d54f8)

**Expected behavior**  
The text should be changed, like the sub-button for which it works fine.

**Screenshots**  

**YAML**  
Here, the whole yaml code of my card:

```yaml
square: false
type: grid
cards:
  - type: custom:bubble-card
    card_type: separator
    name: "EDF Tempo "
    sub_button:
      - entity: sensor.rte_tempo_cycle_jours_restants_bleu
        show_state: true
      - entity: sensor.rte_tempo_cycle_jours_restants_blanc
        show_state: true
      - entity: sensor.rte_tempo_cycle_jours_restants_rouge
        show_state: true
    styles: |
      ha-card {
        border-radius: 0px !important;
        padding-top: 5px !important;
        padding-bottom: 0px !important;
        bottom: 0 !important;
      }
      .bubble-sub-button-1 {
         background-color: rgb(15, 63, 188,1) !important;
         font-weight: bold !important;
      }
      .bubble-sub-button-2 {
        background-color: rgb(241, 241, 241,1) !important;
        color: rgb(0,0,0, 1) !important;
        font-weight: bold !important;
      }
      .bubble-sub-button-3 {
         background-color: rgb(224, 58, 37,1) !important;
         font-weight: bold !important;
      }
      .bubble-line {
        background: var(--primary-text-color) !important;
        opacity: 0.1 !important;
      }
    icon: mdi:calendar
  - type: custom:bubble-card
    card_type: button
    button_type: state
    entity: sensor.rte_tempo_couleur_actuelle
    name: "Aujourd'hui : "
    show_attribute: false
    attribute: options
    icon: mdi:transmission-tower-export
    styles: >
      .bubble-button-background {
        opacity: 1;
        background-color: ${
          {
            'Blanc': 'rgba(255, 255, 255, 1)',
            'Bleu': 'rgba(15, 63, 188, 1)',
            'Rouge': 'rgba(224, 58, 37, 1)',
            }[state] ?? 'rgba(12, 15, 18, 0.7)'
          };
      }

      .bubble-name { 
        color:  ${
          {
            'Blanc': 'rgba(0, 0, 0, 1)',
            'Bleu': 'rgba(15, 63, 188, 1)',
            'Rouge': 'rgba(224, 58, 37, 1)',
            }[state] ?? 'rgba(12, 15, 18, 0.7)'
          };
      }

      .bubble-state { 
        color:  ${
          {
            'Blanc': 'rgba(0, 0, 0, 1)',
            'Bleu': 'rgba(15, 63, 188, 1)',
            'Rouge': 'rgba(224, 58, 37, 1)',
            }[state] ?? 'rgba(12, 15, 18, 0.7)'
          };
      }

      .bubble-icon-container {
        color: ${
          {
            'Blanc': 'rgba(0, 0, 0, 1)',
            'Bleu': 'rgba(15, 63, 188, 1)',
            'Rouge': 'rgba(224, 58, 37, 1)',
            }[state] ?? 'rgba(12, 15, 18, 0.7)'
          };
        background-color: ${
          {
            'Blanc': 'rgba(255, 255, 255, 1)',
            'Bleu': 'rgba(22, 21, 23, 1)',
            'Rouge': 'rgba(22, 21, 23, 1)',
            }[state] ?? 'rgba(12, 15, 18, 0.7)'
          };
        }

      .bubble-sub-button-1 {
         font-weight: bold;
      }


      ${card.querySelector('.bubble-name').innerText = "Aujourd'hui :" + "  " 
        + hass.states['sensor.rte_tempo_couleur_actuelle_visuel'].state
        + " " + hass.states['sensor.rte_tempo_couleur_actuelle'].state
      }


      ${card.querySelector('.bubble-sub-button-name-container').innerText =
      "Demain :" + "  " +
      hass.states['sensor.rte_tempo_prochaine_couleur_visuel'].state + " " +
      hass.states['sensor.rte_tempo_prochaine_couleur'].state }
    sub_button:
      - entity: sensor.rte_tempo_prochaine_couleur
        name: Demain
        icon: mdi:transmission-tower-export
        show_name: true
        show_state: true
        show_attribute: false
        show_background: true
        show_icon: true
        show_last_changed: false
    show_state: true
    show_name: true
    force_icon: false
    show_last_changed: false
    double_tap_action:
      action: none
    hold_action:
      action: none
    button_action:
      double_tap_action:
        action: none
      hold_action:
        action: none
columns: 1

```

**Informations (please complete the following information):**  
 - OS: macOS 15.2
 - Browser/App: Ms Edge
 - Bubble Card version: 2.3.4-beta.1
 - Home Assistant version: 2024.12.5

Thank you! 🍻
