### ISSUE TITLE
[2.3.4.beta1] - Attributes Names with spaces are crashing the bubble card

### ISSUE THREAD

**Issue by FROlCi** [Clooos/Bubble-Card#1082]
**Describe the bug**  
When trying to use an attribute from a sensor that contains spaces in its name, the card displays an error: "Unexpected identifier ..."

**To Reproduce**  
If you have Onedrive installed create this card:

```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.onedrivebackup
name: Backup
show_last_changed: false
show_attribute: true
attribute: Last OneDrive backup date
show_state: true
show_name: true
show_icon: true
card_layout: large-2-rows
scrolling_effect: false
```
**Expected behavior**  
Display the last OneDrive backup date as a state infomation in the card

**Screenshots**  
![image](https://github.com/user-attachments/assets/e8bfc6ee-9a62-4a10-8536-91754c9495f4)

![image](https://github.com/user-attachments/assets/3b443c68-02f5-41ed-936f-2cd7aca3951c)

**Informations (please complete the following information):**  
 - OS: [Win11]
 - Browser/App: chrome
 - Bubble Card version: [e.g. 2.3.4.beta1]
 - Home Assistant version: 2024.12.5

**Comment by sbwilson** [comment]
I'm getting the same issue, despite using double quotes. Trying to read "due in" as the attribute name without success, though changing it to one of the non-whitespace-containing attributes, it works fine. 

```yaml
        - type: custom:bubble-card
          card_type: button
          button_type: switch
          entity: sensor.home_to_work_1
          show_state: false
          show_last_changed: false
          button_action:
            tap_action:
              action: more-info
          sub_button:
            - name: Departure
              show_background: false
              show_attribute: true
              show_name: true
              attribute: "due in"
```

The HA log reads:
```
Unexpected end of input 
getAttribute (/hacsfiles/Bubble-Card/bubble-card.js:2:9781) /hacsfiles/Bubble-Card/bubble-card.js:2:38409 
D (/hacsfiles/Bubble-Card/bubble-card.js:2:38247) 
Y (/hacsfiles/Bubble-Card/bubble-card.js:2:59592) 
gt.updateBubbleCard (/hacsfiles/Bubble-Card/bubble-card.js:1445:828) 
gt.connectedCallback (/hacsfiles/Bubble-Card/bubble-card.js:1445:127) 
apply (src/scoped-custom-element-registry.js:248:41) 
this.removeChild (src/panels/lovelace/cards/hui-card.ts:276:11) 
_updateVisibility (src/panels/lovelace/cards/hui-card.ts:261:9)
```

I'm not a javascript developer, but looks like the problem is in https://github.com/Clooos/Bubble-Card/blob/5682d08ae06e4b6d2828196c9fea6490961a7a18/src/tools/utils.js#L436

Should this line instead use array lookup notation rather than dot notation?
```javascript
return eval(`context._hass.states['${entity}']?.attributes.['${attribute}']`) ?? '';
```

I also haven't really peered into the code to see if there's other instances where this occurs in the code.
