### ISSUE TITLE
Bug: Media player card volume control broken

### ISSUE THREAD

**Issue by captainawesomejnr** [Clooos/Bubble-Card#1106]
**Describe the bug**  
Upon exiting the volume control in the media player card, the card shows no text and the icons do not update. 

**To Reproduce**  
1. Create a Media Player Bubble card
2. Click on the volume controls
3. Exit from the volume controls

**Expected behavior**  
It is expected that, upon exiting on the

**Screenshots**  

https://github.com/user-attachments/assets/eb1c5196-3fef-485f-a01f-1b432c91d6ac

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: media-player
entity: media_player.charlies_choc_room
icon: mdi:monitor-speaker
name: Charlie's Speaker
show_state: false
```

**Informations (please complete the following information):**  
 - OS: iOS, Windows
 - Browser/App: iPhone/iPad Companion App, Microsoft Edge
 - Bubble Card version: v2.3.0
 - Home Assistant version: 2024.12.5

> [!NOTE]
> This issue occurs on *all* systems and browsers!
