### ISSUE TITLE
2.3.4. update introduces hard blur at the bottom of screen

### ISSUE THREAD

**Issue by LedLeoHA** [Clooos/Bubble-Card#1139]
**Describe the bug**  
After updating to 2.3.4., bottom of the screen has a shadow-like blur, that is very noticable on computers especially.

**Screenshots**  
Before update;
![image](https://github.com/user-attachments/assets/731437f6-8066-4eed-906e-196ea8b66dc0)

After update:
![image](https://github.com/user-attachments/assets/63bc96c2-9120-4dd6-a223-bfc23bd8efbd)

**YAML**  
YAML code wasn't changed between updates, but here is my first BC YAML

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#office"
    name: Office
    icon: mdi:chair-rolling
    state: sensor.office_temperature
    auto_close: ""
    bg_color: "#1a1c50"
    button_type: state
    entity: sensor.office_temperature
    bg_opacity: "30"
    shadow_opacity: "0"
    margin: 7px
    columns: 2
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none
    button_action:
      tap_action:
        action: none
      double_tap_action:
        action: none
      hold_action:
        action: none
    show_attribute: false
    attribute: unit_of_measurement
    sub_button:
      - entity: climate.office_radiator
        show_last_changed: false
        show_attribute: true
        attribute: temperature
        name: Target
        show_name: true
    backdrop_blur: "10"
    bg_blur: "0"
```

**Informations (please complete the following information):**  
 - OS: Windows/Android
 - Browser/App: Chrome/Mobile app
 - Bubble Card version: 2.3.4.
 - Home Assistant version: 2025.1.2.
