### ISSUE TITLE
Bubble Cover card in Large layout has way to much vertical space below it

### ISSUE THREAD

**Issue by sjcrossley** [Clooos/Bubble-Card#1152]
**Describe the bug**  
Bubble Cover card in Large layout has a lot of blank space below it.  It seems as though the space reserved for the card is the same as it is when in Normal layout, but in normal layout most of that space is actually being used to display controls.  Even in Normal layout the space is more than for other Bubble cards.

**To Reproduce**  
1. Add a Bubble cover card to a dashboard above any other card.
2. In Normal layout (where the open/close buttons are along the bottom of the card) observe more vertical space below the card than expected.
3. In Large layout (where the open/close buttons are at the right hand side of the card) observe that the card still consumes the same amount of vertical space but is only using half of it.

**Expected behavior**  
Extra space should be removed and a Bubble Cover card in Large layout should consume the same amount of vertical space as other Bubble cards in Large layout.

**Screenshots**  
![Image](https://github.com/user-attachments/assets/90f7e91d-7366-45b0-9dde-b0194b6385e2)

**YAML**  
Here's the code my card in Large layout

```yaml
type: custom:bubble-card
card_type: cover
card_layout: large
entity: cover.garage
icon_open: mdi:garage-open-variant
icon_close: mdi:garage-variant
show_state: true
show_last_changed: true
styles: |
  .bubble-cover-card-container {
    background-color: rgb(0,0,0,0.4) !important;
  }
  .bubble-icon {
    color: ${hass.states[entity].state === 'closed' ? 'var(--success-color)' : 'var(--warning-color)'} !important;
    opacity: 1 !important;
  }
```

**Informations (please complete the following information):**  
 - OS: generic-x86-64  Version 14.1
 - Browser/App: Edge, Chrome, Android companion app
 - Bubble Card version: 2.3.4
 - Home Assistant version: 2025.1.0

**Additional context**  
I've tried to reduce the height through custom styling, but have been unsuccessful.

Love the Bubble Card though - your work on this is appreciated!
Thank you! 🍻
