### ISSUE TITLE
e.config.styles?.includes is not a function

### ISSUE THREAD

**Issue by Symbiot78** [Clooos/Bubble-Card#1161]
**Describe the bug**  

bubblecard shows the buttons then after 2-3 seconds it throws an error:

e.config.styles?.includes is not a function

**To Reproduce**  
no idea..

**Expected behavior**  
no error

**Screenshots**  

![Image](https://github.com/user-attachments/assets/b74a3380-412c-4bb5-af13-c8fded54e0fc)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
                                     - type: custom:bubble-card
                                        card_type: cover
                                        entity: cover.ka_alkove
                                        show_state: true
                                        name: Alkove
                                        open_service: cover.open_cover
                                        stop_service: cover.stop_cover
                                        close_service: script.curtain_alkove_luk
                                        styles:
                                          card:
                                            - background-color: var(--card-background-color)
                                            - color: var(--primary-foreground-color)
                                            - border-radius: 10px

```

**Informations (please complete the following information):**  
 - OS: ios, windows
 - Browser/App: opera, app, chrome
 - Bubble Card version: 2.3.4
 - Home Assistant version: 2025.1.2

**Additional context**  
restart tried, checked other cards.. only bubblecard throwing this error.
started.... yesterday.. nothing changed or updated.
