### ISSUE TITLE
Altered color climate cards

### ISSUE THREAD

**Issue by userdema** [Clooos/Bubble-Card#1164]
**Describe the bug**  
When i try to change the color of climate card when the state of my thermostatic valve are heating, the color that results it's deeply altered respect the #hex that i choose, and only in those cards.. in the others there aren't problem.. seems that the original theme color Merges with the chosen one and the result is a really ugly color.

**To Reproduce**  
create a climate cards for heating element that color the entire bar when's heating and try to change the state color.

**Expected behavior**  
The color would be the same of the other cards using the same #hex

In the screenshot you can see the original theme color (orange) in the bottom card (bagno) and the altered one in the top card (sala)
While the colour that I'm trying to reproduce is in 

![Image](https://github.com/user-attachments/assets/319889cf-37e6-4a16-946a-75abdb51df74)
![Image](https://github.com/user-attachments/assets/37f1a5fe-55a1-4750-9054-713bca30004b)

the other screenshot (estate)

**YAML**  
If applicable, add any relevant YAML code.

.bubble-color-background {
  background: ${hass.states['climate.giorno'].attributes.hvac_action === 'heating' ? '#ebc634' : '' } !important;
}

**Informations (please complete the following information):**  
 - OS: android
 - Browser/App: [not relevant]
 - Bubble Card version: 2.3.4
 - Home Assistant version: 2025.1.2

**Comment by Clooos** [comment]
Hi! There is an opacity on that element, to improve the text contrast with some colors.

You can add this to your custom style:

```yaml
.bubble-color-background {
    background: ${hass.states['climate.giorno'].attributes.hvac_action === 'heating' ? '#ebc634' : '' } !important;
    opacity: 1 !important;
}
```
