### ISSUE TITLE
Random spacing appears when using multiple bubble cards with pop-ups

### ISSUE THREAD

**Issue by greenship24** [Clooos/Bubble-Card#1167]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
Random spacing appears in between bubble cards that contain pop ups. Sometimes the space is not there (expected) and other times it shifts and produces plenty of space. Does not require a mouse click/tap, etc. to reproduce.

**To Reproduce**  
1. Take the yaml below
2. Simply save the cards and wait. 
3. Initially the space should be the same as normal bubble cards lining up against each other but they then separate.

**Expected behavior**  
Expect consistent spacing that does not adjust.

**Screenshots**  
https://imgur.com/a/9gFgJst

**YAML**  
If applicable, add any relevant YAML code.

``` yaml
    type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: Lights
            icon: mdi:lightbulb-group
            tap_action:
              action: navigate
              navigation_path: /lovelace-lighting
            sub_button:
              - entity: light.porch_lights
                name: porch
                tap_action:
                  action: navigate
                  navigation_path: "#porch"
                hold_action:
                  action: toggle
                light_background: false
              - entity: switch.kasa_1
                name: Kids
                show_name: true
                tap_action:
                  action: navigate
                  navigation_path: "#kids"
                hold_action:
                  action: toggle
              - entity: switch.nightstand_lights
                name: Master
                show_name: true
                tap_action:
                  action: navigate
                  navigation_path: "#master"
                hold_action:
                  action: toggle
              - entity: light.basement_lights
                name: Basement
                show_name: true
                tap_action:
                  action: navigate
                  navigation_path: "#basement"
                light_background: false
            button_action:
              tap_action:
                action: navigate
                navigation_path: /lovelace-lighting
            styles: |-
              .bubble-icon-container {
                background:  #a77e00 !important;
                }
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: "#porch"
                button_type: state
                name: Porch
                icon: ""
                sub_button: []
                entity: light.porch_lights
                tap_action:
                  action: toggle
              - type: light
                entity: light.porch_lights
                name: Porch Lights
          - type: vertical-stack
            cards:
and so on and so forth...
```

**Informations (please complete the following information):**  
 - OS: Linux/android
 - Browser/App: firefox/hass-minimal
 - Bubble Card version: 2.3.4
 - Home Assistant version: 2025.1.2

**Additional context**  
I have not seen any kind of error or indication of what is going on while using dev tools in Firefox to track it when it moves.

Thank you! 🍻
