### ISSUE TITLE
Animating sub-button icon requires duplicate yaml line

### ISSUE THREAD

**Issue by Flicker20** [Clooos/Bubble-Card#1175]
**Describe the bug**  
Whilst trying to animate a sub-button icon conditionally, it seems I have to have duplicate code in order for it to work.

```yaml
        .bubble-sub-button-2 > ha-icon {
          color: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'green' : 'red'} !important;
        }

        .bubble-sub-button-2 > ha-icon {
          color: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'green' : 'red'} !important;
          animation: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'rock-back-forth 2.5s ease-in-out infinite' : ''} !important;
        }       
 
        @keyframes rock-back-forth {
          0%, 100% { transform: rotate(0deg); }
          25% { transform: rotate(-15deg); }
          75% { transform: rotate(15deg); }
        }
```

**To Reproduce**  
If I only have one of the below lines in I don't get my animation or color change. If I repeat the line, it works 
```yaml
        .bubble-sub-button-2 > ha-icon {
          color: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'green' : 'red'} !important;
        }
```

**Expected behavior**  
I should be able to just use the below for it to work:
```yaml
        .bubble-sub-button-2 > ha-icon {
          color: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'green' : 'red'} !important;
          animation: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'rock-back-forth 2.5s ease-in-out infinite' : ''} !important;
        }       
 
        @keyframes rock-back-forth {
          0%, 100% { transform: rotate(0deg); }
          25% { transform: rotate(-15deg); }
          75% { transform: rotate(15deg); }
        }
```

**Screenshots**  

![Image](https://github.com/user-attachments/assets/4ee8d568-fbb0-4aee-9ef6-8989f0b47ba0)
![Image](https://github.com/user-attachments/assets/c5f33abe-86aa-46be-8027-de18b5ee0fbf)

![Image](https://github.com/user-attachments/assets/585a951b-038a-4968-95ce-88445a7475bd)
![Image](https://github.com/user-attachments/assets/5d40db10-bb12-4ea7-b13f-8cde182d45aa)

**Informations (please complete the following information):**  
 - OS: Windows 11 / Android 15
 - Browser/App: Chrome / Companion App
 - Bubble Card version: v2.3.4
 - Home Assistant version: 2025.1.2

The full card is:
```yaml
type: custom:bubble-card
card_type: button
entity: light.utility
show_icon: true
show_name: true
show_last_changed: false
show_state: true
show_attribute: false
attribute: supported_color_modes
sub_button:
  - entity: binary_sensor.utility_movement_sensor_occupancy
    show_background: false
    show_name: false
    show_last_changed: false
    show_state: false
    show_attribute: false
    attribute: occupancy
    tap_action:
      action: none
    icon: ""
    visibility:
      - condition: state
        entity: binary_sensor.utility_movement_sensor_occupancy
        state: "on"
  - show_background: false
    show_icon: true
    visibility: []
    icon: ""
    show_state: true
    show_last_changed: false
    show_attribute: false
    attribute: friendly_name
    show_name: false
    light_background: false
    entity: sensor.tumble_dryer_mode
card_layout: large-2-rows
icon: mdi:washing-machine
tap_action:
  action: toggle
hold_action:
  action: navigate
  navigation_path: "#kitchen"
button_action:
  tap_action:
    action: toggle
  hold_action:
    action: navigate
    navigation_path: "#kitchen"
use_accent_color: false
styles: |2-
        ha-card {
          --primary-background-color: '#1c1c1c' !important;
          --bubble-main-background-color: ${hass.states['light.utility'].state === 'on' ? 
          'rgba(254, 219, 104, ' + ((hass.states['light.utility'].attributes.brightness || 255) / 255) + ')' : 
          '#1c1c1c'} !important;

          --primary-text-color: ${hass.states['light.utility'].state === 'on' ? 'black' : 'white'} !important;
          --secondary-text-color: ${hass.states['light.utility'].state === 'on' ? 'black' : 'grey'} !important;
        }

        .bubble-icon {
          background-color: '#1c1c1c' !important;
        }

        
        
        
        
        .bubble-sub-button-1 > ha-icon {
          color: ${hass.states['binary_sensor.utility_movement_sensor_occupancy'].state === 'on' ? 'red' : 'grey'} !important;
        }
        ${subButtonIcon[0].setAttribute("icon", hass.states['binary_sensor.utility_movement_sensor_occupancy'].state === 'on' ? 'mdi:motion-sensor' 
           : 'mdi:motion-sensor-off')}

        
        
        ${subButtonIcon[1].setAttribute("icon", hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'mdi:tumble-dryer' 
           : 'mdi:tumble-dryer-off')}

        .bubble-sub-button-2 > ha-icon {  
          color: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'green' : 'red'} !important;
        }
        .bubble-sub-button-2 > ha-icon { 
          color: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'green' : 'red'} !important;
          animation: ${hass.states['sensor.tumble_dryer_mode'].state === '1' ? 'rock-back-forth 2.5s ease-in-out infinite' : ''} !important;
        }        
        @keyframes rock-back-forth {
          0%, 100% { transform: rotate(0deg); }
          25% { transform: rotate(-15deg); }
          75% { transform: rotate(15deg); }
        }
```

Thank you! 🍻
