### ISSUE TITLE
Removing Conditions for a PopUp using the visual editor results in popup always triggering.

### ISSUE THREAD

**Issue by JaronrH** [Clooos/Bubble-Card#1178]
**Describe the bug**  
Removing a Button-Card's PopUp triggers in Visual Editor causes the popup to appear whenever loading a dashboard containing the popup.

**To Reproduce**  
1. Create a new popup card. 
2. Add any trigger and save.  

```
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#pop-up-demo'
                trigger:
                  - condition: state
                    entity: update.home_assistant_core_update
                    state: invalid
```
3. Edit Pop-up in Visual Editor and remove all triggers.

![Image](https://github.com/user-attachments/assets/97072039-7900-4d78-93a5-d41f8d4cbf7b)

![Image](https://github.com/user-attachments/assets/192b3d82-7244-42fe-adfe-b8cac55c8d21)

5. Save
```
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#pop-up-demo'
                trigger: []

```

Popup will now open EVERY time.  **This is because the visual editor leaves "trigger: []" in the configuration**.

![Image](https://github.com/user-attachments/assets/9b971252-3250-4ed7-bf49-005189f9b655)

**Expected behavior**  
I expected one of two things:
1)  Visual Editor removes "trigger: []" when there are no conditions (or make an option to always-popup).
-or-
2) The logic ignores triggers when the array is empty.

(I vote for option 1 as that leaves the ability to have a popup open automatically)

**Informations (please complete the following information):**  
 - OS: HAOS for HASS; Edge for Windows 11, HA Companion App, etc
 - Bubble Card version: v2.3.4
 - Home Assistant version: 2025.1.3 (Frontend 20250109.0)
