### ISSUE TITLE
Varying scroll speed when multiple cards on popup

### ISSUE THREAD

**Issue by smeadow2** [Clooos/Bubble-Card#1186]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
I have created a pop-up card which contains 7 horizontal stack cards.
On each horizontal stack card are 2 Button 'state' cards with the text scrolling effect enabled.
These are showing the status of the london underground tube lines.
There are 12 cards in total on the popup.
The scrolling text describes if there are any issues with the tube line.
The length of the text that is scrolling can vary and this seems to have an effect on the scroll speed.
All of the scrolling text starts and repeats at the same time but depending on the length of the text to scroll, this alters the speed of the scroll.
So short text scrolls slowly whereas long text goes fast.
If there is just one card showing scrolling text, it goes at a slow pace regardless of the length of text.
It's only when there are multiple scrolls that the speed varies based on the slowest, shortest scroll.

**To Reproduce**  

**Expected behavior**  
While the bug is understandable I would expect the scroll to be at a defined steady speed, regardless of the length of text.

**Screenshots**  

![Image](https://github.com/user-attachments/assets/faa0b8ec-5d9f-4e5a-bee8-66cb78c3600e)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#pop-up-tube-status"
    show_header: false
    bg_color: "#242e42"
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.piccadilly
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #003688;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.bakerloo
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #B36305;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.central
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #E32017;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.circle
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #FFD300;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.district
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #00782A;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.dlr
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #00A4A7;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.elizabeth_line
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #6950a1;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.hammersmith_city
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #F3A9BB;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.jubilee
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #A0A5A9;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.metropolitan
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #9B0056;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.northern
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #000000;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: sensor.victoria
        show_icon: false
        force_icon: false
        show_name: true
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: Description
        sub_button: []
        card_layout: large
        styles: |-
          .bubble-button-card-container {
            background: #0098D4;
          }
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none

```

**Informations (please complete the following information):**  
 - OS: Any
 - Browser/App: Any
 - Bubble Card version: v2.3.4
 - Home Assistant version: 2025.1.3

**Additional context**  
Using the London Underground integration for the sensors: https://www.home-assistant.io/integrations/london_underground/

Thank you! 🍻
