### ISSUE TITLE
Starting Apps from Attribute activity_list - Android TV Remote Integration

### ISSUE THREAD

**Issue by schmierlappe** [Clooos/Bubble-Card#1187]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
Android TV Remote provide a remote entity with possibility to add apps to an activity_list. I can start apps from the entity page but when I add this activity_list attribute to an sub button I can see and select them but the apps are not starting.

**To Reproduce**  

**Expected behavior**  
starting apps from select list

**Screenshots**  

**YAML**  

```yaml
  type: custom:bubble-card
  card_type: media-player
  button_type: state
  entity: media_player.shield
  name: Shield TV
  icon: si:nvidia
  show_state: false
  sub_button:
      - entity: remote.shield
        select_attribute: activity_list
        icon: mdi:apps
        show_arrow: false
```

**Informations (please complete the following information):**  
 - OS: [e.g. iOS] - iOS
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4] - latest

**Additional context**  

Thank you! 🍻
