### ISSUE TITLE
Pop-up closes too easily when triggered from a hold_action

### ISSUE THREAD

**Issue by marcuscps** [Clooos/Bubble-Card#1188]
**Describe the bug**  
Pop ups close too fast when triggered by a long click in a button.

**To Reproduce**  
1. Configure a button that triggers a pop-up from the hold_action.
2. Create the pop up section
3. Click and hold the button
4. Check it is difficult to keep the pop-up from closing. Release too soon, it won't open. Hold it for too long, the pop-up will close. The hold time must be very precise to avoid the issue.

**Expected behavior**  
The pop-up should ignore the release of the triggering button.
The release event should be tied to the button that triggered the pop-up instead.

**Screenshots**  
https://github.com/user-attachments/assets/f94941b3-e95d-4866-879a-039f1167c8b2

**YAML**  
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: button
    button_type: state
    name: Dummy Entity
    entity: << your entity here >>
    show_state: true
    show_name: true
    show_icon: true
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: navigate
      navigation_path: "#test-popup"
    button_action:
      tap_action:
        action: none
      double_tap_action:
        action: none
      hold_action:
        action: navigate
        navigation_path: "#test-popup"
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        button_type: name
        hash: "#test-popup"
        name: Dummy Pop up...
        close_on_click: true
        show_icon: false
```

**Informations (please complete the following information):**  
 - OS: Desktop - MacOS
 - Browser/App: chrome
 - Bubble Card version: v2.3.4
 - Home Assistant version: 2025.1.4

Thank you! 🍻
