### ISSUE TITLE
Pop-up triggers other Pop-up in background

### ISSUE THREAD

**Issue by ndrtrp** [Clooos/Bubble-Card#1190]
I have created a popup button card that mainly contains groups of lamps as slider button cards, some with sub-buttons. Some of these lamps have several light sources, which is why sub-buttons on slider buttons are used to navigate to other pop-ups and control individual light sources.
If I now navigate to a pop-up (2) via a sub-button on a slider button card in the pop-up (1), pop-up (1) closes in the background. So far, so good! However, if I then navigate from pop-up (2) to a pop-up (3), pop-up (2) closes but pop-up (1) opens in the background. As I have partially reduced the height of the individual pop-ups, it is unfortunately immediately noticeable when the significantly higher pop-up (1) is visible in the background.

1. Go to Pop-Up Card
2. Click on a Sub-Button on a slider button card (Navigation to next Pop-Up Card)
3. Do the same again
4. The first Pop-Up opens in the background, while the actual Pop-Up stays in the foreground.

**Expected Behavior**

All unused Pop-Up Cards remain closed.

**Screenshots**  

https://github.com/user-attachments/assets/1948da55-4fd0-497e-815c-956e72640d1a

**YAML**  

```

views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: custom:mushroom-template-card
            primary: Hallo, {{user}}
            secondary: ''
            icon: mdi:account
            tap_action:
              action: navigate
              navigation_path: /profile
            hold_action:
              action: none
            double_tap_action:
              action: none
            grid_options:
              columns: full
              rows: 1
            icon_color: ''
            fill_container: false
            multiline_secondary: false
            layout: horizontal
        column_span: 1
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Bewegung
            icon: mdi:motion-sensor
            card_layout: large
            sub_button: []
            grid_options:
              columns: full
          - show_state: false
            show_name: true
            camera_view: auto
            type: picture-entity
            entity: camera.g3_flex_vorgarten_high
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            camera_image: camera.g3_flex_vorgarten_high
            name: Kamera Vorgarten
            grid_options:
              columns: full
            visibility:
              - condition: state
                entity: binary_sensor.g3_flex_vorgarten_motion
                state: 'on'
          - show_state: false
            show_name: true
            camera_view: auto
            type: picture-entity
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            camera_image: camera.g3_flex_terrasse_garten_high
            name: Kamera Terrassen & Garten
            grid_options:
              columns: full
            entity: camera.g3_flex_terrasse_garten_high
            visibility:
              - condition: state
                entity: binary_sensor.g3_flex_terrasse_garten_motion
                state: 'on'
        visibility:
          - condition: or
            conditions:
              - condition: state
                entity: binary_sensor.g3_flex_vorgarten_motion
                state: 'on'
              - condition: state
                entity: binary_sensor.g3_flex_terrasse_garten_motion
                state: 'on'
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Netzwerk & Sicherheit
            icon: mdi:server-security
            card_layout: large
            grid_options:
              columns: full
              rows: 1
          - type: tile
            entity: sensor.udm_se_state
            vertical: true
            name: Netzwerk
            icon: mdi:network
            state_content: state
            grid_options:
              columns: 3
              rows: 2
          - type: tile
            entity: sensor.eaton_el650usbdin_status
            vertical: true
            name: USV
            icon: mdi:power-plug-battery
            state_content: state
            grid_options:
              columns: 3
              rows: 2
          - type: tile
            vertical: true
            entity: sensor.usw_pro_24_state
            icon: mdi:cctv
            name: Kameras
            grid_options:
              columns: 3
              rows: 2
          - type: tile
            vertical: true
            icon: mdi:home-lightning-bolt
            grid_options:
              columns: 3
              rows: 2
            entity: sensor.total_power_saldiert
            name: Energie
        column_span: 1
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Bereiche
            icon: mdi:dots-square
            card_layout: large
            grid_options:
              columns: full
          - type: custom:bubble-card
            card_type: button
            entity: light.beleuchtung_eg_2
            name: Wohnen EG
            icon: mdi:home-floor-0
            scrolling_effect: false
            show_attribute: false
            show_state: false
            tap_action:
              action: more-info
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#wohnen_eg_pop'
            card_layout: large-2-rows
            sub_button:
              - entity: sensor.temperatur_wohnen_eg
                name: ''
                show_state: true
                state_background: false
              - entity: sensor.feuchtigkeit_wohnen_eg
                state_background: false
                show_last_changed: false
                show_state: true
            grid_options:
              columns: full
              rows: 1
            styles: ''
          - type: custom:bubble-card
            card_type: button
            entity: light.deckenleuchte_kind
            name: Kinderzimmer
            icon: mdi:teddy-bear
            scrolling_effect: false
            show_attribute: false
            show_state: false
            tap_action:
              action: more-info
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#kind_pop'
            card_layout: large-2-rows
            sub_button:
              - entity: sensor.temperatur_kinderzimmer
                name: ''
                show_state: true
                state_background: false
              - entity: sensor.feuchtigkeit_kinderzimmer
                state_background: false
                show_last_changed: false
                show_state: true
            grid_options:
              columns: full
              rows: 1
          - type: custom:bubble-card
            card_type: button
            entity: light.deckenleuchte_schlafen_2
            name: Schlafzimmer
            icon: mdi:bed
            scrolling_effect: false
            show_attribute: false
            show_state: false
            tap_action:
              action: more-info
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#schlafen_pop'
            card_layout: large-2-rows
            sub_button:
              - entity: sensor.temperatur_schlafzimmer
                name: ''
                show_state: true
                state_background: false
              - entity: sensor.feuchtigkeit_schlafzimmer
                state_background: false
                show_last_changed: false
                show_state: true
            grid_options:
              columns: full
              rows: 1
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#wohnen_eg_pop'
                button_type: slider
                entity: light.beleuchtung_eg_2
                name: Wohnen EG
                icon: mdi:home-floor-0
                show_header: true
                card_layout: large
                margin: 7px
                scrolling_effect: false
              - type: custom:button-card
                variables:
                  var_temp: >
                    [[[  return
                    Math.round((states['sensor.aqara_th_sensor_wohnen_temperature'].state)
                    * 10)/10 + '°' ]]]
                  var_hum: >
                    [[[ return '<span style="font-size:0.3em">' +
                    Math.round((states['sensor.aqara_th_sensor_wohnen_humidity'].state)
                    * 10)/10 + '%' ]]]
                show_icon: false
                show_name: false
                show_label: true
                custom_fields:
                  temp: |
                    [[[ return `${variables.var_temp} ${variables.var_hum}`]]]
                  graph:
                    card:
                      type: custom:mini-graph-card
                      entities:
                        - entity: sensor.aqara_th_sensor_wohnen_temperature
                          color: rgba(76, 123, 139, 1)
                      line_width: 0.3
                      height: 100
                      show:
                        icon: false
                        name: false
                        state: false
                        legend: false
                        labels: false
                      card_mod:
                        style: |
                          ha-card {
                            border-style: none;
                            background: none;
                          }    
                styles:
                  grid:
                    - grid-template-areas: '"temp"'
                  card:
                    - padding: 24px
                  custom_fields:
                    temp:
                      - justify-self: start
                      - text-align: left
                      - font-size: 54px
                      - line-height: 66px
                      - font-weight: 400
                      - padding: 12px 0 0 0
                    graph:
                      - position: absolute
                      - width: 100%
                      - left: 0
                      - bottom: 0
              - type: custom:bubble-card
                card_type: separator
                name: Beleuchtung
                icon: mdi:lightbulb-multiple
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.beleuchtung_wohnen_2
                name: Sofa & TV
                icon: mdi:sofa
                card_layout: large
                sub_button:
                  - tap_action:
                      action: navigate
                      navigation_path: '#sofatv_pop'
                    icon: mdi:chevron-down
                    state_background: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.deckenleuchte_essen_2
                name: Esstisch
                icon: mdi:table-furniture
                card_layout: large
                sub_button:
                  - icon: mdi:chevron-down
                    state_background: false
                    tap_action:
                      action: navigate
                      navigation_path: '#esstisch_pop'
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.deckenleuchte_kochen_2
                name: Küche
                icon: mdi:chef-hat
                card_layout: large
                sub_button:
                  - tap_action:
                      action: navigate
                      navigation_path: '#kueche_pop'
                    icon: mdi:chevron-down
                    state_background: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.deckenleuchte_flur_eg
                name: Flur
                icon: mdi:shoe-print
                card_layout: large
                sub_button:
                  - icon: mdi:chevron-down
                    state_background: false
                    tap_action:
                      action: navigate
                      navigation_path: '#flur_eg_pop'
              - type: custom:bubble-card
                card_type: separator
                name: Rollläden
                icon: mdi:window-shutter
                card_layout: large
              - type: custom:bubble-card
                card_type: cover
                entity: cover.shelly_rollladen_terrasse
                name: Terrasse
                card_layout: large
                show_state: false
                show_attribute: true
                attribute: current_position
              - type: custom:bubble-card
                card_type: cover
                entity: cover.shelly_rollladen_wohnzimmer
                name: Sofa
                card_layout: large
                show_state: false
                show_attribute: true
                attribute: current_position
              - type: custom:bubble-card
                card_type: cover
                entity: cover.rolladensteuerung_kuche
                name: Küche
                card_layout: large
                show_state: false
                show_attribute: true
                attribute: current_position
            grid_options:
              columns: full
              rows: auto
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#sofatv_pop'
                show_header: true
                button_type: slider
                name: Sofa & TV
                icon: mdi:sofa
                show_icon: true
                scrolling_effect: false
                show_name: true
                close_action:
                  action: navigate
                  navigation_path: '#wohnen_eg_pop'
                entity: light.beleuchtung_wohnen_2
                force_icon: false
                show_last_changed: false
                show_state: false
                show_attribute: false
                attribute: brightness
                card_layout: large
                margin_top_mobile: calc(100vh - 560px)
              - type: custom:bubble-card
                card_type: separator
                name: ''
                icon: ''
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.stehleuchte_wohnen_2
                name: Stehleuchte
                card_layout: large
                icon: mdi:lightbulb-group
                sub_button:
                  - entity: light.stehleuchte_wohnen_2
                    icon: mdi:chevron-down
                    state_background: false
                    tap_action:
                      action: navigate
                      navigation_path: '#stehleuchte_pop'
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_iris_wohnen
                name: Hue Iris
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.ikea_tradfri_gu10_wohnen
                name: Leseleuchte
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.ikea_tradfri_e27_wohnen
                name: Deckenleuchte
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#stehleuchte_pop'
                show_header: true
                button_type: slider
                name: Stehleuchte
                icon: mdi:lightbulb-group
                show_icon: true
                scrolling_effect: false
                show_name: true
                close_action:
                  action: navigate
                  navigation_path: '#sofatv_pop'
                entity: light.stehleuchte_wohnen_2
                show_attribute: false
                show_state: false
                attribute: brightness
                card_layout: large
                margin_top_mobile: calc(100vh - 500px)
                close_by_clicking_outside: true
              - type: custom:bubble-card
                card_type: separator
                name: ''
                icon: ''
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_1_stehleuchte_wohnen
                name: Oben
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_2_stehleuchte_wohnen
                name: Mitte
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_3_stehleuchte_wohnen
                name: Unten
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#esstisch_pop'
                show_header: true
                button_type: slider
                name: Esstisch
                icon: mdi:table-furniture
                show_icon: true
                scrolling_effect: false
                show_name: true
                close_action:
                  action: navigate
                  navigation_path: '#wohnen_eg_pop'
                entity: light.deckenleuchte_essen_2
                card_layout: large
                margin_top_mobile: calc(100vh - 500px)
              - type: custom:bubble-card
                card_type: separator
                name: ''
                icon: ''
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_1_essen
                name: Links
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_2_essen
                name: Mitte
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_3_essen
                name: Rechts
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#kueche_pop'
                show_header: true
                button_type: slider
                name: Küche
                icon: mdi:chef-hat
                show_icon: true
                scrolling_effect: false
                show_name: true
                close_action:
                  action: navigate
                  navigation_path: '#wohnen_eg_pop'
                entity: light.deckenleuchte_kochen_2
                card_layout: large
                margin_top_mobile: calc(100vh - 560px)
              - type: custom:bubble-card
                card_type: separator
                name: ''
                icon: ''
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_deckenfluter_kochen
                name: Deckenfluter
                card_layout: large
                icon: mdi:wall-sconce-flat
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_1_kochen
                name: Spot 1
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_2_kochen
                name: Spot 2
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_3_kochen
                name: Spot 3
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#flur_eg_pop'
                show_header: true
                button_type: slider
                name: Flur
                icon: mdi:shoe-print
                show_icon: true
                scrolling_effect: false
                show_name: true
                close_action:
                  action: navigate
                  navigation_path: '#wohnen_eg_pop'
                entity: light.deckenleuchte_flur_eg
                card_layout: large
                margin_top_mobile: calc(100vh - 500px)
              - type: custom:bubble-card
                card_type: separator
                name: ''
                icon: ''
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_deckenfluter_flur_eg
                name: Deckenfluter
                card_layout: large
                icon: mdi:wall-sconce-flat
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_1_flur_eg
                name: Spot 1
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_2_flur_eg
                name: Spot 2
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#kind_pop'
                show_header: true
                button_type: slider
                name: Kinderzimmer
                icon: mdi:teddy-bear
                show_icon: true
                scrolling_effect: false
                show_name: true
                entity: light.deckenleuchte_kind
                force_icon: false
                show_last_changed: false
                show_state: false
                show_attribute: false
                attribute: brightness
                card_layout: large
              - type: custom:button-card
                variables:
                  var_temp: >
                    [[[  return
                    Math.round((states['sensor.aqara_th_sensor_kind_temperature'].state)
                    * 10)/10 + '°' ]]]
                  var_hum: >
                    [[[ return '<span style="font-size:0.3em">' +
                    Math.round((states['sensor.aqara_th_sensor_kind_humidity'].state)
                    * 10)/10 + '%' ]]]
                show_icon: false
                show_name: false
                show_label: true
                custom_fields:
                  temp: |
                    [[[ return `${variables.var_temp} ${variables.var_hum}`]]]
                  graph:
                    card:
                      type: custom:mini-graph-card
                      entities:
                        - entity: sensor.aqara_th_sensor_kind_temperature
                          color: rgba(225, 117, 100, 1)
                      line_width: 0.3
                      height: 100
                      show:
                        icon: false
                        name: false
                        state: false
                        legend: false
                        labels: false
                      card_mod:
                        style: |
                          ha-card {
                            border-style: none;
                            background: none;
                          }    
                styles:
                  grid:
                    - grid-template-areas: '"temp"'
                  card:
                    - padding: 24px
                  custom_fields:
                    temp:
                      - justify-self: start
                      - text-align: left
                      - font-size: 54px
                      - line-height: 66px
                      - font-weight: 400
                      - padding: 12px 0 0 0
                    graph:
                      - position: absolute
                      - width: 100%
                      - left: 0
                      - bottom: 0
              - type: custom:bubble-card
                card_type: separator
                name: Beleuchtung
                icon: mdi:lightbulb-multiple
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.deckenleuchte_kind
                name: Deckenleuchte
                card_layout: large
                icon: mdi:lightbulb-group
                sub_button:
                  - icon: mdi:chevron-down
                    state_background: false
                    tap_action:
                      action: navigate
                      navigation_path: '#deckenleuchte_kind_pop'
                show_state: false
              - type: custom:bubble-card
                card_type: separator
                name: Rollladen
                icon: mdi:window-shutter
                card_layout: large
              - type: custom:bubble-card
                card_type: cover
                entity: cover.shelly_rollladen_kinderzimmer
                name: Fenster
                card_layout: large
                show_state: false
                force_icon: false
                show_name: true
                show_attribute: true
                attribute: current_position
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#deckenleuchte_kind_pop'
                show_header: true
                button_type: slider
                name: Deckenleuchte
                icon: mdi:lightbulb-group
                show_icon: true
                scrolling_effect: false
                show_name: true
                close_action:
                  action: navigate
                  navigation_path: '#kind_pop'
                entity: light.deckenleuchte_kind
                show_attribute: false
                show_state: false
                attribute: brightness
                card_layout: large
                margin_top_mobile: calc(100vh - 500px)
              - type: custom:bubble-card
                card_type: separator
                name: ''
                icon: ''
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_3_kind
                name: Links
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_2_kind
                name: Mitte
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_bulb_1_kind
                name: Rechts
                card_layout: large
                icon: mdi:lightbulb
                sub_button: []
                scrolling_effect: false
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#schlafen_pop'
                show_header: true
                button_type: slider
                name: Schlafzimmer
                icon: mdi:bed
                show_icon: true
                scrolling_effect: false
                show_name: true
                entity: light.deckenleuchte_schlafen_2
                force_icon: false
                show_last_changed: false
                show_state: false
                show_attribute: false
                attribute: brightness
                card_layout: large
              - type: custom:button-card
                variables:
                  var_temp: >
                    [[[  return
                    Math.round((states['sensor.aqara_th_sensor_schlafen_temperature'].state)
                    * 10)/10 + '°' ]]]
                  var_hum: >
                    [[[ return '<span style="font-size:0.3em">' +
                    Math.round((states['sensor.aqara_th_sensor_schlafen_humidity'].state)
                    * 10)/10 + '%' ]]]
                show_icon: false
                show_name: false
                show_label: true
                custom_fields:
                  temp: |
                    [[[ return `${variables.var_temp} ${variables.var_hum}`]]]
                  graph:
                    card:
                      type: custom:mini-graph-card
                      entities:
                        - entity: sensor.aqara_th_sensor_schlafen_temperature
                          color: rgba(94, 104, 109, 1)
                      line_width: 0.3
                      height: 100
                      show:
                        icon: false
                        name: false
                        state: false
                        legend: false
                        labels: false
                      card_mod:
                        style: |
                          ha-card {
                            border-style: none;
                            background: none;
                          }    
                styles:
                  grid:
                    - grid-template-areas: '"temp"'
                  card:
                    - padding: 24px
                  custom_fields:
                    temp:
                      - justify-self: start
                      - text-align: left
                      - font-size: 54px
                      - line-height: 66px
                      - font-weight: 400
                      - padding: 12px 0 0 0
                    graph:
                      - position: absolute
                      - width: 100%
                      - left: 0
                      - bottom: 0
              - type: custom:bubble-card
                card_type: separator
                name: Beleuchtung
                icon: mdi:lightbulb-multiple
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.deckenleuchte_schlafen_2
                name: Deckenleuchte
                card_layout: large
                icon: mdi:lightbulb-group
                sub_button:
                  - icon: mdi:chevron-down
                    state_background: false
                    tap_action:
                      action: navigate
                      navigation_path: '#deckenleuchte_schlafen_pop'
              - type: custom:bubble-card
                card_type: separator
                name: Rollladen
                icon: mdi:window-shutter
                card_layout: large
              - type: custom:bubble-card
                card_type: cover
                entity: cover.shelly_rollladen_schlafzimmer
                name: Fenster
                card_layout: large
                show_state: false
                force_icon: false
                show_name: true
                show_attribute: true
                attribute: current_position
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#deckenleuchte_schlafen_pop'
                show_header: true
                button_type: slider
                name: Deckenleuchte
                icon: mdi:lightbulb-group
                show_icon: true
                scrolling_effect: false
                show_name: true
                close_action:
                  action: navigate
                  navigation_path: '#schlafen_pop'
                entity: light.deckenleuchte_schlafen_2
                card_layout: large
                margin_top_mobile: calc(100vh - 600px)
              - type: custom:bubble-card
                card_type: separator
                name: ''
                icon: ''
                card_layout: large
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_deckenfluter_schlafen
                name: Deckenfluter
                card_layout: large
                icon: mdi:wall-sconce-flat
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_1_schlafen
                name: Spot 1
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_2_schlafen
                name: Spot 2
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_3_schlafen
                name: Spot 3
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_centris_spot_4_schlafen
                name: Spot 4
                card_layout: large
                icon: mdi:lightbulb-spot
                sub_button: []
                scrolling_effect: false
            grid_options:
              columns: full
    badges:
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        color: state
        entity: weather.openweathermap
        state_content:
          - state
          - temperature
          - humidity
          - wind_speed
        show_entity_picture: false
    type: sections
    max_columns: 2
    subview: false
    cards: []
    background:
      opacity: 70
      alignment: center
      size: cover
      repeat: no-repeat
      attachment: fixed
      image: /api/image/serve/ba2af0fb4fb98974ae658f990e486827/original
    icon: mdi:home
    visible:
      - user: f0c9f1692726480cbe816b63cf25ee54
      - user: 1d2e64cf434241139e8dc8e157940468
      - user: 9a2ba050f5434a638284ee0af2162aa4
      - user: 049c647d93d04e2e88206aac3ae1d95b
  - type: sections
    max_columns: 4
    title: Netzwerk
    path: netzwerk
    subview: true
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Neuer Abschnitt
    icon: mdi:network
    cards: []

```

 - OS: iOS 
 - Browser/App: Companion App
 - Bubble Card version: 2.3.4 / 2.4.0
 - Home Assistant version:
Core
2025.1.4
Supervisor
2024.12.3
Operating System
14.2
Frontend
20250109.2
