### ISSUE TITLE
Buttom row blocked by horizontal-button-stack

### ISSUE THREAD

**Issue by jenssvedlund** [Clooos/Bubble-Card#12]
When using the horizontal-button-stack it will block the last row as you can't scroll past it.
![image](https://github.com/Clooos/Bubble-Card/assets/128328187/b0fac082-a23b-4cc0-b186-053522055db1)

**Comment by agrestisdavid** [comment]
what is your code for the horizontal-button-stack?

**Comment by Clooos** [comment]
On my dashboard I have an invisible card right at the top of my horizontal buttons stack, it's how I've fixed it. But I will look if there is something I can do to fix that without adding an other card.

**Comment by jenssvedlund** [comment]
If this is what you meant it didn't make difference:

```
title: Home
views:
  - title: Home
    path: bubble
    badges: []
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: weather
            entity: weather.forecast_home
            show_conditions: true
            show_temperature: true
        alignment: center
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Hus
            icon: mdi:home
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-entity-card
                entity: sensor.faktist_manadskostnad
                name: Elkostnad
                icon: mdi:currency-usd
                layout: horizontal
                icon_color: green
              - type: custom:mushroom-entity-card
                entity: sensor.energyconsumption_month
                name: Elförbrukning
                icon: mdi:lightning-bolt-outline
                layout: horizontal
                icon_color: primary
          - type: custom:mushroom-vacuum-card
            entity: vacuum.robocock_s6_maxv
            commands:
              - on_off
              - start_pause
              - stop
              - return_home
            icon_animation: true
            fill_container: false
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Information
            icon: mdi:information
          - type: custom:mushroom-entity-card
            entity: sensor.postnord_delivery_72233
            name: Postnord Nästa leverans
          - type: custom:mushroom-entity-card
            entity: sensor.3d_skrivare_status
            name: 3D Skrivare
            icon: mdi:printer-3d-nozzle
      - type: vertical-stack
          - type: custom:bubble-card
            card_type: separator
            name: Belysning
            icon: mdi:lightbulb
          - type: custom:bubble-card
            card_type: button
            icon: mdi:lightbulb-group
            name: Inomhusbelysning
            entity: light.all_inomhusbelysning
          - type: custom:bubble-card
            card_type: button
            icon: mdi:lightbulb-group
            name: Utomhusbelysning
            entity: light.utomhusbelysning
      - type: custom:bubble-card
        card_type: horizontal-buttons-stack
        1_name: Vardagsrum
        1_icon: mdi:sofa
        1_link: '#vardagsrum'
        2_name: TV Rum
        2_icon: mdi:television
        2_link: '#tvroom'
        3_name: Sovrum
        3_icon: mdi:bed
        3_link: '#bedroom'
        1_entity: light.fonstersmyg_2
        2_entity: media_player.lg_webos_tv_oled65c9pla
        3_entity: light.sovrum_taklampa_light
        4_name: Tvättstuga
        4_icon: mdi:washing-machine
        4_link: '#laundry'
        4_entity: light.tvattstuga_light
        5_icon: mdi:door
        5_name: Dörrar
        5_link: '#doors'
        5_entity: binary_sensor.alla_dorrar_status
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#vardagsrum'
            icon: mdi:sofa
            name: Vardagsrum
            margin_top: 50px
          - type: custom:bubble-card
            card_type: separator
            name: Belysning
            icon: mdi:lightbulb
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.spottar_kok
            icon: mdi:lightbulb-spot
            name: Spottar
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.fonstersmyg_2
            icon: mdi:lightbulb
            name: Smygbelysning
          - type: custom:bubble-card
            card_type: button
            button_type: switch
            entity: light.kokslampor_light
            icon: mdi:lightbulb
            name: Kökslampor
          - type: custom:bubble-card
            card_type: separator
            name: Gardiner
            icon: mdi:curtains
          - type: grid
            cards:
              - type: custom:state-switch
                entity: template
                template: >-
                  {% if state_attr('cover.gardiner_vardagsrum_stora_fonster',
                  'current_position') < 8 %} Stängd {% else %} Öppna {% endif %}
                states:
                  Stängd:
                    type: button
                    icon: mdi:curtains-closed
                    title: Gardiner
                    show_icon: true
                    show_name: true
                    name: Framsida
                    tap_action:
                      action: call-service
                      service: script.turn_on
                      target:
                        entity_id: script.vardagsrum_oppna_gardiner_stora_fonster
                      data: {}
                      entity: script.vardagsrum_oppna_gardiner_stora_fonster
                  Öppna:
                    type: button
                    icon: mdi:curtains
                    title: Gardiner
                    show_icon: true
                    show_name: true
                    name: Framsida
                    tap_action:
                      action: call-service
                      service: script.turn_on
                      target:
                        entity_id: script.vardagsrum_stang_gardiner_stora_fonster
                      data: {}
                      entity: script.vardagsrum_stang_gardiner_stora_fonster
              - type: custom:state-switch
                entity: template
                template: >-
                  {% if state_attr('cover.gardiner_vardagsrum_kortsida',
                  'current_position') < 8 %} Stängd {% else %} Öppna {% endif %}
                states:
                  Stängd:
                    type: button
                    icon: mdi:curtains-closed
                    title: Gardiner
                    show_icon: true
                    show_name: true
                    name: Kortsida
                    tap_action:
                      action: call-service
                      service: script.turn_on
                      target:
                        entity_id: script.vardagsrum_oppna_gardiner_kortsida
                      data: {}
                      entity: script.vardagsrum_oppna_gardiner_kortsida
                  Öppna:
                    type: button
                    icon: mdi:curtains
                    title: Gardiner
                    show_icon: true
                    show_name: true
                    name: Kortsida
                    tap_action:
                      action: call-service
                      service: script.turn_on
                      target:
                        entity_id: script.vardagsrum_stang_gardiner_kortsida
                      data: {}
                      entity: script.vardagsrum_stang_gardiner_kortsida
            columns: 2
          - type: custom:bubble-card
            card_type: separator
            name: Media
            icon: mdi:television
          - type: custom:mushroom-media-player-card
            entity: media_player.samsung_au9075_55_tv
            fill_container: false
            media_controls:
              - on_off
            volume_controls:
              - volume_set
              - volume_buttons
              - volume_mute
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#doors'
            name: Dörrar
            icon: mdi:door
            margin_top: 50px
          - type: custom:bubble-card
            card_type: separator
            name: Entréer
          - type: custom:mushroom-lock-card
            entity: lock.huvudentre
            name: Huvudentre
            layout: horizontal
            fill_container: false
          - type: custom:bubble-card
            card_type: separator
            name: Alltan
          - type: custom:mushroom-entity-card
            entity: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_3
            layout: horizontal
            fill_container: false
            name: Framsida
          - type: custom:mushroom-entity-card
            entity: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2
            layout: horizontal
            fill_container: false
            name: Kortsida
          - type: custom:mushroom-entity-card
            entity: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
            layout: horizontal
            fill_container: false
            name: Baksida
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#tvroom'
            icon: mdi:television
            name: TV rum
            margin_top: 50px
          - type: custom:bubble-card
            card_type: separator
            name: Belysning
            icon: mdi:lightbulb
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.fonstersmyg
            icon: mdi:lightbulb
            name: Smygbel
          - type: custom:bubble-card
            card_type: separator
            name: Media
            icon: mdi:television
          - type: custom:mushroom-media-player-card
            entity: media_player.lg_webos_tv_oled65c9pla
            fill_container: false
            media_controls:
              - on_off
            volume_controls:
              - volume_set
              - volume_buttons
              - volume_mute
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#bedroom'
            icon: mdi:bed
            name: Sovrum
            margin_top: 50px
          - type: custom:bubble-card
            card_type: separator
            name: Belysning
            icon: mdi:lightbulb
          - type: custom:bubble-card
            card_type: button
            button_type: switch
            entity: light.sovrum_taklampa_light
            icon: mdi:lightbulb
            name: Taklampa
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: Styrka
            icon: mdi:lightbulb-on-20
            entity: light.sovrum_taklampa_styrka_light
          - type: custom:bubble-card
            card_type: separator
            name: Media
            icon: mdi:television
          - type: custom:mushroom-media-player-card
            entity: media_player.tv_sovrum_2
            fill_container: false
            media_controls:
              - on_off
            volume_controls:
              - volume_set
              - volume_buttons
              - volume_mute
            name: TV
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#laundry'
            icon: mdi:television
            name: Tvättstuga
            margin_top: 50px
          - type: custom:bubble-card
            card_type: separator
            name: Belysning
            icon: mdi:lightbulb
          - type: custom:bubble-card
            card_type: button
            button_type: switch
            entity: light.tvattstuga_light
            icon: mdi:lightbulb
            name: Taklampa
```
