### ISSUE TITLE
Weather temperature hidden when 0

### ISSUE THREAD

**Issue by HyperCriSiS** [Clooos/Bubble-Card#1213]
Hi, 
Last night I wondered why the temperature attribute was not shown anymore.
Turns out it was because the temperature was 0°C 😅

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
button_type: state
name: Wetter
icon: ""
show_icon: true
show_name: false
show_attribute: true
sub_button:
  - name: "Verbindung "
    show_state: true
    entity: binary_sensor.f0tzb0x_verbindung
    state_background: false
    show_background: false
    tap_action:
      action: navigate
      navigation_path: "#router"
  - show_background: false
    show_icon: true
    show_name: false
    entity: sensor.zeit_in_prozent_bis_jahresende
    show_state: true
    icon: mdi:timer-sand
  - name: Download
    show_last_changed: false
    show_state: true
    icon: mdi:download
    show_background: false
    entity: sensor.download_geschwindigkeit_dynamisch
  - icon: mdi:upload
    name: Upload
    show_state: true
    show_background: false
    show_icon: true
    entity: sensor.upload_geschwindigkeit_dynamisch
styles: |-
  .bubble-button-card-container .state {
          display: inline-flex;
          white-space: nowrap; /* Verhindert Umbruch */
          align-items: center;
   }

  .bubble-name-container, .bubble-state {
          margin: 0; /* Entfernt unnötige Abstände */
          white-space: nowrap;
   }

  .bubble-state {
          margin-left: 4px; /* Leicht anpassen für saubere Anzeige */
          font-size: 14px; /* Optimale Größe für Mobilgeräte */
   }


  .bubble-button-card-container {
       background: none;
       margin-left: 0px;
       margin-right: 0px;
   }

  .bubble-icon-container {
    background: none;
    border-radius: 0;
   }

  .bubble-sub-button-container{
          position: absolute;
          right: anchor(left);
          margin-left: 195px;
   }

  .bubble-sub-button-3{
    position: absolute;
    top: anchor(top, 0px);
    right: anchor(left);
    margin-left: 85px;
  }

  .bubble-sub-button-4{
    position: absolute;
    bottom: anchor(bottom, 0px);
    right: anchor(left);
    margin-left: 85px;
  }
scrolling_effect: false
entity: weather.heilbronn
show_state: true
card_layout: large-2-rows
tap_action:
  action: navigate
  navigation_path: "#wetter"
button_action:
  tap_action:
    action: navigate
    navigation_path: "#wetter"
force_icon: false
show_last_changed: false
attribute: temperature

```

**Informations (please complete the following information):**  
 - OS: Android 
 - Browser/App: HA App
 - Bubble Card version: [e.g. 2.4.0]
 - Home Assistant version: 2025.2.0
