### ISSUE TITLE
Rato of height and width of an background-image

### ISSUE THREAD

**Issue by Gordon746** [Clooos/Bubble-Card#1216]
I use a cover-button with Subbuttons, but want to replace the icons by an image. This works:
```yaml
.bubble-sub-button-2 {
      background-image: url("/local/pictures/lamelle_offen.svg");
      background-size: contain;
      background-repeat: no-repeat;
      background-position: center;
      border-radius: 50%;      
      ha-icon {
       color: transparent! important;
       }
}
```
Adding a border though by
```yaml
      border-style: solid;
      border-color: red;
      border-width: 4px;
```
stretches the background-image in the horizontal dimensions (the height remains constant)

<img width="457" alt="Image" src="https://github.com/user-attachments/assets/b0bc0cd0-030c-4248-b299-dff7062704b3" />

**Expected behavior**  
Maybe it's not a bug but a bad coding of mine? Anyways, I can prevent the stretching by adding 'width 1px':
```yaml
  ha-icon {
       color: transparent! important;
       width: 1px;
      }
```

<img width="480" alt="Image" src="https://github.com/user-attachments/assets/0b7f253a-f17e-4bc9-bc60-b818f359c1f5" />

**YAML**  
So this code works, but I don't know weather this is future proof:

```yaml
  .bubble-sub-button-2 {
      background-image: url("/local/pictures/lamelle_offen.svg");
      background-size: contain;
      background-repeat: no-repeat;
      background-position: center;
      border-radius: 50%;      
      border-style: solid;
      border-color: red;
      border-width: 8px;
      ha-icon {
       color: transparent! important;
       width: 1px;
      }
}
```

Thank you very much! 🍻
