### ISSUE TITLE
Button only showup in dashboard during editing

### ISSUE THREAD

**Issue by plummm** [Clooos/Bubble-Card#1223]
**Describe the bug**  
I try to create a test pop up, I can see the pop up when editing

But once I click `done`, it won't showup in the the dashboard.

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#test"
    button_type: switch
    name: My popup
    auto_close: ""
  - type: sensor
    entity: sensor.system_monitor_disk_free
    graph: line
title: Test popup
```

**To Reproduce**  
Following the step above

**Screenshots**  
It shows up in editing
<img width="470" alt="Image" src="https://github.com/user-attachments/assets/a0bf3d63-1466-4958-90c5-145e11cb0a49" />

But disappear when click done
<img width="465" alt="Image" src="https://github.com/user-attachments/assets/d0eee659-0468-44d3-abfe-a8b6e716de27" />

**YAML**  
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#test"
    button_type: switch
    name: My popup
    auto_close: ""
  - type: sensor
    entity: sensor.system_monitor_disk_free
    graph: line
title: Test popup
```

**Informations (please complete the following information):**  
 - OS: MacOS
 - Browser/App: Chrome
 - Bubble Card version: 2.4.0
 - Home Assistant version: 
Core 2025.2.1
Supervisor 2025.02.0
Operating System 14.2
Frontend 20250205.0

**Additional context**  

Thank you! 🍻
