### ISSUE TITLE
High CPU usage when using custom styles and custom style compatibility issues

### ISSUE THREAD

**Issue by xiayesuifeng** [Clooos/Bubble-Card#1236]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
1. High CPU usage when using custom styles and very slow on mobile devices but not much on PC
2. My custom styles are broken after updating to v2.5.0-beta.1, and the problem remains in beta.2

I think one of the reasons for high CPU usage is the use of custom styles. On a separate dashboard, there is only a list of room cards and the corresponding pop-up cards. When using custom styles, the CPU usage can sometimes be as high as 35%. Without custom styles, it is much lower (10-14%), and it is much faster on mobile devices. My dashboard uses a lot of pop-up cards, and the CPU usage is even higher, 60%.

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
square: false
type: grid
cards:
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F1 大厅
    icon: mdi:sofa
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f1_livingroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: fan.211106241022386_fan
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f1-livingroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F2 客厅
    icon: mdi:sofa
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f2_livingroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: media_player.sony_xr_75x95el_2
        icon: mdi:youtube-tv
        tap_action:
          action: toggle
        hold_action:
          action: navigate
          navigation_path: "#f2-tv-remote"
      - entity: cover.dooya_f2_livingroom_balcony_cover
        icon: mdi:curtains
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        hold_action:
          action: more-info
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f2-livingroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F2 头房
    icon: mdi:bed
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f2_front_bedroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - icon: ""
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        hold_action:
          action: more-info
        entity: climate.f2_front_bedroom_climate
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f2-front-bedroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F2 尾房
    icon: mdi:bed
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f2_back_bedroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - icon: mdi:curtains
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        hold_action:
          action: more-info
        entity: cover.dooya_f2_bedroom_2_cover
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f2-back-bedroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F3 客厅
    icon: mdi:sofa
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f3_livingroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: cover.f3_livingroom_covers
        icon: mdi:curtains
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        hold_action:
          action: more-info
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f3-livingroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F3 头房
    icon: mdi:bed
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f3_front_bedroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: cover.dooya_f3_front_bedroom_cover
        icon: mdi:curtains
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        hold_action:
          action: more-info
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f3-front-bedroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F3 尾房
    icon: mdi:bed
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f3_back_bedroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: cover.f3_back_bedroom_covers
        icon: mdi:curtains
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        hold_action:
          action: more-info
      - entity: climate.f3_wei_fang_leng_qi
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f3-back-bedroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: F4 客厅
    icon: mdi:bed
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f4_livingroom_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f4-livingroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: 客房
    icon: mdi:bed
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f4_guest_room_lights
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#f4-guestroom"
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: 家庭影院
    icon: mdi:youtube-tv
    show_icon: true
    show_name: true
    scrolling_effect: true
    card_layout: normal
    styles: |
      .bubble-button-card-container {
        height: 100px;
      }

      .bubble-button-card,
      .bubble-range-slider,
      .bubble-button-background {
        flex-wrap: wrap;
      }

      .bubble-sub-button-container {
        justify-content: center;
        width: 100%;
        bottom: 8px;
        left: 0px;
      }
    sub_button:
      - entity: light.f4_home_cinema_lights_fully_on_off
        name: ""
        show_name: false
        show_background: true
        icon: mdi:lightbulb-group
        tap_action:
          action: toggle
      - entity: cover.dooya_f4_home_cinema_cover
        icon: mdi:curtains
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        hold_action:
          action: more-info
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#home-cinema"
columns: 2
title: 区域
```
dashboard yaml
https://pastebin.com/gUHKi4Bu

**Informations (please complete the following information):**  
 - OS: ArchLinux
 - Browser/App: chromium
 - Bubble Card version: 2.5.0-beta.2
 - Home Assistant version: 2025.2.1

**Additional context**  
use styles
![Image](https://github.com/user-attachments/assets/99bf9836-52b6-411b-98e5-bfb8cef3ed4a)
no use styles
![Image](https://github.com/user-attachments/assets/a1a506a8-1fc8-49de-b098-c1ff66d85d20)

![Image](https://github.com/user-attachments/assets/b1dba876-3b4e-467d-a4f1-dc251c6872bb)

https://github.com/user-attachments/assets/3fcbba70-03f1-4a65-a8c5-129e9b94a0a6

After v2.5.0-bate.1 update

![Image](https://github.com/user-attachments/assets/c3c8cb31-3d7b-4e30-8f83-124e0f5819c5)

Before v2.5.0-bate.1 update

![Image](https://github.com/user-attachments/assets/ea103078-50d1-447a-81ac-ccb5918e91ae)

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! Have you tried the latest v2.5.0-beta.4 for your styling issues?

And for your CPU issue, you should try to move most of your custom styles into modules, or directly under `default:` in the `bubble-modules.yaml` file. This should improve performance a lot 🙂

**Comment by xiayesuifeng** [comment]
The style issue has been fixed since v2.5.0-beta.3. The high CPU usage issue has existed for months, long before v2.3.0

**Comment by Clooos** [comment]
This is weird, because you seem to only have simple custom styles. I will check if I can't optimize that for custom styles without templates.

**Comment by Clooos** [comment]
Do you have card-mod installed? Someone said recently that he fixed his performance issue by removing it.

And good to know for the higher CPU usage in the latest beta, I will revert some code then 👌

**Comment by xiayesuifeng** [comment]
I have card-mod v3.4.0 installed, I've tried removing it but it didn't change anything

**Comment by xiayesuifeng** [comment]
There is also a bit of lag when editing. Clicking Save will be stuck for a long time. In fact, it has been saved soon and it is still spinning. Force F12 has taken effect. Because I don't edit often, I don't know which version started. A previous version was normal.

**Comment by Clooos** [comment]
You seems to have a lot of errors with Apex charts, I don't see any errors from Bubble Card in these logs.

**Comment by xiayesuifeng** [comment]
I think this is not a problem caused by apexcharts. After uninstalling apexcharts, the problem still exists.

**Comment by xiayesuifeng** [comment]
When I remove these three cards from the dashboard, the speed of popping up cards will increase. The entity part corresponding to the sub-button of this card may be updated very quickly, once a second. Is it a performance problem caused by the entity updating too quickly?

![Image](https://github.com/user-attachments/assets/1eec6832-3ec8-4f3f-81a1-60b91003ed56)

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: button
    button_type: state
    entity: weather.he_feng_tian_qi
    show_name: true
    show_state: true
    card_layout: large-2-rows
    grid_options:
      columns: full
    sub_button:
      - name: 湿度
        show_icon: false
        show_background: false
        show_name: true
      - name: ""
        entity: weather.he_feng_tian_qi
        attribute: humidity
        show_state: false
        show_attribute: true
        show_icon: false
        show_background: false
      - name: 云量
        show_icon: false
        show_background: false
        show_name: true
      - name: ""
        entity: weather.he_feng_tian_qi
        attribute: cloud_coverage
        show_state: false
        show_attribute: true
        show_icon: false
        show_background: false
      - name: 风向
        show_icon: false
        show_background: false
        show_name: true
      - name: ""
        entity: weather.he_feng_tian_qi
        attribute: wind_bearing
        show_state: false
        show_attribute: true
        show_icon: false
        show_background: false
      - name: 风速
        show_icon: false
        show_background: false
        show_name: true
      - name: ""
        entity: weather.he_feng_tian_qi
        attribute: wind_speed
        show_state: false
        show_attribute: true
        show_icon: false
        show_background: false
      - name: 室温
        entity: sensor.room_temperature
        show_state: true
        show_attribute: false
        show_background: false
        icon: mdi:home-thermometer-outline
        tap_action:
          action: more-info
        show_name: true
      - name: 室外
        entity: weather.he_feng_tian_qi
        show_state: false
        icon: mdi:thermometer
        show_attribute: true
        attribute: temperature
        show_background: false
        tap_action:
          action: more-info
        show_name: true
        show_icon: true
    name: 天气
  - type: custom:bubble-card
    card_type: button
    button_type: state
    card_layout: large-2-rows
    name: 能源
    entity: sensor.mppt_pv_total_power
    icon: mdi:home-lightning-bolt-outline
    show_state: true
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#energy"
    sub_button:
      - entity: sensor.solar_system_module_ac_output_power
        icon: mdi:counter
        show_background: false
        show_state: true
        tap_action:
          action: more-info
      - entity: sensor.mppt_total_daily_charging_energy
        show_state: true
        show_background: false
      - entity: sensor.solar_system_module_inverter_output_mode
        show_background: false
        show_state: true
      - entity: sensor.mppt_total_week_charging_energy
        show_state: true
        show_background: false
        icon: mdi:calendar-week
    styles: ""
    layout_options:
      grid_columns: 4
      grid_rows: 1
  - type: custom:bubble-card
    card_type: button
    button_type: state
    card_layout: large-2-rows
    name: 热水器
    entity: sensor.water_heater_currenttemperature
    icon: mdi:thermometer-water
    show_state: true
    button_action:
      tap_action:
        navigation_path: "#energy"
        action: none
    sub_button:
      - icon: mdi:thermometer
        show_background: false
        show_state: true
        tap_action:
          action: more-info
        entity: number.water_heater_targettemperature
        name: ""
        show_attribute: false
        show_icon: true
      - entity: sensor.zero_cold_water_system_1_water_temperature
        show_state: true
        show_background: false
      - show_background: false
        show_state: true
        entity: sensor.water_heater_workstatus
        show_icon: true
        icon: mdi:list-status
      - entity: sensor.zero_cold_water_system_1_status
        show_background: false
        show_name: false
        show_icon: true
        show_attribute: true
        show_last_changed: false
        show_state: true
        icon: mdi:list-status
      - entity: switch.water_heater_onoffstatus
        icon: mdi:power
        show_name: true
        name: 热水器
        tap_action:
          action: toggle
      - entity: switch.zero_cold_water_system_switch_circulation_pump
        show_state: false
        show_background: true
        icon: mdi:power
        name: 循环泵
        show_name: true
        tap_action:
          action: toggle
    styles: ""
    show_attribute: false
```
