### ISSUE TITLE
attribute: icon

### ISSUE THREAD

**Issue by Quokka1979** [Clooos/Bubble-Card#1241]
![Image](https://github.com/user-attachments/assets/31e21f72-eeda-4bcd-9ed4-f10080022c61)

```
style_templates:
  - get_state_attribute
get_state_attribute:
  - entity: light.lights_kitchen
    attribute: brightness
  - entity: sensor.count_lights_kitchen
    attribute: icon
```

I expected that 'attribute: icon' shows the icon, instead of the name of the icon that is used
