### ISSUE TITLE
double_tap_action on sub button in separator not working

### ISSUE THREAD

**Issue by kimzeuner** [Clooos/Bubble-Card#1250]
**Describe the bug**  
The double_tap_action for a sub button is not working in a separator.

**To Reproduce**  
1. define double_tap_action (here "toggle" but all other actions are also not working) in a sub button
2. double tap on the sub button, nothing happens
3. define the same action for tap_action or hold_action on the same sub button is working

**Expected behavior**  
Toggle the light on/off when double tapping on the sub button

**Screenshots**  
none

**YAML**  

double_tap_action not working:
```yaml
type: custom:bubble-card
card_type: separator
name: Küche
icon: mdi:knife
card_layout: large
sub_button:
  - entity: light.licht_kuche
    show_attribute: false
    state_background: false
    show_background: false
    show_state: false
    tap_action:
      action: none
    double_tap_action: 
      action: toggle
    hold_action:
      action: none
  - entity: binary_sensor.alle_fenster_kuche
    state_background: false
    show_background: false
    show_state: false
    tap_action:
      action: none
    double_tap_action:
      action: navigate
      navigation_path: /dashboard-kim/fenster
  - entity: climate.fussbodenheizung_kueche_template
    show_attribute: true
    attribute: current_temperature
    state_background: false
    show_background: false
    show_state: false
    show_icon: false
    tap_action:
      action: none
    double_tap_action:
      action: navigate
      navigation_path: /dashboard-kim/heizung-kueche
styles: |
  .bubble-icon {
    margin: 0px 15px;
  }
  .bubble-name { 
    font-size: 24px;
    font-weight: normal !important;
  }
  .large .bubble-line {
    opacity: 0 !important;
  }
  .bubble-sub-button {
    justify-self: center !important;
    min-width: 10px !important;
  }
  .bubble-sub-button-2 {
    padding: 0px !important;
  }
  .bubble-sub-button-1 > ha-icon {
    color: ${hass.states['light.licht_kuche'].state === 'on' ? 'yellow' : ''} !important;
  }
  .bubble-sub-button-3 {
     font-size: 20px;
     font-weight: semi-bold;
     justify-self: right !important;
  }
  .bubble-sub-button-1 {
    padding: 0px !important;
  }

```

tap_action working (everything else is the same):
```yaml
type: custom:bubble-card
card_type: separator
name: Küche
icon: mdi:knife
card_layout: large
sub_button:
  - entity: light.licht_kuche
    show_attribute: false
    state_background: false
    show_background: false
    show_state: false
    tap_action:
      action: toggle
    double_tap_action: 
      action: none
    hold_action:
      action: none
  - entity: binary_sensor.alle_fenster_kuche
    state_background: false
    show_background: false
    show_state: false
    tap_action:
      action: none
    double_tap_action:
      action: navigate
      navigation_path: /dashboard-kim/fenster
  - entity: climate.fussbodenheizung_kueche_template
    show_attribute: true
    attribute: current_temperature
    state_background: false
    show_background: false
    show_state: false
    show_icon: false
    tap_action:
      action: none
    double_tap_action:
      action: navigate
      navigation_path: /dashboard-kim/heizung-kueche
styles: |
  .bubble-icon {
    margin: 0px 15px;
  }
  .bubble-name { 
    font-size: 24px;
    font-weight: normal !important;
  }
  .large .bubble-line {
    opacity: 0 !important;
  }
  .bubble-sub-button {
    justify-self: center !important;
    min-width: 10px !important;
  }
  .bubble-sub-button-2 {
    padding: 0px !important;
  }
  .bubble-sub-button-1 > ha-icon {
    color: ${hass.states['light.licht_kuche'].state === 'on' ? 'yellow' : ''} !important;
  }
  .bubble-sub-button-3 {
     font-size: 20px;
     font-weight: semi-bold;
     justify-self: right !important;
  }
  .bubble-sub-button-1 {
    padding: 0px !important;
  }

```

**Informations (please complete the following information):**  
 - OS: windows/ios
 - Browser/App: chrome/ios app
 - Bubble Card version: v2.5.0-beta.5
 - Home Assistant version: 2025.2.4

**Additional context**  
not sure if this was already a problem in previous versions as i just created this separator after the release of beta 5
*edit: just tried all beta versions from v2.5.0 and it is working in none of them. In version v2.4.0 the double_tap_action works.
