### ISSUE TITLE
double_tap_action on button not working

### ISSUE THREAD

**Issue by fellipute** [Clooos/Bubble-Card#1258]
**Describe the bug**  
The button_action -> double_tap_action is not working on buttons using bubble-card.

**To Reproduce**  
Use the YAML below.

**Expected behavior**  
Double click should work.

**Screenshots**  

![Image](https://github.com/user-attachments/assets/100da99b-40e9-4143-b8e2-1bc521d43079)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: button
entity: group.luzes_sala
name: Sala
icon: mdi:sofa-outline
show_last_changed: true
card_layout: large
columns: 2
sub_button:
  - icon: mdi:menu
    state_background: false
    show_background: false
    show_attribute: false
    tap_action:
      action: navigate
      navigation_path: "#sala"
styles: |
  .bubble-icon-container {
      background: #F23A74
  }

  .bubble-button-background {
    opacity: 1 !important;
    background-color: ${state === 'on' ? '#E60F53' : ''} !important;
  }

  .bubble-icon {
    color: white !important;
  }
button_action:
  tap_action:
    action: none
  double_tap_action:
    action: toggle
  hold_action:
    action: none
double_tap_action:
  action: toggle
tap_action:
  action: none
hold_action:
  action: none
style_templates:
  - get_state_attribute
get_state_attribute:
  - entity: sensor.sala_temperatura

```

**Informations (please complete the following information):**  
 - OS: windows / android
 - Browser/App: chrome
 - Bubble Card version: v2.5.0-beta5
 - Home Assistant version: 2025.2.4
