### ISSUE TITLE
2.50 b1/5 breaks attributes in sub-buttons

### ISSUE THREAD

**Issue by rononline** [Clooos/Bubble-Card#1264]
Beta2.5 breaks for me attributes in sub-buttons.

```
type: custom:bubble-card
card_type: button
button_type: state
entity: weather.combined
name: Weer in Barendrecht
icon: " "
show_state: true
scrolling_effect: false
card_layout: large-2-rows
sub_button:
  - name: Min
    icon: mdi:thermometer-low
    entity: sensor.weather_forecast_daily
    attribute: forecast[0].templow
    show_background: false
    show_attribute: true
    tap_action:
      action: navigate
      navigation_path: weer
  - name: Wind
    icon: mdi:weather-windy
    entity: sensor.weather_forecast_daily
    attribute: forecast[0].wind_speed
    show_background: false
    show_attribute: true
    show_icon: true
    tap_action:
      action: navigate
```

![Image](https://github.com/user-attachments/assets/591ecd77-2263-41bd-8259-418daa2d82b7)

and in 2.40:

![Image](https://github.com/user-attachments/assets/9475e559-89b6-4cfc-b63c-132e34b659ac)
