### ISSUE TITLE
2.5.0 beta 6 - sub-button row - Space between first and second sub-button

### ISSUE THREAD

**Issue by amstermk** [Clooos/Bubble-Card#1270]
I‘m using the sub-button row from the examples on git-hub. With the new beta there is space added between first and second button:

![Image](https://github.com/user-attachments/assets/f6845e16-a4b3-4c4e-8a78-41b9b1422023)

**Comment by Clooos** [comment]
Hi! You're right, I use it as well and you need to use these custom styles now:

```css
.card-content {
  width: 100%;
  margin: 0 !important;
}

.bubble-container {
  background: none;
  border: none;
}

.bubble-sub-button {
  height: 46px !important;
  width: 46px !important;
}

.bubble-sub-button-container {
  display: flex !important;
  width: 100%;
  justify-content: space-between !important;
}

.bubble-sub-button-icon {
  --mdc-icon-size: inherit !important;
}

.bubble-name-container {
  margin-right: 0px !important;
}
```
