### ISSUE TITLE
Layout changes do not resize card in 2.5.0 beta7

### ISSUE THREAD

**Issue by davidepanato** [Clooos/Bubble-Card#1273]
**Describe the bug**  
I just installed beta 7 and layout feature seems to be not working. I already cleared the cache and reinstalled bubble card multiple times. Issue is reproducible on multiple browsers on different systems

**To Reproduce**  
install bubble card 2.5.0 beta 7
add a new bubble card in any dashboard and try to change the layout.

**Expected behavior**  
layout change should modify card aspect

**Screenshots**  

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/65ffe530-067a-4469-87d6-a9be434630bc" />

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
entity: automation.ulanzi_night_mode
grid_options:
  columns: 12
  rows: 4
sub_button:
  - entity: automation.ulanzi_night_mode
  - entity: automation.ulanzi_night_mode
modules:
  - default
```

**Informations (please complete the following information):**  
 - OS: macOS + iOS + windows 11
 - Browser/App: chrome/safari/safari mobile
 - Bubble Card version: [e.g. 2.5.0 beta 7
 - Home Assistant version: [e.g. 2025.2.4

Thank you! 🍻

**Comment by DerHerzog7** [comment]
Ah yeh I just posted on the subreddit. Same here. 

![image](https://github.com/user-attachments/assets/2889be75-f2f7-493e-9219-a80258219680)

**Comment by Clooos** [comment]
Hi! Can you check the Bubble Card version at the bottom of the editor?

**Comment by davidepanato** [comment]
It says 2.5.0 beta 7
![image](https://github.com/user-attachments/assets/ebf00a1e-044b-4004-aef6-4f74f0735270)

**Comment by MrBearPresident** [comment]
@davidepanato 
You have to select large layout. 
`card_layout: large`

![Image](https://github.com/user-attachments/assets/1ed1858b-b136-43e1-9838-b18fb582fcf0)

**Comment by MrBearPresident** [comment]
@DerHerzog7 
> Ah yeh I just posted on the subreddit. Same here.

Could you post your yaml?

**Comment by davidepanato** [comment]
@MrBearPresident i tested with large and it works! I think you should just update the doc to highlight the dependency.

Thanks 
Davide

**Comment by Clooos** [comment]
@MrBearPresident Is there any downside to add the multiple rows to all layouts by default?

**Comment by DerHerzog7** [comment]
> @DerHerzog7 
> > Ah yeh I just posted on the subreddit. Same here.
> 
> Could you post your yaml?
> 

: custom:bubble-card
card_type: button
entity: light.bedroom_3
name: Bedroom
icon: hue:room-bedroom
tap_action:
  action: toggle
double_tap_action:
  action: more-info
hold_action:
  action: more-info
button_type: slider
card_layout: large
sub_button:
  - icon: mdi:menu
    show_background: false
    show_name: false
    tap_action:
      action: navigate
      navigation_path: "#bedroom"
show_attribute: false
show_last_changed: true
show_state: true
scrolling_effect: true
grid_options:
  columns: 12
  rows: 4

**Comment by DerHerzog7** [comment]
> @DerHerzog7 
> > Ah yeh I just posted on the subreddit. Same here.
> 
> Could you post your yaml?
> 

```

: custom:bubble-card
card_type: button
entity: light.bedroom_3
name: Bedroom
icon: hue:room-bedroom
tap_action:
  action: toggle
double_tap_action:
  action: more-info
hold_action:
  action: more-info
button_type: slider
card_layout: large
sub_button:
  - icon: mdi:menu
    show_background: false
    show_name: false
    tap_action:
      action: navigate
      navigation_path: "#bedroom"
show_attribute: false
show_last_changed: true
show_state: true
scrolling_effect: true
grid_options:
  columns: 12
  rows: 4
```
