### ISSUE TITLE
Dropdown in swipe-card

### ISSUE THREAD

**Issue by nehasjains** [Clooos/Bubble-Card#1282]
Dropdown items are not shown if used within swipe-card
```
type: custom:swipe-card
parameters:
  spaceBetween: 0
  effect: fade
  fadeEffect:
    crossFade: true
  autoplay:
    delay: 5500
  speed: 5000
  pagination:
    type: none
cards:
  - type: custom:bubble-card
    card_type: select
    entity: input_select.speaker
    show_state: true
    show_name: false
  - type: custom:bubble-card
    card_type: select
    entity: input_select.podcasts
    show_state: true
    show_name: false
```
