### ISSUE TITLE
Icon style changes based on unrelated subbutton entity state

### ISSUE THREAD

**Issue by HenryJIII** [Clooos/Bubble-Card#1312]
I recentlly noticed that I have a button in my dashboard that slightly changes icon color based on the state of an unrelated subbutton entity

Subbutton entity is off
![Image](https://github.com/user-attachments/assets/ae4ec19d-e923-496f-95dc-089d3535c36f)

Subbutton entity is on
![Image](https://github.com/user-attachments/assets/422ce010-3c53-4074-8ce2-af0fc8278b25)

The icon in the second picture is whiter, than in the first, although the 2 entities used in the button and subbuttons are unrelated.

Weirdly that behaviour disappears when I add another subbutton with a media_player entity:
Subbutton entity is off

Subbutton entity is off
![Image](https://github.com/user-attachments/assets/9f7973e0-e66b-42d3-b379-8d2bd29c8b6d)

Subbutton entity is on
![Image](https://github.com/user-attachments/assets/dbee1ddc-b81e-413d-9a85-0b0018a4ff5d)

```yaml
{# Without Mediaplayer Entity #}
type: custom:bubble-card
entity: input_boolean.light_dummy
card_type: button
button_type: state
name: Test
icon: mdi:account
sub_button:
  - entity: light.wohnzimmertisch
    tap_action:
      action: toggle
modules:
  - default

{# With Mediaplayer Entity #}
type: custom:bubble-card
entity: input_boolean.light_dummy
card_type: button
button_type: state
name: Test
icon: mdi:account
sub_button:
  - entity: light.wohnzimmertisch
    tap_action:
      action: toggle
  - entity: media_player.wohnzimmer
modules:
  - default
```

**Informations (please complete the following information):**  
 - OS: Windows
 - Browser/App: Chrome
 - Bubble Card version: v2.5.0-beta.7
 - Home Assistant version: 2025.2.5
