### ISSUE TITLE
Timer entity in card doesn't update

### ISSUE THREAD

**Issue by yurividal** [Clooos/Bubble-Card#1324]
**Describe the bug**  
I have a timer that is set to 10 mins and starts (via autmoation) every time my light turns on.
I would like to display this timer inside the bubble card, when the light is on.
But, in bubble card, the timer doesn't update with the remaining time, it just shows the original time.

**To Reproduce**  
1. Add a timer helper
2. Create automation to start the timer when light turns on
3. Add timer as sub-button in bubble card
4. Show attribute on button, set it to "remaining"

**Expected behavior**  
Item should update every second, with remaining time in timer.

**Screenshots**  
Bubble card, stuck on 10:00 even though the timer is running:

![Image](https://github.com/user-attachments/assets/241e2b8a-7b80-456e-8003-15de5582f169)

Stock tile card, updates with remaining time, every seccond:

![Image](https://github.com/user-attachments/assets/11e3b514-8a42-4720-889c-99464287082a)

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
entity: light.pantry_light
name: Pantry
icon: mdi:wardrobe
scrolling_effect: true
grid_options:
  columns: 6
  rows: 1
show_state: true
show_attribute: false
tap_action:
  action: toggle
force_icon: false
use_accent_color: false
sub_button:
  - entity: timer.pantry_light_timer
    show_state: false
    state_background: false
    show_background: false
    visibility:
      - condition: state
        entity: light.pantry_light
        state: "on"
    show_attribute: true
    attribute: remaining
    show_icon: false
styles: >2-
    .bubble-button-background {
      opacity: ${state === 'on' ? '10%' : '0%'} !important;
      background-color: ${state === 'on' ? 'yellow' : 'white'} !important;
    }

    .bubble-icon {
      color: ${state === 'on' ? 'yellow' : ''} !important;
    }

  ${icon.setAttribute("icon", state === 'on' ? 'mdi:wardrobe' :
  'mdi:wardrobe-outline')}
    

```

**Informations (please complete the following information):**  
 - OS: All platforms
 - Browser/App: any
 - Bubble Card version: [e.g. 2.4.0]
 - Home Assistant version: [e.g. 2025.3]

Thank you! 🍻

**Comment by hitslc** [comment]
I'm experiencing something similar, with a pop-up and flip down timer card. IF "background_upate: false", the card only shows the original timer duration. If I set "background_update: true", then the card will countdown until I close the card. If I close the card or navigate to another page and then open the timer card popup again, the timer card shows whatever the remaining time is at that moment, but it does not update any further.

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#officealexatimerhome"
    show_header: false
    auto_close: ""
    trigger:
      - condition: state
        entity: input_boolean.office_alexa_timer_active
        state: "on"
    icon: ""
    name: ""
    show_state: true
    force_icon: false
    width_desktop: "90"
    hide_backdrop: false
    close_by_clicking_outside: false
    bg_blur: "0"
    bg_opacity: "0"
    shadow_opacity: "0"
    backdrop_blur: "0"
    margin_top_desktop: 20vh
    sub_button: []
    button_action:
      tap_action:
        action: toggle
    modules:
      - default
    slide_to_close_distance: ""
    close_on_click: true
    background_update: true
    trigger_close: true
  - type: custom:flipdown-timer-card
    entity: sensor.office_dot_next_timer
    show_hour: auto
    show_title: false
    show_header: false
    theme: light
    styles:
      rotor:
        width: 360px
        height: 250px
        fontsize: 18rem
    card_mod:
      style: |
        ha-card {
          background: transparent;
          box-shadow: none;
        }
grid_options:
  rows: 1
  columns: 12
```
