### ISSUE TITLE
Popup problem

### ISSUE THREAD

**Issue by nelsonamen** [Clooos/Bubble-Card#133]
The corners are white maybe a problem with the 
type: iframe in card?

![IMG_20231025_221059](https://github.com/Clooos/Bubble-Card/assets/5807434/cfda0434-ceee-4f0c-8160-2840258c512b)
![IMG_20231025_221111](https://github.com/Clooos/Bubble-Card/assets/5807434/3a6c7725-3f73-40cb-9480-6df1efc5f00b)
![IMG_20231025_221120](https://github.com/Clooos/Bubble-Card/assets/5807434/273ab72f-a3ac-4026-977c-b859aef2efad)

**Comment by nelsonamen** [comment]
Can you make a option for disable round corners?

**Comment by nelsonamen** [comment]
I have resolve in fully Kiosk browser 

Default Webview Background Color
Select default background color for the Webview

**Comment by nelsonamen** [comment]
![16983547241361814769115849063238](https://github.com/Clooos/Bubble-Card/assets/5807434/1f9fe926-e7b3-4515-8908-5dcbf5e12b1c)

**Comment by Clooos** [comment]
Hi and thanks for you feedback, you can change it directly in the pop-up yaml:
```yaml
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#your-pop-up'
    styles: |
      #root {
        border-radius: 0;
      }
```
