### ISSUE TITLE
Map- card shows wrong zoom level in pop-up-card

### ISSUE THREAD

**Issue by enedberg** [Clooos/Bubble-Card#1334]
**Describe the bug**  
I have a pop-up-card with a map card. The map works fine as a separate card, but in a pop-up it show with the wrong zoom level, completely zoomed out. I tried with background_update: true , tried placing the map inside another container (horizontal-stack), tried with no default-zoom, but the problem persists. I have also cleared my cache. Same problem on Mac and iPhone (browser and HA-app).

I have three other pop-up on the same dashboard, they work fine. I use sections on this dashboard and it is my default mobile dashboard.

I tried the same pop-up with the map on a different dashboard (using Masonry layout). It worked as expected there. Also, if I show only one entity on the map card it works as expected.

**To Reproduce**  
1. On a dashboard using sections: Add a vertical stack with a pop-up-card and a map card
2. Add more than one entity to the map
3. Click on whatever button opens the pop-up
4. Map is zoomed out

The map is shown correctly in the editor, and it _sometimes_ opens correctly after a refresh 

**Expected behavior**  
The map card should open with the correct zoom level

**Screenshots**  

<img width="605" alt="Image" src="https://github.com/user-attachments/assets/5199a1ff-84f0-4b0c-b17f-b8cdcbe7b08c" />

**YAML**  
This is the code for the vertical-stack with pop-up and map

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#pop-up-maps"
    show_header: false
    auto_close: "15000"
    background_update: false
  - type: map
    entities:
      - entity: person.e
      - entity: person.y
      - entity: person.i
      - entity: person.t
    theme_mode: light
    hours_to_show: 4
    default_zoom: 17
```

**Informations (please complete the following information):**  
 - OS: Tried on Mac and iPhone
 - Browser/App: Chrome, Safari and HA App
 - Bubble Card version: 2.4.0
 - Home Assistant version: 2025.3.3
