### ISSUE TITLE
(Sub) Buttons are not on the same line

### ISSUE THREAD

**Issue by GunterAv** [Clooos/Bubble-Card#1347]
Hello,

with version v2.5.0-beta.8 the sub buttons are no longer on the same line.
![Image](https://github.com/user-attachments/assets/131e0ec0-d395-4175-ad21-c07e865ca008)

```
type: custom:bubble-card
card_type: media-player
entity: media_player.wave_kueche_3
show_state: false
show_attribute: false
attribute: volume_level
show_name: true
show_icon: true
scrolling_effect: true
hide:
  play_pause_button: true
  volume_button: true
  previous_button: true
  next_button: true
  power_button: true
sub_button:
  - entity: media_player.wave_kueche_3
    name: Aus
    icon: mdi:power
    tap_action:
      action: call-service
      target: {}
      service: script.bose10_toggle
name: Bose Wave 10
modules: []
card_layout: normal
```
```
type: custom:bubble-card
card_type: button
button_type: slider
entity: media_player.wave_kueche_3
show_state: false
show_icon: false
show_last_changed: false
show_attribute: true
attribute: volume_level
name: Lautstärke
sub_button:
  - entity: switch.bose10mute
    show_state: false
    name: Mute
    tap_action:
      action: toggle
modules: []
card_layout: normal
```

Thanks
Gunter
