### ISSUE TITLE
[2.5.0-beta.8] After sliding, 2 clicks are needed to switch off slider button

### ISSUE THREAD

**Issue by infinicode** [Clooos/Bubble-Card#1348]
**Describe the bug**  
With the new sliders in 2.5.0-beta.8,  sometimes you need two "clicks" on the button to switch it off. This happens both on Mobile (Android) and Web, but it's more common on mobile (happens almost every time).

**To Reproduce**  
1. Slide one button (from off, or already in on state)
2. Click on the button to switch it off (it does not switch of)
3. Click again on the button to switch it off (it does switch of)

**Expected behavior**  
After sliding, if the button is clicked, it should switch off.

**Screenshots**  
[Screen capture](https://imgur.com/a/NnMDtAy)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: button
entity: light.tv_lamp
layout_options:
  grid_columns: 2
  grid_rows: 1
card_layout: large
name: Lamp TV
hold_action:
  action: more-info
button_type: slider
tap_action:
  action: toggle
icon: phu:ikea-paparlamp
modules:
  - default
tap_to_slide: false
step: 5
```

**Informations (please complete the following information):**  
 - OS: [Android 15]
 - Bubble Card version: [2.5.0-beta.8 ]
 - Home Assistant version: [2025.3.2]

Thank you! 🍻
