### ISSUE TITLE
several broken elements from beta 6 onwards

### ISSUE THREAD

**Issue by userdema** [Clooos/Bubble-Card#1350]
i can share before and after of my cards, describe the issues is more difficult that show these:

1-separators on top of my dashboard (are 2 cards)

before

![Image](https://github.com/user-attachments/assets/84611fa0-aea4-4796-9862-ad6e7c5c5f4c)

after

![Image](https://github.com/user-attachments/assets/76a4ea61-2286-48fb-82fc-d49477350b4e)

style:
1)
```yaml
.large .separator-container {
  height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
  overflow: hidden !important;
  position: relative !important;
  }
.bubble-line {
  position: relative !important;
  opacity: 0.2;
  }
.bubble-name {
  position: absolute;
  left: 0px !important;
  top: 0px;
  font-weight: 350;
  font-size: 14px;
  opacity: 0.2;
  }
.bubble-icon {
  position: absolute !important;
  transform: rotate(-15deg) !important;
  position: relative !important;
  width: auto !important;  
  height: auto !important;
  top: 3px;
  right: -20px;
  --mdc-icon-size: 100px !important;
  opacity: 0.02;
  }
.bubble-sub-button-container {
  position: absolute;
  left: 0px !important;
  top: -7px;
  gap: 10;
  right: 0px !important;
  }
.bubble-sub-button {
  opacity: 0.5;
  }
```
2)
```yaml
.large .separator-container {
  height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
  overflow: hidden !important;
  position: relative !important;
  }
.bubble-line {
  position: relative !important;
  opacity: 0.2;
  }
.bubble-name {
  position: absolute;
  left: 0px !important;
  top: 0px;
  font-weight: 350;
  font-size: 14px;
  opacity: 0.2;
  }
.bubble-icon {
  position: absolute !important;
  transform: rotate(25deg) !important;
  width: auto !important;  
  height: auto !important;
  position: relative !important;
  top: 5px;
  left: 20px;
  --mdc-icon-size: 105px !important;
  opacity: 0.02;
  }
.bubble-sub-button-container {
  position: absolute;
  left: 0px !important;
  top: -7px;
  gap: 10;
  right: 0px !important;
  }
.bubble-sub-button {
  opacity: 0.5;
  }
```
person card (battery icon misaligned)

before 

![Image](https://github.com/user-attachments/assets/c6159b0b-8ffa-4fc2-89cb-ab6859412852)

after

![Image](https://github.com/user-attachments/assets/a68c8fb9-125b-4d8a-9ba3-8d3b744a1fe2)

style

```yaml
.large .bubble-button-card-container {
  height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
  overflow: hidden !important;
  position: relative;
  border-radius: 36px 16px 50px 26px !important;
  }

.bubble-icon-container {
  border-radius: 50% !important;
  width: 137px !important;
  height: 137px !important;
  position: absolute !important;
  left: -11%;
  bottom: -11%;
  opacity: ${hass.states['person.maurizio_de_maio'].state === 'home' ? '1' : '0.3'} !important;
 }
.bubble-name-container {
  position: absolute;
  top: 7%; 
  left: 5%;
  }

.bubble-name {
  font-weight: 400;
  font-size: 15px;
}

.bubble-state {
  font-weight: 350;
  font-size: 13px;
}

.bubble-sub-button-container {
  position: absolute;
  top: -7%;
  right: -3%;
}
.bubble-sub-button-1 {
  height: 80px !important;
  width: 80px !important;
  border-radius: 100% !important;
  background-color: transparent;
}
.bubble-sub-button-2 {
  position: absolute;
  transform: translateX(10%) rotate(90deg) scaleY(-1) !important;
  margin-top: 0;
  }
.bubble-sub-button-2 ha-icon {
  opacity: 0.06;
  --mdc-icon-size: 110px;
  transform-origin: top right;  
  }
@media (max-width: 700px) {
.bubble-state {
  font-size: 12px;
  }
}
```

alarm card

before

![Image](https://github.com/user-attachments/assets/f8ce3e33-7190-4b65-b720-45afad6d91f8)

after

![Image](https://github.com/user-attachments/assets/61f094fb-2f50-43fb-ae40-335b8877db71)

style

```yaml
.large .bubble-button-card-container {
  height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
  overflow: hidden !important;
  position: relative !important;
  }
.bubble-icon-container {
  width: 185px !important;
  height: 185px !important;
  left: 5%;
  bottom: -3%;
  background-color: transparent;
 }

.bubble-icon {
  transform: rotate(0deg) !important;
  --mdc-icon-size: 150px !important;
  opacity: 0.06;  
  }
@keyframes lampeggio {
    0% { 
        color: var(--primary-text-color); 
    }
    1% { 
        color: rgba(242, 109, 109, 0.8); 
    }
    100% { 
        color: var(--primary-text-color); 
    }
}


.bubble-name-container {
  position: absolute;
  top: 68%;
  transform: translateY(-50%);
  left: 12%;
  transform: translate(-50%, -50%);
  }
.bubble-name {
  font-weight: 400;
  font-size: 15px;
  }
.bubble-state {
  font-weight: 350;
  font-size: 13px;
  animation: ${hass.states['sensor.stato_generale_allarme'].state === 'Disinserito' ? '' : 'lampeggio 1s infinite ease-in-out'} !important;
  }
.bubble-sub-button-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;
  width: 42%;
  height: 90%;
  position: relative;
  border-radius: 0%;
  overflow: visible; 
  gap: 0px 8px
  right: 1%;
}

.bubble-sub-button {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
}

.bubble-sub-button-1 { 
  border-radius: 50px 12px 50px 50px;
  grid-area: 1 / 1; 
  background-color: ${hass.states['alarm_control_panel.ingressi'].state === 'armed_away' ? 'rgba(240, 202, 115, 0.8)' : 'rgba(240, 202, 115, 0.2)'} !important;
  color: ${hass.states['alarm_control_panel.ingressi'].state === 'armed_away' ? 'rgba(0,0,0,0.8)' : 'rgba(0,0,0, 0.4)'} !important;
  }
.bubble-sub-button-2 { 
  border-radius: 50px 12px 50px 50px;
  grid-area: 2 / 1; 
  background-color: ${hass.states['alarm_control_panel.interni'].state === 'armed_away' ? 'rgba(149, 199, 201, 0.8)' : 'rgba(149, 199, 201, 0.2)'} !important;
  color: ${hass.states['alarm_control_panel.interni'].state === 'armed_away' ? 'rgba(0,0,0,0.8)' : 'rgba(0,0,0, 0.4)'} !important;
  }
.bubble-sub-button-3 { 
  border-radius: 50px 50px 50px 12px;
  grid-area: 2 / 2; 
  background-color: ${hass.states['alarm_control_panel.esterni'].state === 'armed_away' ? 'rgba(180, 196, 122, 0.8)' : 'rgba(180, 196, 122, 0.2)'} !important;
  color: ${hass.states['alarm_control_panel.esterni'].state === 'armed_away' ? 'rgba(0,0,0,0.8)' : 'rgba(0,0,0, 0.4)'} !important;
  }
.bubble-sub-button-4 { 
  border-radius: 50px 50px 50px 12px;
  grid-area: 1 / 2; 
  background-color: ${hass.states['alarm_control_panel.radar'].state === 'armed_away' ? 'rgba(163, 108, 131, 0.8)' : 'rgba(163, 108, 131, 0.2)'} !important;
  color: ${hass.states['alarm_control_panel.radar'].state === 'armed_away' ? 'rgba(0,0,0,0.8)' : 'rgba(0,0,0, 0.4)'} !important;
  }
.bubble-sub-button ha-icon {
  --mdc-icon-size: 30px !important;
  }
.bubble-sub-button-1 ha-icon {
  animation: ${(() => {
          const finestre = [
            'binary_sensor.09_ingr_taverna_2',
            'binary_sensor.10_fin_taverna_2',
            'binary_sensor.11_fin_one_tav_2',
            'binary_sensor.19_ingr_giorno_2',
            'binary_sensor.21_bagno_giorno_2',
            'binary_sensor.22_fin_scale_2',
            'binary_sensor.23_ripostiglio_2'
          ];
          const esclusioni = [
            'switch.09_ingr_taverna_bypassato_2',
            'switch.10_fin_taverna_bypassato_2',
            'switch.11_fin_one_tav_bypassato_2',
            'switch.19_ingr_giorno_bypassato_2',
            'switch.21_bagno_giorno_bypassato_2',
            'switch.22_fin_scale_bypassato_2',
            'switch.23_ripostiglio_bypassato_2'
          ];
          
          return finestre.some((fin, i) => 
            hass.states[fin].state === 'on' && hass.states[esclusioni[i]].state === 'off'
          ) ? 'blinking 1s infinite' : 'none';
        })()}
}
.bubble-sub-button-2 ha-icon {
  animation: ${(() => {
          const finestre = [
            'binary_sensor.14_int_terrazzo_2',
            'binary_sensor.16_int_sala_2',
            'binary_sensor.18_int_cucina_2',
            'binary_sensor.25_int_studio_2',
            'binary_sensor.27_int_armadio_2',
            'binary_sensor.29_int_camera_2',
            'binary_sensor.31_int_bag_nott_2'
          ];
          const esclusioni = [
            'switch.14_int_terrazzo_bypassato_2',
            'switch.16_int_sala_bypassato_2',
            'switch.18_int_cucina_bypassato_2',
            'switch.25_int_studio_bypassato_2',
            'switch.27_int_armadio_bypassato_2',
            'switch.29_int_camera_bypassato_2',
            'switch.31_int_bag_nott_bypassato_2'
          ];
          
          return finestre.some((fin, i) => 
            hass.states[fin].state === 'on' && hass.states[esclusioni[i]].state === 'off'
          ) ? 'blinking 1s infinite' : 'none';
        })()}
}
.bubble-sub-button-3 ha-icon {
  animation: ${(() => {
          const finestre = [
            'binary_sensor.13_est_terrazzo_2',
            'binary_sensor.15_est_sala_2',
            'binary_sensor.17_est_cucina_2',
            'binary_sensor.24_est_studio_2',
            'binary_sensor.26_est_armadio_2',
            'binary_sensor.28_est_camera_2',
            'binary_sensor.30_est_bag_nott_2'
          ];
          const esclusioni = [
            'switch.13_est_terrazzo_bypassato_2',
            'switch.15_est_sala_bypassato_2',
            'switch.17_est_cucina_bypassato_2',
            'switch.24_est_studio_bypassato_2',
            'switch.26_est_armadio_bypassato_2',
            'switch.28_est_camera_bypassato_2',
            'switch.30_est_bag_nott_bypassato_2'
          ];
          
          return finestre.some((fin, i) => 
            hass.states[fin].state === 'on' && hass.states[esclusioni[i]].state === 'off'
          ) ? 'blinking 1s infinite' : 'none';
        })()}
}
.bubble-sub-button-4 ha-icon {
  animation: ${(() => {
          const finestre = [
            'binary_sensor.12_radar_taverna_2',
            'binary_sensor.20_radar_giorno_2',
            'binary_sensor.32_radar_notte_2'
          ];
          const esclusioni = [
            'switch.12_radar_taverna_bypassato_2',
            'switch.20_radar_giorno_bypassato_2',
            'switch.32_radar_notte_bypassato_2'
          ];
          
          return finestre.some((fin, i) => 
            hass.states[fin].state === 'on' && hass.states[esclusioni[i]].state === 'off'
          ) ? 'blinking 1s infinite' : 'none';
        })()}
}
@keyframes blinking {
      0% { 
        opacity: 1; 
      }
      50% { 
        opacity: 0.1; 
      }
      100% { 
        opacity: 1; 
      }
    }
@media (max-width: 700px) {

}
```

separator misaligned

before

![Image](https://github.com/user-attachments/assets/a3b5ea3f-223d-4ddd-9a76-e6d636fa82da)

after

![Image](https://github.com/user-attachments/assets/908777e4-4ee0-4ca6-8ae6-4ce82a1b51d4)

yaml

```yaml
type: custom:bubble-card
card_type: separator
icon: ""
sub_button: []
card_layout: normal
visibility:
  - condition: screen
    media_query: "(min-width: 0px) and (max-width: 767px)"
grid_options:
  columns: 12
  rows: 0.5
styles: |-
  ha-card {
    margin-top: 9px;
    }
```

popup with large climate cards

before

![Image](https://github.com/user-attachments/assets/f395aa25-0dd5-4619-b8d4-6748cf6fc7cd)

after

![Image](https://github.com/user-attachments/assets/d7702edd-2551-4a39-b473-1d32dba13656)

yaml (of the entire popup)

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#clima"
    name: Clima
    button_type: name
    icon: mdi:sun-snowflake
    margin_top_mobile: 260px
    hide_backdrop: false
    margin_top_desktop: 50px
    width_desktop: ""
    styles: |
      .bubble-button-card-container {
          background: transparent !important;
        }
      .bubble-close-button {
          display: none !important;
          }
      .card-content {
        width: 100%;
        height: 100%;
        margin: 0 !important;
        position: relative;
      }

      .bubble-button-card-container {
        position: relative;
        width: 100%;
        height: 100%;
        #border-radius: 20px;
        overflow: hidden;
        #border-radius: 12px 24px 12px 24px !important;
      }

      .bubble-button-card {
        position: relative;
        width: 100%;
        height: 100%;
      }

      .bubble-icon-container {
        position: absolute;
        width: 170px;
        height: 170px;
        border-radius: 50%;
        left: 30%;
        top: 50%;
        background-color: transparent;
        transform: translate(-50%, -50%);
      }

      .bubble-icon {
        --mdc-icon-size: 65px;
        transform: rotate(-20deg);
        opacity: 0.4;
      }

      .bubble-name-container {
        position: absolute;
        left: 10px; 
        top: 50%; 
        transform: translateY(-50%); 
        max-width: calc(100% - 20px);
      }

      .bubble-name {
        font-weight: 350;
        font-size: 15px;
      }

      .bubble-state {
        font-weight: 350;
        font-size: 13px;
      }
    show_header: true
    card_layout: large
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: climate
        entity: climate.samsung
        sub_button:
          - entity: sensor.broadlink_rm4_mini_umidita
            show_icon: false
            show_state: fa
            show_background: false
            state_background: false
            show_name: false
          - show_background: false
            icon: mdi:circle-small
            tap_action:
              action: none
          - select_attribute: fan_modes
            icon: mdi:fan
            show_arrow: false
            state_background: false
            entity: climate.samsung
          - name: HVAC modes menu
            select_attribute: hvac_modes
            state_background: false
            show_arrow: false
            entity: climate.samsung
          - entity: input_select.timer_spegnimento_palestra
            visibility:
              - condition: state
                entity: climate.samsung
                state_not: "off"
          - entity: input_datetime.orario_spegnimento_palestra
            show_background: false
            show_icon: true
            show_state: true
            show_attribute: false
            show_last_changed: false
            show_name: false
            visibility:
              - condition: state
                entity: input_boolean.stato_timer_palestra
                state: "on"
        name: Palestra
        show_name: true
        show_icon: true
        show_attribute: true
        state_color: false
        scrolling_effect: false
        show_state: false
        show_last_changed: false
        attribute: current_temperature
        styles: |
          .large .bubble-climate-container {
            height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
            position: relative;
            overflow: visible;
            }
          .bubble-color-background {
            opacity: 0 !important;
          }
          .bubble-climate {
            overflow: hidden;
            }
          .bubble-temperature-container {
            position: absolute;
            width: 90px;
            height: 40px;
            top: 10%;
            right: 5%;
            }
          .bubble-name-container {
            position: absolute;
            top: 10%;
            left: 5%;
            }

          .bubble-name {
            font-size: 16px;
            font-weight: 400;
            }
          .bubble-state {
            font-size: 14px;
            }
          .bubble-icon-container {
            position: absolute;
            background-color: transparent;
            width: 150px;
            height: 150px;
            --mdc-icon-size: 150px !important;
            border-radius: 0;
            left: 0;
            margin-left: 0 !important;
            overflow: hidden;
            }
          .bubble-icon {
              display: flex;
              position: absolute;
              height: 120px;
              width: 120px;
              justify-content: center;
              align-items: center;
              transition: all 2s;
              opacity: 0.08 !important;
              left: -15%;
              color: var(--icon-primary-color) !important;
              fill: var(--icon-primary-color) !important;
              }
          .bubble-sub-button-container {
            position: absolute;
            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr;
            grid-template-rows: 1fr 1fr;
            justify-content: space-between;
            width: calc(100% - 10%);
            margin-right: 5%;
            left: 3%;
            bottom: 10%;
            gap: 16px 8px;
            justify-items: end;
            }
          .bubble-sub-button-container > div {
            display: flex;
            justify-content: center;
            align-items: center;
            }
          .bubble-sub-button-3,
          .bubble-sub-button-4 {
              background: ${hass.states['climate.samsung'].state !== 'off' ? '#b2d1c8' : ''} !important;
              color: ${hass.states['climate.samsung'].state !== 'off' ? 'black' : 'var(--icon-primary-color)'} !important;
              --primary-text-color: black !important;
          }
          .bubble-sub-button-3,
          .bubble-sub-button-4,
          .bubble-sub-button-5 {
              --accent-color: ${hass.states['climate.samsung'].state !== 'off' ? '#b2d1c8' : 'initial'} !important;
              opacity: 1 !important;
          }
          .bubble-sub-button-1 {
            grid-column: 1;
            grid-row: 2;
            }
          .bubble-sub-button-2 {
            grid-column: 2;
            grid-row: 2;
            }
          .bubble-sub-button-3 {
            grid-column: 3;
            grid-row: 2;
            }
          .bubble-sub-button-4 {
            grid-column: 4;
            grid-row: 2;
            }
          .bubble-sub-button-5 {
            grid-column: 3/5;
            grid-row: 1;
            }
          .bubble-sub-button-6 {
            grid-column: 1/3;
            grid-row: 1;
            }
          mwc-list-item[aria-selected="true"] ha-icon {
              --icon-primary-color: black !important;
          }
          mwc-list-item[aria-selected="true"] ha-attribute-icon {
              --icon-primary-color: black !important;
          }
          mwc-list-item[aria-selected="true"] {
              background: #b2d1c8 !important;
              color: black !important;
          }
          @media (max-width: 650px) {
          .bubble-temperature-container {
            position: absolute;
            width: 82px;
            height: 40px;
            }
          .bubble-icon {
              clip-path: inset(0 0 0 15%) !important;
          }
          .bubble-sub-button-container {
            margin-left: 0%;
            margin-right: 6%;
          }
          }
        card_layout: large
        grid_options:
          columns: 6
          rows: 3
        icon: mdi:dumbbell
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:bubble-card
        card_type: climate
        entity: climate.camera
        sub_button:
          - entity: sensor.camera_umidita
            show_icon: false
            show_state: fa
            show_background: false
            state_background: false
            show_name: false
          - entity: climate.camera
            select_attribute: swing_modes
            show_icon: true
            show_name: false
            show_arrow: false
            icon: mdi:chevron-double-down
            show_background: false
          - entity: climate.camera
            select_attribute: fan_modes
            icon: mdi:fan
            show_arrow: false
            state_background: false
          - name: HVAC modes menu
            select_attribute: hvac_modes
            state_background: false
            show_arrow: false
          - entity: input_select.timer_spegnimento_mitsubishi
            state_background: false
            show_arrow: true
            visibility:
              - condition: state
                entity: climate.camera
                state_not: "off"
          - entity: input_datetime.orario_spegnimento_mitsubishi
            show_background: false
            show_icon: true
            show_state: true
            show_attribute: false
            visibility:
              - condition: state
                entity: input_boolean.stato_timer_mitsubishi
                state: "on"
        name: Camera
        show_name: true
        show_icon: true
        show_attribute: true
        state_color: false
        scrolling_effect: false
        show_state: false
        show_last_changed: false
        attribute: current_temperature
        styles: |
          .large .bubble-climate-container {
            height: calc( var(--row-height) * var(--row-size) + var(--row-gap) * ( var(--row-size) - 1 )) !important;
            position: relative;
            overflow: visible;
            }
          .bubble-color-background {
              opacity: 0 !important;
          }
          .bubble-climate {
            overflow: hidden;
            }
          .bubble-temperature-container {
            position: absolute;
            width: 90px;
            height: 40px;
            top: 10%;
            right: 5%;
            }
          .bubble-name-container {
            position: absolute;
            top: 10%;
            left: 5%;
            }

          .bubble-name {
            font-size: 16px;
            font-weight: 400;
            }
          .bubble-state {
            font-size: 14px;
            }
          .bubble-icon-container {
            position: absolute;
            background-color: transparent;
            width: 150px;
            height: 150px;
            --mdc-icon-size: 150px !important;
            border-radius: 0;
            left: 0;
            margin-left: 0 !important;
            overflow: hidden;
            }
          .bubble-icon {
              display: flex;
              position: absolute;
              height: 120px;
              width: 120px;
              justify-content: center;
              align-items: center;
              transition: all 2s;
              opacity: 0.08 !important;
              left: -15%;
              color: var(--icon-primary-color) !important;
              fill: var(--icon-primary-color) !important;
              }
          .bubble-sub-button-container {
            position: absolute;
            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr;
            grid-template-rows: 1fr 1fr;
            justify-content: space-between;
            width: calc(100% - 10%);
            margin-right: 5%;
            left: 3%;
            bottom: 10%;
            gap: 16px 8px;
            justify-items: end;
            }
          .bubble-sub-button-container > div {
            display: flex;
            justify-content: center;
            align-items: center;
            }
          .bubble-sub-button-3,
          .bubble-sub-button-4 {
              background: ${hass.states['climate.camera'].state !== 'off' ? '#b2d1c8' : ''} !important;
              color: ${hass.states['climate.camera'].state !== 'off' ? 'black' : 'var(--icon-primary-color)'} !important;
              --primary-text-color: black !important;
          }
          .bubble-sub-button-2,
          .bubble-sub-button-3,
          .bubble-sub-button-4,
          .bubble-sub-button-5 {
              --accent-color: ${hass.states['climate.camera'].state !== 'off' ? '#b2d1c8' : 'initial'} !important;
              opacity: 1 !important;
          }
          .bubble-sub-button-1 {
            grid-column: 1;
            grid-row: 2;
            }
          .bubble-sub-button-2 {
            grid-column: 2;
            grid-row: 2;
            }
          .bubble-sub-button-3 {
            grid-column: 3;
            grid-row: 2;
            }
          .bubble-sub-button-4 {
            grid-column: 4;
            grid-row: 2;
            }
          .bubble-sub-button-5 {
            grid-column: 3/5;
            grid-row: 1;
            }
          .bubble-sub-button-6 {
            grid-column: 1/3;
            grid-row: 1;
            }
          mwc-list-item[aria-selected="true"] ha-icon {
              --icon-primary-color: black !important;
          }
          mwc-list-item[aria-selected="true"] ha-attribute-icon {
              --icon-primary-color: black !important;
          }
          mwc-list-item[aria-selected="true"] {
              background: #b2d1c8 !important;
              color: black !important;
          }
          @media (max-width: 650px) {
          .bubble-temperature-container {
            position: absolute;
            width: 82px;
            height: 40px;
            }
          .bubble-icon {
              clip-path: inset(0 0 0 15%) !important;
          }
          .bubble-sub-button-container {
            margin-left: 0%;
            margin-right: 6%;
          }
          }
        card_layout: large
        grid_options:
          columns: 6
          rows: 3
        icon: mdi:bed-king-outline
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
    grid_options:
      columns: 12
      rows: 3
grid_options:
  columns: 12
  rows: 3
```

**Informations (please complete the following information):**  
 - Bubble Card version: [2.0.5 beta 6 onward] (last working beta 5)
 - Home Assistant version: [2025.3.3]

Thank you! 🍻

**Comment by Clooos** [comment]
Thank you for the feedback!

These are really advanced custom styles, you will probably have to adapt some of them for the new version, but I will try these to see if something can be done on my side to avoid too many changes.

**Comment by Clooos** [comment]
Hi! These issues should be all fixed in the next beta 🥳

**Comment by userdema** [comment]
> Hi! These issues should be all fixed in the next beta 🥳

Wooooh that's an amazing news! You're a magician! 🧙🏻‍♂️

**Comment by Clooos** [comment]
And done! 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.5.0-beta.9

**Comment by userdema** [comment]
> And done! 🤞
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.5.0-beta.9

Almost all was fixed, 🎉 apart the climate pop-up. Seems There is no longer support for cards with more rows

**Comment by Clooos** [comment]
Yeah! Thank you for the fast feedback! 🥳

For you climate card, I'm even surprised this was working before, but I will take a look at this!

**Comment by userdema** [comment]
The only way to get it work before, was change the entire rows of the vertical stack to fit the rows desired for my climate cards, but seems no longer work

![Image](https://github.com/user-attachments/assets/6958cf7e-7f9b-4b94-87ae-2d70e95829c6)

**Comment by Clooos** [comment]
Indeed, this was more a bug than a feature 😅

But you can replace the `height` like this:

```yaml
.large .bubble-climate-container {
  height: 200px !important;
  position: relative;
  overflow: visible;
}
```

**Comment by userdema** [comment]
> Indeed, this was more a bug than a feature 😅
> 
> But you can replace the `height` like this:
> 
> .large .bubble-climate-container {
>   height: 200px !important;
>   position: relative;
>   overflow: visible;
> }

Yeah that's worked... But now it's returned the problem of the list selector that opens on top, hiding part of it... 🫣

![Image](https://github.com/user-attachments/assets/b668127a-f37c-43b1-90d5-6a627982f0c6)

**Comment by userdema** [comment]
I don't know if i've found another bug in climate card or is my fault.
As you can see from my yaml, i have a rule for not get icon colored when entity is on:

```yaml
.bubble-icon { 
  color: var(--icon-primary-color) !important;
  fill: var(--icon-primary-color) !important;
  }
```
But with new beta I'm getting the icon colored when climate is different from off

![Image](https://github.com/user-attachments/assets/1bb856be-6aac-4387-b863-b0817a6c698b)

**Comment by Clooos** [comment]
Hi! I'm not sure of that but I've just fixed an issue that could fix the height of your climate card, and maybe the dropdown as well.

For the icon color there was a change indeed (the icon was not colored at all when On before), but you can change it with:

```yaml
.bubble-main-icon {
  --bubble-icon-color: white;
}
```

**Comment by userdema** [comment]
> Hi! I'm not sure of that but I've just fixed an issue that could fix the height of your climate card, and maybe the dropdown as well.
> 
That's great! 🤞🤞
> For the icon color there was a change indeed (the icon was not colored at all when On before), 
> 
In reality i've add those lines, because in fan mode the icon was colored also before.. now is colored in every mode.
> but you can change it with:
 .bubble-main-icon {
>   --bubble-icon-color: white;
> }
I'll try in this way, but i must use var(--primary-icon-color) because i need that the color follow the theme in light and dark mode...

**Comment by userdema** [comment]
for completeness of information, i want tell you that the only way that i found to fix icon color to not change on entity state is using
```yaml
.bubble-icon {
  color: var(--primary-text-color) !important;
  fill: var(--primary-text-color) !important;
  }
```
probably taking "icon" as reference, it follow icon rules, while text have a more "static" behaviour
