### ISSUE TITLE
Idea: progress bar

### ISSUE THREAD

**Issue by traysh** [Clooos/Bubble-Card#1352]
The card format is perfect for a progress bar. I emulated one with the code bellow, but it would be nice to have it supported.

```yaml
type: custom:bubble-card
card_type: button
button_type: state
styles: |-
  .bubble-button-background {
    right: ${100-state}%;
    opacity: 0.5 !important;
    background-color: #ffdcc8 ! important;
  }
entity: sensor.pixel_9_pro_battery_level
grid_options:
  columns: 6
icon: mdi:cellphone
name: Battery Level
```
