### ISSUE TITLE
Sub-buttons on a slider no longer work.

### ISSUE THREAD

**Issue by GunterAv** [Clooos/Bubble-Card#1358]
I have a slider (to control the volume) with two sub-buttons.

![Image](https://github.com/user-attachments/assets/97a5cb7f-f61a-448c-a3e1-fdb4e61c1d3e)

With version v2.5.0-beta.8, these can no longer be used.

As soon as I click on one of the sub-buttons, only the volume is increased.

YAML Code:
````
type: custom:bubble-card
card_type: button
show_icon: false
button_type: slider
entity: media_player.soundtouch_300_3
show_state: false
show_last_changed: false
show_attribute: true
attribute: volume_level
name: Lautstärke
sub_button:
  - entity: switch.soundtouchdialog
    name: Dialogmodus
    icon: ave:dialog1
    show_name: false
    tap_action:
      action: toggle
  - entity: switch.bose300mute
    show_state: false
    name: Mute
    tap_action:
      action: toggle
modules:
  - home-assistant-default
styles: |
  .bubble-button-card-container {
  opacity: 1 !important;
  background-color: rgb(229, 229, 229) !important;
  }
       .bubble-sub-button-1 { background-color: ${hass.states['sensor.bose300dialog'].state === '1' ? 'rgb(0,170,240)' : 'white'}
       !important; }

       .bubble-sub-button-2 { background-color: ${hass.states['sensor.bose300mute'].state === '1' ? 'rgb(0,170,240)' : 'white'}
       !important; }
card_layout: normal
tap_to_slide: true
slider_live_update: true
read_only_slider: false
````

Best regrards
Gunter
