### ISSUE TITLE
Media-Player card play button not hiding

### ISSUE THREAD

**Issue by MetalOnes** [Clooos/Bubble-Card#1363]
**Describe the bug**  
With 2.5.0.beta.9, the play button is not hiding. Reverting to beta.8 resolves the issue. Also, if I hide all of the buttons, play will then become hidden.

**To Reproduce**  
1. Create a media-player card
2. Hide the play button
3. It doesn't hide unless all buttons are hidden.

**Expected behavior**  
The previous behavior

**Screenshots**  
![Image](https://github.com/user-attachments/assets/670f083b-a04b-4917-ac2f-2aafeac342e4)

**YAML**  
```yaml
type: custom:bubble-card
card_type: media-player
entity: media_player.denon_avr_s720w
hide:
  next_button: true
  previous_button: true
  power_button: true
  play_pause_button: true
  volume_button: false
sub_button:
  - entity: select.living_room_activities
    show_background: false
    show_name: false
    show_state: true
scrolling_effect: false
show_attribute: true
attribute: volume_level
name: Television
force_icon: false
cover_background: true
grid_options:
  columns: 12
  rows: 1
styles: >
  ${icon.setAttribute("icon",
  hass.states['sensor.harmony_living_room'].attributes.icon)}
card_layout: large
modules:
  - default

```

**Informations (please complete the following information):**  
 - OS: Windows 11
 - Browser/App: Firefox, Chrome
 - Bubble Card version: 2.5.0.beta.9
 - Home Assistant version: 2025.3.4

Thank you! 🍻
