### ISSUE TITLE
Issue with 2025.4.0

### ISSUE THREAD

**Issue by rononline** [Clooos/Bubble-Card#1369]
The sub-buttons are not working anymore in the next HA release:

```
type: custom:bubble-card
card_type: button
card_layout: large
button_type: name
show_icon: false
show_name: false
sub_button:
  - name: Vandaag
    entity: sensor.weather_forecast_daily_combined
    show_background: false
    show_name: false
    show_last_changed: false
    show_state: false
    show_attribute: true
    attribute: forecast[1]?.temperature
    tap_action:
      action: navigate
      navigation_path: weer
  - name: Morgen
    entity: sensor.weather_forecast_daily_combined
    show_background: false
    show_attribute: true
    attribute: forecast[2]?.temperature
    tap_action:
      action: navigate
      navigation_path: weer
  - name: Overmorgen
    entity: sensor.weather_forecast_daily_combined
    show_background: false
    show_state: false
    show_attribute: true
    attribute: forecast[3]?.temperature
    tap_action:
      action: navigate
      navigation_path: weer
  - name: OverOvermorgen
    entity: sensor.weather_forecast_daily_combined
    show_background: false
    show_state: false
    show_attribute: true
    attribute: forecast[4]?.temperature
    tap_action:
      action: navigate
      navigation_path: weer
  - name: OverOverOvermorgen
    entity: sensor.weather_forecast_daily_combined
    show_background: false
    show_state: false
    show_attribute: true
    attribute: forecast[5]?.temperature
    tap_action:
      action: navigate
      navigation_path: weer
 
```

![Image](https://github.com/user-attachments/assets/4f619599-6570-4c2a-9cef-242543e92918)

A rollback does work, so I guess something has changed in the frontend?! Maybe you can take a look already @cloos? Before there will be more problems when released next week :-)
