### ISSUE TITLE
Zoom is broken in beta 9

### ISSUE THREAD

**Issue by adnansarajlic** [Clooos/Bubble-Card#1371]
**Describe the bug**  
Zoom has been disabled in beta 9 when using picture element on touch screens. 

**To Reproduce**  
Create card according to code and try to zoom after selecting.

**Expected behavior**  
Zoom works in 2.4

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#image"
    show_header: false
    name: STATUS
    button_type: name
    show_icon: true
    icon: mdi:home
  - type: vertical-stack
    cards:
      - type: picture
        image: /local/images/image.png
        tap_action:
          action: none
        hold_action:
          action: none

```

**Informations (please complete the following information):**  
 - OS: Android
 - Browser/App: HA app
 - Bubble Card version: [e.g. beta 9]
 - Home Assistant version: [latest]
