### ISSUE TITLE
Timer card in popup stops updating

### ISSUE THREAD

**Issue by sdholden28** [Clooos/Bubble-Card#1378]
**Describe the bug**  
I have a pop-up for a flip down timer card. IF "background_upate: false", the card only shows the original timer duration. If I set "background_update: true", then the card will countdown until I close the card. If I close the card or navigate to another page and then open the timer card popup again, the timer card shows whatever the remaining time is at that moment, but it does not update any further.

**To Reproduce**  
1. Create popup card using flipdown timer card
2. Activate popup
3. Observer card not updating as it should

**Expected behavior**  
Timer card should update and show "counting down" whenever it is open and there is an active timer

**YAML**  
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#officealexatimerhome"
    show_header: false
    auto_close: ""
    trigger:
      - condition: and
        conditions:
          - condition: state
            entity: sensor.office_dot_next_timer
            state_not: unavailable
          - condition: state
            entity: sensor.office_dot_next_timer
            state_not: unknown
    icon: ""
    name: ""
    show_state: true
    force_icon: false
    width_desktop: "90"
    hide_backdrop: false
    close_by_clicking_outside: false
    bg_blur: "0"
    bg_opacity: "0"
    shadow_opacity: "0"
    backdrop_blur: "0"
    margin_top_desktop: 20vh
    sub_button: []
    button_action:
      tap_action:
        action: toggle
    modules:
      - default
    slide_to_close_distance: ""
    close_on_click: true
    background_update: true
    trigger_close: false
  - type: custom:flipdown-timer-card
    entity: sensor.office_dot_next_timer
    show_hour: auto
    show_title: false
    show_header: false
    theme: light
    styles:
      rotor:
        width: 360px
        height: 250px
        fontsize: 18rem
    card_mod:
      style: |
        ha-card {
          background: transparent;
          box-shadow: none;
        }
grid_options:
  rows: 1
  columns: 12
```
**Informations (please complete the following information):**  
 - OS: All
 - Browser/App: All
 - Bubble Card version: 2.5.0-beta.9
 - Home Assistant version: 2025.3.4

**Additional context**  
possibly related to #1324
