### ISSUE TITLE
Bubble card with slider:  can't actually SLIDE it?

### ISSUE THREAD

**Issue by Doni49** [Clooos/Bubble-Card#1381]
**Describe the bug**  

**To Reproduce**  

1. Place bubble card with type set to slider within a pop-up.
2. When the popup opens try sliding to get the appropriate value.
3. As soon as your finger moves across the screen, the popup closes and the value did not change.

The only way I can actually change the value using the slider is by tapping on the slider.  I only get one chance to get it right because as soon as I tap the screen, the popup closes.

**Expected behavior**  
When the popup opens and the slider is shown, I should be able to slide the bar across the screen to get the desired value.

**Screenshots**  

![Image](https://github.com/user-attachments/assets/9bc6563e-c418-4886-bbc5-13f679176359)

**YAML**  
This is the YAML for the button that calls the pop-up.  The sub-button in question is living room lamp.

```
type: custom:bubble-card
card_type: button
name: Living Room
sub_button:
  - entity: fan.living_room_fan
    icon: mdi:ceiling-fan
    tap_action:
      action: toggle
  - entity: light.living_room_fanlight
    icon: mdi:ceiling-fan-light
    show_icon: true
    light_background: false
    tap_action:
      action: toggle
  - entity: light.living_room_lamp
    icon: mdi:lamp
    tap_action:
      action: toggle
    hold_action:
      action: navigate
      navigation_path: "#living-room-lamp"
  - entity: media_player.living_room_roku
    icon: mdi:television-classic
    tap_action:
      action: toggle
icon: mdi:sofa
entity: input_boolean.living_room
tap_action:
  action: none
double_tap_action:
  action: none
hold_action:
  action: none
button_action:
  tap_action:
    action: none
  double_tap_action:
    action: none
  hold_action:
    action: none

```

This is the YAML for the popup and the slider.

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#living-room-lamp"
    card_layout: large-2-rows
    hide_backdrop: false
    margin_top_mobile: calc(100vh - 250px)
    close_on_click: true
    slide_to_close_distance: ""
    show_header: false
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.living_room_lamp
    icon: mdi:lamp
    sub_button: []
    tap_action:
      action: toggle
    card_layout: normal
    columns: 4


``` 

**Informations (please complete the following information):**  
 - OS: Android Phone and Android tablet.  Tested on both with same results.
 - Browser/App: the HA Companion app on my phone and FKB on the tablet.
 - Bubble Card version: 2.4
 - Home Assistant version: 

![Image](https://github.com/user-attachments/assets/527abf98-30d1-435d-b43f-1396fb85e54e)

**Additional context**  

Thank you! 🍻
