### ISSUE TITLE
Invalid config for 'template' at configuration.yaml

### ISSUE THREAD

**Issue by cuttydiamond** [Clooos/Bubble-Card#1423]
Added the code in the configuration.yaml to add the storage entity sensor.bubble_card_modules.  Saved and restarted.  Got the following notification:

      The following integrations and platforms could not be set up:

      template (Show logs)

From the logs:

     Log details (ERROR)
     Logger: homeassistant.config
     Source: config.py:357
     First occurred: 11:52:03 AM (1 occurrences)
     Last logged: 11:52:03 AM

     Invalid config for 'template' at configuration.yaml, line 34: 'triggers' is an invalid option for 'template', check: 
     triggers

Code I added:

# Storage for Bubble Card Modules
template:
  - triggers:
      - trigger: event
        event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        icon: "mdi:puzzle"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"

**Comment by Clooos** [comment]
Yes I made a mistake!

It's `trigger` and not `triggers`. I will change that in the next beta.

**Comment by cuttydiamond** [comment]
That fixed it, thank you!!!

PS, thanks for all your hard work!  This is by far my favorite HA project and I use your cards almost exclusively in my dashboards.

**Comment by blueJack92** [comment]
I have this code here in my configuration.yaml:

```
  - trigger:
      - platform: event
        event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"
```

Which is the correct one?

**Comment by Clooos** [comment]
This is the same one, but the new YAML syntax is just more modern 🙂 

You can replace it with the new one if you want, this will not remove anything.

**Comment by blueJack92** [comment]
Could you paste the new code here or (later) in the documentation? Thank you very much! ☺️

**Comment by Clooos** [comment]
Here's the new one:

```yaml
# Storage for Bubble Card Modules
template:
  - trigger:
      - trigger: event
        event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        icon: "mdi:puzzle"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"
```

This will be changed in the new beta today 🙂
