### ISSUE TITLE
One Button state card is regularly broken

### ISSUE THREAD

**Issue by HyperCriSiS** [Clooos/Bubble-Card#1433]
Hi,

totally forgot to report this. One of my button state cards is regularly broken.
With the Icon, I control a Hue Smart plug. If I turn it off, the LG TV, which is the entity of the card, is taken from power.
And this seems to be the issue. When the entity is offline, the card does not show. It blinks up for a second and then the error appears. Can we add a fallback value here?

**Screenshots**  
On Desktop:
![Image](https://github.com/user-attachments/assets/84500aea-6d84-45f0-8e85-48594fc15fb2)
On Android companion app different error message then:
Cannot read properties of undefined (reading 'forEach')

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
card_layout: normal
tap_action:
  action: perform-action
  perform_action: button.press
  target:
    entity_id: button.wake_on_lan_dc_03_98_13_7c_3e
button_type: state
icon: mdi:monitor-speaker
sub_button:
  - entity: remote.android_tv_192_168_0_20
    show_attribute: false
    icon: phu:nvidia-shield
    tap_action:
      action: navigate
      navigation_path: "#shield"
    double_tap_action:
      action: perform-action
      perform_action: androidtv.adb_command
      target:
        entity_id: media_player.android_tv_192_168_0_20
      data:
        command: >-
          am start -a android.intent.action.VIEW -d -n
          com.nvidia.remotelocator/.RemoteLocatorActivity
    state_background: true
    show_background: false
  - entity: media_player.lg_tv
    icon: mdi:television
    show_attribute: false
    tap_action:
      action: navigate
      navigation_path: "#TV"
    show_background: false
  - entity: media_player.lg_tv
    select_attribute: source_list
    icon: mdi:video-input-hdmi
    show_background: false
  - entity: media_player.hyperceiver_2
    icon: mdi:audio-video
    tap_action:
      action: none
    hold_action:
      action: toggle
    state_background: true
    show_background: false
entity: media_player.lg_tv
show_state: true
modules:
  - default
scrolling_effect: false
show_attribute: false
show_last_changed: false
hold_action:
  action: perform-action
  target:
    entity_id: light.steckdose_tv
  perform_action: light.toggle
```

**Informations (please complete the following information):**  
 - Browser/App: Waterfix/Android App
 - Bubble Card version: beta 3
 - Home Assistant version: 2025.4.4

Thank you! 🍻
