### ISSUE TITLE
There's no response when I click the subbutton.

### ISSUE THREAD

**Issue by Pscharumbel** [Clooos/Bubble-Card#1439]
Clooos! Thank you for your amazing work! Home Assistant is a great platform—but it was never sexy. You changed that with your bubble cards! 🥰 However, with all 3 betas, I've had the problem that I can no longer click on the subbuttons (detail view). Occasionally—quite rarely—it works, but most of the time nothing happens. I use the companion app on my iPhone/iPad.

**Comment by Clooos** [comment]
Hi! And thank you for the feedback!

Can you provide a YAML example? Because all my sub-buttons are working 😅

**Comment by Pscharumbel** [comment]
Hi, quick update: It's working fine on my PC (with Firefox). On iOS, the Alexa Music subbutton is the most problematic. The other buttons work occasionally. Alexa only works on the first click—after that, no Alexa button on any other card works. No issues with 2.5 either, by the way.

```
card_type: button
icon: ""
show_name: false
scrolling_effect: false
sub_button:
  - entity: light.schranklicht_kuche_schranklicht
    icon: mdi:wall-sconce-flat
    name: Licht
  - icon: mdi:window-open-variant
    visibility:
      - condition: state
        entity: binary_sensor.fensterkontakt_kuche_kuchenverschluss_state
        state: "on"
    entity: binary_sensor.fensterkontakt_kuche_kuchenverschluss_state
    name: "Fenster "
  - entity: cover.rollladenaktor_kuche_kuchenfenster
    show_icon: true
    state_background: false
    name: Klima
  - icon: mdi:dishwasher
    show_icon: true
    state_background: true
    show_state: true
    show_attribute: false
    visibility:
      - condition: state
        entity: sensor.geschirrspuler_program_progress
        state_not: unavailable
    entity: sensor.geschirrspuler_restzeit
    name: Spülmaschine
  - entity: media_player.jens_echo_dot
    icon: mdi:music
    state_background: false
    name: Alexa
show_attribute: false
attribute: source
cover_background: true
button_type: state
show_icon: false
show_state: false
button_action:
  tap_action:
    action: none
  double_tap_action:
    action: none
  hold_action:
    action: none
styles: |2-
    .bubble-sub-button-4 {
      background-color: var(--bubble-default-color) !important;
    }
    .bubble-sub-button-5 {
      background-color: ${hass.states['media_player.jens_echo_dot'].state === 'playing' ? 'var(--bubble-default-color)' : ''} !important;
    }
use_accent_color: false
entity: light.schranklicht_kuche_schranklicht
double_tap_action:
  action: none
hold_action:
  action: none
tap_action:
  action: none
modules:
  - default
card_layout: normal
```

**Comment by Clooos** [comment]
Just to be sure, are you sure you've cleared the cache correctly in your browser and in the iOS app?

I really have no clue why the behavior is different between these two.

**Comment by Pscharumbel** [comment]
Yes, I'm sure. (Sorry! 🙈). I've now tried it with Edge (cleared the cache) and restarted HA. No problem on the PC (Windows), but the problem persists on the iPhone and two iPads despite clearing the cache.

**Comment by Pscharumbel** [comment]
Strange: In the preview of the editing window, the subbuttons work

**Comment by Clooos** [comment]
I will try to reproduce this on my iPad 🤞

**Comment by Pscharumbel** [comment]
Thanks for your effort! I'm surprised no one else has this problem... 
By the way, I opened HA in Safari on my iPad. The problem exists there too.

**Comment by Pscharumbel** [comment]
Hey Clooos, it's working now. I completely deleted the companion app and reinstalled it. Clearing the cache somehow didn't help. 🤷🏻‍♂️ Doesn't explain why it wasn't working in Safari either. 🤷🏻‍♂️ 
I hope I didn't waste too much of your time!

**Comment by Pscharumbel** [comment]
Oh shit, I was too happy too soon. It didn't install beta 3.4, but version 2.4. After I reinstalled the beta again, the subbuttons aren't working again. 😩

**Comment by Clooos** [comment]
I just tried on my iPad and I have this issue as well! That's a good start! It seems to happen only on sub-buttons with default actions (more info), and even on the main icon of some cards.

That's clearly a major issue 😅

**Comment by Pscharumbel** [comment]
Ah, good news! 😃

**Comment by Pscharumbel** [comment]
Great! Thank you very much! 🤩

**Comment by Clooos** [comment]
The new beta is here 😄

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-beta.5

**Comment by Pscharumbel** [comment]
Works wonderfully! 😍

**Comment by Clooos** [comment]
Yeah! Thank you for the quick feedback! 😄

**Comment by Pscharumbel** [comment]
Hey Clooos!
Beta 3.6 is causing problems with the subbuttons again. This time, however, it's not working on the iPad—it works on the iPhone. 
Best regards!

**Comment by Clooos** [comment]
Damn! I don't even remember having changed something with the actions, but I will check that on my iPad 🙂

**Comment by elliotcz97** [comment]
Today i also noticed this bug too! Hopefully it gets fixed soon! Btw amazing work!!

**Comment by Pscharumbel** [comment]
Unfortunately, I can't confirm that. Beta 7 also brought the bug to the iPhone. 😬🙈

**Comment by m3rguez0o** [comment]
Hello, I guess it's the same problem for me, I noticed yesterday that the sub buttons to choose the hvac mode doesn't work anymore.
Here is the yaml of a card if you can please check:

```
type: custom:bubble-card
card_type: climate
entity: climate.radiateur_anna
sub_button:
  - entity: sensor.radiateur_anna_electric_energy_consumption
    show_name: false
    show_last_changed: false
    show_state: true
    show_icon: true
    state_background: true
    show_background: false
    show_attribute: false
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: false
    show_arrow: false
    show_icon: true
show_attribute: true
state_color: true
show_state: false
show_last_changed: false
attribute: current_temperature
name: ""
card_layout: large
grid_options:
  columns: full

```
Thx in advance and thank you so much for your hard work! :)
