### ISSUE TITLE
Media Player Card does not show a power button

### ISSUE THREAD

**Issue by blueJack92** [Clooos/Bubble-Card#1440]
**Describe the bug**  
With the Media Player Card, the power button for switching on the device is not displayed. My device is the Google TV Streamer. The native Media Player Card from Home Assistant shows the button - so it's not the device.

**To Reproduce**  
1. add Bubble Media Player Card
2. select Google TV Streamer
3. save card

**Expected behavior**  
The Media Player Card not only displays a button to switch the device off, but also to switch it on.

**Screenshots**  
![Image](https://github.com/user-attachments/assets/367ea755-87d2-4c9d-9740-d6785a8326e2)
![Image](https://github.com/user-attachments/assets/7b97b00f-a4fb-40b4-904a-d355b7818367)

**YAML**  
```yaml
type: custom:bubble-card
card_type: media-player
modules:
  - default
entity: media_player.living_area_streaming_device
```

**Informations (please complete the following information):**  
 - OS: Windows, Android
 - Browser/App: Edge
 - Bubble Card version: 3.0.0-beta4
 - Home Assistant version: 2025.4.3
