### ISSUE TITLE
Remaining time for timer

### ISSUE THREAD

**Issue by timm68** [Clooos/Bubble-Card#1455]
Displaying the remaining time as subbutton does not work.
Thanks for the great work!

For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
Using the subbutton feature, show Attribute 
all other are working
remaining behaves like duration

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: button
name: Schatten für Hansi bis
show_state: false
show_attribute: false
tap_action:
  action: none
double_tap_action:
  action: none
hold_action:
  action: none
button_action:
  tap_action:
    action: none
  double_tap_action:
    action: none
  hold_action:
    action: none
sub_button:
  - entity: timer.schattentimer_fur_hansi
    show_state: false
    show_attribute: true
    show_background: true
    visibility: []
    state_background: true
    show_icon: true
    show_name: false
    attribute: remaining
icon: mdi:bird
styles: ""
entity: binary_sensor.sonneneinstrahlung_hansi
visibility:
  - condition: state
    entity: timer.schattentimer_fur_hansi
    state: active

```

**Informations (please complete the following information):**  
Bubble Card Version 2.4.0 
same issue on 
Windows 11, Chrome (Version 135.0.7049.115 (Offizieller Build) (64-Bit))
iOS App (latest)
Android App (latest)

 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻
