### ISSUE TITLE
Backdrop-Filter definitions not working in 3.0.0-beta.6

### ISSUE THREAD

**Issue by pedolsky** [Clooos/Bubble-Card#1469]
**Describe the bug**  
When using the Popup Card, version 2.4.0 blurs the background properly, version (tried also 3.0.0-beta.5 and 3.0.0-beta.4) not.

Version 2.4.0

![Image](https://github.com/user-attachments/assets/171b6e9c-4440-4d71-906d-17191e18abfb)

Version 3.0.0-beta.5 and beta.6

![Image](https://github.com/user-attachments/assets/fdeddf35-57e9-4749-ba75-e270fe785aa3)

**To Reproduce**  
1. Copy the below YAML code into a blank card
2. Trigger the popup

**Expected behavior**  
A blurred background as defined in the styles section

**YAML**  

```yaml

type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    name: Test
    icon: ""
    hash: "#test"
    trigger_entity: light.ankleide
    trigger_state: "on"
    trigger_close: true
    button_type: name
    styles: |-
      #root:not(.editor){
        top: 50% !important;
        transform: translate(0, -50%) !important;
        height: auto;
        max-height: 70vh !important;
        width: 97%;
        --desktop-width: 60vw !important;
        margin-left: auto !important;
        margin-right: auto !important;
        bottom: auto !important;
      }
      .bubble-pop-up-container{
        padding: 20px;
        mask-image: none;
      }
      .bubble-pop-up-background{
        border-radius: 8px;
        filter: brightness(600%);
      }
      .bubble-backdrop{
        transition-delay: 0;
        transition: opacity 0.2s;
        background-color: rgba(0,0,0,.3);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
      }
      .is-popup-closed { 
        opacity: 0;
        transition: opacity 0.4s !important;
      }
      .is-popup-opened, .is-popup-closed.editor {
        opacity: 1;
        transition: opacity 0.2s !important;
      }

  - type: custom:bubble-card
    card_type: separator
    name: Lampen
    icon: mdi:lightbulb-outline
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.kugellampe
        show_state: true
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.lounge
        show_state: true
  …
  …


```

**Informations (please complete the following information):**  
 - OS: iPadOS 18.4
 - Browser/App: Safari, Brave, mobile App
 - Bubble Card version: 3.0.0.-beta.5
 - Home Assistant version: 2025.5.1

Thank you! 🍻
