### ISSUE TITLE
Tap action on card not working

### ISSUE THREAD

**Issue by NyCreamZ** [Clooos/Bubble-Card#1472]
**Describe the bug**  
Tap action on card doesn't work. It's not written in the card code. For tap action, double tap action, hold action.

**To Reproduce**  
Create a bubble card,
Card Type: button (but also for others)
Button Type: Name/Text (all as well)
Tap action on card
     Tap action: navigate
     Browsing path: /cover

**Expected behavior**  
Perform the action on tapping the card. And write tap_action in the yaml code.

**YAML**  
```yaml
type: custom:bubble-card
card_type: button
button_type: name
modules:
  - default

```

**Informations (please complete the following information):**  
 - OS: [iOS, windows10]
 - Browser/App: [chrome, APP]
 - Bubble Card version: 2.4.0 and 3.0.0-beta.5
 - Home Assistant version: 2025.5.1

Thank you! Great job!🍻
