### ISSUE TITLE
[3.0.0-beta.6] Slider doesnt work as expected, when entity step size is not 1

### ISSUE THREAD

**Issue by robbelt** [Clooos/Bubble-Card#1478]
Slider doesn't work as expected when step size of the entity is not 1.
I tested with a input_number (helper) with min. value 0, max. value 1700, step size 100.
If I create a slider for this helper the value is not set correctly. Instead if I set the slider to something < 850 the entity is set to 0. If I set the slider to something > 851 the entity is set to the maximum of 1700.
If I change the step size of the helper to 1, everything is working fine.

```
- type: custom:bubble-card
        card_type: button
        name: Reserve
        icon: mdi:home-battery-outline
        button_type: slider
        sub_button: []
        entity: input_number.helfer_pv_reserve_fuer_akkuladung
        show_state: true
        styles: ""
        slider_live_update: false
        card_layout: normal
        show_attribute: false
        modules:
          - default
```

 - OS: Android, Windows
 - Browser/App: chrome
 - Bubble Card version: v3.0.0-beta.6
 - Home Assistant version: 2025.5.1
