### ISSUE TITLE
3.0.0-beta 6 custom element doesn`t exist

### ISSUE THREAD

**Issue by kimzeuner** [Clooos/Bubble-Card#1482]
**Describe the bug**  
After updating to v3.0.0 beta 6 bubble card is no longer shown on mobile device (iOS). In Chrome Browser the cards are still working but on mobile it says "custom element doesn`t exist: bubble-card".
Downgrading to beta 5 makes it work again.
Refreshing the page and also a HA restart doesn`t help.

**To Reproduce**  
1. Update to beta 6
2. Open HomeAssistant App on iPhone
3. failure mentioned in the description above is shown

**Expected behavior**  
Show Bubble Cards normal as e.g. in Beta 5

**YAML**  

```yaml
type: custom:bubble-card
card_type: separator
name: Erdgeschoss
icon: mdi:home-floor-0
sub_button:
  - entity: sensor.mittelwert_temperatur_eg
    show_state: true
    show_icon: false
    show_attribute: false
    show_background: false
    tap_action:
      action: none
card_layout: large
modules:
  - separator_floor_card

```

**Informations (please complete the following information):**  
 - OS: iOS 18.4.1
 - Browser/App: Chrome
 - Bubble Card version: 3.0.0 beta 6
 - Home Assistant version: 2025.5.1
