### ISSUE TITLE
Sub button moved in center of the card

### ISSUE THREAD

**Issue by userdema** [Clooos/Bubble-Card#1486]
**Describe the bug**  
I have a card with the "time to end" of a dryer in a sub button, with some CSS, in the latest betas, this sub button was moved to the left...

**Screenshots**  

![Image](https://github.com/user-attachments/assets/4289c8ce-1666-4b1e-9f9f-67e2178fe4e2)

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.aeg_asciugatrice_timetoend
name: "Asciugatrice "
icon: mdi:tumble-dryer
show_attribute: false
double_tap_action:
  action: none
hold_action:
  action: none
button_action:
  double_tap_action:
    action: none
  hold_action:
    action: none
styles: |-
  .bubble-icon-container {
    background-color: transparent;
    left: 50%
    }
  .bubble-icon {
    --mdc-icon-size: 65px !important;
    opacity: 0.06 !important;
    }
  .bubble-name-container {
    position: absolute;
    margin: 6%
    }
  .bubble-name {
    font-weight: 400;
    font-size: 15px;
  }
  .bubble-sub-button {
    font-weight: 350;
    font-size: 16px;
    }
  .bubble-button-card-container {
    overflow: hidden;
    }
visibility:
  - condition: state
    entity: sensor.aeg_asciugatrice_connectivitystate
    state: Connected
card_layout: large
grid_options:
  columns: 12
  rows: 1
show_state: false
sub_button:
  - entity: sensor.aeg_asciugatrice_timetoend
    show_background: false
    show_icon: false
    show_state: true
    visibility:
      - condition: state
        entity: sensor.aeg_asciugatrice_cyclephase
        state_not: Anticrease
  - entity: sensor.aeg_asciugatrice_cyclephase
    state_background: false
    show_background: false
    show_icon: false
    show_state: false
    show_name: true
    name: Antipiega
    visibility:
      - condition: state
        entity: sensor.aeg_asciugatrice_cyclephase
        state: Anticrease
modules:
  - default
  - 
```

**Informations (please complete the following information):**  
 - OS: [android]
 - Browser/App: [all]
 - Bubble Card version: [e.g. 3.0.0 beta 6]
 - Home Assistant version: [e.g. 2025.5.2]

Thank you! 🍻
