### ISSUE TITLE
Sub Button not functional

### ISSUE THREAD

**Issue by rlburgan** [Clooos/Bubble-Card#1489]
Sub buttons on both iOS display and in Chrome browser non-functional. Instead of listing options, the button just renders a "click" with a change in shading, but no list appears. I have observed this on the HVAC card for modes, as well as light cards, when trying to select a scene.

**Expected behavior**  
On the HVAC card, expected a dropdown of "Cool, Heat, Off, Eco"

<img width="492" alt="Image" src="https://github.com/user-attachments/assets/45970730-a432-4e21-9012-9f9ad0f9ebc1" />

**YAML**  

```yaml
type: custom:bubble-card
card_type: climate
entity: climate.nest_living_room
sub_button:
  - entity: climate.nest_living_room
    select_attribute: hvac_modes
state_color: false
force_icon: false
show_state: true
show_attribute: true
attribute: current_temperature
```

**Informations (please complete the following information):**  
 - OS: Sequoia 
 - Browser/App: Chrome
 - Bubble Card version: v2.4.0
 - Home Assistant version: 2025.5.1

Thank you! 🍻
