### ISSUE TITLE
Auto-scrolling to top when opening a pop-up

### ISSUE THREAD

**Issue by Neokimx** [Clooos/Bubble-Card#1495]
**Describe the bug**  
Within HA iOS App:
I have multiple bubble card buttons on my dashboard. The number of bubble cards is >15 which means I can scroll on my dashboard. When I click a card it opens a pop-up. 

This works after freshly refreshing the dashboard via the "pull-down-to-refresh" gesture on iOS. But after some time (or closing and reopening the app without "refresh") i get a "scroll-to-top" bug. This means that if I click one of the last/bottom cards the pop-up opens but the dashboard in the background automatically scrolls to the top. This behavior can be fixed by refreshing the app but will happen again after some time or closing and reopening the app (without the pull-to-refresh gesture)

I have made a screen recording of the problem:
[https://streamable.com/0mblee](https://streamable.com/0mblee)

In the video I have an empty dashboard with "only" 15 bubble cards and one pop-up in one section. All bubble cards have the same config. They all open the single pop-up when tapping on card. They just differ by name to see the effect of auto scrolling. In the video I click on two of the upper cards where I did not need to scroll down to see them. After that I scroll down to the bottom cards. Then I click on two of the bottom cards and as you can see the dashboard in the background "auto-scrolls" to the top. I added the dashboard config in the issue. I tried to eliminate all potential error sources and therefore created an empty test dashboard, didn't add any entities and disabled my theme.

**To Reproduce**  
1. Create a dashboard with 15 or more bubble cards in one section (may take my dashboard raw config from below)
2. Create a pop-up card within the same section
3. Set "tap-on-card" action of all 15 cards to "Navigate" with the URL of the one pop-up
4. Scroll down to the last bubble card and click on the card to open the pop-up
5. See the auto-scrolling to top

**Expected behavior**  
No auto-scrolling to the dashboard top in the background.

**Screenshots**  
See video above.

**YAML**  
```yaml
views:
  - title: Home
    type: sections
    max_columns: 4
    sections:
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 1
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 2
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 3
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 4
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 5
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 6
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 7
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 8
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 9
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 10
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 11
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 12
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 13
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 14
            icon: mdi:test-tube
          - type: custom:bubble-card
            card_type: button
            button_type: name
            modules:
              - default
            entity: weather.openweathermap
            button_action:
              tap_action:
                action: navigate
                navigation_path: '#test1'
            name: Card 15
            icon: mdi:test-tube
          - type: vertical-stack
            cards:
              - type: custom:bubble-card

Can someone reproduce this behavior on his iOS device? 
                card_type: pop-up
                hash: '#test1'
                button_type: name
                modules:
                  - default
                name: Test Pop-up
                icon: mdi:test-tube

```

**Informations (please complete the following information):**  
 - OS: iOS
 - Bubble Card version: 3.0.0beta5
 - Home Assistant version: 2025.4.4
