### ISSUE TITLE
"card_layout: large-sub-buttons-grid" not working

### ISSUE THREAD

**Issue by ManuelSteinfels** [Clooos/Bubble-Card#1500]
**Describe the bug**  

- When I use your code example "A large button with multiple rows with 12 sub-buttons" from the docu the buttons are all displayed in the same row. There is no second row. Even though the card height changes when changing the value of "rows".
- And I'missing this option (large-sub-buttons-grid) including the setting for the number of rows in the visual editor.

**To Reproduce**  
Use the config YAML shown in the example and use the card in a section, or inside a popup or on other dashboard type.

**Expected behavior**  
It should look like this:
![Image](https://github.com/user-attachments/assets/013cf355-c51d-4bf6-a65f-8332c89e6db5)

**Screenshots**  
It does look like this.
![Image](https://github.com/user-attachments/assets/51a40bd1-5a41-4f6d-b4f9-afb988dff7a6)

**YAML**  
```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: sun.sun
card_layout: large-sub-buttons-grid
grid_options:
  rows: 3
sub_button:
  - entity: sun.sun
    icon: mdi:numeric-0
  - entity: sun.sun
    icon: mdi:numeric-1
  - entity: sun.sun
    icon: mdi:numeric-2
  - entity: sun.sun
    icon: mdi:numeric-3
  - entity: sun.sun
    icon: mdi:numeric-4
  - entity: sun.sun
    icon: mdi:numeric-5
  - entity: sun.sun
    icon: mdi:numeric-6
  - entity: sun.sun
    icon: mdi:numeric-7
  - entity: sun.sun
    icon: mdi:numeric-8
  - entity: sun.sun
    icon: mdi:numeric-9
  - entity: sun.sun
    icon: mdi:numeric-10
  - entity: sun.sun
    icon: mdi:numeric-negative-1
```

**Informations (please complete the following information):**  
 - OS: Windows 11
 - Browser/App: chrome
 - Bubble Card version: 2.4.0
 - Home Assistant version: 2025.5.1

**Additional context**  
- none

Thank you! 🍻
