### ISSUE TITLE
3.0.0-beta.7 select isn't always adhering to state

### ISSUE THREAD

**Issue by Daniel-dev22** [Clooos/Bubble-Card#1501]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
_https://github.com/Clooos/Bubble-Card/discussions/categories/q-a_

**Describe the bug**  

Sometimes select entities are being shown with the incorrect entity state.

Sometimes it works sometimes I notice if I close the window and come back or open a more info dialog then close it the select entity is showing the wrong state.

**To Reproduce**  
1. Create select entity with multiple options
2. Select an option
3. Leave window or open more info and notice sometimes the state reverts to another option 

**Expected behavior**  

Select entity always matches entity state.

**Screenshots**  

https://github.com/user-attachments/assets/c551b013-52d9-4959-90d1-d28bade1e5d4

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#ansible_manage_custom_web_app_images"
    name: Manage Custom Web App Images
    icon: phu:portainer
    margin_top_mobile: 0px
    margin_top_desktop: 28px
    width_desktop: 75%
    button_type: name
    modules:
      - default
  - type: custom:bubble-card
    card_type: select
    show_state: true
    entity: input_select.target_servers
    modules:
      - default
  - type: custom:bubble-card
    card_type: select
    show_state: true
    name: Build Option
    modules:
      - default
    entity: input_select.ansible_custom_web_app_image_build_option
  - type: custom:bubble-card
    card_type: select
    show_state: true
    modules:
      - default
    entity: input_select.ansible_create_portainer_docker_registry
  - type: vertical-stack
    cards:
      - type: conditional
        conditions:
```

**Informations (please complete the following information):**  
 - OS: Android 15
 - Browser/App: companion app
 - Bubble Card version: 3.0.0-beta.7
 - Home Assistant version: 2025.5.1

**Additional context**  

Thank you! 🍻
