### ISSUE TITLE
Trigger-based popup pops up when leaving edit view

### ISSUE THREAD

**Issue by pedolsky** [Clooos/Bubble-Card#1511]
I've created a trigger-based popup. Trigger is an input boolean. After editing the view and leaving the edit mode, the card pops up without being triggered.

**To Reproduce**  
1. Copy code below
2. Save
3. Switch to edit view
4. Leave edit view

**Expected behavior**  
The card shouldn’t popup without being triggered

**YAML**  

```yaml

type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    name: ""
    icon: ""
    hash: "#warnung"
    button_type: name
    show_header: true
    modules:
      - default
    backdrop_blur: "10"
    trigger:
      - condition: state
        entity: input_boolean.test
        state: "on"
    card_layout: normal
    close_by_clicking_outside: false
    close_action:
      action: perform-action
      perform_action: homeassistant.toggle
      target:
        entity_id: input_boolean.test
  - type: markdown
    content: >
      <h2>Test</h2>

```

**Informations (please complete the following information):**  
 - OS: [e.g. iOS] iPadOS
 - Browser/App: [e.g. chrome, safari] Brave
 - Bubble Card version: [e.g. 2.0.4] 3.0.0-beta.7
 - Home Assistant version: [e.g. 2024.6.4] 2025.5.1
