### ISSUE TITLE
Climate card - Scrolls when large-2-row and dropdown menu at bottom

### ISSUE THREAD

**Issue by StaleLoafOfBread** [Clooos/Bubble-Card#1513]
**Describe the bug**  
When you scroll past a climate card it will scroll the card within its own container. This only happens sometimes. I _think_ what's required is that a menu subbutton is at the bottom and that it is `large-2-row`. My example yaml will reproduce it.

**To Reproduce**  
1. Use my yaml example but replace `climate.thermostat` with your own climate entity. 
2. Scroll with your mouse hovered over the bubble card.

**Expected behavior**  
No scrolling.

**Screenshots**  

![Image](https://github.com/user-attachments/assets/4c021fe4-f976-468e-8d92-a5bc570406a7)

**YAML**  

```yaml
type: custom:bubble-card
card_type: climate
modules:
  - default
entity: climate.thermostat
sub_button:
  - entity: climate.thermostat
    show_attribute: true
    name: State
    show_state: true
    tap_action:
      action: none
    show_background: false
  - entity: climate.thermostat
    name: Current Temperature
    icon: mdi:thermometer
    state_background: true
    show_attribute: true
    attribute: current_temperature
    tap_action:
      action: none
    show_background: false
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: true
    show_arrow: false
    show_attribute: false
    show_background: true
  - name: Presets
    select_attribute: preset_modes
    state_background: true
    show_arrow: false
    show_name: false
    show_state: false
    show_attribute: false
    attribute: preset_mode
force_icon: false
show_name: true
show_state: false
show_last_changed: false
show_attribute: false
attribute: hvac_action
rows: "1"
card_layout: large-2-rows
show_last_updated: true
show_icon: true
scrolling_effect: true
button_action: {}
state_color: false
```

**Informations (please complete the following information):**  
 - OS: Windows 11 & Android
 - Browser/App:  `chrome`
 - Bubble Card version: `v3.0.0-beta.7`
 - Home Assistant version: `2025.5.2`

**Additional context**  
The following CSS fixes the issue but breaks the menu subbuttons. 

```css
.bubble-climate {
	overflow: hidden;
}
```

Thank you! 🍻
