### ISSUE TITLE
Button card 'tap action on button' action not working correctly.

### ISSUE THREAD

**Issue by ghxstxch** [Clooos/Bubble-Card#1516]
**Describe the bug**  
When attempting to change the action for tap action 'on button', it seems it does not correctly apply the behavior to the 'on button' action. Saving and refreshing the page causes the tap action 'on button' to revert back to 'Default' 

**To Reproduce**  
1. Create button
2. Attempt to change action. 
3. Hit Save/Done

**Expected behavior**  
Tapping on the button to do the expected action. 

**Screenshots**  
N/A, but can add any if needed

**YAML**  
```
type: custom:bubble-card
card_type: button
button_type: state
entity: weather.pirateweather
tap_action:
  action: navigate
  navigation_path: "#weather"
```

**Informations (please complete the following information):**  
 - OS: Debian (Host) 
 - Browser/App: All
 - Bubble Card version: [2.4.0
 - Home Assistant version: [2025.5.1]
