### ISSUE TITLE
Popup header name shown multiple times with streamline templates (bubble card: 3.0.0-beta 7)

### ISSUE THREAD

**Issue by ErikT80** [Clooos/Bubble-Card#1520]
**Describe the bug**  
Header name in popup is shown multiple times when using streamline card together with bubble-card popup

**To Reproduce**  
1. On a dashboard configured through the UI add:
```
streamline_templates:
  cover_popup_card:
    card:
      type: vertical-stack
      cards:
        - type: custom:bubble-card
          background_update: false
          card_layout: normal
          force_icon: false
          show_icon: false
          bg_opacity: '100'
          card_type: pop-up
          hash: '#kitchen-covers'
          button_type: name
          modules:
            - default
          show_header: true
          name: Shutters
```

to the top of the page (just like any other streamline template.

2. Add a streamline card with cover_popup_card template to the same dashboard:
```
type: custom:streamline-card
template: cover_popup_card
variables: {}

```

3. Add a simple button that will trigger the popup:
```
show_name: true
show_icon: true
type: button
entity: light.light
name: Open popup
tap_action:
  action: navigate
  navigation_path: "#kitchen-covers"

```
4. Open de popup by clicking the button, after this go into edit mode on the dashboard and go out of it directly. Click the button again to open the popup and you will see the header name twice. You can do this multiple times and the header name will be added 3,4,5 etc times depending on how many times you do this.

**Expected behavior**  
Only show the header once

**Screenshots**  

<img width="569" alt="Image" src="https://github.com/user-attachments/assets/1688d1de-8069-41cb-ae83-10dd1896228d" />

**YAML**  
See 'How to reproduce'

**Informations (please complete the following information):**  
 - OS: Android, MacOS
 - Browser/App: Chrome, Home assistant Companion app
 - Bubble Card version: 3.0.0 beta 7
 - Home Assistant version: 2025.5.2

This issue also happens on yaml configured dashboards and streamline templates configured in yaml.
