### ISSUE TITLE
Button_action actions does not populate in yaml when edited with the UI

### ISSUE THREAD

**Issue by ThePastPlayer** [Clooos/Bubble-Card#1523]
**Describe the bug**  
When creating a Bubble card button from the UI, the 'Tap action on icon' settings gets written in YAML, but the 'Tap action on button' doesn't

**To Reproduce**  
1. Create a Bubble Card
2. Card Type : Button
3. Button Type : Switch
4. Select one of your switches
5. Under 'Tap action on icon' > Set 'Tap Action' , 'Double ta action' and 'Hold action' to 'More Info'
6. Under 'Tap action on button' > Set 'Tap Action' , 'Double ta action' and 'Hold action' to 'More Info'
7. Press Show YAML (Yaml below)

```
type: custom:bubble-card
card_type: button
entity: switch.entityid
double_tap_action:
  action: more-info
hold_action:
  action: more-info
tap_action:
  action: more-info
```

**Expected behavior**  
```
type: custom:bubble-card
card_type: button
entity: switch.entityid
double_tap_action:
  action: more-info
hold_action:
  action: more-info
tap_action:
  action: more-info
button_action:
  double_tap_action:
     action: more-info
  hold_action:
     action: more-info
  tap_action:
     action: more-info
```

**Informations:**  
 - OS: [IOS, Windows]
 - Browser/App: [Firefox,Chrome]
 - Bubble Card version: [2.4.4]
 - Home Assistant version: [2025.5.2]

Thank you very much otherwise for this awesome project! 🍻
