### ISSUE TITLE
Climate Card - Termostat/Air Conditioning sub-button doesn't work

### ISSUE THREAD

**Issue by octavianolteanu** [Clooos/Bubble-Card#1526]
**Describe the bug**  
After the last update the cards for air conditining/termostats don't work when I click on the small button to change the state. Only if I change to open the "more info" modal. If I click on the mode button it doesn't open the dropdown with (Cool, Heat, Dry, Fan, etc). 

**To Reproduce**  
1. Add the bubble-card
2. Click on the sub-button that opens the mode dropdown

**YAML**  
```
type: custom:bubble-card
card_type: climate
entity: climate.midea_ac_123
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: false
    show_arrow: false
name: AC
show_attribute: false
show_last_changed: false
show_state: false
icon: mdi:air-conditioner
tap_action:
  action: more-info
double_tap_action:
  action: none
hold_action:
  action: more-info
card_layout: large
state_color: true
```

**Informations (please complete the following information):**  
 - OS: ios
 - Browser/App: Chrome
 - Bubble Card version: 2.4.0
 - Home Assistant version: 
Installation method: Home Assistant OS
Core: 2025.5.2
Supervisor: 2025.05.1
Operating System:15.2
Frontend: 20250516.0

Thank you! 🍻
