### ISSUE TITLE
Climate card - sub-button doesn't work

### ISSUE THREAD

**Issue by Ivkaiv** [Clooos/Bubble-Card#1532]
Today I decided to start my pop-up dashboard creating and found a problem. The climate card doesn't work properly, For example, my waterheater is ok with bubble, but AC is not - the problem is sub-button, which even doesn't open dropdown menu with AC states or any other options. Just clicking on it and nothing happens. Other cards as mushroom or stock HA climate are working well.

1. Create bubble-card for climate
2. Add sub-button for choosing modes (cooling, heating, etc)
3. Save it and tap on in
4. Nothing happens

Also, I noticed, that "tap action" setting appears gray, so I can't configure it. I tried to add this through text mode editing, but it doesn't help.

![Image](https://github.com/user-attachments/assets/45d63443-f970-46f5-be24-f808cac17c6d)

```yaml
type: custom:bubble-card
card_type: climate
entity: climate.kitchen_ac_kitchen_ac
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: false
    show_arrow: false
```

 - OS: HA OS
 - Browser/App: Chrome and Mobile App
 - Bubble Card version: 3.0.0 beta 7
 - Home Assistant version: 2025.5.3

Thank you! 🍻
