### ISSUE TITLE
Climate Card's Preset Mode Dropdown doesn't update

### ISSUE THREAD

**Issue by StaleLoafOfBread** [Clooos/Bubble-Card#1536]
**Describe the bug**  
When using the presets subbutton dropdown, it won't update its value when changed from external sources such as an automation.

**To Reproduce**  
1. Create a climate card with the `Preset` subbutton
2. Change the preset via another tab
3. Observe that the preset selection is not updated on the card

**Expected behavior**  
Preset dropdown to update on state (attribute) change

**Screenshots**  

**YAML**  
``` yaml
type: custom:bubble-card
card_type: climate
modules:
  - default
sub_button:
  - entity: climate.thermostat
    select_attribute: preset_modes
entity: climate.thermostat
```

**Informations (please complete the following information):**  
 - OS: Windows 11 & Android
 - Browser/App:  `chrome`
 - Bubble Card version: `v3.0.0-beta.7`
 - Home Assistant version: `2025.5.2`

**Additional context**  
If you don't have a climate entity, you can make one via helpers. Mine is created this way.

Thank you! 🍻
