### ISSUE TITLE
Saving own actions for button doesn't work

### ISSUE THREAD

**Issue by KoMa1012** [Clooos/Bubble-Card#1545]
**Describe the bug**  
Button doesn't store button click actions.

**To Reproduce**  
1. Create a button of type state
2. set for "Tap action on icon" "perform action" select a script, set the data field
3. set for "Tap action on Button" "perform action" select a script, set the data field
4. save
5. edit same button => only Tap action on Icon is saved, the other went back to default
6. close the edit window
7. click on the button => opens more info
8. click on icon => perform action

**Expected behavior**  
it stores icon tap and button tap and both are working.
1. Create a button of type state
2. set for "Tap action on icon" "perform action" select a script, set the data field
3. set for "Tap action on Button" "perform action" select a script, set the data field
4. save
=> Button runs Tap Icon command if icon is being tapped and runs Tap Button if Button ist being tapped.

**YAML**  
Yaml example after point 4:
```yaml
  - type: custom:bubble-card
    card_type: button
    button_type: state
    entity: input_number.cnt
    tap_action:
      action: perform-action
      perform_action: script.cnt
      target: {}
      data: input_number.cnt
    grid_options:
      rows: 1
      columns: 4
```
interestingly it's storing it as "tap_action" and not as "tap_icon_action"

**Informations (please complete the following information):**  
 - OS: ubuntu
 - Browser/App: Firefox
 - Bubble Card version: 2.4.0
 - Home Assistant version: 2025.5.3 (in docker container)
