### ISSUE TITLE
Module not getting saved

### ISSUE THREAD

**Issue by dpeter99** [Clooos/Bubble-Card#1549]
**Describe the bug**  
When I add a new module and change it, the module is shown while the editor is opne but gets lost when closing the card editor.

**To Reproduce**  
1. Open a card editor
2. Add a module by importing it using the YAML import
3. Add a change to the options
4. Save the module
5. Save the card
6. Open the card editor again

**Expected behavior**  
It shoud still be there and have the cahnges

**Screenshots**  
https://github.com/user-attachments/assets/11d1729f-6740-4a69-9c4e-c62d625de0c8

**Informations (please complete the following information):**  
 - OS: Linux Fedora KDE
 - Browser/App: Chrome
 - Bubble Card version: 3.0.0-beta9
 - Home Assistant version: 2025.5.3

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! Thank you for that detailed feedback! I will check that!

**Comment by Clooos** [comment]
I just fixed this issue, thanks again for the feedback!

**Comment by Clooos** [comment]
I just release v3.0.0-rc.1, let me know if this is fixed! 😄

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-rc.1

**Comment by Poyaan** [comment]
> I just release v3.0.0-rc.1, let me know if this is fixed! 😄
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-rc.1

I tried to add a module by importing a yaml code. It's imported successfully it said, but when i save the card and edit again the new module are gone.

3.0.0 rc1

**Comment by Clooos** [comment]
Can you confirm you see v3.0.0-rc.1 at the bottom of the editor? Some pre-release are not correctly updated with the current HACS version.

**Comment by alaneurich** [comment]
I seem to be having an at least similar issue.

When downloading a module from the store I see it added to the list of modules but after saving the card, it’s just gone.

I also can’t enable it for all cards at all. Also interesting and maybe related: Whenever I open the card editor I see the “module installed successfully” snack bar.

I’m on rc-1, also tried reinstalling from scratch without success.

If you need any debugging done on my end lmk. Thanks for the awesome work. Big fan 😊

**Comment by Poyaan** [comment]
> Can you confirm you see v3.0.0-rc.1 at the bottom of the editor? Some pre-release are not correctly updated with the current HACS version.

Yes it says 3.0.0 rc1 in the editor.
Im very new to this module thing so it could be me doing something wrong too 😁
Im not even sure where my modules are supposed to be stored..😁

**Comment by Clooos** [comment]
I will check that again, of course modules should be stored in all cases 😄

**Comment by Poyaan** [comment]
> I will check that again, of course modules should be stored in all cases 😄

I mean, in which file are the downloaded modules stored? bubble-modules.yaml seems to store only the default one. I download another module "sub button below" but it doesnt exist in that yaml file which i thought it should. But as i said. I may have done something wrong.

The only thing i did was to add the yaml to my configuration.yaml then it could start using the module. Or which is the correct installation process?

**Comment by Clooos** [comment]
This is the way, the bubble-modules.yaml file is not required, this file is for users who don't want to use the editor at all.

In your case, all modules are stored in the sensor your created in your configuration.yaml 🙂

**Comment by Poyaan** [comment]
> This is the way, the bubble-modules.yaml file is not required, this file is for users who don't want to use the editor at all.
> 
> In your case, all modules are stored in the sensor your created in your configuration.yaml 🙂

Ah ok i see 👍🏻
Are the sensor needed to be i configuration.yaml?

I have this line of code in configuration.yaml
##
template:
- binary_sensor: !include_dir_merge_list entities/templates/binary_sensors
- sensor: !include_dir_merge_list entities/templates/sensors
##

And keep my sensors in seperate single yaml files in /entities/templates/sensors/

But when added your sensor in my configuration.yaml i get some duplicate warning.
So i ended removing my line of code to get the module store working.

Do you know how to keep your sensor in my external dir as all my other (2 😅 sensors) 😁

**Comment by Clooos** [comment]
I guess this should works as well, I'm not splitting my configuration.yaml so I'm not sure.

The duplicate issue is maybe because you haven't removed `template:` in the YAML to paste, or something like that.

**Comment by Poyaan** [comment]
> I guess this should works as well, I'm not splitting my configuration.yaml so I'm not sure.
> 
> The duplicate issue is maybe because you haven't removed `template:` in the YAML to paste, or something like that.

Thanks! I'll check if i can sort it out 👍🏻😀

**Comment by Sholofly** [comment]
I'm experiencing this issue as well. Install the HA default config module, is available until i save. Gone when reloading. 
I'm also splitting my config in packages. In this case I have a folder called integrations. One of the files is templates.yaml  that looks like this:

```yaml
template:
  - sensor: !include_dir_list ../entities/templates/sensors
  - binary_sensor: !include_dir_list ../entities/templates/binary_sensors
  - select: !include_dir_list ../entities/templates/selects
  - trigger:
      trigger: event
      event_type: set_camera_description
    sensor:
      - unique_id: 4a4c8e53-9e68-4198-9cc5-b336e228ea4d
        name: Camera detection
        state: "{{trigger.event.data.key}}"
        attributes:
          full_description: "{{ trigger.event.data.value}}"
  - trigger:
      - trigger: event
        event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        icon: "mdi:puzzle"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"
```

**Comment by Kirello** [comment]
I'm experiencing the same issue. I can install modules from the store and they work fine, but when I create my own module, click save, and then reload or reopen the page, it disappears.

**Comment by Clooos** [comment]
@Kirello Indeed, I had this issue as well yesterday, but only with an incomplete module, I wanted to try some forms for the editor, without any code in the code field, and it disappears in that case. Try again by filling all fields (the editor field is optional).

I will do my best to fix this in the next release 🙂

**Comment by Kirello** [comment]
@Clooos Thank you for your reply! Indeed, once I filled in all the fields, it saved successfully. I suspect that I hadn’t filled in the "creator" field before, because I definitely provided the code and description, and it didn’t work.

**Comment by Sholofly** [comment]
I think my issue is different. If i install the module it's there. I can't click the all cards option then.
As soon as i reload the page the module isn't installed anymore.

**Comment by Clooos** [comment]
@Sholofly if you have the bubble-modules.yaml, remove it. Having both the YAML file and the template sensor can lead to this issue. You just need the sensor in your case 🙂

**Comment by Sholofly** [comment]
No, i've only the example variant in my  community/Bubble-Card folder..

**Comment by sobchek** [comment]
Similar problem. It doesn't even make it to saving. I can download module from the store, and as soon as I change a parameter, the module disappears. It still says downloaded when I go back to the store.

**Comment by Scoobler** [comment]
> Similar problem. It doesn't even make it to saving. I can download module from the store, and as soon as I change a parameter, the module disappears. It still says downloaded when I go back to the store.

If you have added the yaml snippet, be careful how you’ve added it.
I have a templates.yaml as an include, I have my sensors and binary sensors separated from each other so I only have the `- sensor:` heading once. 
So when I added the required yaml I made the mistake of adding a `- trigger:` section and moving the sensor under the current sensors section - everything showed up in HA, I could see the sensor under developers tool and monitoring the event I could see things being triggered, just the two were not linked so although it would say it’s downloaded, it would just disappear when I tried to do anything else.

```
  - trigger:
     - platform: event
       event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules”
        state: "saved"
```

Note there is no - before the `sensor:` part, so I moved that section from where my other sensors are listed and put it back to how it is shown and it started working as expected.
