### ISSUE TITLE
select_attribute drop down appearing inside of card

### ISSUE THREAD

**Issue by StaleLoafOfBread** [Clooos/Bubble-Card#1559]
**Describe the bug**  
If you have two `select_attribute` subbuttons and click on one while the other is currently displaying its menu, then the new menu appears inside of the bubble card. See screen recording.

**To Reproduce**  
1. Create a climate card with two drop downs
2. Click on one drop down to make the menu appear
3. Click on the other drop down and now the new menu appears inside the bubble card

**Expected behavior**  
Dropdown to not be located inside the bubble card.

**Screenshots**  

![Image](https://github.com/user-attachments/assets/c4cdec7d-dcaa-40e0-9c73-980e818e9864)

**YAML**  
```yaml
type: custom:bubble-card
card_type: climate
modules:
  - default
entity: climate.thermostat
sub_button:
  - entity: climate.thermostat
    select_attribute: hvac_modes
  - entity: climate.thermostat
    select_attribute: preset_modes
force_icon: false
show_name: false
show_state: false
show_last_changed: false
show_attribute: false
attribute: hvac_action
rows: "1"
card_layout: large
show_last_updated: false
show_icon: true
scrolling_effect: false
button_action: {}
```

**Informations (please complete the following information):**  
 - OS: `windows 10`
 - Browser/App: `chrome`
 - Bubble Card version: `v3.0.0-beta.9`
 - Home Assistant version: `2025.5.3`

**Additional context**  

Thank you! 🍻
