### ISSUE TITLE
read_only_slider-option for the slider button has no effect

### ISSUE THREAD

**Issue by Soukyuu** [Clooos/Bubble-Card#1568]
**Describe the bug**  
The YAML option `read_only_slider` seems to have no effect

**To Reproduce**  
1. Create a slider button
2. Assign to any numeric entity
3. Add `read_only_slider: true` to the card as a YAML parameter
4. Attempt to change slider value
5. Value changes despite `read_only_slider`

**Expected behavior**  
Value not changing because `read_only_slider` is set

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: input_number.uv_1h
show_state: true
name: UV Index
styles: >-
  * {
    --bubble-border-radius: 8px;
  }

  .bubble-range-fill {  
    background-color: rgba(${state > 7.0 ?  '190, 0, 0' : state > 3.5 ? '255, 150, 0' : '0, 80, 0'}, 0.4) !important;
  }

  .bubble-icon {
    color: ${state > 7.0 ? 'red' : state > 3.5 ? 'orange' : 'green'} !important;
  }


  ${card.querySelector('.bubble-state').innerText = state + ' / ' +
  hass.states['sensor.uv_maximaler_uv_index'].state}
card_layout: large
show_last_changed: false
read_only_slider: true
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: 3.0.0-beta9
 - Home Assistant version: 2025.5.3

**Additional context**  
I saw the option in multiple examples of configurations, but it seems to be missing in the docs? Was it maybe removed? It'd be pretty useful to me.
