### ISSUE TITLE
Tap Button on slider card-> more Info (details) doesnt work.

### ISSUE THREAD

**Issue by Nico1300** [Clooos/Bubble-Card#1579]
When i set the tap Action on a slider card to more details it doesnt get saved.

1. Create new bubble card slider button
2. Set Tap Action on Button to more Details
3. Save everything and click on the switch.
4. It doesnt open the details view, instead it turns of the switch.

**Expected behavior**  
Open the details page

**YAML** 
This is my YAML, the switch however and all settings were made by the gui.

```yaml
type: custom:bubble-card
card_type: button
button_type: switch
name: HELIOS  NICO-PC
icon: mdi:toggle-switch-variant
scrolling_effect: true
show_icon: true
force_icon: false
show_name: true
show_state: true
show_last_changed: false
show_attribute: false
double_tap_action:
  action: more-info
hold_action:
  action: more-info
styles: |2-
   .bubble-button-card-container {
        border-radius: 7px;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.3)
      }

   .bubble-button-background {
    border-radius: 7px;
  }
grid_options:
  columns: 6
  rows: 1
card_layout: normal
sub_button: []
entity: switch.helios
use_accent_color: false
slider_live_update: true
tap_action:
  action: more-info
```

**Informations (please complete the following information):**  
 - OS: Browser (Windows)
 - Browser/App: Floorp (Firefox Fork)
 - Bubble Card version: 2.0.4
 - Home Assistant version: 2025.5.3
