### ISSUE TITLE
v3.0.0-beta9 Hold Action combined with Navigate works just once

### ISSUE THREAD

**Issue by josefkgit** [Clooos/Bubble-Card#1582]
1. Create bubble card button
2. Set hold_action to navigate to a page in the **same** dashboard

**Expected behavior**  
navigate to the page every time, I use the hold_action

Instead: 
Navigate to the page works one time, after that no action at all is possible.
It's the same for the button, the card and the sub-buttons.

Navigation with tap_action works everytime.
After Strg+F5  hold_action works again once.
no problems with hold_action and navigate to a **different** dashboard

YAML:

```yaml
type: custom:bubble-card
card_type: button
name: Zimmer
entity: sensor.zi_24_klima_temperature
button_type: state
tap_action:
  action: navigate
  navigation_path: /dashboard-test/raumtest
hold_action:
  action: navigate
  navigation_path: /dashboard-test/raumtest
button_action:
  tap_action:
    action: navigate
    navigation_path: /dashboard-test/raumtest
  hold_action:
    action: navigate
    navigation_path: /dashboard-test/raumtest
```

**Informations (please complete the following information):**  
 - OS: Windows 11 / Android
 - Browser/App: chrome, edge, HomeAssistant App
 - Bubble Card version: 3.0.0-beta9
 - Home Assistant version: 2025.5.3

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! I just tried and I was unable to reproduce this issue, so I maybe fixed it by fixing some other issues on the build I'm currently working on 🤞

**Comment by josefkgit** [comment]
Thank you for your answer, and happy to hear that the problem will be fixed with the next version!

**Comment by Clooos** [comment]
I just release v3.0.0-rc.1, let me know if this is fixed! 😄

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-rc.1

**Comment by josefkgit** [comment]
Thank you for your hard work and the new release.
I did download it and restarted Home Assistant.
I do still have the same problem.
I created a small dashboard for testing named db-Test: 

```yaml
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: switch
            entity: sensor.zi_11_bewegung_device_temperature
            name: Flur
            force_icon: false
            modules: []
            button_action:
              tap_action:
                action: more-info
              hold_action:
                action: navigate
                navigation_path: /db-Test/temperaturen
            hold_action:
              action: navigate
              navigation_path: /db-Test/temperaturen
  - type: sections
    path: temperaturen
    max_columns: 3
    title: Temperaturen
    icon: mdi:home-thermometer-outline
    dense_section_placement: true
    sections:
      - type: grid
        cards:
          - type: tile
            features_position: bottom
            vertical: false
            entity: sensor.zi_11_bewegung_device_temperature
        column_span: 3
    badges: []
    subview: true
    cards: []
```

I did test it in edge, firefox and chrome in Windows 11.
I did test it in the app and in Fully Kiosk Browser at my android tablet.

After any hold_action and going back to the first site, I can't use the icon or card anymore.
It only works after STRG+F5 again.
