### ISSUE TITLE
Icon color of light entity of after "change device type of a switch"

### ISSUE THREAD

**Issue by vzvl** [Clooos/Bubble-Card#1598]
**Describe the bug**
When turning switch entities off, the icon flashes blue for a brief moment. The blue seems to the default icon color for switches when no .bubble-icon { color: !important } attribute is set.

Furthermore, switch entities that are converted to a light entity via a helper ("change device type of a switch") do not change their icon color, even when .bubble-icon { color: !important } is set. When the toggle "Use accent color instead of light color" is used, the on icon color will be the default blue color, even if .bubble-icon { color: !important } is set.

**To Reproduce**  
1. Create a helper light based on a switch
2. Assign a custom bubble-icon color
3. Switch the light on
4. Icon is grey when light is on
5. IF "Use accent color instead of light color" is enabled
6. Icon is blue when light is on

**Expected behavior**  
The icon color should respect the .bubble-icon { color: !important } value.

**YAML**
Bubble card:

```yaml
  - type: custom:bubble-card
    card_type: button
    entity: light.stehleuchte
    name: ""
    icon: ""
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: none
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#pop-up-stehleuchte"
      double_tap_action:
        action: none
      hold_action:
        action: none
    card_layout: large
    show_last_changed: true
    sub_button:
      - tap_action:
          action: navigate
          navigation_path: "#pop-up-stehleuchte"
        show_background: false
        icon: mdi:dots-vertical
    styles: |-
      .bubble-button-background {
          opacity: 0.2 !important;
          background-color: ${state === 'on' ? '#ffc107' : ''} !important;
        }
      .bubble-icon {
          color: ${state === 'on' ? '#ffc107' : ''} !important;
    scrolling_effect: true
    use_accent_color: false
    button_type: switch
    force_icon: false
    show_name: true
    show_icon: true
    show_state: false
    show_attribute: false
    show_last_updated: false
```

**Informations (please complete the following information):**  
 - OS: iOS
 - Browser/App: Firefox
 - Bubble Card version: 3.0.0-rc1
 - Home Assistant version: 2025.6.1
