### ISSUE TITLE
Pink accent colour in Safari

### ISSUE THREAD

**Issue by dopeytree** [Clooos/Bubble-Card#1600]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
Bubble-card overrides the default accent colour from yellow to pink (Safari only as chrome is normal)

**To Reproduce**  
1. Open Safari on a Mac or iPhone or the homeassisnta app on an iPhone
2. Click on some of your cards and sections 
3. After a while anything that's using the default accent colour from a user theme i.e default yellow will now be pink.

**Expected behavior**  
Stay yellow as that's what in the user theme setting.

**Screenshots**  

![Image](https://github.com/user-attachments/assets/6e8a0a57-d4b3-4fe3-b9a8-041c241a326f)
![Image](https://github.com/user-attachments/assets/61bb5be9-7aec-488b-9c03-a9fe501ca3ac)
![Image](https://github.com/user-attachments/assets/a17959f2-7e80-405a-9be1-bd98e5d9d3a9)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Solar Panels
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.solar_output_75_watts
            icon: mdi:solar-power-variant
            name: East
            show_icon: false
            show_name: true
            show_state: false
            sub_button:
              - entity: sensor.solar_output_75_watts
                show_state: true
                show_last_changed: false
                show_attribute: false
                show_name: false
                show_icon: false
              - entity: sensor.solar_meter_daily_75
                show_state: true
                show_icon: false
            styles: |2-

                .bubble-icon {
                  color: green !important;
                }

               
                .bubble-sub-button-1 {
                  background-color: green !important;
                }

               .bubble-sub-button-2 {
                  background-color: black !important;
                }

                .bubble-sub-button-3 {
                  background-color: green !important;
                }

                .bubble-sub-button-4 {
                  background-color: black !important;
                }
                
                .bubble-button-card-container {
                  background: rgba(12,120,50,0.2) !important;
                }
            scrolling_effect: true
          - type: vertical-stack
            cards:
              - type: heading
                icon: fas:house-chimney
                heading: ~ 1
                heading_style: title
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_1_watts
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:current-dc
                heading: Current
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_1_current
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: Op Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_1_op_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: In Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_1_input_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:thermometer
                heading: Temp
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_1_temperature
                    tap_action:
                      action: more-info
              - type: entities
                entities: []
                footer:
                  type: graph
                  entity: sensor.powerstream_75_solar_1_watts
                  detail: 2
                  hours_to_show: 24
          - type: custom:bubble-card
            card_type: separator
            name: ""
          - type: vertical-stack
            cards:
              - type: entities
                entities: []
                footer:
                  type: graph
                  entity: sensor.powerstream_75_solar_2_watts
                  detail: 2
                  hours_to_show: 24
              - type: heading
                icon: fas:house-chimney
                heading: ~ 2
                heading_style: title
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_2_watts
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:current-dc
                heading: Current
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_2_current
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: Op Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_2_op_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: In Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_2_input_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:thermometer
                heading: Temp
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_75_solar_2_temperature
                    tap_action:
                      action: more-info
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: state
            entity: sensor.solar_output_75_watts
            icon: mdi:solar-power-variant
            name: South
            show_icon: false
            show_name: true
            show_state: false
            sub_button:
              - entity: sensor.solar_output_53_watts
                show_name: false
                show_state: true
                state_background: true
                show_background: true
                show_icon: false
              - entity: sensor.solar_meter_daily_53
                show_state: true
                show_icon: false
                state_background: true
                show_name: false
            styles: |2-

                .bubble-icon {
                  color: green !important;
                }

               
                .bubble-sub-button-1 {
                  background-color: green !important;
                }

               .bubble-sub-button-2 {
                  background-color: black !important;
                }

                .bubble-sub-button-3 {
                  background-color: green !important;
                }

                .bubble-sub-button-4 {
                  background-color: black !important;
                }
                
                .bubble-button-card-container {
                  background: rgba(12,120,50,0.2) !important;
                }
          - type: vertical-stack
            cards:
              - type: heading
                icon: mdi:garage-variant
                heading: ~ 1
                heading_style: title
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_1_watts
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:current-dc
                heading: Current
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_1_current
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: Op Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_1_op_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: In Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_1_input_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:thermometer
                heading: Temp
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_1_temperature
                    tap_action:
                      action: more-info
              - type: entities
                entities: []
                footer:
                  type: graph
                  entity: sensor.powerstream_53_solar_1_watts
                  detail: 2
                  hours_to_show: 24
          - type: custom:bubble-card
            card_type: separator
            name: ""
          - type: vertical-stack
            cards:
              - type: entities
                entities: []
                footer:
                  type: graph
                  entity: sensor.powerstream_53_solar_2_watts
                  detail: 2
                  hours_to_show: 24
              - type: heading
                icon: mdi:garage-variant
                heading: ~ 2
                heading_style: title
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_2_watts
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:current-dc
                heading: Current
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_2_current
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: Op Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_2_op_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:sine-wave
                heading: In Potential
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_2_input_potential
                    tap_action:
                      action: more-info
              - type: heading
                icon: mdi:thermometer
                heading: Temp
                heading_style: subtitle
                badges:
                  - type: entity
                    show_state: true
                    show_icon: false
                    entity: sensor.powerstream_53_solar_2_temperature
                    tap_action:
                      action: more-info
  - type: entities
    entities: []
    footer:
      type: graph
      entity: sensor.solar_output_now_watts
      detail: 2
    theme: Mushroom Shadow
    state_color: false
    show_header_toggle: true
    title: Output Watts
  - type: entities
    entities: []
    theme: Mushroom Shadow
    state_color: false
    show_header_toggle: true
    title: Solar Radiation
    footer:
      type: graph
      entity: sensor.gw1100a_solar_radiation
      detail: 2
```

**Informations (please complete the following information):**  
 - OS: unraid
 - Browser/App: Safari
 - Bubble Card version: 3.00rc1
 - Home Assistant version: Core= 2025.6.1   -   Frontend=20250531.3

**Additional context**  

Thank you! 🍻
