### ISSUE TITLE
Select card not working

### ISSUE THREAD

**Issue by tmerlandsen** [Clooos/Bubble-Card#1603]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

Describe the bug
The select card type fails to populate its dropdown list when using a valid options_template. The template is confirmed to be working correctly in the Home Assistant Developer Tools and also works as expected in other custom cards (like auto-entities). However, the Bubble Card select card renders as if the template returned an empty list, resulting in a card with no dropdown arrow and no selectable options.

Steps to Reproduce:

1. Create several scenes in Home Assistant with a common naming convention for their entity IDs (e.g., scene.bathroom_day, scene.bathroom_night, scene.bathroom_bath).
2. Create a standard input_select helper entity in Home Assistant (e.g., input_select.scene_selector_helper).
3. Create a Lovelace card using the "Failing Bubble Card Configuration" provided below.
4. Observe that the card renders on the dashboard but has no dropdown list and is not interactive.

Expected behaviour:
The Bubble Card should display a dropdown menu populated with the entities found by the template (Bathroom Day, Bathroom Night, etc. in our case). Selecting an option should trigger the tap_action.

Actual behaviour:
The card renders with the correct name and icon, but it is completely static. There is no dropdown arrow to click, and no options are displayed. It behaves as if the template result was an empty list [].

Evidence and Code
This is the key piece of evidence. The exact same template logic works perfectly in a standard auto-entities card but fails in the Bubble Card select card. This proves the template and the underlying Home Assistant data are correct, and isolates the issue to Bubble Card.

1. Failing Bubble Card Configuration:
This configuration results in a card with no dropdown.

```
type: custom:bubble-card
card_type: select
name: Bathroom Scenes
icon: mdi:palette
entity: input_select.scene_selector_helper # This helper entity exists
options_template: |
  {% set prefix = 'scene.bathroom_' %}
  {{ states.scene | map(attribute='entity_id') | select('match', prefix) | list }}
tap_action:
  action: call-service
  service: scene.turn_on
  service_data:
    entity_id: '{{ this.state }}'
```

2. Working auto-entities Configuration (for comparison):
This configuration, using the identical template logic, works correctly and displays a list of the bathroom scenes. This proves the template is valid.

```
type: custom:auto-entities
card:
  type: entities
  title: Test - Bathroom Scenes
filter:
  template: |
    {% set prefix = 'scene.bathroom_' %}
    {{ states.scene | map(attribute='entity_id') | select('match', prefix) | list }}
```

Additional Context:

This issue was discovered after extensive troubleshooting.

We initially tried to filter using label_entities(), which also failed to populate the options_template. We pivoted to the more direct entity ID naming convention to ensure the data source was not the problem.
The user's Home Assistant instance appears to have some deeper, unrelated issues regarding how the UI saves labels to the backend, but the naming convention method bypasses this entirely and should work.
The auto-entities card working while the bubble-card fails is the definitive proof that the issue lies in how the select card processes the options_template result.

Thank you for your work on this great card! Hopefully, this detailed report helps you track down the issue.

**Informations (please complete the following information):**  
 - OS: HAOS
 - Browser/App: Brave
 - Bubble Card version: 2.4.0
 - Home Assistant version: 
Core 2025.6.3
Supervisor 2025.06.2
Operating System 15.2
Frontend 20250531.4

Thank you! 🍻
