### ISSUE TITLE
Slider “steps” option ignored on release – actual value is set instead of snapped step

### ISSUE THREAD

**Issue by bxjrke** [Clooos/Bubble-Card#1607]
**Describe the bug**  
When using button_type: slider, the step setting (e.g., step: 20) is only partially respected.

While dragging the slider, the displayed value snaps correctly to the nearest defined step (e.g., moving from 60 toward 73 displays 80, as expected with step: 20). However, once the slider is released, the raw value (e.g., 73) is set instead of the snapped step value (e.g., 80).

This means the visual behavior during sliding is correct, but the actual service call or state update uses an incorrect, non-stepped value—effectively ignoring the defined step value on release.

**To Reproduce**  

1. Set up a custom:bubble-card with card_type: button and button_type: slider, and define a step value (e.g., 20).
2. Use the slider to change the value (e.g., move the thumb from 60 to somewhere around 73).
3. Observe the displayed value while dragging — it correctly snaps to 80, based on the defined step: 20.
4. Release the slider and observe the set value.

**Expected behavior**  
When releasing the slider, the value sent should be the nearest valid step (e.g., 80), not the raw pointer value (e.g., 73).

**Screenshots**  

![Image](https://github.com/user-attachments/assets/0135b446-d7fa-4e51-8bde-109d7518aa26)

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
entity: cover.rollo_rechts
show_state: true
show_last_changed: false
show_last_updated: false
show_attribute: true
attribute: current_position
show_icon: true
button_type: slider
step: 20
slider_live_update: false
tap_to_slide: false
```

**Informations (please complete the following information):**  
 - OS: macOS 15.5; iOS 18.5
 - Browser/App: Safari, Google Chrome, Home Assistant Companion App
 - Bubble Card version: v3.0.0-rc.3
 - Home Assistant version: 2025.6.3

**Additional context**  
none

Thank you! 🍻
