### ISSUE TITLE
Cards are empty in chrome

### ISSUE THREAD

**Issue by mitusbe** [Clooos/Bubble-Card#1611]
Bubble Card v3.0.0-rc.3 and v3.0.0-rc.1

Browser Google Chrome version 138.0.7204.50 (Officiële build) (arm64) on macOS 15.5 

Problem:
Cards name, labels are empty in Google Chrome.
Cleared all cache and stuff.

Works in Safari.

See screenshot Chrome

![Image](https://github.com/user-attachments/assets/e8f5933b-1f44-497e-81e8-9caed38173c4)

See screenshot Safari

![Image](https://github.com/user-attachments/assets/a338465a-f24b-4f20-a6df-8cd23d2fca0c)

Example one of the cards:

```
type: horizontal-stack
cards:
  - type: custom:bubble-card
    card_type: button
    sub_button:
      - entity: switch.sfeer_koken
        name: koken
        icon: mdi:pot-steam
        tap_action:
          action: toggle
        show_background: true
        show_icon: true
        state_background: true
        show_state: false
        show_attribute: false
      - entity: switch.sfeer_eten
        icon: mdi:silverware-fork-knife
        tap_action:
          action: toggle
        name: eten
      - entity: switch.sfeer_keuken_klein
        name: Uit
        icon: mdi:wall-sconce
        tap_action:
          action: toggle
      - entity: switch.dampkap_2
        icon: mdi:fan
        name: Dampkap
        tap_action:
          action: toggle
    1_link: "#keuken"
    1_name: Keuken
    1_icon: mdi:chef-hat
    highlight_current_view: false
    hide_gradient: false
    button_type: slider
    name: Keuken
    icon: mdi:kettle
    tap_action:
      action: navigate
      navigation_path: "#keuken"
    scrolling_effect: false
    modules:
      - subbutton_below
      - get_state_attribute
    visual_styling_center:
      height_multiplier: 1
      icon_size_multiplier: 1
      hide_icon_background: false
      hide_subbutton_background: false
      enable_entity_colored_main_icon: false
      enable_gradient: false
      gradient_entity: light.keuken_gang
      gradient_target: slider
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#keuken"
    rows: "2"
    entity: light.keuken_tafel
    show_attribute: true
    attribute: current_temperature
    show_state: false
    get_state_attribute:
      - entity: climate.tdeg_keuken
        attribute: current_temperature
  - type: custom:bubble-card
    card_type: button
    sub_button:
      - entity: switch.apero
        name: Apero
        icon: mdi:glass-cocktail
        tap_action:
          action: toggle
      - entity: switch.diner
        icon: mdi:candelabra-fire
        name: Diner
        tap_action:
          action: toggle
    1_link: "#keuken"
    1_name: Keuken
    1_icon: mdi:chef-hat
    highlight_current_view: false
    hide_gradient: false
    button_type: slider
    name: Eetplaats
    icon: mdi:silverware-variant
    tap_action:
      action: navigate
      navigation_path: "#eetplaats"
    scrolling_effect: false
    modules:
      - subbutton_below
      - get_state_attribute
    visual_styling_center:
      height_multiplier: 1
      icon_size_multiplier: 1
      hide_icon_background: false
      hide_subbutton_background: false
      enable_entity_colored_main_icon: false
      enable_gradient: false
      gradient_entity: light.keuken_gang
      gradient_target: slider
    button_action:
      tap_action:
        action: navigate
        navigation_path: "#eetplaats"
    rows: "2"
    entity: light.lamp_eettafel
    show_attribute: true
    attribute: current_temperature
    show_state: false
    get_state_attribute:
      - entity: climate.tdeg_woonkamer
        attribute: current_temperature
```
