### ISSUE TITLE
mute button/mediaplayer card

### ISSUE THREAD

**Issue by collateral87** [Clooos/Bubble-Card#1612]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
On mobile browsers or the ha-app when i hit the mute button, the more info dialog appears from the button/icon) underneath. In desktop view, all works as expected.

**To Reproduce**  
1. Create a mediaplayer card
2. Click on volume
3. Hit mute
4. The more info dialog appears

**Expected behavior**  
The mute button should work.

**Screenshots**  
![Image](https://github.com/user-attachments/assets/1fd54a27-04fc-4798-9b58-012d418a3aca)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: media-player
entity: media_player.kfrawi
name: Musikplayer
styles: |-
  * {
    --bubble-media-player-main-background-color: ${state !== 'off' ? 'var(--media-on-color)' : 'var(--card-background-color)'} !important;
  }
  ha-card {
    border-radius: 40px !important;
    border: solid 1px black !important;
  }
  .bubble-icon {
    color: var(--text-color-white) !important;
  }
  .is-off .bubble-main-icon {
    opacity: 1;
  }
  .bubble-media-button {
    background-color: var(--card-background-color) !important;
  }
  .range-fill {
    background-color: var(--select-color) !important;
  }
  .bubble-play-pause-button {
    width: 35px !important;
    height: 35px !important;
  }
  .name-container {
    display: block !important;
  }
  .bubble-media-info-container {
    display: none !important;
  }
  .bubble-volume-button {
    background-color: ${hass.states[entity].attributes.is_volume_muted === true ? 'var(--warn-color)' : 'var(--card-background-color)'} !important;
  }
  .bubble-mute-button {
    background-color: ${hass.states[entity].attributes.is_volume_muted === true ? 'var(--warn-color)' : 'var(--card-background-color)'} !important;
  }
cover_background: false
button_action: {}
double_tap_action:
  action: more-info
hide:
  power_button: true
  volume_button: false
  play_pause_button: false
  previous_button: false
  next_button: false
show_state: true
force_icon: true
show_attribute: true
attribute: volume_level
show_name: true
scrolling_effect: true
show_icon: true
rows: "1"
```

**Informations (please complete the following information):**  
 - OS: android
 - Browser/App: homeassistant app/mobile chrome
 - Bubble Card version: v3.0.0-rc.3
 - Home Assistant version: 2025.6.3

**Additional context**  
---
