### ISSUE TITLE
Cannot read properties of undefined (reading 'config') at createIcon

### ISSUE THREAD

**Issue by Edwin-Luijten** [Clooos/Bubble-Card#165]
After installing via HACS and a fresh reboot.
I created a basic dashboard config:
```yaml
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#main'
            entity: media_player.living_room
            state: climate.woonkamer
      - type: custom:bubble-card
        card_type: horizontal-buttons-stack
        1_link: '#main'
        1_icon: mdi:view-dashboard-outline
```

I'm getting thousands of the same error that keep going on without stopping:
```
Cannot read properties of undefined (reading 'config')
    at createIcon (bubble-card.js?hacstag=680112919142:1:5028)
    at e (bubble-card.js?hacstag=680112919142:1:9078)
    at bubble-card.js?hacstag=680112919142:1:18042
```

Resources:
- /browser_mod.js?automatically-added
- /hacsfiles/apexcharts-card/apexcharts-card.js?hacstag=331701152204
- /hacsfiles/Bubble-Card/bubble-card.js?hacstag=680112919142
- /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524324
- /hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375322

---
HAS version: 11.1
Frontend version: 20231030.1
Bubble card version: 1.4.2
