### ISSUE TITLE
Feature request: Close all covers

### ISSUE THREAD

**Issue by Wobak** [Clooos/Bubble-Card#177]
Hello,

First, thank you very much for all the hard work, I now have a lovely Dashboard thanks to you :)

I have 2 set of pop-up for covers (one for each floor), but I find it a bit bothersome to have to click on each individually to close everything.

I created a button for this in my dashboard, but I was wondering if there was a way to include an action, maybe on the cover button of a pop-up to close all covers in the same stack.

Thanks !

**Comment by Clooos** [comment]
Hi and thanks! Actually you can just have a cover group then you can add it as an `entity` and even as a `state` in your pop-up header, like this:
```yaml
type: custom:bubble-card (or 'custom:bubble-pop-up' in the new beta)
card_type: pop-up
hash: '#covers'
entity: cover.cover_group
state: cover.cover_group
```

**Comment by Wobak** [comment]
Thanks, I didn't know about the cover group, It works perfectly now.

I'm just adding the code to create a cover group in case someone finds this thread :
```
cover:
  - platform: group
    name: volets_rdc
    entities:
      - cover.cover_1
      - cover.cover_2
      - cover.kitchen
      - cover.living_room
```
