### ISSUE TITLE
Hide name on button

### ISSUE THREAD

**Issue by mutasim** [Clooos/Bubble-Card#180]
Is it possible to have no name and just icon on a button?

**Comment by Clooos** [comment]
Hi! Yes it's possible, try that:
```yaml
type: custom:bubble-card
card_type: button
entity: your.entity
name: []
styles: >
  ha-card {
    width: 50px;
  }
```
