### ISSUE TITLE
Pop-up border radius

### ISSUE THREAD

**Issue by GGSSDD** [Clooos/Bubble-Card#202]
Hi,

Is there a possibility to remove or alter the pop-up’s border radius? I’ve tried a lot of things, including card mod, but nothing seems to work and i’ve run out of ideas.

Would really appreciate if you could guide in the right direction.
Thank you.

**Comment by Clooos** [comment]
Hi, you can tweak that with custom styles like this in your YAML:
```yaml
  - type: custom:bubble-pop-up
    hash: '#your-pop-up'
    styles: |
      #root {
        border-radius: 0px;
      }
```
