### ISSUE TITLE
Bubble-Card is hidden behind Swipe-Cards

### ISSUE THREAD

**Issue by marwonn** [Clooos/Bubble-Card#21]
I have two swipe cards on my home screen and they are organised in a vertical-stack card.

I set up a bubble-card:
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#light'
    name: Licht
    icon: mdi:lightbulb-group
    margin_top_desktop: 10px
  - square: true
    type: grid
    cards:
      - type: custom:slider-button-card
        entity: light.zbmini_bad
        slider:
          direction: left-right
          background: gradient
          use_state_color: true
          use_percentage_bg_opacity: false
          show_track: false
          toggle_on_click: false
          force_square: false
          show_attribute: false
        show_name: true
        show_state: true
        compact: false
        icon:
          show: true
          use_state_color: true
          tap_action:
            action: more-info
          icon: mdi:led-strip
        action_button:
          mode: custom
          icon: mdi:power
          show: true
          show_spinner: false
          tap_action:
            action: toggle
        name: Bad
        show_attribute: true

```
When I trigger the bubble-card it is opened in the background, hidden behind the swipe cards. 

<img width="825" alt="Bildschirmfoto 2023-08-31 um 19 28 43" src="https://github.com/Clooos/Bubble-Card/assets/60670299/392c842d-0a48-4597-8622-7dc8a8f5be2d">
