### ISSUE TITLE
Invisible with bottom nav bar

### ISSUE THREAD

**Issue by dnestico** [Clooos/Bubble-Card#22]
I'm having multiple issues and trying to figure them out...

I use a bottom nav-bar instead of a top nav-bar so it seems like on mobile it is I guess hidden behind it and I can't see the button row

<img width="460" alt="Screenshot 2023-08-31 at 11 43 50 PM" src="https://github.com/Clooos/Bubble-Card/assets/3034555/de942d85-b2dd-4f44-a2b5-8b2c40651af0">

My code:

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#basement'
    name: Basement
    icon: hue:downstairs
    entity: light.basement_lights
    state: light.basement_lights
    margin_top_mobile: 60px
    margin_top_desktop: 60px
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: m3s:light-group-outlined-filled
  - square: false
    type: grid
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: light.huego
        button_type: slider
      - type: custom:bubble-card
        card_type: button
        entity: light.davids_lightstrip
        button_type: slider
      - type: custom:bubble-card
        card_type: button
        entity: light.davids_lightstrip2
        button_type: slider
      - type: custom:bubble-card
        card_type: button
        entity: light.davids_lamp
        button_type: slider
      - type: custom:bubble-card
        card_type: button
        entity: light.davids_lamp
        button_type: slider
      - type: custom:bubble-card
        card_type: button
        entity: light.davidslamp2
        button_type: switch
      - type: custom:bubble-card
        card_type: button
        entity: light.tv_lightstrip
        button_type: slider
      - type: custom:bubble-card
        card_type: button
        entity: light.basement_smart_plug
        button_type: switch
        name: Display Shelf
    columns: 2
  - type: custom:bubble-card
    card_type: separator
    name: Media Players
    icon: m3s:speaker-group-outlined-filled
  - square: false
    type: grid
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: media_player.david_s_display
        button_type: switch
        icon: phu:nest-hub
      - type: custom:bubble-card
        card_type: button
        entity: media_player.david_s_tv
        button_type: switch
        icon: m3s:tv-gen-outlined
      - type: custom:bubble-card
        card_type: button
        entity: media_player.samsung_tv_control
        button_type: switch
        icon: m3s:tv-gen-outlined
        name: Samsung TV
    columns: 2
```
Code 2:

```
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_name: Basement
1_link: '#basement'
1_entity: light.basement_lights
1_icon: mdi:home-floor-b
auto_order: false
```
