### ISSUE TITLE
Light cannot turn on/off on button card

### ISSUE THREAD

**Issue by rcavezzale** [Clooos/Bubble-Card#230]
Ciao Clooos,

I'm tried your plugin because is very interesting but i have strange problem with toogle service, in detail the light not turn on/off.

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#cameraa'
    name: cameraa
    icon: mdi:bed-double
    state: sensor.camera_all_count
  - type: grid
    columns: 1
    square: false
    cards:
      - type: custom:bubble-card
        card_type: separator
        name: Faretti
        icon: mdi:lightbulb-multiple
        styles: |
          .separator-container div:last-child {
            opaticy: 1|important;
          }
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:button-card
            name: Faretto 1
            icon: mdi:lightbulb
            label: Camera Matrimoniale
            show_label: true
            show_state: false
            entity: light.faretto1cm
            tap_action:
              action: toogle
            hold_action:
              action: more-info
            state:
              - value: 'on'
                styles:
                  card:
                    - background: >-
                        linear-gradient(50deg, rgba(241,201,59,1) 30%,
                        rgba(250,227,146,1) 100%)
              - value: 'off'
                styles:
                  card:
                    - background: '#ffffff'
            styles:
              icon:
                - width: 24px
                - color: black
              image_cell:
                - justify-self: end
                - width: 30px
                - height: 30px
              name:
                - justify-self: start
                - font-size: 18px
                - line-height: 40px
                - fond-weight: 600
              label:
                - justify-self: start
                - font-size: 14px
                - font-weight: 500
              card:
                - padding: 18px
                - background: '#ffffff'
```
For checking in below the error logs:

```
 Logger: frontend.js.latest.202312082
Source: components/system_log/__init__.py:300
First occurred: 19:30:03 (48012 occurrences)
Last logged: 20:37:32

    Uncaught error from Firefox 120.0 on Windows 10 TypeError: e is undefined entities (src/common/entity/compute_state_display.ts:48:17) formatEntityState (src/common/translations/entity-state.ts:38:26) n (/hacsfiles/Bubble-Card/bubble-card.js:1:8774) set hass/K< (/hacsfiles/Bubble-Card/bubble-card.js:1:18944)
    Uncaught error from Firefox 120.0 on Windows 10 TypeError: undefined has no properties entities (src/common/entity/compute_state_display.ts:48:17) formatEntityState (src/common/translations/entity-state.ts:38:26) n (/hacsfiles/Bubble-Card/bubble-card.js:1:8774) set hass/K< (/hacsfiles/Bubble-Card/bubble-card.js:1:18944)
    Uncaught error from Firefox 120.0 on Windows 10 TypeError: element is null addStyles (/hacsfiles/Bubble-Card/bubble-card.js:1:4019) n (/hacsfiles/Bubble-Card/bubble-card.js:1:18381) set hass/K< (/hacsfiles/Bubble-Card/bubble-card.js:1:18944)
    Uncaught error from Firefox 120.0 on Windows 10 Error: Pop-up card must be placed inside a vertical_stack! If it's already the case, please ignore this error 🍻 set hass/< (/hacsfiles/Bubble-Card/bubble-card.js:1:19061)
```

Could you check?
i'm using lasted hassio version.
