### ISSUE TITLE
Screen flickering and duplicating elements when using custom expander card

### ISSUE THREAD

**Issue by 42Craft** [Clooos/Bubble-Card#237]
I am using a [custom card](https://github.com/Alia5/lovelace-expander-card) on the separator ˋcard_typeˋ to create a collapsable card stack. When I use this card the UI starts flickering and the custom card element seems to be duplicating. I recorded it to better show what I mean. When the recording starts it already duplicated once.

``` yaml

- type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#corridor'
            icon: mdi:image-frame
            name: Overloop
            state: sensor.t1_temperature
            entity: light.hue_e27_2
          - type: custom:bubble-card
            card_type: separator
            name: Verlichting
            icon: mdi:lightbulb-multiple
          - square: false
            type: grid
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.hue_e27_2
                name: Plafond
                icon: mdi:ceiling-light
            columns: 2
          - type: custom:expander-card
            clear: true
            expanded: false
            padding: 0
            title-card:
              type: custom:bubble-card
              card_type: separator
              name: Instellingen
              icon: mdi:cog
            cards:
              - type: entities
                entities:
                  - entity: automation.corridor_presencedetected
                    name: Bewegingsgestuurde verlichting
                    secondary_info: last-triggered
```

https://github.com/Clooos/Bubble-Card/assets/34486569/53bf5f1d-5ec1-4f7a-a4d0-92363715fa49
