### ISSUE TITLE
Reload issue still present on 1.6.0-1 beta

### ISSUE THREAD

**Issue by xCapeITA** [Clooos/Bubble-Card#248]
I'm sorry to inform you that the reload issue is still present on my Samsung A7 with companion app.

It looses connection and reload UI .
If I delete bubble card integration is ok
System log says

Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving

**Comment by limitless00net** [comment]
Same here. It definitely is "too many redirects" error.

**Comment by Clooos** [comment]
I'm on it, can you guys just tell me more details about your dashboards? How many pop-ups (more or less), and what are the Bubble Cards that you use?

My guess is that this issue is caused by the pop-ups but I'm still not sure.

**Comment by vcntt** [comment]
I am NOT on the beta, but I have the same issue on `1.5.3`: "Reached 4096 pending messages."

I have used ChatGPT to extract the skeleton of my dashboard and for statistics. I hope this will help. Let me know what other details you might need. 

- Button Cards: 69
- Bubble Cards: 52
- Grid Cards: 14
- Entities Cards: 9
- Vertical Stack Cards: 11
- Separator Cards: 12
- Auto-Entities Cards: 2
- Conditional Cards: 2
- Weather Forecast Cards: 6
- Picture Entity Cards: 1
- ApexCharts Cards: 9
- Media Control Cards: 2
- Thermostat Cards: 2
- Weather Forecast Cards: 6
- Expander Cards: 2
- Webrtc-Camera Cards: 4
- Logbook Cards: 1
- Horizontal-Buttons-Stack Cards: 1

``` yaml
- type: vertical-stack
  cards:
    - type: grid
      cards:
        - type: custom:button-card
        - type: custom:button-card
        - type: custom:button-card
        - type: custom:button-card
    - type: grid
      cards:
        - type: custom:button-card
        - type: custom:button-card
        - type: custom:button-card
        - type: custom:button-card
        - type: custom:button-card
    - type: custom:bubble-card
      card_type: separator
    - type: vertical-stack
      cards:
        - type: grid
          cards:
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
        - type: custom:bubble-card
          card_type: separator
        - type: grid
          cards:
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
            - type: custom:button-card
        - type: custom:bubble-card
          card_type: separator
        - type: custom:auto-entities
        - type: custom:auto-entities
        - type: custom:button-card
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: weather-forecast
    - type: weather-forecast
    - type: custom:neerslag-card
    - type: weather-forecast
    - type: weather-forecast
    - type: picture-entity
    - type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: pop-up
        - type: custom:bubble-card
          card_type: separator
        - type: entity
        - type: custom:apexcharts-card
        - type: custom:apexcharts-card
        - type: entities
        - type: custom:bubble-card
          card_type: separator
        - type: entity
        - type: custom:apexcharts-card
        - type: entities
    - type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: pop-up
        - type: custom:bubble-card
          card_type: separator
        - type: entity
        - type: custom:apexcharts-card
        - type: entities
        - type: custom:bubble-card
          card_type: separator
        - type: entity
        - type: custom:apexcharts-card
        - type: entities
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: conditional
      conditions:
        - condition: user
          users:
            - ca8e271e89f54e8585de85711b619e38
      card:
        type: entities
        entities:
          - input_boolean.isdebuggingenabled
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: custom:bubble-card
      card_type: separator
    - type: vertical-stack
      cards:
        - type: grid
          cards:
            - type: button
              entity: scene.bedroom_strolling
            - type: button
              entity:
                - scene.bedroom_bedtime
        - type: grid
          cards:
            - type: custom:bubble-card
              card_type: button
            - type: custom:bubble-card
              card_type: button
        - type: custom:bubble-card
          card_type: separator
        - type: custom:bubble-card
          card_type: separator
        - type: entity
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: custom:bubble-card
      card_type: separator
    - type: grid
      cards:
        - type: custom:bubble-card
          card_type: button
      columns: 2
    - type: custom:apexcharts-card
      experimental:
        color_threshold: true
    - type: custom:bubble-card
      card_type: separator
    - type: entity
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: custom:apexcharts-card
    - type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: pop-up
        - type: custom:apexcharts-card
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: custom:bubble-card
      card_type: separator
    - type: grid
      cards:
        - type: button
        - type: button
        - type: button
        - type: button
        - type: custom:button-card
    - type: grid
      cards:
        - type: custom:bubble-card
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: custom:bubble-card
      card_type: separator
    - type: entities
      entities:
        - entity: scene.studio_lounging
        - entity: scene.studio_relaxing
        - entity: scene.studio_working
    - type: grid
      cards:
        - type: custom:bubble-card
          card_type: button
        - type: custom:bubble-card
          card_type: button
      columns: 2
    - type: custom:bubble-card
      card_type: separator
    - type: entities
      entities:
        - entity: switch.wake_on_lan_2
    - type: custom:bubble-card
      card_type: separator
    - type: entity
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: custom:bubble-card
      card_type: separator
    - type: grid
      cards:
        - type: button
        - type: button
        - type: button
        - type: button
        - type: custom:button-card
    - type: grid
      cards:
        - type: custom:bubble-card
        - type: custom:bubble-card
        - type: custom:bubble-card
    - type: conditional
      conditions:
        - condition: state
          entity: input_boolean.ui_enablechristmasmode
          state: 'on'
      card:
        type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
              - type: custom:bubble-card
    - type: custom:bubble-card
      card_type: separator
    - type: entities
      entities:
        - entity: switch.p4
        - entity: switch.wake_on_lan_2
    - type: media-control
      entity: media_player.sony_bravia_tv
    - type: media-control
      entity: media_player.shield_tv
    - type: custom:bubble-card
      card_type: separator
    - type: entity
    - type: thermostat
      entity: climate.woonkamer
      name: Stadsverwarming
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: entity
    - type: entity
    - type: entity
    - type: entity
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
    - type: custom:webrtc-camera
    - type: vertical-stack
      cards:
        - type: grid
          cards:
            - type: custom:bubble-card
      - type: custom:bubble-card
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#corridor'
      icon: mdi:image-frame
      name: Overloop
      state: sensor.t1_temperature
      entity: light.hue_e27_2
    # ... (other cards)
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#washingroom'
      icon: mdi:washing-machine
      name: Washok
      state: sensor.w1_device_temperature
    # ... (other cards)
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#guestroom'
      icon: mdi:bed
      name: Logeerkamer
      state: sensor.t4_temperature
      entity: light.hue_e27_17
    # ... (other cards)
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#shed'
      icon: mdi:greenhouse
      name: Schuur
      state: sensor.t8_temperature
    # ... (other cards)
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#hallway'
      icon: mdi:coat-rack
      name: Gang
      state: sensor.t5_temperature
      entity: light.hue_e27_1
    # ... (other cards)
- type: custom:bubble-card
  card_type: horizontal-buttons-stack
  1_link: '#bedroom'
  1_name: Slaapkamer
  1_entity: light.hue_e27_8
  1_pir_sensor: binary_sensor.m5_occupancy
  auto_order: true
  rise_animation: true
  is_sidebar_hidden: false
  2_link: '#kitchen'
  2_name: Keuken
  2_entity: light.kitchen_ceiling_lights
  2_pir_sensor: binary_sensor.m4_occupancy
  3_link: '#diningroom'
  3_name: Eetkamer
  3_entity: light.dining_table_lights
  3_pir_sensor: binary_sensor.m2_occupancy
  4_link: '#livingroom'
  4_name: Woonkamer
  4_entity: light.l1
  4_pir_sensor: binary_sensor.hallway_combinedoccupancy
  5_link: '#studio'
  5_name: Studio
  5_entity: light.studio_office_lights
  5_pir_sensor: binary_sensor.secondfloor_haspresence
  6_link: '#yard'
  6_name: Tuin
  6_entity: light.hue_e27_5
  6_pir_sensor: binary_sensor.frontyard_hasdetectedmotion

```
