### ISSUE TITLE
Instructions state that card_mod: is supported, but does not seem to be consistant

### ISSUE THREAD

**Issue by lzthqx** [Clooos/Bubble-Card#25]
Instructions state:
There is no styling options (for now) but it fully support [card-mod](https://github.com/thomasloven/lovelace-card-mod).
Here is an example on how you can change the font size:

```
card_mod:
  style: |
    ha-card { 
      font-size: 12px;
    }
```

The above code works for changing fonts, but the code below (working on both mushroom and default buttons) does not change the background color based on status.

```
card_mod:
          style: |
            ha-card { 
              background-color: {{ '#3f9f3a' if is_state('lock.back_door', 'locked') else '#FFAAAA' }};
            }
```

**Comment by dsellers1** [comment]
I threw as much card mod as I could find to see what all could be done. I was able to change the background color but not the result I was looking for.
```yaml
card_mod:
  style: |
    :host {
      background-color: hotpink;
    }
```
![image](https://github.com/Clooos/Bubble-Card/assets/67642332/075badda-eb0e-40eb-af3a-9261fcab80d7)
I think the intent would be to able to change the button color. I can see it when inspecting the page, but I cannot figure out how to change it with card mod. Looking at the code, there's only two places where `var(--accent-color)` is used but I don't know what I'm looking at in the code.
![image](https://github.com/Clooos/Bubble-Card/assets/67642332/4b290bc2-e26b-41a6-b7ed-5124522aaf80)

I made this monstrosity with a bunch of card mod.
![image](https://github.com/Clooos/Bubble-Card/assets/67642332/aabaa898-cb22-4513-b49b-53fcc52c8354)
```yaml
type: custom:bubble-card
card_type: button
entity: light.living_room_lights
button_type: switch
card_mod:
  style: |
    :host {
      background-color: hotpink;
      --ha-card-background: white;
      box-shadow: 0px 2px 5px 1px red;
      --ha-card-border-width: 5px;
    }
    ha-card {
      font-size: 22px;
      font-family: Comfortaa;
      font-weight: bold !important;
      text-align: left;
      width: 250px;
      height: 100px;
      color: white;
      --primary-text-color: red;
      --card-mod-icon: mdi:check;
      --card-mod-icon-color: green;
    }
```
The color and --primary-text-color are the same thing, but only the first one gets used.
I noticed the button does not scale when a height and width are used.
`Text-align: center` creates a crazy result: 

![image](https://github.com/Clooos/Bubble-Card/assets/67642332/bd214acf-f9b0-4fbc-80c5-eddc10562c37)

Most of the card mod does not show in the Editor UI (which is not uncommon) and some does not show while editing the dashboard.
