### ISSUE TITLE
Get rid of whitespace

### ISSUE THREAD

**Issue by panhans** [Clooos/Bubble-Card#250]
Hi,

first: great integration! Thank you for that.

Now my question: Is there a way to get rid of this whitespace? I have several popups on this page and every vertical-stack creates such a whitespace.

![image](https://github.com/Clooos/Bubble-Card/assets/4427249/d67caa54-4f66-4070-9ee7-a54335f7f040)

Thanks in advance!

**Comment by vcntt** [comment]
Did you turn off `render as square`?

**Comment by panhans** [comment]
Yes, the small lines are the popups. Iv'e embedded them in a horizontal stack now. Seems to work. Now there is only one line. xD

**Comment by panhans** [comment]
Oh, no. Doesn't work! The popups get beeing shifted when putting them in a horizontal-stack. :(

**Comment by panhans** [comment]
I'd solved it by embed a vertical stack into a mod card and set its height to 0px.

```yaml
type: "custom:mod-card"
style:
  .: >
    ha-card {
      padding: 0x !important;
      margin: 0px !important;
      height: 0px;
    }
card:
  type: vertical-stack
  cards:
    # POPUPS HERE
```
