### ISSUE TITLE
Creating bubble card without entities

### ISSUE THREAD

**Issue by joaopedros2** [Clooos/Bubble-Card#262]
From what I've tested, I didn't see an option to create a bubble card without relying on an entity.
My goal was to have a button that simply calls a service when pressed. 
In Mushroom Cards, there's an option for templates for these cases. 

```
type: custom:mushroom-chips-card
alignment: center
chips:
  - type: template
    content: Iniciar
    icon: mdi:power-on
    icon_color: green
    tap_action:
      action: call-service
      service: ffmpeg.start
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: template
    content: Parar
    icon: mdi:power-off
    icon_color: red
    tap_action:
      action: call-service
      service: ffmpeg.stop
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: template
    content: Reiniciar
    icon: mdi:restart
    icon_color: yellow
    tap_action:
      action: call-service
      service: ffmpeg.restart
    hold_action:
      action: none
    double_tap_action:
      action: none
```

It would be very useful to have this feature in this project as well.
