### ISSUE TITLE
Popup button active color

### ISSUE THREAD

**Issue by arkpoah** [Clooos/Bubble-Card#263]
In the example video, we can see popup button changes color when entities are enabled in popup.
I don't achieve to do this.
How can we get the popup button enabled when an entity is on in popup vertical stack ?
thanks

**Comment by Clooos** [comment]
Hi! You need to add an entity to that pop-up, ideally a light group with all your lights from that pop-up in it.

In YAML it looks like this:
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#kitchen'
    name: Kitchen
    icon: mdi:fridge
    entity: light.kitchen #This is what you need to add
```
