### ISSUE TITLE
0 Height Rows Showing at Bottom of Page

### ISSUE THREAD

**Issue by efaden** [Clooos/Bubble-Card#268]
I have a layout card that takes up the full screen.  The vertical stacks for the popups are making blank lines at the bottom with height 0.  I have tried using card mod, etc to get rid of them, but can't seem to get it right.  I did try making them invisible, but that also seems to kill the popup.
![Screenshot 2023-12-24 at 8 59 10 AM](https://github.com/Clooos/Bubble-Card/assets/12599300/e4da09c1-7c1f-44f3-8125-a96932e3c787)

**Comment by Clooos** [comment]
Hi! Is this issue is still happening in the new v1.7.X?

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.1

**Comment by efaden** [comment]
Appears to be.  Need to play with it some more, but the space does appear to be gone.  Thanks!

**Comment by efaden** [comment]
Just kidding.  Was looking at the wrong version of my page.  They are still there.

**Comment by Clooos** [comment]
Hi, can you tell me if you still have this issue in the v2 beta?

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by efaden** [comment]
Sorry just got around to this.  I am still seeing them.

**Comment by Clooos** [comment]
Hi, is it still the case in v2.0.4 with HA 2024.6.X?

**Comment by efaden** [comment]
Seems fixed!
-Eric

**Comment by GewoonRoy** [comment]
Hi,

I am using v2.0.4 with HA 2024.6.X and i'm experiencing an issue just like this. I've tried several options to fix it but haven't been able to. 

Can you help me with what i'm possibly doing wrong? I've noticed the #root of the hui-vertical-stack-card is using a gap of 8px for each element within the stack-card which creates a lot of space.

I've have a vertical stack with a lot of vertical stacks in it.
<img width="541" alt="Screenshot 2024-06-28 at 09 41 26" src="https://github.com/Clooos/Bubble-Card/assets/9586175/8f38a1e8-a32e-4ce0-9b0d-51ced80d1d79">


```
type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:button-card
         name: Woonkamer
         ...
  - type: vertical-stack
     cards:
      - type: custom:bubble-card
         card_type: pop-up
         hash: '#living-room'
         auto_close: '30000'
         name: Woonkamer
  - type: vertical-stack
     cards:
       - type: custom:bubble-card
          card_type: pop-up
          hash: '#living-room-lights'
          auto_close: '30000'
          name: Woonkamer - Lampen
   - type: vertical-stack
     cards:
        - type: custom:bubble-card
           card_type: pop-up
           hash: '#living-room-curtains'
           auto_close: '30000'
           name: Woonkamer - Gordijnen
...some more cards
```
