### ISSUE TITLE
Companion APP with URL and hash

### ISSUE THREAD

**Issue by joaopedros2** [Clooos/Bubble-Card#270]
Hello, I'm trying to migrate things to have just one 'view' in the homepage lovelace.

I attempted to use the 'hash' directly in the URL of my camera notifications, but unfortunately, it doesn't work; it ignores the 'hash.'

Is there another way to achieve this?

```
service: notify.mobile_app_phone
data:
  title: "Motion Detected"
  message: "Someone."
  data:
    clickAction: '/lovelace/homepage#cameras'
```
