### ISSUE TITLE
Bubble Card only visible in Edit Mode

### ISSUE THREAD

**Issue by sascha005** [Clooos/Bubble-Card#276]
Hello, my Bubble Card disapears if i leave the Edit Mode. My Home Assistant is a fresh Install. Clear Browsers Cache does not help. Tested with different Browsers and the Companion App.

**Comment by Clooos** [comment]
Hi! All pop-ups are hidden by default when leaving the editor. To open a pop-up just had a button pointing to your hash, everything is explained in the documentation:
```yaml
type: button
tap_action:
  action: navigate
  navigation_path: '#kitchen'
name: Kitchen
icon: mdi:fridge
```
