### ISSUE TITLE
Custom button does not call tap_action

### ISSUE THREAD

**Issue by Kamii** [Clooos/Bubble-Card#333]
**Describe the bug**
When clicking on a custom button the tap action is not called. It works when clicking on the icon (icon-container). 

**To Reproduce**
1. Add a custom button with tap_action. e.g: 
```
      - type: custom:bubble-card
        card_type: button
        button_type: custom
        entity: light.lights_kitchen
        name: Köket
        icon: mdi:fridge
        tap_action:
          action: navigate
          navigation_path: '#kitchen'
 ```   
3. Click on the label in the button

**Expected behavior**
Call the tap action

**Screenshots**
[Nothing happens](https://github.com/Clooos/Bubble-Card/assets/1037827/97f6b4a8-5745-4866-9943-6b51e41ec36b)

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.1 (23B81)
 - Browser Chrome
 - Version 1.6.2 

**Additional context**
I did a update today and it stopped working on both my phone and desktop
