### ISSUE TITLE
cant remove shadow from horizontal buttons Stack

### ISSUE THREAD

**Issue by telegrambeans** [Clooos/Bubble-Card#337]
Unfortunately I can't remove the shadow at the bottom of the bubble stack card, see picture. 

![fully-screenshot (4)](https://github.com/Clooos/Bubble-Card/assets/13040847/4429ec96-2a09-423e-9318-d7b677da1fa3)

Version: current
HA Version : Current

**Comment by Clooos** [comment]
Hi! You can just add this custom style to your horizontal buttons stack YAML:

```yaml
type: custom:bubble-card
card_type: horizontal-buttons-stack
# Your config...
styles: |
  .horizontal-buttons-stack::before {
    display: none !important;
  }
```
