### ISSUE TITLE
Bubble card and shopping list

### ISSUE THREAD

**Issue by skank01** [Clooos/Bubble-Card#362]
Been having this since the beginning
If i use bubble card to show my shopping list, its empty

![image](https://github.com/Clooos/Bubble-Card/assets/53368406/aa54a42f-3ac5-4ce0-a7a6-b7cd61a95191)

If i wait long enough or sometimes click again, its there... 

![image](https://github.com/Clooos/Bubble-Card/assets/53368406/517747d8-a937-4337-b5ca-531f6eaaedc6)

Any idea?

**Comment by Clooos** [comment]
Hi! I have myself an identical pop-up on my personal config and I've never had this issue. Can you show me the code of your pop-up?

Here's mine:

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    icon: mdi:cart-outline
    name: Shopping list
    hash: '#shopping-list'
  - type: shopping-list
```
