### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Trzinka** [Clooos/Bubble-Card#373]
Hi!

# I am looking for a solution to my problem.

## I have a floor plan card before/through which I load a horizontal-stack card and then a vertical-stack card where I have 4 cameras set up with a custom:webrtc-camera card.

`This is how it looks right now and I don't like it:`

![20240126-FP cameras](https://github.com/Clooos/Bubble-Card/assets/40424965/2791874b-4ac4-4647-9d21-212598496f7c)

`Would it be possible to arrange via the popup so that the video would be displayed if some of these sensors were detected`

![Frigat camera_1](https://github.com/Clooos/Bubble-Card/assets/40424965/ed99cf92-4c07-4db9-be92-fc160a2afde0)

`I currently have it set up like this`
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#pop-up-jedilnica'
    trigger_entity: binary_sensor.diane_all_occupancy
    trigger_close: true
    state: camera.jedilnica
    trigger_state: 'on'
```

`I don't know if `trigger_state: 'on'' is correct given:`

![20240127-Frigat-Jedilnica-HA Developer tools](https://github.com/Clooos/Bubble-Card/assets/40424965/8d5ec7a7-c0f0-45ab-bf16-3760bf2af203)

`I would like to have such an appearance that if the camera detects an object, a pop-up video play, if possible.`

![20240126-FP cameras-Motion](https://github.com/Clooos/Bubble-Card/assets/40424965/1f26127e-04ce-4f9b-a04f-fca3efed63a5)

_Originally posted by @Trzinka in https://github.com/Clooos/Bubble-Card/discussions/289#discussioncomment-8264390_
