### ISSUE TITLE
Popup card not visible

### ISSUE THREAD

**Issue by PrzemekSkw** [Clooos/Bubble-Card#376]
**Describe the bug**
I choose vertical stack card. Then I choose popup cards X2. I see them in edit mode but when I click finish at the top right corner card is not there.

**
**Screenshots**

![Screenshot_2024-02-03-23-46-08-15_c3a231c25ed346e59462e84656a70e50](https://github.com/Clooos/Bubble-Card/assets/25219988/440d037d-0d0d-4092-a536-c7ba46e3f2c8)
![Screenshot_2024-02-03-23-46-04-39_c3a231c25ed346e59462e84656a70e50](https://github.com/Clooos/Bubble-Card/assets/25219988/89c8a199-6931-4f27-9631-b8bbfcbe631f)

**Desktop (please complete the following information):**
 - OS: unRAID server
 - HA docker ver. 2024.1.6

**Smartphone (please complete the following information):**
 - Device: OnePlus9pro
 - OS: Android 13
 - HA companion app
 - Version - 2024.1.5-full.

Yaml:
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#lampy'
    name: Lampy
    icon: mdi:ceiling-light-multiple-outline
    entity: light.lampy_stol
    state: light.gu10_salon
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#lampy'
    name: Sypialnia
    icon: mdi:outdoor-lamp
```

Regards.
