### ISSUE TITLE
Mostly-transparent bar blocking portion of a card

### ISSUE THREAD

**Issue by Cameronwyatt** [Clooos/Bubble-Card#402]
**For any feature request [you can open a new discussion here](https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests) to allow everyone to vote.**

**For any question [you can open a new discussion here](https://github.com/Clooos/Bubble-Card/discussions/categories/q-a).**

**Describe the bug**
The top-most card in each of my pop-ups has a mostly-transparent bar that has shown up and blocks me from clicking anything underneath it. In the below screenshots you can see it applies to various types of cards. It's tough to see it, but you can see it clipping through the borders of the cards and the info underneath the bar is obscured. 

**To Reproduce**
1. Click on pop-up
2. Try to click something towards the bottom of the first card and you're unable to

**Expected behavior**
I'd expect it not to block the cards

**Screenshots**
![2024-02-27_16-05-28](https://github.com/Clooos/Bubble-Card/assets/9828890/c7cd0769-c78e-4ddc-9e60-e6c54ae5d246)
![2024-02-27_16-05-46](https://github.com/Clooos/Bubble-Card/assets/9828890/1f75dd45-ae96-486c-876a-2d00b53acf35)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 123.0 (64-bit)

**Additional context**
Vertical stack 1 (affected):
```yaml
- type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: light.basement_stairs
          - entity: light.foyer_light
          - entity: light.kitchen
          - entity: light.middle_stairs
          - entity: light.porch_light
        title: Common Lights
        state_color: true
      - type: custom:bubble-card
        card_type: pop-up
        hash: '#common-lights'
        name: Common Lights
        icon: mdi:lightbulb
        is_sidebar_hidden: true
        close_on_click: true
```

Vertical stack 2 (also affected):
```yaml
  - type: vertical-stack
    cards:
      - type: custom:alarmo-card
        entity: alarm_control_panel.alarmo
        button_scale_actions: 1.5
        button_scale_keypad: 1.5
        keep_keypad_visible: true
      - type: entities
        entities:
          - entity: binary_sensor.zone_1
          - entity: binary_sensor.zone_3
          - entity: binary_sensor.zone_2
        title: Sensors
        state_color: true
        show_header_toggle: false
      - type: custom:bubble-card
        card_type: pop-up
        hash: '#alarmo'
        margin: 7px
        width_desktop: 700px
        name: Alarm
        is_sidebar_hidden: true
```

Horizontal stack:
```yaml
  - type: custom:bubble-card
    card_type: horizontal-buttons-stack
    auto_order: false
    1_name: Common Lights
    1_icon: mdi:lightbulb
    1_link: '#common-lights'
    2_name: Basement Lights
    2_icon: mdi:home-floor-b
    2_link: '#basement-lights'
    3_link: '#covers'
    3_name: Blinds
    3_icon: mdi:roller-shade
    is_sidebar_hidden: true
    4_link: '#alarmo'
    4_name: Alarm
    4_icon: mdi:alarm-panel
    rise_animation: false
    margin: 7px
    width_desktop: 800px
    hide_gradient: true
```

Thank you! 🍻
