### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by Perfect-Web** [Clooos/Bubble-Card#410]
**For any feature request [you can open a new discussion here](https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests) to allow everyone to vote.**

**For any question [you can open a new discussion here](https://github.com/Clooos/Bubble-Card/discussions/categories/q-a).**

**Describe the bug**
2024-03-10 23:15:51.152 ERROR (MainThread) [frontend.js.latest.202403060] Uncaught error from Chrome 122.0.0.0 on Linux x86_64
TypeError: Cannot read properties of null (reading 'classList')
/hacsfiles/Bubble-Card/bubble-card.js:520:1627

**To Reproduce**
```
      type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: pop-up
          hide_backdrop: true
          hash: '#groupTemperature'
          bg_blur: 0
          bg_opacity: 100
          name: Senzori din grup
          icon: mdi:leak
          width_desktop: 100%
        - type: custom:auto-entities
          filter:
            include:
              - {id}
          card:
            type: entities
            state_color: true
          else:
            type: custom:mushroom-template-card
            tap_action:
              action: none
            hold_action:
              action: none
            primary: bbbbb
            secondary: aaaaa
            icon: mdi:exclamation-thick
            fill_container: false
            badge_icon: mdi:thermometer
            badge_color: red
            icon_color: pink
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 1.6.2]

**Smartphone (please complete the following information):**
 - Browser [e.g. Home Assistant Companion App, Safari]
 - Version [e.g. 1.6.2]

**Additional context**

Thank you! 🍻
