### ISSUE TITLE
Bug: Unable to access popup card from external link

### ISSUE THREAD

**Issue by sayam93** [Clooos/Bubble-Card#422]
I use homeassistant://navigate/lovelace/ios to access my dashboard through a notification tap-action. I have a pop-up with path #feed in /lovelace/ios which has my cameras in it but am unable to access it using homeassistant://navigate/lovelace#feed

This is what happens when I tap the notification.
![RPReplay_Final1711532977](https://github.com/Clooos/Bubble-Card/assets/163408168/18a31532-5203-402e-adb8-b33da89c4056)

This is what it should open:
![RPReplay_Final1711532996](https://github.com/Clooos/Bubble-Card/assets/163408168/2a4855a2-e019-4aa2-925a-2334b7bb36f8)

My notification code is as below

```
service: notify.mobile_app_iphone
metadata: {}
data:
  message: Balcony camera detected motion at {{ now().strftime('%m/%d/%Y, %H:%M:%S') }}
  title: Motion Detected!
  data:
    url: homeassistant://navigate/lovelace/ios#feed
    push:
      sound:
        name: default
        critical: 1
        volume: 1

```

Please help!
