### ISSUE TITLE
Ignore query args in url

### ISSUE THREAD

**Issue by NickM-27** [Clooos/Bubble-Card#43]
This is likely a bit of a niche request, but I use [a custom card that supports query args](https://github.com/dermotduffy/frigate-hass-card#query-string-actions) that allow controlling it. I am looking to put this card in a popup, however it seems that the query args throw off the `#popup`

**Comment by Clooos** [comment]
Hi @NickM-27! Glad to see that you are trying my cards, I really love Frigate and you answered some of my questions on GitHub about one year ago (this is not relevant but I wanted to say it anyway). 

This is indeed a niche request and I didn't even new that this was possible with Frigate. To be honest I'm quite new in JS and I don't really know how this can be fixed for now, but if you have any idea to suggest I will be glad to try to add this feature. Or maybe this is a feature that need to be added to the Frigate card?

**Comment by NickM-27** [comment]
> Or maybe this is a feature that need to be added to the Frigate card?

Without having looked at the code, I believe the problem is that the bubble card is not matching on the `#popup` hash, likely because of the extra text in the navigation path (being the query args). So I think it should just be a matter of the bubble card ignoring `?` and anything that comes after it when checking if the path matches on a popup hash

**Comment by Clooos** [comment]
Thanks, I think that I was to tired to understand your request at first but this is now fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.8

**Comment by NickM-27** [comment]
This doesn't seem to be working for me. For example I am using

`#cameras?frigate_card_action:popup:camera_select=back_gate_cam`

and the card is not popping up. I remove the `?frigate_card_action:popup:camera_select=back_gate_cam` part and it works

**Comment by Clooos** [comment]
This is weird, I've just tried with this and this is working on my configuration:

type: custom:bubble-card
card_type: button
button_type: custom
entity: media_player.salon
tap_action:
  action: navigate
  navigation_path: '#cuisine?frigate_card_action:popup:camera_select=back_gate_cam'
name: Test

**Comment by Clooos** [comment]
This is working too for me, so this is indeed probably a cache issue or something related to the new v4.0.0 of the Frigate card (I'm still on v3.0.1).

```yaml
show_name: true
show_icon: false
type: button
name: Test
tap_action:
  action: navigate
  navigation_path: '#cuisine?frigate_card_action:popup:camera_select=back_gate_cam'
```

**Comment by NickM-27** [comment]
yeah looks like a cache issue, after force disabling cache in browser tools it is working

**Comment by Clooos** [comment]
Great! 😄

**Comment by dnestico** [comment]
I don't get it, this just doesn't work for me at all.

Card:
```
type: grid
square: false
cards:
  - camera_view: auto
    type: picture-glance
    entities: []
    camera_image: camera.porch
    tap_action:
      action: navigate
      navigation_path: '#frigate?frigate_card_action:popup:camera_select=porch'
  - camera_view: auto
    type: picture-glance
    entities: []
    camera_image: camera.driveway
    tap_action:
      action: navigate
      navigation_path: '#frigate?frigate_card_action:popup:camera_select=driveway'
  - camera_view: auto
    type: picture-glance
    entities: []
    camera_image: camera.garage
    tap_action:
      action: navigate
      navigation_path: '#frigate?frigate_card_action:popup:camera_select=garage'
columns: 3
```
Frigate card:
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#frigate'
    name: Cameras • Quick view
    icon: mdi:cctv
    margin_top_mobile: 60px
    margin_top_desktop: 60px
  - type: vertical-stack
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.porch
            live_provider: go2rtc
            frigate:
              url: 192.168.2.176
            go2rtc:
              modes:
                - webrtc
                - mse
            dependencies:
              all_cameras: true
          - camera_entity: camera.nest_doorbell
            dependencies:
              all_cameras: true
          - camera_entity: camera.driveway
            live_provider: go2rtc
            dependencies:
              all_cameras: true
          - camera_entity: camera.garage
            dependencies:
              all_cameras: true
        live:
          controls:
            timeline:
              mode: none
              style: ribbon
            thumbnails:
              mode: none
            title:
              mode: none
          layout:
            fit: contain
          draggable: false
          auto_unmute: selected
          auto_play: selected
          lazy_unload: unselected
          auto_mute: all
          auto_pause: unselected
        media_viewer:
          controls:
            timeline:
              mode: below
            title:
              mode: none
          auto_unmute: visible
          auto_mute: hidden
          draggable: false
        menu:
          style: outside
          position: bottom
          buttons:
            frigate:
              enabled: false
            substreams:
              enabled: false
            clips:
              enabled: false
            snapshots:
              enabled: false
            download:
              alignment: opposing
            fullscreen:
              alignment: opposing
            camera_ui:
              enabled: false
              alignment: opposing
            expand:
              alignment: opposing
            media_player:
              alignment: opposing
            play:
              enabled: true
            mute:
              enabled: true
            screenshot:
              enabled: true
              icon: mdi:cellphone-screenshot
            cameras:
              enabled: false
        view:
          scan:
            enabled: true
            untrigger_seconds: 10
          update_force: true
        timeline: {}
```
