### ISSUE TITLE
Horizontal Stack: Use array for buttons

### ISSUE THREAD

**Issue by SLaks** [Clooos/Bubble-Card#455]
Instead of using numeric prefixes like `1_name:`, `2_icon:`, etc, can you please accept an array of buttons?

eg,

```yaml
buttons:
  - name: First button
    icon: mdi:light
  - name: Second button
    ...
```

This will make it much simpler for me to build a dynamic set of buttons using https://github.com/thomasloven/lovelace-auto-entities or https://github.com/iantrich/config-template-card
