### ISSUE TITLE
Bug: Popup always visible when using lovelace state switch

### ISSUE THREAD

**Issue by rcjkierkels** [Clooos/Bubble-Card#47]
I am using this https://github.com/thomasloven/lovelace-state-switch integration to easily seperate mobile and desktop views using a mediaquery as state switch. But if I use this configuration and use your popup example the popup is always visible. I am using the latest version (beta 7). When I press the button the popup moves only up and down.

```
panel: true
title: ""
icon: mdi:tablet-dashboard
path: overzicht
cards:
  - type: custom:state-switch
    entity: mediaquery
    states:
      "(max-width: 600px)": !include ./mobile/overzicht.yaml
      "all": !include ./desktop/overzicht.yaml
 ```

```
- type: button
    tap_action:
      action: navigate
      navigation_path: "#kitchen"
    name: Kitchen
    icon: mdi:fridge
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        hash: "#kitchen"
        name: Kitchen
        icon: mdi:fridge
        margin_top_mobile: 0px
      - !include ../cards/chips/voordeur.yaml
      - !include ../cards/chips/achterdeur.yaml
      - !include ../cards/chips/garagedeur.yaml
      - !include ../cards/chips/schuifpui.yaml
```
