### ISSUE TITLE
Tap on icon, tap on name?

### ISSUE THREAD

**Issue by jockebq** [Clooos/Bubble-Card#476]
Using latest 2.0 beta, and changing the tap on icon works, but tapping on the name does only toggle the entity on or off?
Can you make it so both are doing the same thing, or make it custom for the icon and the name?

**Comment by Clooos** [comment]
This issue should be fixed in the new beta! Can you confirm this?

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

**Comment by jockebq** [comment]
Tested this again, but the behaviour is the same on Beta 5. I have only set the icon to Hold action, not tap. This works on the icon, but the name will still do the default behaviour. Can you separate them or make the behaviour the same on both?

Another issue I have is I cannot show a separate sensor next to the title:
    state: sensor.tanda_lampor
It doesnt show up?

**Comment by Clooos** [comment]
I guess that you are not using the GUI editor, I still need to edit the documentation for that but you can change the tap actions on the button itself now.

In YAML it looks like this:

button_action:
  tap_action: more-info

For the state you now have to add a sub-button, like this:

```yaml
sub_button:
  - entity: sensor.kitchen_temperature
    icon: mdi:thermometer
    show_name: false
    show_icon: true
    show_background: false
    show_attribute: false
    show_state: true
    tap_action:
      action: more-info
```
