### ISSUE TITLE
Cards disappearing when exiting 'edit' mode

### ISSUE THREAD

**Issue by siliconsolder** [Clooos/Bubble-Card#48]
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#uppfarten'
    name: Uppfarten
    icon: mdi:garage
    entity: light.uppfartsbelysningen
    state: sensor.uppfarten_temperatur
    state_unit: °C
    width_desktop: 600px
    margin_top_mobile: 18px
    margin_top_desktop: 74px
    is_sidebar_hidden: false
  - square: false
    type: grid
    columns: 3
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: binary_sensor.ytterdorr_open
        name: Hallen
        icon: mdi:door
        card_mod:
          style: |
            .switch-button { 
                {% if is_state(config.entity, 'on') %}
                  background-color: #990000 !important
                {% else %}
                  background-color: green !important
                {% endif %}
            }
  - type: custom:bubble-card
    card_type: separator
    name: Lampor
    icon: mdi:lightbulb-group
  - square: false
    type: grid
    columns: 2
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: switch
        entity: light.svampen
        name: Svampen
      - type: custom:bubble-card
        card_type: button
        button_type: switch
        entity: light.lilla_hallen
        icon: mdi:ceiling-light
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.vintagelampan
        icon: mdi:lamp-outline
        name: Vintagelampan
  - type: custom:bubble-card
    card_type: separator
    name: Mídia
    icon: mdi:play
  - square: false
    type: grid
    columns: 2
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: media_player.tv_n_i_vardagsrummet_cc
        icon: mdi:google-chrome
        name: Chromecast

```

![image](https://github.com/Clooos/Bubble-Card/assets/58149288/4ab0f00d-eeaa-495b-8b38-f9395f393989)
![image](https://github.com/Clooos/Bubble-Card/assets/58149288/0e7a0a69-265c-4160-b212-9a103e5d2e28)
