### ISSUE TITLE
button entity's do not toggle as intended

### ISSUE THREAD

**Issue by ElDingo424** [Clooos/Bubble-Card#496]
**Problem:**
add button entity and set action to toggle 
(Same as you would using standard button card)

**Code:**
```
     - entity: button.living_room_speaker_on_2
        name: false
        icon: mdi:power-on
        tap_action:
          action: toggle
```
          
**Throws error:** 

Service button.turn_off not found
