### ISSUE TITLE
Service calls not working on sub-buttons

### ISSUE THREAD

**Issue by AndLindemann** [Clooos/Bubble-Card#500]
**Describe the bug**  
I'm having bad luck with call-service actions on sub-buttons. The services are not being called. 
I think it is interferring with double_tap_action. If that is set to "none", then tap_action and hold_action also don't work. 
If you define double_tap_action, then tap_action and hold_action will start working as well. The same seems to apply if you for example set hold_action to "none". Then also tap_action and double_tap_action will stop working.

**To Reproduce**  
```
      - type: custom:bubble-card
        card_type: button
        entity: light.lampen
        name: Lampen
        tap_action:
          action: toggle
        double_tap_action:
          action: more-info
        hold_action:
          action: none
        button_action:
          tap_action:
            action: navigate
            navigation_path: "#popuptest"
          double_tap_action:
            action: none
          hold_action:
            action: none
        sub_button:
          - entity: binary_sensor.pc
            name: PC
            tap_action:
              service: light.toggle
              target:
                entity_id: light.lamp
            icon: fas:computer
            hold_action:
              action: call-service
              service: button.press
              target:
                entity_id: button.lamp
            double_tap_action:
              action: none
```

**Expected behavior**  
Service being called when tapping on respective sub_button (PC), even when double_tap_action is not defined or defined as "none"

**Screenshots**  
n/a

**Informations (please complete the following information):**  
 - OS: Win11 / iOS
 - Browser: Firefox / Safari
 - Bubble Card version: 2.0.0-beta.6
 - Home Assistant version: 2024.5.1

**Additional context**  
n/a

Thank you! 🍻
