### ISSUE TITLE
Popups appear on the left side of the screen instead of the center in Kiosk mode in desktop browsers

### ISSUE THREAD

**Issue by nomonkeynodeal** [Clooos/Bubble-Card#528]
**Describe the bug**  
Popups appear on the left side of the screen instead of the center with Kiosk Mode in desktop browsers (Brave, Firefox). When Kiosk Mode is disabled, the popups appear centered.

**To Reproduce** 
kiosk mode:
```
title: Home
kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.editmode: 'off'
      kiosk: true
    - entity:
        input_boolean.editmode: 'on'
      kiosk: false
```

bubble card:
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    bg_opacity: 20
    shadow_opacity: 10
    bg_blur: '10'
    hash: '#second'
    name: Controls
    is_sidebar_hidden: true
    width_desktop: 1000px
    hide_backdrop: true
    scrolling_effect: false
    card_layout: large
    margin_top_desktop: '-50px'
```

**Additional context**  
This started happening 2-3 versions ago I think. (I installed several updates in a short period.) There used to be a toggle in the GUI to fix it, but that option is now gone.

I thought I saw something that said Kiosk Mode shouldn't be used with Bubble Card, or that there are better options, but my searches have turned up nothing about this now.

**Comment by Clooos** [comment]
Hi, what toggle are you referencing too?

**Comment by nomonkeynodeal** [comment]
> Hi, what toggle are you referencing too?

The toggle just turns turns on and off kiosk mode. The popups don't center when kiosk mode is enabled.

**Comment by nomonkeynodeal** [comment]
Oh, I don't remember the name of the toggle. I thought it was something like "Fix ..." and it fixed the menu alignment on desktop. Sorry I don't have more info.

**Comment by Clooos** [comment]
Do you have this issue if you create a new pop-up?

**Comment by nomonkeynodeal** [comment]
> Do you have this issue if you create a new pop-up?

Yes, I just tried.

**Comment by nomonkeynodeal** [comment]
> Hi again, I've just released a new beta and I've found some issues related to the pop-ups, with some luck it will fix this issue 🤞 Keep me informed 🙂
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.12

No change. Are you able to replicate the issue?

**Comment by nomonkeynodeal** [comment]
https://github.com/NemesisRE/kiosk-mode

**Comment by Clooos** [comment]
I've tested it, can you try to add this in a pop-up custom style?
```yaml
@media only screen and (min-width: 768px) {
    .bubble-pop-up {
      left: inherit !important;
    }
}
```

**Comment by nomonkeynodeal** [comment]
> I've tested it, can you try to add this in a pop-up custom style?
> 
> ```yaml
> @media only screen and (min-width: 600px) {
>   .bubble-pop-up {
>     left: calc(50% - (var(--desktop-width, 540px) / 2)) !important;
>   }
> }
> ```

That works! Are you going to make this a part of Bubble card, or should I add it to all my cards manually?

**Comment by Clooos** [comment]
I'm looking for a way to makes this automatic when `hide_sidebar: true` is detected. If I don't find a way I will add an option in the editor.

This is probably the last issue I will fix before releasing the v2 final 🥳

**Comment by Clooos** [comment]
I've found the best way to fix that and this will be the official fix for the kiosk mode users.

First for your kiosk mode config, remove `hide_sidebard: true` or `kiosk: true` and just keep that under `kiosk_mode`:
```yaml
kiosk_mode:
  hide_header: true
```

Then go to your HA profile configuration then toggle this:

<img width="744" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/36499953/20d9e81d-aee0-4306-9ca4-376bf6406a94">

This will now works as expected and you can remove the custom style I've sent previously.

**Comment by nomonkeynodeal** [comment]
That does seem to work for me.

**Comment by Clooos** [comment]
Someone on the HA forum has confirmed that it was working, are you sure that you have followed my instructions correctly?

**Comment by nomonkeynodeal** [comment]
You misread. It works!

**Comment by Clooos** [comment]
Hahaha indeed! It seems that I'm getting used to see negative comments 🤓

I'm glad that it's working for you too!

**Comment by nomonkeynodeal** [comment]
Yeah, I guess I snaked you there with the phrasing. I just could have sworn I had tried this already.

**Comment by Perfect-Web** [comment]
Hi, but why have you guys marked this a closed ? if we do not wanna hide the sidebar for various reasons, the problem still persists ....

**Comment by Clooos** [comment]
Hi, you probably haven't updated kiosk-mode, this issue was fixed a few month ago. Don't forget to clear your cache after that.

**Comment by Perfect-Web** [comment]
@Clooos nope, have everything to the last version and hard cleared, and pop-up still persists, far left under the bar i'm afraid

**Comment by Clooos** [comment]
Just to be sure, do you have this one installed?

https://github.com/NemesisRE/kiosk-mode

**Comment by Perfect-Web** [comment]
yes

**Comment by Perfect-Web** [comment]
![image](https://github.com/user-attachments/assets/6b6eb13e-438f-4f10-b8d6-73f376bc4e78)

As you can see, using 
```
kiosk_mode:
  non_admin_settings:
    hide_notifications: true
    hide_account: true
  hide_header: true
  hide_dialog_header_action_items: true
  hide_dialog_history_show_more: true
  hide_dialog_logbook_show_more: true
  hide_dialog_attributes: true
  ```
and

```
    card:
      type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: pop-up
          hide_backdrop: true
          trigger_entity: var.pop_up
          trigger_close: true
          bg_blur: 0
          bg_opacity: 100
.....
          width_desktop: 100%
```

throws the pop-up under the left menu
