### ISSUE TITLE
Navigate to page using browser-mod

### ISSUE THREAD

**Issue by robotsmarthomes** [Clooos/Bubble-Card#53]
Hi Cloos,

Love the card - quick question. Are you able to navigate to the popups through popups. for example, doorbell press, then it opens up the camera on the bubble card. Not sure if its possible yet, but would love it to be!

**Comment by Clooos** [comment]
Hi! This could be interesting indeed, but I have a slightly different approach in mind, what do you think of something like a trigger based on an entity state directly in the pop-up?

This could be like this :
```yaml
type: custom:bubble-card
card_type: pop-up
icon: mdi:video
name: Camera
hash: '#camera'
trigger_entity: binary_sensor.doorbell
trigger_entity_state: on
```

And then if your doorbell is sending an event you can add something like this in your config, this is what I did with my Amcrest doorbell :
```yaml
template:
  - trigger:
      - platform: event
        event_type: amcrest
        event_data:
          event: "CallNoAnswered"
          payload:
            action: "Start"
    binary_sensor:
      - name: "Doorbell Button Pressed"
        state: on
        auto_off: 00:00:20
```

Tell me what do you think of this approach.
