### ISSUE TITLE
Other color on seperator line and title

### ISSUE THREAD

**Issue by Orionxyy** [Clooos/Bubble-Card#530]
Is there any way to give the sepeator line or the seperator title an other color?

**Comment by brunosabot** [comment]
Just add the `background-color` you like in the styles.
Example:
```yaml
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: mdi:ceiling-light-multiple
    styles: |
      .bubble-line {
        background-color: red;
      }

```
