### ISSUE TITLE
Beta 10 button shifted

### ISSUE THREAD

**Issue by peterthepeter** [Clooos/Bubble-Card#534]
Hello,

since beta 10 the buttons are shifted and have a scrollline on the outside.

This only happens on the PC (on my Mac) tested with several browsers (Arc, Safari, Edge).
Cache and cookies have been cleared and all add-ons in the browsers have also been deactivated for test purposes.
I don't have this error on my mobile phone (iOS).
I am attaching a picture of the error.

![Bildschirmfoto 2024-05-26 um 09 17 31](https://github.com/Clooos/Bubble-Card/assets/74273835/5915503d-d2bd-4ed1-b2d3-68ceebf6e3ef)
![Bildschirmfoto 2024-05-26 um 09 18 07](https://github.com/Clooos/Bubble-Card/assets/74273835/5eaaf4dd-2da5-44a1-9020-ee72bb4377c0)

**Comment by Clooos** [comment]
Hi, can you check in the editor if you are not on the beta 9?

**Comment by peterthepeter** [comment]
You're absolutely right. I am 99.9% sure that I did the update yesterday and everything was OK.

I have now installed update 10 again and now it works.

Sorry for the confusion.

A quick question should be if I want to change the colour of the button. Does this also work when the device is switched off. As soon as I switch it on it briefly turns green and then the normal money for switched on devices is displayed. 
Have I done something wrong?

```
styles: |-
  .switch-button {
    background-color: ${hass.states['switch.socket_lelit_mara_x2'].state === 'on' ? 'green' : 'rgba(0,190,240,0.6)' } !important;
  } .bubble-icon-container {
    color: rgba(0,190,240,0.6);
  }```

**Comment by Clooos** [comment]
There is indeed a weird issue when installing this update, some got beta 9 instead of 10.

For you styling issue you can try this:

```yaml
styles: |-
  .bubble-button-card-container {
      background-color: ${hass.states['switch.socket_lelit_mara_x2'].state === 'on' ? 'green' : 'rgba(0,190,240,0.6)' } !important;
  } 
  .bubble-icon-container {
      color: rgba(0,190,240,0.6);
  }

**Comment by peterthepeter** [comment]
I'll keep an eye on the update.

Unfortunately, changing the ON colour does not work. The button briefly turns green and then immediately turns yellow. I have attached a video.


https://github.com/Clooos/Bubble-Card/assets/74273835/6e61f58c-795f-4aed-8ef0-70c5039fe9ff

**Comment by Clooos** [comment]
My bad, this one should work:

```yaml
styles: |-
  .bubble-button-background {
      opacity: 1 !important;
      background-color: ${hass.states['switch.socket_lelit_mara_x2'].state === 'on' ? 'green' : 'rgba(0,190,240,0.6)' } !important;
  }
  .bubble-icon-container {
      color: rgba(0,190,240,0.6);
  }
```
