### ISSUE TITLE
Inaccessible input_select options

### ISSUE THREAD

**Issue by mnneely** [Clooos/Bubble-Card#565]
**Describe the bug**  
Menu dropdown items from input_select entity only display 5 max, rendering additional items inaccessible.

**To Reproduce**  
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#quick_run'
    name: Quick Run
    icon: mdi:timer-outline
  - type: vertical-stack
    cards:
      - type: custom:mushroom-select-card
        entity: input_select.irrigation_zone
        fill_container: false
        name: Selected Zone
        secondary_info: none
        layout: horizontal
```

```
# Example configuration.yaml entry
input_select:
  irrigation_zone:
    options:
      - Zone1
      - Zone2
      - Zone3
      - Zone4
      - Zone5
      - Zone6
      - Zone7
      - Zone8
      - Zone9
      - Zone10
```

**Expected behavior**  
All dropdown menu items to be accessible.

**Screenshots**  
Unable to scroll to lower dropdown items.
<img width="797" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/8136142/3a5f3226-64e2-4d07-bc38-e9a5189f8288">

**Informations (please complete the following information):**  
 - OS: iOS and MacOS
 - Browser: Safari
 - Bubble Card version: 2.0.1
 - Home Assistant version: 2024.6.1

**Additional context**  
Thank you for your very useful card! My dashboards couldn't live without it. :) 

Thank you! 🍻
