### ISSUE TITLE
Bubble card button is unable to trigger input_button helper

### ISSUE THREAD

**Issue by 0verEngineer** [Clooos/Bubble-Card#568]
**Describe the bug**  
I have a bubble card button and an input_button helper and i have the input_button entity in the bubble card button but it is not triggered.

**To Reproduce**  
1. Create input_button helper
2. Create bubble card button with input_button as entity
3. Click the bubble card button
4. See the problem (check the last triggered state of input_button)

**Expected behavior**  
The input_button should be triggered

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! You're issue seems related to this one:

https://github.com/Clooos/Bubble-Card/issues/496

Just change the service to `input_button.press` then it should works.

**Comment by 0verEngineer** [comment]
@Clooos Thanks a lot for the fast answer, however i don't know why, i tried like this and it did not work:

`- type: custom:bubble-card
            card_type: button
            entity: input_button.nightmode_trigger_button
            name: Nachtmodus
            show_state: false
            tap_action:
              action: call-service
              service: input_button.press
              target:
                entity_id: input_button.nightmode_trigger_button`

**Comment by Clooos** [comment]
You need to add this action under `button_action`, with your YAML it only works by tapping the icon, this YAML should works:

```yaml
          - type: custom:bubble-card
            card_type: button
            entity: input_button.nightmode_trigger_button
            name: Nachtmodus
            show_state: false
            button_action:
              tap_action:
                action: call-service
                service: input_button.press
                target:
                  entity_id: input_button.nightmode_trigger_button

**Comment by 0verEngineer** [comment]
Unfortunately this does not work either

**Comment by Clooos** [comment]
Oh I realize that you haven't added any button type, add this `button_type: switch`, this should works now 🤞

**Comment by 0verEngineer** [comment]
Do you mean like that:

```
- type: custom:bubble-card
            card_type: button
            entity: input_button.nightmode_trigger_button
            name: Nachtmodus
            show_state: false
            button_type: switch
            button_action:
              tap_action:
                action: call-service
                service: input_button.press
                target:
                  entity_id: input_button.nightmode_trigger_button
```

does not work.
