### ISSUE TITLE
Pop up don't work from bubble button

### ISSUE THREAD

**Issue by idarius** [Clooos/Bubble-Card#57]
Hello,

when using this code for exemple : 
```
views:
  - title: Home
    path: Home
    subview: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            state: sensor.temperature_grenier
            entity: light.grenier
            name: Grenier
            icon: mdi:air-purifier
            hash: '#grenier'
            state_unit: °C

      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:clock-weather-card
            entity: weather.xxxx
            sun_entity: sun.sun
            weather_icon_type: line
            animated_icon: true
            forecast_days: 2
            locale: fr
            time_format: 24
            hide_today_section: false
            hide_forecast_section: false
            tap_action:
              action: navigate
              navigation_path: '#grenier'

          - type: custom:bubble-card
            card_type: button
            button_type: custom
            entity: light.grenier
            name: Grenier
            icon: mdi:ceiling-light-multiple-outline
            tap_action:
              action: navigate
              navigation_path: '#grenier'
            double_tap_action:
              action: none
            hold_action:
              action: none

      - type: custom:bubble-card
        card_type: horizontal-buttons-stack
        1_name: grenier
        1_icon: mdi:garage
        1_link: '#grenier'
```
I can click on the weather card or the footer and the pop up will open just find.
However when i click on the button card "Grenier" nothing happens, just the address in chrome browser who add #grenier after the url.

With the vertical stack card like in this exemple, i can't open the popup with the Grenier button no matter what.

Without the vertical stack card, i need to click 2 times on the button to open the popup (first time the address link change to http://x.x.x.x:8123/dashboard-mobile/Home#grenier, second time the popup open)

Thanks you for this awesome card :)
