### ISSUE TITLE
Service sensor.turn_off not found

### ISSUE THREAD

**Issue by StuartHaire** [Clooos/Bubble-Card#575]
**Describe the bug**  
Error "Service sensor.turn_off not found."

**To Reproduce**  
1. Use the following code:
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#hotwater'
    back_open: true
    trigger_close: false
    name: Hot Water
    icon: mdi:faucet
  - type: custom:bubble-card
    card_type: button
    icon: mdi:faucet
    entity: sensor.thermostat_1_availability
    name: 15 minutes
    button_type: custom
    tap_action:
      action: call-service
      confirmation:
        text: Are you sure you want to turn on HOT WATER ONLY for 15 minutes?
      service: script.boost_hot_water_15m
    show_state: false
    show_name: true
  - type: custom:bubble-card
    card_type: button
    icon: mdi:faucet
    entity: sensor.thermostat_1_availability
    name: 30 minutes
    button_type: custom
    tap_action:
      action: call-service
      confirmation:
        text: Are you sure you want to turn on HOT WATER ONLY for 30 minutes?
      service: script.boost_hot_water_30m
    show_state: false
  - type: custom:bubble-card
    card_type: button
    icon: mdi:faucet
    entity: sensor.thermostat_1_availability
    name: 1 hour
    button_type: custom
    tap_action:
      action: call-service
      confirmation:
        text: Are you sure you want to turn on HOT WATER ONLY for 1 hour?
      service: script.boost_hot_water_1hr
    show_state: false
  - type: conditional
    conditions:
      - condition: state
        entity: timer.heating
        state: active
    card:
      type: custom:timer-bar-card
      entity: timer.heating
      name: Time Remaining
      invert: true
      mushroom:
        color: orange
```
2. Click on any of the 15/30/1hr buttons
3. No confirmation box, error appears "Service sensor.turn_off not found."

**Expected behavior**  
Was working before. Confirmation box should appear, then select yes and script should run.

**Screenshots**  
![image](https://github.com/Clooos/Bubble-Card/assets/38922184/09ad8e26-229c-4c49-94a0-52a16210475f)

![image](https://github.com/Clooos/Bubble-Card/assets/38922184/cb7b6dee-5bfe-4d9a-9612-d52af388e780)

**Informations (please complete the following information):**  
 - OS: Any
 - Browser: Any
 - Bubble Card version: v2.0.3
 - Home Assistant version: 2024.6.1

**Additional context**  
The script runs correctly when ran manually. Nothing change changed except update to 2024.6 and latest Bubble-Card release, unsure if this is related.

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, the `button_type: custom` has been removed because every buttons are now customizable.

To change the button action you now need to do this:

```yaml
    button_action:
      tap_action:
        action: call-service
        confirmation:
          text: Are you sure you want to turn on HOT WATER ONLY for 1 hour?
        service: script.boost_hot_water_1hr
```
