### ISSUE TITLE
Can't target/resetting Areas/Area ID's with Sub Buttons

### ISSUE THREAD

**Issue by Andrewpaps** [Clooos/Bubble-Card#584]
**Describe the bug**  
Unable to specify within Sub Button a target Area ID for which to send service calls.

The following works in Developer Tools when called manually, but not within Bubble Card:

```
service: light.turn_off
target:
  area_id:
    - 2ad90885fa5111eaae53859d04696348
```

On occasion this will work once, but will not be saved permanently between card changes, as this info resets to the following:

```
type: custom:bubble-card
card_type: separator
sub_button:
  - tap_action:
      action: call-service
      service: light.turn_off
      target: {}
```

**To Reproduce**  
1. Create Bubble Card
2. Create Sub Button
3. Specify Tap Action: Service Call
4. Provide an Area ID as a target

**Expected behavior**  
Area ID is referenced to complete Service Call the same way it does in Developer Tools

**Informations (please complete the following information):** 
 - Bubble Card version (v2.0.4)
 - Home Assistant version (v2024.6.2)
