### ISSUE TITLE
Disabling "Text scrolling effect" then ignores "Show name"

### ISSUE THREAD

**Issue by jstrot** [Clooos/Bubble-Card#598]
**Describe the bug**  

I have a small button in a 1/4 width column where I show state entities of my climate system. When the state value is too large ("Home") the "Text scrolling effect" kicks in. If I disable "Text scrolling effect" then the button doesn't only show the state but also the entity name ("Lennox iComfort S30") even though I disabled "Show name".

**To Reproduce**  

Create an horizontal stack with 4 buttons such as this one:
```yaml
type: custom:bubble-card
card_type: button
entity: binary_sensor.system_home_state
show_name: false
show_state: true
button_type: state
scrolling_effect: true
```

The state (second button in my example) starts scrolling. (See screenshot 1)

Now change to `scrolling_effect: false`. The state stops scrolling but the name is added even though there is `show_name: false`. (See screenshot 2)

**Expected behavior**  

The entity state should be fixed, on multiple lies and/or with the overflow hidden or ellipsized.
The entity name must not be displayed.

**Screenshots**  

Screenshot 1: Scrolling state
![image](https://github.com/Clooos/Bubble-Card/assets/44594069/fb1e9057-234e-4fee-b64d-f2561d595348)

Screenshot 2: Entity name wrongly displayed
![image](https://github.com/Clooos/Bubble-Card/assets/44594069/88446eec-d857-4705-b97f-e86708b1ed00)

**Informations (please complete the following information):**  

 - OS: Linux, Android
 - Browser: Chrome
 - Bubble Card version: v2.0.4
 - Home Assistant version 2024.6.4

**Additional context**  

None.

Thank you! 🍻
