### ISSUE TITLE
0 height rows showing in vertical stack

### ISSUE THREAD

**Issue by GewoonRoy** [Clooos/Bubble-Card#608]
Hi,

I am using v2.0.4 with HA 2024.6.X and i'm experiencing an issue just like this. I've tried several options to fix it but haven't been able to. 

Can you help me with what i'm possibly doing wrong? I've noticed the #root of the hui-vertical-stack-card is using a gap of 8px for each element within the stack-card which creates a lot of space.

I've have a vertical stack with a lot of vertical stacks in it.
<img width="541" alt="Screenshot 2024-06-28 at 09 41 26" src="https://github.com/Clooos/Bubble-Card/assets/9586175/8f38a1e8-a32e-4ce0-9b0d-51ced80d1d79">

```
type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:button-card
         name: Woonkamer
         ...
  - type: vertical-stack
     cards:
      - type: custom:bubble-card
         card_type: pop-up
         hash: '#living-room'
         auto_close: '30000'
         name: Woonkamer
  - type: vertical-stack
     cards:
       - type: custom:bubble-card
          card_type: pop-up
          hash: '#living-room-lights'
          auto_close: '30000'
          name: Woonkamer - Lampen
   - type: vertical-stack
     cards:
        - type: custom:bubble-card
           card_type: pop-up
           hash: '#living-room-curtains'
           auto_close: '30000'
           name: Woonkamer - Gordijnen
...some more cards
```

_Originally posted by @GewoonRoy in https://github.com/Clooos/Bubble-Card/issues/268#issuecomment-2196345051_
