### ISSUE TITLE
Separator - Line length and spacing

### ISSUE THREAD

**Issue by Shasdo** [Clooos/Bubble-Card#614]
**Describe the bug**  
The separator line doesn't end with the right spacing when sub buttons are added.
The space gets longer with each sub-buttons added
The two purple line are the same length and are there to illustrate the uneven spacing.
![image](https://github.com/Clooos/Bubble-Card/assets/4083901/d1c7a834-03e0-4b72-a539-88cf13d1e677)

Also the space after the text and before the subbutton is a bit longer to my taste, is there a styling option to change it ?

Subsidiary question: (can make another issue)
 why "normal" card layout doesn't reduce the height of the cell used by each bubble card ? 
Is it a fixed minimal height linked to the LoveLace frontend ?
If there is a another card type above the separaror, it results in an unven vertical spacing. 
Could the Bubble Card be vertically centered in each cell (with styling ?) ?

![image](https://github.com/Clooos/Bubble-Card/assets/4083901/0db20c6d-4cb5-422b-a91b-90a977cf39c1)

Thank you for your great work !

**Expected behavior**  
The divider should be closer to the sub-buttons

**YAML**  
If applicable, add any relevant YAML code.

```yaml
  - type: sections
    max_columns: 2
    sections:
      - type: grid
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Test 1
            sub_button:
              - icon: mdi:numeric-1
            styles: |2-
                .bubble-line {
                  background: red ;
                  opacity: 1;
                }
                .bubble-sub-button-1 {
                  background-color: grey !important;
                }
                .bubble-sub-button-2 {
                  background-color: grey !important;
                }
                .bubble-sub-button-3 {
                  background-color: grey !important;
                }
          - type: custom:bubble-card
            card_type: separator
            name: Test 2
            sub_button:
              - icon: mdi:numeric-1
              - icon: mdi:numeric-2
            styles: |2-
                .bubble-line {
                  background: red ;
                  opacity: 1;
                }
                .bubble-sub-button-1 {
                  background-color: grey !important;
                }
                .bubble-sub-button-2 {
                  background-color: grey !important;
                }
                .bubble-sub-button-3 {
                  background-color: grey !important;
                }
          - type: custom:bubble-card
            card_type: separator
            name: Test 3
            sub_button:
              - icon: mdi:numeric-1
              - icon: mdi:numeric-2
              - icon: mdi:numeric-3
            styles: |2-
                .bubble-line {
                  background: red ;
                  opacity: 1;
                }
                .bubble-sub-button-1 {
                  background-color: grey !important;
                }
                .bubble-sub-button-2 {
                  background-color: grey !important;
                }
                .bubble-sub-button-3 {
                  background-color: grey !important;
                }
```

**Informations (please complete the following information):**  
 - Browser/App: Firefox
 - Bubble Card version: 2.0.4
 - Home Assistant version: 2024.6.4

**Comment by arthanoss** [comment]
As for the second question, the section layout in HA defines a fixed row height for cards inside it to keep everything even in a grid.

There's a section optimized layout available for separators (and buttons too) in Bubble Card and it does exactly what you want, it vertically aligns the separator in the middle of a row.

```yaml
type: custom:bubble-card
card_type: separator
name: Separator
card_layout: large
```

![Layouts](https://github.com/Clooos/Bubble-Card/assets/72643066/e3394769-0016-4cc8-8ec9-8e9f72d40e98)
