### ISSUE TITLE
Haptic feedback events firing multiple times or not at all

### ISSUE THREAD

**Issue by arthanoss** [Clooos/Bubble-Card#616]
Tapping on buttons or sub buttons makes haptic events fire multiple times. The `forwardHaptic` function gets called two or three times depending on the button type (on icons it seems fine). It's really noticeable on my Android device through the companion app, can feel each vibration separately. For some reason it feels fine when HA is opened through Chrome (single vibration on tap), but the issue is still there.

Another issue is when there's no haptic feedback at all. Seems kinda random, but there's one example scenario where it's pretty consistent:

```
- type: custom:bubble-card
  card_type: button
  button_type: name
  name: Open popup
  button_action:
    tap_action:
      action: navigate
      navigation_path: '#testpopup'
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#testpopup'
      button_type: name
      name: Test
```

1. Tap on a button - vibration.
2. Close popup with the X button.
3. Tap on a button again - no vibration.

If between steps 2 and 3 I tap somewhere else, then it works.

Also, when clicked on a desktop in the same scenario (or even through DevTools connected to the same Android device), the aformentioned `forwardHaptic` function gets called every time. It's only with touch events directly on the phone it sometimes doesn't. Dunno, I haven't dug deeper into this. Hope that helps somehow 😅 

Tested on the latest versions of HA and Bubble Card.

As a side note. There's an option in the Android companion app settings that allows to disable vibrations. Bubble Card seems to ignore that setting. Not sure if it's even possible to use that, but maybe even better would be a YAML option to disable vibrations per action.

Thanks for your great work. Love these cards! ❤️
