### ISSUE TITLE
View behind pop-up becomes scrollable under certain conditions

### ISSUE THREAD

**Issue by fcassata** [Clooos/Bubble-Card#617]
See attached video, first pop-up all is as expected, then I navigate directly to another pop-up,  and now the view  behind the pop-up becomes scrollable. I also tested removing everything from the pop-up, with the same results, just in case some of the custom CSS there was messing something up. So the conditions are: 2nd pop-up to open in a row without closing pop-ups in between.

If the pop-up contains enough content to become scrollable itself, this does not happen.

https://github.com/Clooos/Bubble-Card/assets/97367937/67cb86e6-9a78-48a6-a12d-c5dfd482c8e2

My stripped YAML:

```YAML
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#lists'
    bg_opacity: '0'
    bg_blur: '0'
    icon: none
    close_by_clicking_outside: false
```
