### ISSUE TITLE
Vertical stack hopping when opening and closing a pop-up in Desktop mode

### ISSUE THREAD

**Issue by Nazze** [Clooos/Bubble-Card#626]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
In Desktop mode, when opening and closing a pop-up, the whole vertical stack is moving to the left. 

**To Reproduce**  
1. Create an empty dashboard
2. Create vertical stack
3. Create a button in the vertical stack
4. Set navigate to "#bla_popup" for this button 
5. Create a new vertical stack
6. Create a bubble pop in that vertical stack
7. Set the name of the pop up "Test"
8. Save and refresh
9. Press the button
10. Close the button
11. See that the button moves from middle to left to the middle

**Expected behavior**  
The vertical stack should not move.

**Screenshots**  

https://github.com/Clooos/Bubble-Card/assets/33813707/d50338be-0ee7-497c-b281-2438617670fa

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Sample code here:
`views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#bla_popup'
            entity: light.lichter_buero
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#bla_popup'
            name: Test
`
```

**Informations (please complete the following information):**  
 - OS: MacOS 13.6.7.
 - Browser/App: Firefox 127.0.2 (64 Bit)
 - Bubble Card version: v2.1.0-beta.1
 - Home Assistant version: 2024.6.4

**Additional context**  

Thank you! 🍻
Thank you, Clooos!
