### ISSUE TITLE
seperator not showing

### ISSUE THREAD

**Issue by Tehral** [Clooos/Bubble-Card#635]
**Describe the bug**  
I added a seperator btu it doesn't show it at all

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#popLivingroom'
    name: Livingroom
    icon: mdi:sofa
    button_type: state
  - type: grid
    columns: 1
    square: false
    cards:
      - type: custom:bubble-card
        card_type: seperator
        name: Lights
        icon: mdi:coach-lamp
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.livingroom
            show_brightness_control: true
            show_color_control: true
          - type: custom:mushroom-light-card
            entity: light.kitchen
            show_brightness_control: true
            show_color_control: true
      - type: horizontal-stack
        cards:
          - type: custom:bubble-card
            card_type: cover
            entity: cover.velux_external_cover_roller_shutter
            name: Livingroom
            icon_open: mdi:window-shutter-open
            icon_close: mdi:window-shutter
            show_icon: true
            force_icon: false
            show_name: true
            show_state: true
            show_last_changed: false
            show_attribute: true
            attribute: current_position
            card_layout: large
            icon_down: mdi:arrow-down-bold
            icon_up: mdi:arrow-up-bold
            sub_button: []
      - type: custom:bubble-card
        card_type: cover
        entity: cover.shutterbalcony
        name: Balcony
        icon_open: mdi:window-shutter-open
        icon_close: mdi:window-shutter
        show_icon: true
        force_icon: false
        show_name: true
        show_state: true
        show_last_changed: false
        show_attribute: true
        attribute: current_position
        card_layout: large
        icon_down: mdi:arrow-down-bold
        icon_up: mdi:arrow-up-bold
        sub_button: []
      - type: horizontal-stack
        cards:
          - type: custom:bubble-card
            card_type: cover
            entity: cover.velux_window_roof_window
            name: Livingroom WIndow
            icon_open: mdi:window-open-variant
            icon_close: mdi:window-closed-variant
            show_icon: true
            force_icon: false
            show_name: true
            show_state: true
            show_last_changed: false
            show_attribute: true
            attribute: current_position
            card_layout: large
            icon_down: mdi:arrow-down-bold
            icon_up: mdi:arrow-up-bold
            sub_button: []

```
tinkered a bit but couldn't fix it.

anyone has a solution?

Thank you! 🍻
