### ISSUE TITLE
2.1.0-beta.2 pop-up open/close action not working with horizontal button stack

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#636]
**Describe the bug**  

When using the horizontal button stack and tapping a button to close an already open pop-up and open another one, the close action doesn't fire. In my case I have a service call in the close action:

```
close_action:
  action: call-service
  service: input_boolean.turn_off
  target:
    entity_id: input_boolean.paul_s_alarm_show_controls
```

I think it might be inconsistent in that I *thought* I saw it work ok once but in further testing it doesn't work. 

The close action does fire and work ok when closing the popup via other means - swiping down or using the close button. 

This might possibly be down to the complexity of my dashboards and I'm planning on setting up a simple test dashboard to try it out with nothing else getting in the way. I thought I'd raise this sooner rather than later though. 

I've been testing this by using the developer tools and triggering the pop-up Boolean and watching it as I use the horizontal button stack buttons to open/close other pop-ups. 

 - OS: windows 11
 - Browser/App: Safari
 - Bubble Card version: 2.1.0-beta.2
 - Home Assistant version: 2024.7.1
