### ISSUE TITLE
Pup-up header failed to hide the icon

### ISSUE THREAD

**Issue by DHT-Xavier** [Clooos/Bubble-Card#638]
![Capture](https://github.com/Clooos/Bubble-Card/assets/10126213/368ee3ad-b544-4a82-87ad-013ec2ef67df)

```
views:
  - title: Testing
    type: sections
    max_columns: 4
    sections:
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: '#testing'
                button_type: name
                name: Header Name
                show_icon: false
                show_name: true
              - type: custom:bubble-card
                card_type: button
                entity: switch.living_room_ac_nanoe
                show_icon: false
```

The Button card work as expected. However, I could not be abled to hide the header icon / name in the Pop-up card

- OS: Windows 10 / OSX Sonoma 14.4.1
- Browser: Chrome, 126.0.6478.127
- Core: 2024.6.4
- Supervisor: 2024.06.2
- Operating System: 12.4
- Frontend: 20240610.1
- HACS: 1.34.0
- HACS Frontend version: 20220906112053
- Bubble Card: v2.0.4
