### ISSUE TITLE
Can bubble popup be used with decluttering card ?

### ISSUE THREAD

**Issue by realroywalker** [Clooos/Bubble-Card#65]
Firstly great work on the bubble card, love how it looks and the functionality is just great.
I wonder if someone knows if it's possible to make use of the bubble popup card along with decluttering card in HA ? - Currently I have buttons on my dashboard which when I hold gives me a custom 'more-info' style popup window, this is automatically generated using decluttering-card as the entity that was pressed is passed as a variable (like so;)

```
hold_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      deviceID: this
      content:
        type: custom:decluttering-card
        template: history-timeline-popup
        variables:  
          - history-entity: '[[light-entity]]'  
```
I'd really like to switch from using browser_mod.popup to using the bubble popup instead, but I can't figure out if it's possible to have the bubble popup card as a decluttering template and then somehow pass the variable to it.
Obviously what I'm trying to avoid here is having to manually create tons of popups for each entity or room.
