### ISSUE TITLE
Cover cards do not display when name is undefined

### ISSUE THREAD

**Issue by Boo1098** [Clooos/Bubble-Card#67]
When creating a cover card, nothing is displayed unless a name is defined. The documentation says this field is optional, and the expected behavior would be the name is pulled from the cover entity similar to the button cards.
Example:
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Curtains
    icon: mdi:curtains
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: cover
        entity: cover.living_room_curtain_cover
        button_type: slider
      - type: custom:bubble-card
        card_type: cover
        entity: cover.dining_room_curtain_cover
        button_type: slider
  - type: custom:bubble-card
    card_type: cover
    entity: cover.bedroom_curtains_cover
```

Displayed on dashboard:
![image](https://github.com/Clooos/Bubble-Card/assets/7719705/3bcca0bd-b8e5-4b29-b019-af3173f70a70)

After names are defined for covers:

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Curtains
    icon: mdi:curtains
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: cover
        entity: cover.living_room_curtain_cover
        button_type: slider
        name: test 1
      - type: custom:bubble-card
        card_type: cover
        entity: cover.dining_room_curtain_cover
        button_type: slider
        name: test 2
  - type: custom:bubble-card
    card_type: cover
    entity: cover.bedroom_curtains_cover
    name: test 3
```
![image](https://github.com/Clooos/Bubble-Card/assets/7719705/a4cddfbd-9c6d-4c40-9f3c-d4f22cc2d592)
