### ISSUE TITLE
Conditional styles not working

### ISSUE THREAD

**Issue by regnighc** [Clooos/Bubble-Card#673]
I cant seem to figure out why my css isnt working

```
.bubble-icon-container {
    opacity: 1 !important;
    background-color: ${(['device_tracker.module_one'].state === "Home") ? "#548ce8" : (state === "Away") ? "red" : "gray"}
  }
```

The state of this entity is 'Home' yet the icon gets coloured gray. I've tried it with more than 20 entities and it does not work for any of them. Binary Sensors do work however.

**Comment by Clooos** [comment]
Hi, you need to compare the condition to the raw state, so this should works:

```yaml
.bubble-icon-container {
    opacity: 1 !important;
    background-color: ${(['device_tracker.module_one'].state === "home") ? "#548ce8" : (state === "not_home") ? "red" : "gray"}
  }
```
