### ISSUE TITLE
Nested pop-ups not working - only blur

### ISSUE THREAD

**Issue by thehedgefrog** [Clooos/Bubble-Card#675]
**Describe the bug**  
Nested pop-ups do not display - the screen goes blurry and stops there.  The behaviour persists with Chromium/Firefox and on mobile.

**YAML**  

I can provide further examples if needed.

```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: light.corridor_hue
icon: mdi:light-recessed
show_last_changed: true
show_state: true
show_attribute: false
hold_action:
  action: navigate
  navigation_path: '#m-corridor-details'
```

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#m-corridor-details'
    name: Corridor
    button_type: slider
    entity: light.corridor_hue
    icon: mdi:light-recessed
    show_state: true
    show_last_changed: true
    show_attribute: false
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.corridor_door
    name: Door Light
    icon: mdi:light-recessed
    show_state: true
    show_last_changed: true
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.corridor_back
    name: Corridor Light
    icon: mdi:light-recessed
    show_state: true
    show_last_changed: true
  - type: custom:bubble-card
    card_type: button
    entity: switch.adaptive_lighting_main_floor
    show_state: true
    show_last_changed: true
```

**Informations (please complete the following information):**  
 - OS: HA on HAOS 12.4.  Tried on Android 14, Windows 10, Windows 11.
 - Browser/App: Vivaldi, Edge, Firefox
 - Bubble Card version: 2.1.1
 - Home Assistant version: 2024.7.3
