### ISSUE TITLE
Make gradient opacity on top of pop-up card optional

### ISSUE THREAD

**Issue by scalt** [Clooos/Bubble-Card#68]
The gradient on top of the pop-up card is nice on a white background, but disturbing with darker colors. Can you make it optional or make it configurable colors? Thanks.

**Comment by Clooos** [comment]
Hi, I'm not in front of my computer right now but for your second question you can just do that:
```yaml
styles: | 
  #root { 
    background: blue !important;
  }
```

Just change blue with any RGB or HEX color.

You can also remove that gradient with `styles` and I'll come back when I have the right code for this.
