### ISSUE TITLE
Margins broken after 2024.8 update

### ISSUE THREAD

**Issue by danewhitfield** [Clooos/Bubble-Card#688]
**Describe the bug**  
Margins broken after 2024.8 update

**To Reproduce**  
1. Go to any view that is using the bubble-card
2. See error

**Expected behavior**  
Previously the margins worked fine, expected space between cards within a section.

**Screenshots**  
<img width="1449" alt="Screenshot 2024-08-07 at 23 02 07" src="https://github.com/user-attachments/assets/92e53570-d669-4682-8e62-3d29c8fa71d2">

**YAML**  
```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: light.dining_area
name: TV Area
force_icon: false
show_icon: true
show_name: true
show_state: false
show_last_changed: false
show_attribute: false
scrolling_effect: true
card_layout: large
sub_button:
  - entity: switch.living_room_plug
    icon: mdi:power-socket-uk
    tap_action:
      action: toggle
    double_tap_action:
      action: more-info
```

**Informations (please complete the following information):**  
 - OS: All devices
 - Browser/App: All browsers
 - Bubble Card version: 2.1.1
 - Home Assistant version: 2024.8.0

Thank you! 🍻
