### ISSUE TITLE
The Horizontal buttons stack does not display "Highlight current hash / view" when it is first loaded.

### ISSUE THREAD

**Issue by zyi840449** [Clooos/Bubble-Card#690]
I used multiple Horizontal buttons stacks and set display conditions for each to achieve the effect of switching menus.

I found that except for the one shown at the beginning,
The Horizontal buttons stack does not display "Highlight current hash / view" when it is first loaded.

![mybug2](https://github.com/user-attachments/assets/8844f678-f3cb-405a-8834-3f1d5b5e1796)

```yaml
Horizontal buttons stacks 1:

type: custom:bubble-card
card_type: horizontal-buttons-stack
rise_animation: true
highlight_current_view: true
hide_gradient: false
1_link: '#study_roof'
1_name: 書房
1_icon: mdi:book-open-variant-outline
2_link: '#living_roof'
2_name: 客廳
2_icon: mdi:sofa-outline
3_link: '#bed_roof'
3_name: 臥室
3_icon: mdi:bunk-bed-outline
width_desktop: 340px
**visibility:
  - condition: state
    entity: input_number.bar_list
    state: '1.0'**

Horizontal buttons stacks 2:

type: custom:bubble-card
card_type: horizontal-buttons-stack
rise_animation: true
highlight_current_view: true
hide_gradient: false
1_link: '#sensor_study'
1_name: ''
1_icon: mdi:book-open-variant-outline
2_link: '#sensor_bed'
2_name: ''
2_icon: mdi:bunk-bed-outline
3_link: '#sensor_bath'
3_name: ''
3_icon: mdi:shower
4_link: '#sensor_living'
4_name: ''
4_icon: mdi:sofa-outline

width_desktop: 340px
**visibility:
  - condition: state
    entity: input_number.bar_list
    state: '2.0'**



button 1:

type: vertical-stack
view_layout:
  position: sidebar
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#sensor_study'
    button_type: name
    show_header: false
    margin_top_mobile: 64%
    bg_blur: '50'
    bg_opacity: '70'
    shadow_opacity: '40'
    **open_action:
      action: call-service
      service: input_number.set_value
      target:
        entity_id: input_number.bar_list
      data:
        value: 2
    close_action:
      action: call-service
      service: input_number.set_value
      target:
        entity_id: input_number.bar_list
      data:
        value: 1**
  - type: horizontal-stack
    cards:
      - graph: line
        type: sensor
        detail: 2
        entity: sensor.myremote_temperature
        hours_to_show: 24
      - graph: line
        type: sensor
        detail: 2
        entity: sensor.myremote_humidity
        hours_to_show: 24

button 2:
type: vertical-stack
view_layout:
  position: sidebar
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#sensor_bed'
    button_type: name
    show_header: false
    margin_top_mobile: 64%
    bg_blur: '50'
    bg_opacity: '70'
    shadow_opacity: '40'
    **open_action:
      action: call-service
      service: input_number.set_value
      target:
        entity_id: input_number.bar_list
      data:
        value: 2
    close_action:
      action: call-service
      service: input_number.set_value
      target:
        entity_id: input_number.bar_list
      data:
        value: 1**
  - type: horizontal-stack
    cards:
      - graph: line
        type: sensor
        detail: 2
        entity: sensor.myremote4_temperature
        hours_to_show: 24
      - graph: line
        type: sensor
        detail: 2
        entity: sensor.myremote4_humidity
        hours_to_show: 24
```
Thank you! 🍻
