### ISSUE TITLE
Sub-buttons don't work when double tap action set to no action

### ISSUE THREAD

**Issue by koleos6** [Clooos/Bubble-Card#691]
**Describe the bug**  
Sub button don’t work anymore snif in some case: 
buttons are no more detected as “button” mousse icon don’t change when it goes on the sub-buttons.

**To Reproduce**  
 I found what parameter is causing the issue: it is when I put “no action” in the “Doubble Tap action” on “Top action on icon”

**Expected behavior**  
Action linked to sub_button 

**YAML**  

```yaml
type: custom:bubble-card
card_type: button
entity: light.cellier_lumiere
tap_action:
  action: none
double_tap_action:
  action: none
name: 'Cellier '
show_last_changed: true
show_state: true
sub_button:
  - entity: light.cellier_lumiere
    icon: ''
    tap_action:
      action: toggle
    double_tap_action:
      action: more-info
  - entity: binary_sensor.cellier_fenetre
styles: >
  .bubble-button-card-container {
    border-radius: 10px !important;
    background: rgba(70, 240, 70, 0.4);
  }
  .bubble-icon {
    opacity: 1;
    color: white !important;
  }
  .bubble-sub-button-2 {
    background-color: ${hass.states['sensor.mosquitto_broker_openstate_11'].state === 'OPEN_FRENCH' ? 'red' : hass.states['sensor.mosquitto_broker_openstate_11'].state === 'OPEN_HOPPER' ? 'rgba(87, 160, 238, 1)' : 'green'} !important;
  }


  ${subButtonIcon[1].setAttribute("icon",
  hass.states['sensor.mosquitto_broker_openstate_11'].state === 'OPEN_FRENCH' ?
  'kuf:fts_window_2w_open' :
  hass.states['sensor.mosquitto_broker_openstate_11'].state === 'OPEN_HOPPER' ?
  'kuf:fts_window_2w_tilt' :'kuf:fts_window_2w')}
icon: hue:room-closet
button_type: state
hold_action:
  action: none
button_action:
  tap_action:
    action: none
  double_tap_action:
    action: none
  hold_action:
    action: none
```

**Informations (please complete the following information):**  
 - OS: all
 - Browser/App: brave
 - Bubble Card version: since all 2.1.x
 - Home Assistant version: 2024.7.4
