### ISSUE TITLE
v2.2.0-beta.1 Pop-up background blur sometimes persists after closing popup

### ISSUE THREAD

**Issue by CZonin** [Clooos/Bubble-Card#693]
**Describe the bug**  
After opening and then closing a pop-up, the background blur will sometimes persist and can only be fixed by refreshing the tab/restarting app.

**Expected behavior**  
Background blur will always be dismissed when pop-up is dismissed.

**Screenshots**  
![Screenshot_20240809-114040](https://github.com/user-attachments/assets/4bf3e2ef-277b-439b-92fd-6b6ad321edc4)

**YAML**  
Here's YAML from one of my pop-ups if it helps:

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#living-room'
    sub_button:
      - entity: sensor.living_room_thermostat_temperature
        show_background: false
        show_state: true
      - entity: sensor.living_room_thermostat_humidity
        show_background: false
        show_state: true
    card_layout: normal
    show_header: true
    name: Living Room
    show_icon: false
    scrolling_effect: false
    show_name: false
    styles: |2-
        .bubble-button-card-container {
          background: none !important;
        }
    icon: ''
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none
    button_action:
      tap_action:
        action: none
      double_tap_action:
        action: none
      hold_action:
        action: none
    margin_top_mobile: calc(100vh - 325px)
    margin_top_desktop: calc(100vh - 325px)
    shadow_opacity: '0'
    bg_blur: '14'
    bg_opacity: '100'
    hide_backdrop: false
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.living_room_light
    name: Light
    card_layout: large
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: custom:bubble-card
    card_type: separator
  - type: custom:bubble-card
    card_type: media-player
    entity: media_player.living_room_shield
    name: Shield
    icon: mdi:television
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
    button_action:
      double_tap_action:
        action: none
      hold_action:
        action: more-info
    show_state: true
    card_layout: large

```

**Informations (please complete the following information):**  
 - OS: Windows 11/Android
 - Browser/App: Chrome/Official App
 - Bubble Card version: v2.2.0-beta.1
 - Home Assistant version: 2024.7.4
