### ISSUE TITLE
Feature Request: Add Scroll Bar

### ISSUE THREAD

**Issue by taikun114** [Clooos/Bubble-Card#705]
I am severely disabled and it is very difficult for me to scroll on any device other than my main computer.
For this reason, I have set my computer to display scroll bars when operating other computers, but pop-up cards do not display scroll bars and cannot be scrolled. This is both for Mac and Windows PC.

So, is it possible to add a scroll bar that can be shown or hidden depending on the computer settings, or a scroll bar that only appears when the mouse cursor is close to it (like on the streaming platform Twitch)?

Here is the current pop-up card screen.
![スクリーンショット 2024-08-13 15 12 24](https://github.com/user-attachments/assets/bc2002a5-4b31-4c1b-bc1c-e7a20cee74f4)

I hope the scroll bar will appear as follows (this is an image created with image editing software).
![スクリーンショット 2024-08-13 15 12 24 2](https://github.com/user-attachments/assets/7cd92c20-6f8f-4b07-a0a1-7cc65ddc5b3f)

It would be very helpful if you could add this kind of functionality!
Thank you.

**Comment by Clooos** [comment]
Hi, you can re-add the scroll bars in your pop-ups by adding this custom style in all of them:

```css
.bubble-pop-up-container {
  -ms-overflow-style: auto !important; /* pour Internet Explorer, Edge */
  scrollbar-width: auto !important; /* pour Firefox */
}
.bubble-pop-up-container::-webkit-scrollbar {
  display: block !important; /* pour Chrome, Safari, et Opera */
  width: 8px;
}
.bubble-pop-up-container::-webkit-scrollbar-thumb {
  background: rgba(0,0,0,0.2);
  border-radius: 10px;
}
```

I really hope this helps!
