### ISSUE TITLE
[Tips] Left-handed close button

### ISSUE THREAD

**Issue by Write** [Clooos/Bubble-Card#720]
To set the close button of a popup on the left-side if you're left-handed (like-me) you can use this snippet : 

```yaml
    styles: |-
      .bubble-header {
        display: none !important;
      }
```

Example 

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#remote-tv'
    margin_top_mobile: calc(100vh - 70vh)
    margin_top_desktop: calc(100vh - 70vh)
    show_header: true
    styles: |-
      .bubble-header {
        display: none !important;
      }
```

Result

![shot on 2024-August-19@00h48(11)](https://github.com/user-attachments/assets/2c365267-7979-4752-8b2f-400f35bda186)
