### ISSUE TITLE
Change Separator Line Color

### ISSUE THREAD

**Issue by Lord0fBytes** [Clooos/Bubble-Card#73]
Is there a way to change/style the separator line color? It is very difficult to see with the standard dark mode background. 
I tried a bunch of the `ha card-mod` styles but I could not locate which one changes the actual line color. 
<img width="512" alt="Screenshot 2023-09-27 at 12 01 43 PM" src="https://github.com/Clooos/Bubble-Card/assets/7501413/e188a197-eaa5-479c-9b8d-bb9fa8e811c6">

**Comment by Lord0fBytes** [comment]
Actually I think I figured it out. Not sure it's correct, but it works for me. I had to adjust the `.separator-container div:last-child` CSS code. 
```yaml
type: custom:bubble-card
card_type: separator
name: Office
icon: mdi:desktop-classic
styles: |
  ha-card { 
    color: mediumseagreen;
    
  }
  .separator-container div:last-child {
    background-color: mediumseagreen !important
  }

```
<img width="499" alt="Screenshot 2023-09-27 at 3 52 37 PM" src="https://github.com/Clooos/Bubble-Card/assets/7501413/58e36a63-c228-4194-8fd1-e5e7ce0f79f9">
