### ISSUE TITLE
v2.2.3 - Pop-ups, different background opacity behaviour in different browsers.

### ISSUE THREAD

**Issue by fcassata** [Clooos/Bubble-Card#735]
HA 2024.8.1

Empty Masonry view, only pop-up, and button to open, see config:

```YAML
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    bg_opacity: 0
    bg_blur: 90
    hash: '#pop-up'
    name: Test
    button_type: name
    icon: mdi:ab-testing
```
Background in Chrome:
<img width="211" alt="Screenshot 2024-08-22 at 15 17 01" src="https://github.com/user-attachments/assets/7f291610-dbba-40ad-b5db-61ea4e56ac68">

Background in Firefox:
<img width="211" alt="Screenshot 2024-08-22 at 15 17 01" src="https://github.com/user-attachments/assets/feda4b94-e0bc-45dc-b34a-5548b52c6bf3">

Background in Safari:
<img width="211" alt="Screenshot 2024-08-22 at 15 17 01" src="https://github.com/user-attachments/assets/be7600ac-1149-450c-accb-1264776c7ef1">
