### ISSUE TITLE
v.2.2.3 - Lights are different color than switches on conditional cards

### ISSUE THREAD

**Issue by gmalbert** [Clooos/Bubble-Card#736]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

I have a conditional card set up for all lights/switches that are on. The switches show bright orange when they're on, but the lights (light entity) show a lighter color. Style is not used on this card.

**To Reproduce**  
Create a conditional card that includes both switches and light entities with a condition set to an entity state of 'on'. The switch entities will be bright orange, but the light entities are a lighter shade.
**Expected behavior**  
I expect both the light entities and switch entities to be the same color when their state is set to on.
**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
- type: conditional
    conditions:
      - condition: state
        entity: switch.top_of_stairs
        state: 'on'
    card:
      type: custom:bubble-card
      card_type: button
      entity: switch.top_of_stairs
      show_last_changed: true
      tap_action:
        action: toggle
      hold_action:
        action: more-info
  - type: conditional
    conditions:
      - condition: state
        entity: light.kitchen_sink
        state: 'on'
    card:
      type: custom:bubble-card
      card_type: button
      entity: light.kitchen_sink
      show_last_changed: true
      tap_action:
        action: toggle
      hold_action:
        action: more-info
```
![Capture](https://github.com/user-attachments/assets/dceee83b-1eba-429a-be6a-fdee63c5e3f8)

In this screenshot, Kitchen, Office, and Side Entrance Light are switch entities. The remainder are light entities.

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻
