### ISSUE TITLE
Media player button loses rounded corners when adding a fourth rgba value

### ISSUE THREAD

**Issue by gmalbert** [Clooos/Bubble-Card#747]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
When the background-color in .bubble-media-player includes a fourth RBGA value, the color changes, but it loses the rounded corners.
**To Reproduce**  
The initial media player boxes are gray. In order to change the color, I'm using the .bubble-media-player style option. When I change the last value in the rgba values, the color of the button changes, but then the corners are gone.

The screenshots show the rounded corners when a 0 is in the last rgba value (but the color has not changed on the button). When you pick any other value (1, for instance), the color changes but then the rounded corners are gone.
**Expected behavior**  
I expect the corners to remain when I add the last rbga value. 
**Screenshots**  
[
![Capture](https://github.com/user-attachments/assets/925a2139-f966-41b1-9f14-61b1a3e2b054)
![Capture2](https://github.com/user-attachments/assets/575cf054-51d5-45ba-b42d-87bdacbf2485)
](url)
**YAML**  
If applicable, add any relevant YAML code.

```yaml
- type: custom:bubble-card
    card_type: media-player
    entity: media_player.basement_ha_tablet
    show_state: false
    name: Basement Tablet
    styles: |-
      .bubble-media-player { 
         background-color: rgb(91, 133, 166);
         display: flex;
         transition: background-color 1.5s;
         }
      .bubble-play-pause-button { 
         background-color: rgb(91, 133, 166) 
         }
      .bubble-media-player-container {
         border-radius: 25px;
      }
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]
v. 2.2.3; Firefox
**Additional context**  

Thank you! 🍻
