### ISSUE TITLE
Cover: Attibute "0" not displayed

### ISSUE THREAD

**Issue by zimbo86** [Clooos/Bubble-Card#750]
**Describe the bug**  
I want to use type: cover and display attribute "current_position". 
Current position is between 0 (closed) and 100 (opened).
When attribute = 0 the attribute is not updated and it displays the last state of the posistion instead 0.

**To Reproduce**  

See Sample card in yaml mode

**Expected behavior**  
Display 0 or "closed"

**Screenshots**  

![image](https://github.com/user-attachments/assets/a10bab1f-84b1-4b7a-adc5-d7b24c83ba74)
![image](https://github.com/user-attachments/assets/7d84c87e-e41b-4920-b910-de67f852567a)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
            - type: custom:bubble-card
              card_type: cover
              entity: cover.shutter_livingroom
              name: Rolladen (Lichtband)
              show_attribute: true
              attribute: current_position
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. edge latest]
 - Bubble Card version: [e.g. 2.2]
 - Home Assistant version: [e.g. 2024.6.4]

**### Can someone stop those Bots?
Please dont click these links with zip downloads...**
