### ISSUE TITLE
Pop-up / Vertical stack not appearing

### ISSUE THREAD

**Issue by frasderp** [Clooos/Bubble-Card#752]
First time playing with Bubble-cards, and can't seem to get the pop-up cards to actually appear. I made a vertical stack and added a basic pop-up card. Any ideas? I am sure it's something basic I've missed...

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#bedroom'
    button_type: state
    entity: light.fraser_bedside_lamp
    name: Bedroom
    icon: mdi:bed-king-outline
    show_attribute: true
    sub_button:
      - entity: climate.sonoff_radiator_bedroom_thermostat
        show_state: false
        show_attribute: true
        attribute: current_temperature
    show_header: true
title: Bedroom
```
