### ISSUE TITLE
Occasional issue for buttons with scene entity

### ISSUE THREAD

**Issue by andreasbrett** [Clooos/Bubble-Card#763]
**Describe the bug**  
I have BubbleCard buttons for toggling scenes. Since one of the last releases (which vastly improved performance I must say) I occasionally get errors that properties of the scene entities can not be read because the scene is undefined.

**Browser Console Log**  
```
bubble-card.js?hacstag=680112919224:1 Uncaught TypeError: Cannot read properties of undefined (reading 'scene.wohnzimmer_teal_pink')
    at getState (bubble-card.js?hacstag=680112919224:1:8333)
    at bubble-card.js?hacstag=680112919224:1:46811
    at D (bubble-card.js?hacstag=680112919224:1:47594)
    at J.updateBubbleCard (bubble-card.js?hacstag=680112919224:1:82649)
    at J.connectedCallback (bubble-card.js?hacstag=680112919224:1:81961)
    at t.connectedCallback (scoped-custom-element-registry.js:248:42)
    at i.value (hui-card.ts:249:12)
    at i.value (hui-card.ts:234:10)
    at i.value (hui-card.ts:59:10)
    at t.connectedCallback (scoped-custom-element-registry.js:248:42)
```

**YAML**  
```yaml
      type: custom:bubble-card
      card_type: button
      button_type: switch
      entity: scene.wohnzimmer_teal_pink
      name: Teal & Pink
      icon: mdi:fire
      tap_action:
        action: call-service
        service: scene.turn_on
        target:
          entity_id: scene.wohnzimmer_teal_pink
      double_tap_action:
        action: none
      hold_action:
        action: none
      button_action:
        tap_action:
          action: call-service
          service: scene.turn_on
          target:
            entity_id: scene.wohnzimmer_teal_pink
        double_tap_action:
          action: none
        hold_action:
          action: none
```

**Informations (please complete the following information):**  
 - OS: OS-independent
 - Browser/App: HA Mobile App, Chrome
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.8.3 (but also on 2024.9.0b2)

Thank you! 🍻
