### ISSUE TITLE
subButtonIcon setAttribute with attributes other than icon?

### ISSUE THREAD

**Issue by thargy** [Clooos/Bubble-Card#767]
Hi,

Are there any other attributes than `icon` on sub-buttons that can be changed from the style?

For example, I've tried, but neither of these work:
```css
${subButtonIcon[2].setAttribute("name", "test")}
${subButtonIcon[2].setAttribute("background-color", "blue")}
```

I'd like to change the text following the icon and the background color based on the hass state, but I'm not sure how to proceed.

**Comment by thargy** [comment]
I've also tried:

```css
  ${subButtonIcon[2].css("background-color", hass.states['sensor.blinds_open_count'].attributes.icon_color)}
```

But I'm getting a lit error and have been unable to find a way past it despite researching lit:

```
Uncaught (in promise) Error: Error in generating separator custom templates: Value passed to 'css' function must be a 'css' function result: cyan. Use 'unsafeCSS' to pass non-literal values, but take care to ensure page security.
    at bubble-card.js?hacstag=680112919224:1:85439
    at J.updateBubbleCard (bubble-card.js?hacstag=680112919224:1:85574)
    at set editMode (bubble-card.js?hacstag=680112919224:1:82088)
    at i.value (hui-card.ts:104:28)
    at i.value (hui-card.ts:40:10)
    at i.value (hui-section.ts:67:13)
    at hui-section.ts:276:12
    at Array.map (<anonymous>)
    at i.value (hui-section.ts:275:32)
    at i.value (hui-section.ts:192:10)
```

**Comment by thargy** [comment]
Ooops, this is definitely a RTFM situation!

I found the example code for changing the background-color, and now this is working for icon and background-color:
```css
styles: >-
  .bubble-sub-button-3 {
    background-color: ${hass.states['sensor.blinds_open_count'].attributes.icon_color}  !important;
  }

  ${subButtonIcon[2].setAttribute("icon", hass.states['sensor.blinds_open_count'].attributes.icon)}
```

So, just need to find a way to change the 'name' (text by the icon)
