### ISSUE TITLE
slider with climate expected float

### ISSUE THREAD

**Issue by oliiivier** [Clooos/Bubble-Card#768]
**Describe the bug**  
when I used a slider with my climate thermostat, i've got this error when I slide to change the temperature : 
Échec de l'appel du service climate/set_temperature. expected float for dictionary value @ data['temperature']

**YAML**  

my button : 
```yaml
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: climate.chauffage_chambre_5
    icon: mdi:heat-wave
    attribute: temperature
    show_state: true
    show_attribute: true
    force_icon: false
```

my climate :  
```yaml
 - platform: smart_thermostat
    name: Chauffage Chambre 5
    heater: switch.chauffage_chambre_5
    target_sensor: sensor.temperature_chambre_5_temperature
    min_temp: 15
    max_temp: 25
    ac_mode: False
    target_temp: 19
    keep_alive:
      seconds: 60
    away_temp: 14
    kp: 50
    ki: 0.01
    kd: 2000
    pwm: 00:15:00
```

**Informations (please complete the following information):**  
 - OS: Windows
 - Browser/App: Firefox
 - Bubble Card version: [e.g. 2.2.4]
 - Home Assistant version: [e.g. 2024.6.4]

Thank you! 🍻
