### ISSUE TITLE
Some pop-up menus cover the horizontal menu

### ISSUE THREAD

**Issue by MrSaiclops** [Clooos/Bubble-Card#78]
I've got the horizontal menu at the very end of the cards and it randomly pops up some of the menus in front of the buttons. Images for this can be found here: https://imgur.com/a/XHsWaCe
Here's my YAML:
```yaml
  - title: Sai's Dashboad
    icon: mdi:alpha-s-circle
    badges: []
    cards:
      - type: entity-filter
        show_empty: false
        entities:
          - light.nanoleaf_a19_6x1p_nanoleaf_bulb
          - light.nanoleaf_a19_8c9l_nanoleaf_bulb
          - light.nanoleaf_a19_3snk_nanoleaf_bulb
          - light.nanoleaf_a19_1j8x_nanoleaf_bulb
          - light.nanoleaf_a19_5wmr_nanoleaf_bulb
          - light.nanoleaf_a19_4gil_nanoleaf_bulb
          - light.nanoleaf_a19_5qmy_nanoleaf_bulb
          - light.nanoleaf_a19_ahm1_nanoleaf_bulb
          - light.nanoleaf_a19_6r1w_nanoleaf_bulb
          - light.nanoleaf_a19_0ah2_nanoleaf_bulb
          - light.nanoleaf_a19_17uc_nanoleaf_bulb
          - light.nanoleaf_a19_6ega_nanoleaf_bulb
          - light.nanoleaf_a19_5e3w_nanoleaf_bulb
          - light.nanoleaf_a19_1u57_nanoleaf_bulb
          - light.nanoleaf_a19_8bnu_nanoleaf_bulb
          - light.nanoleaf_a19_4lwj_nanoleaf_bulb
          - light.nanoleaf_a19_5pwk_nanoleaf_bulb
          - light.nanoleaf_a19_4yth_nanoleaf_bulb
          - light.nanoleaf_a19_8ojg_nanoleaf_bulb
          - light.nanoleaf_a19_5qx7_nanoleaf_bulb
          - light.nanoleaf_a19_24qj_nanoleaf_bulb
          - light.nanoleaf_a19_5j22_nanoleaf_bulb
          - light.nanoleaf_a19_1yn0_nanoleaf_bulb
          - light.nanoleaf_a19_aefq_nanoleaf_bulb
          - light.nanoleaf_a19_339p_nanoleaf_bulb
          - light.nanoleaf_a19_7rs5_nanoleaf_bulb
          - light.nanoleaf_a19_50db_nanoleaf_bulb
          - light.nanoleaf_a19_00rl_nanoleaf_bulb
          - light.wemo_dimmer_588
          - light.nanoleaf_strip_05vi_nanoleaf_light_strip
        state_filter:
          - unavailable
        card:
          type: glance
          title: Thread Lights Down
      - type: vertical-stack
        cards:
          - type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: sensor.closet_temperature
                name: Closet
                use_entity_picture: false
                icon: mdi:hanger
              - type: entity
                entity: sensor.bathroom_temperature
                name: Bathroom
                icon: mdi:paper-roll
              - type: entity
                entity: sensor.family_room_current_temperature
                name: Family Room
                icon: mdi:sofa
              - type: entity
                entity: input_select.car_plugged_in_v2
                use_entity_picture: false
                icon: phu:volkswagen
              - type: entity
                entity: input_boolean.carplay_rachel
                use_entity_picture: false
            alignment: center
          - type: custom:mushroom-climate-card
            entity: climate.family_room
            hvac_modes:
              - auto
              - heat
              - cool
            show_temperature_control: true
            layout: horizontal
            collapsible_controls: false
            tap_action:
              action: more-info
            hold_action:
              action: none
            double_tap_action:
              action: none
            name: Thermostat
            fill_container: false
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.sonoff_1001e02cd4_energy
            name: eGolf
          - entity: sensor.sonoff_1001e02cf7_energy
            name: Fridge
          - entity: sensor.sonoff_1001e02d0d_energy
            name: MiniFridge
          - entity: sensor.server
            name: Server
          - entity: sensor.printer
            name: Printer
          - entity: sensor.sonoff_1001e02c50_energy
            name: Rachel's Computer
      - type: entities
        entities:
          - entity: sensor.back_door_battery
            name: Back Door
          - entity: sensor.front_door_battery
            name: Front Door
          - entity: sensor.eve_motion_1032_battery
            name: Kitchen Motion Detector
          - entity: sensor.eve_motion_ac12_battery
            name: Laundry Motion Detector
        show_header_toggle: false
        state_color: true
      - type: custom:horizon-card
      - type: entities
        entities:
          - entity: switch.adguard_home_filtering
          - entity: input_boolean.downloads
          - entity: switch.adaptive_lighting_circadian_rhythm
      - type: map
        entities:
          - entity: person.sai
          - entity: person.rachel
        dark_mode: true
        aspect_ratio: '4:2.7'
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#living-room'
            name: Living Room
            icon: mdi:sofa
            entity: light.group_living_room
            is_sidebar_hidden: true
            styles: |
              #root { 
                opacity: 1 !important;
                background: linear-gradient(0deg, rgba(65,65,65,0) 0%, rgba(0,0,0,1) 81%); !important;
              }
            margin_top_desktop: 30%
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.shapes_ab5b
                name: Honeybee
                fill_container: false
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.shapes_f2bd
                name: Ladybug
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.nanoleaf_a19_1j8x_nanoleaf_bulb
          - type: custom:bubble-card
            card_type: separator
            name: TV Corner
            icon: mdi:television
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_00rl_nanoleaf_bulb
                name: Top
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_50db_nanoleaf_bulb
                name: Mid
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_7rs5_nanoleaf_bulb
                name: Bot
          - type: custom:bubble-card
            card_type: separator
            name: Frosted
            icon: phu:ceiling-buckram-two
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_6ega_nanoleaf_bulb
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_5e3w_nanoleaf_bulb
          - type: custom:bubble-card
            card_type: separator
            name: Couch Corner
            icon: mdi:sofa-single
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_6r1w_nanoleaf_bulb
                name: Top
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_ahm1_nanoleaf_bulb
                name: Mid
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_5qmy_nanoleaf_bulb
                name: Bot
          - type: custom:bubble-card
            card_type: empty-column
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#bedroom'
            name: Bedroom
            icon: mdi:bed
            state: sensor.closet_temperature
            entity: light.group_bedroom
            is_sidebar_hidden: true
            styles: |
              #root { 
                opacity: 1 !important;
                background: linear-gradient(0deg, rgba(65,65,65,0) 0%, rgba(0,0,0,1) 81%); !important;
              }
            margin_top_desktop: 30%
          - type: custom:bubble-card
            card_type: separator
            name: Lights
            icon: phu:bulb-group
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_1yn0_nanoleaf_bulb
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_5j22_nanoleaf_bulb
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.wemo_dimmer_588
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_17uc_nanoleaf_bulb
          - type: custom:bubble-card
            card_type: separator
            name: Misc.
            icon: mdi:more
          - type: custom:bubble-card
            card_type: button
            entity: switch.smart_switch_2111248089968751858448e1e97dffeb_outlet
          - type: custom:bubble-card
            card_type: button
            entity: switch.smart_switch_2111245621708751858448e1e97e2836_outlet
          - show_name: true
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: binary_sensor.closet_motion
              - entity: binary_sensor.closet_occupancy
            state_color: true
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#kitchen'
            name: Kitchen
            icon: mdi:fridge
            entity: light.group_kitchen
            is_sidebar_hidden: true
            styles: |
              #root { 
                opacity: 1 !important;
                background: linear-gradient(0deg, rgba(65,65,65,0) 0%, rgba(0,0,0,1) 81%); !important;
              }
            margin_top_desktop: 30%
          - type: custom:bubble-card
            card_type: separator
            name: Lights
            icon: phu:bulb-group
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_4lwj_nanoleaf_bulb
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_8bnu_nanoleaf_bulb
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_aefq_nanoleaf_bulb
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_339p_nanoleaf_bulb
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.sonoff_1001e02cf7_energy
                name: Fridge
          - show_name: true
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: binary_sensor.eve_motion_1032
                name: Kitchen Motion
            state_color: true
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#office'
            name: Office
            icon: mdi:desk
            entity: light.group_office
            is_sidebar_hidden: true
            styles: |
              #root { 
                opacity: 1 !important;
                background: linear-gradient(0deg, rgba(65,65,65,0) 0%, rgba(0,0,0,1) 81%); !important;
              }
            margin_top_desktop: 30%
          - type: custom:bubble-card
            card_type: separator
            name: Lights
            icon: phu:bulb-group
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                entity: light.nanoleaf_a19_8ojg_nanoleaf_bulb
                button_type: slider
              - type: custom:bubble-card
                card_type: button
                entity: light.smart_dimmer_switch_2009245203886555852148e1e9350ca1
                button_type: slider
          - type: custom:bubble-card
            card_type: separator
            name: Misc.
            icon: mdi:more
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                entity: input_boolean.downloads
              - type: custom:bubble-card
                card_type: button
                entity: switch.adguard_home_filtering
                name: AdGuard
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.sonoff_1001e02c50_energy
                name: Rachel's Computer
          - type: custom:bubble-card
            card_type: empty-column
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#bathroom'
            name: Bathroom
            icon: mdi:paper-roll
            state: sensor.bathroom_temperature
            entity: light.group_bathroom
            is_sidebar_hidden: true
            styles: |
              #root { 
                opacity: 1 !important;
                background: linear-gradient(0deg, rgba(65,65,65,0) 0%, rgba(0,0,0,1) 81%); !important;
              }
            margin_top_desktop: 30%
          - type: custom:bubble-card
            card_type: separator
            name: Lights
            icon: phu:bulb-group
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_6x1p_nanoleaf_bulb
                name: L
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_8c9l_nanoleaf_bulb
                name: M
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_3snk_nanoleaf_bulb
                name: R
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#family-room'
            name: Family Room
            icon: mdi:sofa-single
            state: sensor.family_room_current_temperature
            entity: light.group_family_room
            is_sidebar_hidden: true
            styles: |
              #root { 
                opacity: 1 !important;
                background: linear-gradient(0deg, rgba(65,65,65,0) 0%, rgba(0,0,0,1) 81%); !important;
              }
            margin_top_desktop: 30%
          - type: custom:bubble-card
            card_type: separator
            name: Lights
            icon: phu:bulb-group
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_4gil_nanoleaf_bulb
                name: Top
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_1u57_nanoleaf_bulb
                name: Hanging
          - type: horizontal-stack
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: slider
                entity: light.nanoleaf_a19_5wmr_nanoleaf_bulb
                name: Bot
              - type: custom:bubble-card
                card_type: empty-column
                button_type: slider
                entity: light.nanoleaf_a19_1u57_nanoleaf_bulb
          - show_name: true
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: binary_sensor.family_room_motion
              - entity: binary_sensor.family_room_occupancy
            state_color: true
      - type: custom:bubble-card
        card_type: horizontal-buttons-stack
        1_name: Living Room
        1_icon: mdi:sofa
        1_link: '#living-room'
        1_entity: light.nanoleaf_a19_6ega_nanoleaf_bulb
        2_name: Kitchen
        2_icon: mdi:fridge
        2_link: '#kitchen'
        2_entity: light.nanoleaf_a19_8bnu_nanoleaf_bulb
        3_name: Bedroom
        3_icon: mdi:bed
        3_link: '#bedroom'
        3_entity: light.nanoleaf_a19_17uc_nanoleaf_bulb
        4_name: Office
        4_icon: mdi:desk
        4_link: '#office'
        4_entity: light.nanoleaf_a19_8ojg_nanoleaf_bulb
        5_name: Bathroom
        5_icon: mdi:paper-roll
        5_link: '#bathroom'
        5_entity: light.nanoleaf_a19_3snk_nanoleaf_bulb
        6_name: Family Room
        6_link: '#family-room'
        6_icon: mdi:sofa-single
        6_entity: light.nanoleaf_a19_4gil_nanoleaf_bulb
        width_desktop: 900px
        is_sidebar_hidden: true
  - title: Rachel's Dashboad
    path: ladybug
    icon: mdi:alpha-r-circle
    theme: ios-light-mode-light-blue-alternative
    type: custom:masonry-layout
    layout:
      width: 300
      max_cols: 10
    badges: []
    cards:
      - type: custom:quote-of-the-day-card
        entity: sensor.quote_of_the_day
        feed_attribute: entries
      - initial_view: listWeek
        type: calendar
        entities:
          - calendar.rho
        title: Upcoming RHO
        card_mod:
          style:
            ha-full-calendar:
              $: |
                #calendar {
                  min-height: 200px !important;
                }
      - type: custom:weather-card
        entity: weather.family_room
        number_of_forecasts: '5'
        name: Weather
  - title: Media
    path: media
    icon: mdi:animation-play
    subview: false
    visible:
      - user: 163562fa945144389ed717139d422b94
      - user: 1a45d882672e47ff9324d6f16a42216a
    badges:
      - entity: sensor.the_academy_library_movies
      - entity: sensor.the_academy_library_tv_shows
    cards:
      - type: entities
        entities:
          - sensor.tautulli_top_movie
          - sensor.tautulli_top_tv_show
          - sensor.tautulli_watching
      - initial_view: listWeek
        type: calendar
        entities:
          - calendar.sonarr
        title: Sonarr
        ```
