### ISSUE TITLE
Pop up doesn't auto-close in non focused-window

### ISSUE THREAD

**Issue by tigers75** [Clooos/Bubble-Card#810]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
I have an autopop of a camera that pos automatically when someone rings, set with an auto-close timeout.
I have a PC with a chrome tab always open on a local HA server. When someone rings and the tab does not have focus the pop-up comes up, but never goes away, finally locking the tab: I have to force a refresh to make it go away.

**To Reproduce**  
1. Set a pop-up with auto-close
2. leave browser unattended navigating a separate Tab
3. trigger the pop-up
4. wait until timeout expires

**Expected behavior**  
The pop-up should auto close even if the window is not in focus.

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    trigger_entity: binary_sensor.citofonato
    trigger_state: 'on'
    hash: '#citofonato'
    show_header: false
    auto_close: '5000'
    close_on_click: true
    trigger_close: true
  - type: custom:mushroom-template-card
    primary: >-
      Ultime immagini di: {%- set time = (as_timestamp(now()) -
      as_timestamp(states('input_datetime.citofono_ultima_chiamata'))) | int  %}

      {%- set minutes = ((time % 3600) // 60) %}

      {%- set minutes = '{} minuti'.format(minutes) if minutes > 0 else '' %}

      {%- set hours = ((time % 86400) // 3600) %}

      {%- set hours = '{} ore '.format(hours) if hours > 0 else '' %}

      {%- set days = (time // 86400) %}

      {%- set days = '{} giorno(i) '.format(days) if days > 0 else '' %}

      {{ 'Meno di 1 minuto' if time < 60 else days + hours + minutes }} fa
    secondary: ''
    icon: mdi:bell-ring
    icon_color: orange

[...] other cards in the vertical stack [...]

```

**Informations (please complete the following information):**  
 - OS: Windows 10
 - Browser/App: Chrome
 - Bubble Card version: latest beta 2.3.0.beta-1
 - Home Assistant version: latest 2024.9.2

Thank you! 🍻
