### ISSUE TITLE
Pop-Up underneath the side menu

### ISSUE THREAD

**Issue by Perfect-Web** [Clooos/Bubble-Card#819]
reference to https://github.com/Clooos/Bubble-Card/issues/528#issuecomment-2368589921

![image](https://github.com/user-attachments/assets/1d8c8895-7867-477c-81c4-91dc1e5b48a2)

As you can see, using
```
kiosk_mode:
  non_admin_settings:
    hide_notifications: true
    hide_account: true
  hide_header: true
  hide_dialog_header_action_items: true
  hide_dialog_history_show_more: true
  hide_dialog_logbook_show_more: true
  hide_dialog_attributes: true
```

and

```
    card:
      type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: pop-up
          hide_backdrop: true
          trigger_entity: var.pop_up
          trigger_close: true
          bg_blur: 0
          bg_opacity: 100
.....
          width_desktop: 100%
```
throws the pop-up under the left menu
