### ISSUE TITLE
Number of rows when placed in a section view 

### ISSUE THREAD

**Issue by timota** [Clooos/Bubble-Card#820]
**Describe the bug**  
When changing number of rows when placed in a section view - card size not changed, only placeholder(marked on screenshot). Similar option for `columns` - does work without any issue. 

**Expected behavior**  
When number of rows changed - card size should be changed accordingly. 

**Screenshots**  
<img width="328" alt="Screenshot 2024-09-29 at 23 32 24" src="https://github.com/user-attachments/assets/f896ca94-4e04-4606-b01e-bc16b3829750">

**YAML**  
```yaml
type: custom:bubble-card
card_type: button
entity: light.f1_r2_dimmer_01
card_layout: large
show_state: true
show_last_changed: false
show_attribute: true
attribute: brightness
button_type: slider
sub_button: []
columns: 2
rows: 2
```

**Informations (please complete the following information):**  
 - OS: macOS
 - Browser/App: chrome, safari, firefox
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.9.3

Thank you! 🍻
