### ISSUE TITLE
[Pop-ups trigger] trigger_close does not work properly

### ISSUE THREAD

**Issue by adrienvsj** [Clooos/Bubble-Card#83]
Hello,

Thanks for your great work!

I've just tested the new feature in beta 9/10: trigger pop-ups.

Attached is a video of the bug I encountered:

https://github.com/Clooos/Bubble-Card/assets/12349073/66c938d0-1d5b-4931-922b-55be7d5cafb7

As you can see, the pop-up opens when my input_boolean is activated, but closes and reopens directly when I deactivate it.

I'm experiencing the problem on the latest version of the HomeAssistant Android app, as well as in my Chrome and Fully Kiosk Browsers.

I'm using version 2023.9.3 of HomeAssistant

Here's the code for my pop-up:

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#test'
    name: Test
    icon: mdi:test-tube
    trigger_entity: input_boolean.test
    trigger_state: 'on'
    trigger_close: true
  - type: entities
    entities:
      - entity: input_boolean.test
```

Thanks for your help
