### ISSUE TITLE
Popup is infinitely long at the bottom

### ISSUE THREAD

**Issue by 1rfsNet** [Clooos/Bubble-Card#846]
**Describe the bug**  
Each popup has no end, the popup always goes down to the bottom of the screen.

**To Reproduce**  
I have this issue with all my popups. I even created a new clean page in my dashboard and tried with the sample from the readme (https://github.com/Clooos/Bubble-Card/tree/main?tab=readme-ov-file#pop-up). Its not working. 

I tried to adjust the margin settings in the popup card but without success.

**Expected behavior**  
The popup should not be longer than the content.

**Screenshots**  
![Screenshot 2024-10-09 215712](https://github.com/user-attachments/assets/2eaeee36-b542-47d1-b95b-59b6dc2b86d0)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#kitchen'
    name: Kitchen
    icon: mdi:fridge
    entity: light.kitchen
```

**Informations (please complete the following information):**  
 - OS: Windows/Android
 - Browser/App: Chrome
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.9.3

**Additional context**  

Thank you! 🍻
