### ISSUE TITLE
Entity name not displayed on Firefox

### ISSUE THREAD

**Issue by Krusenbaum** [Clooos/Bubble-Card#868]
**Describe the bug**  
Entity name not visible in Firefox (Chrome + Safari works).

**To Reproduce**  
1. Use the YAML code below
2. Open dashboard in Firefox (latest stable build)

**Expected behavior**  
The entity name "Scenes" should be visible and the sub-buttons should fit.

**Screenshots**  
![image](https://github.com/user-attachments/assets/f493f93f-8247-4518-9c02-33bec910aba0)

**YAML**  
```yaml
type: custom:bubble-card
card_type: button
card_layout: large
show_name: true
show_icon: false
scrolling_effect: false
name: Scenes
icon: mdi:lightbulb-group-outline
tap_action:
  action: none
sub_button:
  - entity: scene.illuminate
    tap_action:
      action: toggle
    name: Illuminate
    show_attribute: false
  - entity: scene.afternoon
    tap_action:
      action: toggle
    name: Afternoon
  - entity: scene.evening
    tap_action:
      action: toggle
    name: Evening
  - entity: scene.late_night
    tap_action:
      action: toggle
    name: Late Night
  - entity: scene.night
    tap_action:
      action: toggle
    name: Night
  - entity: scene.away
    tap_action:
      action: toggle
    name: Away
entity: scene.away
button_type: name
```

**Informations (please complete the following information):**  
 - OS: MacOS 15.0.1
 - Browser/App: Firefox
 - Bubble Card version: 2.3.0-beta-3
 - Home Assistant version: latest-stable

**Additional context**  
Works well on Chrome + Safari
