### ISSUE TITLE
Clicking outside of popup onto custom:grid-layout does not dismiss popup

### ISSUE THREAD

**Issue by TinyShark** [Clooos/Bubble-Card#88]
My Dashboards are created with css grid using layout-card (https://github.com/thomasloven/lovelace-layout-card).

When using bubble-card popups, I cannot dismiss the popup when clicking outside of it. This is only the case where a css grid is defined. If I click outside of all grid areas, the popup will dismiss was expected.

 </br></br>

<img width="1384" alt="Screenshot 2023-10-02 at 10 32 37" src="https://github.com/Clooos/Bubble-Card/assets/23080224/928ee81c-2e0e-402c-9d4f-c1ccb9034446">

 
 
 </br></br></br>
Test Dashboard to simplify/explain what the issue is:

```
title: Test Pop
path: testpop
panel: false
icon: mdi:lamp
badges: []
type: custom:grid-layout
layout:
  grid-template-columns: 1fr 200px 200px 1fr
  grid-template-rows: 100px 100px 100px

cards:
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        hash: "#testpop"
      - type: button
        entity: sun.sun
  - type: custom:bubble-card
    card_type: horizontal-buttons-stack
    1_name: testpop
    1_icon: mdi:account
    1_link: "#testpop"
    1_entity: sun.sun

```
