### ISSUE TITLE
Unable to change temperature consistently. 

### ISSUE THREAD

**Issue by pavandave** [Clooos/Bubble-Card#881]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
The temperature change does not always take. I can hit the + or - on climate multiple times and sometimes it will only register a change one time and then no additional inputs are taken. Ex setting from 71 to 73, it will not register the clicks after it changes the first time. 
Bubble Card v2.3.0-beta.3 

**To Reproduce**  
1. Enable climate card
2. Click on + or - a few times
3. See either no change or only a single change.

**Expected behavior**  
I expect the + / - taps to increment or decrement the set temperature.

**Screenshots**  
n/a

**YAML**  
If applicable, add any relevant YAML code.

```yaml
    type: custom:bubble-card
    card_type: climate
    entity: climate.downstairs_thermostat
    sub_button:
      - entity: sensor.indoor_temperature
        show_name: false
        name: Current
        show_state: true
        state_background: false
        show_icon: false
        show_background: false
        show_attribute: false
      - name: HVAC modes menu
        select_attribute: hvac_modes
        show_arrow: false
      - name: Set
        show_attribute: true
        attribute: temperature
        icon: mdi:thermometer
        state_background: false
        show_state: false
        show_name: false
        show_icon: true
    name: Thermostat
    double_tap_action:
      action: none
    hold_action:
      action: none
    show_attribute: true
    attribute: current_temperature
    show_state: true
    force_icon: false
    show_last_changed: false
```

**Information (please complete the following information):**  
 - OS: W11 and Android
 - Browser/App: Firefox (W11), Android App (2024.10.3-full)
 - Bubble Card version:  Bubble Card v2.3.0-beta.3 
 - Home Assistant version: 2024.10.3
