### ISSUE TITLE
Old brightness is shown while light is Off

### ISSUE THREAD

**Issue by biva** [Clooos/Bubble-Card#904]
Congrats on your fantastic work and results! This is really amazing.

**Describe the bug**  
I have a slider button to manage a light, and the old brightness value remains displayed while the light is Off

**To Reproduce**  
1. Create a slider button to manage a light
2. Activate Attribute (but not State)
3. Action on tap: Toggle
3. Turn on the light, for example to 35% brightness
4. This displays 35% below the name of the light
4. Turn it Off (click on the icon to toggle the light)
5. 35% is still displayed

**Expected behavior**  
The attribute should disappear

**Screenshots**  
![image](https://github.com/user-attachments/assets/582058eb-9205-4d60-8fc1-0f57be543b96)

**YAML**  
```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: light.dimmer_2_salon_escalier
show_state: false
show_attribute: true
attribute: brightness
tap_action:
  action: toggle
hold_action:
  action: more-info
layout_options:
  grid_columns: 2
  grid_rows: 1
card_layout: large
sub_button: []
name: Escalier
scrolling_effect: false
```

**Workaround**  
If the State is displayed, then we see "Off" instead of 37%
![image](https://github.com/user-attachments/assets/dad31af7-71ed-4f79-931f-0cb050cf25c3)

```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: light.dimmer_2_salon_escalier
show_state: true
show_attribute: true
attribute: brightness
tap_action:
  action: toggle
hold_action:
  action: more-info
layout_options:
  grid_columns: 2
  grid_rows: 1
card_layout: large
sub_button: []
name: Escalier
scrolling_effect: false
show_last_changed: false
```

Thank you! 🍻
