### ISSUE TITLE
[iOS] Bubble Card Button scrolling text becomes larger on click 

### ISSUE THREAD

**Issue by rairulyle** [Clooos/Bubble-Card#912]
**Describe the bug**  
I have a bubble card button that sometimes have a long text so I have to enable the option scrolling text to it. Whenever I click on it, the scrolling text becomes big. This only happens on iOS regardless of via App/Browser.

**To Reproduce**  
1. Create a card with a very long state text and then make it scrolling.
2. Click on it.
3. You'll see that the scrolling text becomes larger

**Expected behavior**  
It should not cause any font changes.

**Screenshots**  

https://github.com/user-attachments/assets/207e399b-cae2-4672-8c5c-8ca527753fc2

**YAML**  
```yaml
type: custom:bubble-card
card_type: button
button_type: state
name: Upcoming TV Show
icon: mdi:youtube-tv
card_layout: normal
show_attribute: false
show_last_changed: false
show_name: true
tap_action:
  action: navigate
  navigation_path: "#upcoming-tv"
button_action:
  tap_action:
    action: navigate
    navigation_path: "#upcoming-tv"
sub_button: []
scrolling_effect: true
```

**Informations:**  
 - OS: iOS 18.1
 - Browser: Arc/Chromium
 - Bubble Card version: 2.3.0-beta5
  - Home Assistant version: 2024.11.0
