### ISSUE TITLE
Horizonal button card not loading images

### ISSUE THREAD

**Issue by Daniel-dev22** [Clooos/Bubble-Card#915]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

I tried to follow the readme for using background images on a horizontal button. My path is correct I triple checked that and I use the same path for mushroom card images with no issues.

Am I doing something wrong?

**To Reproduce**  

**Expected behavior**  

A background image to appear for each sub button

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: horizontal-buttons-stack
    1_link: "#ansible_traefik_routers"
    1_name: Traefik Routers
    styles: |-
      .bubble-sub-button-1 {
        background-image: url("/local/icons/custom_icons/traefik_proxy.png");
        background-size: cover;
      }
      .bubble-sub-button-2 {
        background-image: url("/local/icons/custom_icons/traefik_proxy.png");
        background-size: cover;
      }
    hide_gradient: true
    2_name: Traefik Entrypoints
    2_link: "#ansible"

```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻
