### ISSUE TITLE
v2.3.0-beta.5 Climate Card Shows Multiple Set Temperature Groups

### ISSUE THREAD

**Issue by zanix** [Clooos/Bubble-Card#917]
**Describe the bug**  
Climate card shows set temperature, target_temp_high, and target_temp_low in heat mode.

Thermostat is an Ecobee using the Homekit integration. This also happens when using the (cloud based) Ecobee integration.

**To Reproduce**  
1. Create a bubble climate card
2. Choose an Ecobee thermostat (either homekit or cloud integration)
3. Card shows 3 temperature sub-button groups

**Expected behavior**  
* In heat or cool mode, I expect to only show 1 temperature sub-button group
* In heat/cool mode, I expect to see 2 temperature sub-button groups

**Screenshots**  
![image](https://github.com/user-attachments/assets/5d49c723-6677-4e83-b339-f8a29bfe4033)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: climate
entity: climate.ecobee
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: false
    show_arrow: false
```

**Informations (please complete the following information):**  
 - OS: Windows, Android
 - Browser/App: Chrome, Home Assistant Companion App
 - Bubble Card version: v2.3.0-beta.5
 - Home Assistant version: 2024.11.1

**Additional context**  
Thermostat state and attributes

state:
 `heat`

(homekit) attributes:

```yaml
hvac_modes: off, heat, cool, heat_cool
min_temp: 45
max_temp: 92
min_humidity: 20
max_humidity: 50
fan_modes: on, auto
current_temperature: 68
temperature: 68
target_temp_high: null
target_temp_low: null
current_humidity: 34
humidity: 36
fan_mode: auto
hvac_action: fan
friendly_name: Ecobee
supported_features: 399
```

(cloud) attributes:

```yaml
hvac_modes: heat_cool, heat, cool, off
min_temp: 44.6
max_temp: 95
target_temp_step: 0.5
fan_modes: auto, on
preset_modes: home, away, sleep, away_indefinitely
current_temperature: 68.2
temperature: 68
target_temp_high: null
target_temp_low: null
current_humidity: 34
fan_mode: auto
hvac_action: fan
preset_mode: home
fan: on
climate_mode: Home
equipment_running: fan
fan_min_on_time: 30
```
