### ISSUE TITLE
v2.3.0-beta.5 Slider card with 'preset_modes' sub-button does not actually set the preset

### ISSUE THREAD

**Issue by qnimbus** [Clooos/Bubble-Card#920]
**Describe the bug**  
When selecting and activating a preset (e.g. 'Medium' or 'High'), the preset for the fan entity does not get set.

**Expected behavior**  
The fan entity should be set to the selected preset.

**Screenshots**  
![image](https://github.com/user-attachments/assets/dfcb74ae-1990-4dbd-9946-995d7f9a272d)

**Additional info**
This issue also occurred when I was using v2.3.0-beta.3, but I upgraded to v2.3.0-beta.5 to see if the issue would be resolved.

**Informations (please complete the following information):**  
 - OS: Windows 11, Android
 - Browser/App: Edge, Home Assistant Mobile App
 - Bubble Card version: v2.3.0-beta.5
 - Home Assistant version: 2024.11.1

**Comment by Clooos** [comment]
Hi, can you provide your YAML for this card?

**Comment by QNimbus** [comment]
This is the yaml for the card in question:

```yaml
- type: custom:bubble-card
  card_type: button
  button_type: slider
  icon: fapro:fan
  show_last_changed: false
  name: Mechanische ventilatie
  slider_live_update: false
  show_attribute: true
  attribute: percentage
  sub_button:
    - icon: ""
      name: Preset
      show_arrow: true
      show_attribute: false
      show_state: false
      show_name: true
      show_icon: false
      entity: fan.mv_itho_468_cve_s_eco_he_fan
      select_attribute: preset_modes
      show_last_changed: false
      show_background: true
      state_background: false
```
