### ISSUE TITLE
Unresponsive bubble-temperature-container (Daikin Skyport)

### ISSUE THREAD

**Issue by TobiTenno** [Clooos/Bubble-Card#922]
**Describe the bug**  
When in `auto` HVAC Mode, the `.bubble-temperature-container` is present but uncontrollable.

**To Reproduce**  
1. Add a `Daikin Skyport` (in my case, an Amana Smart Thermostat) integration & thermostat
2. Add a climate card for the above
3. Configuration:
```yaml
type: custom:bubble-card
card_type: climate
entity: climate.amana
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: false
    show_arrow: false
icon: mdi:home-thermometer-outline
card_layout: large
```
![image](https://github.com/user-attachments/assets/d44b07e7-7c34-4cf2-bc83-123f6c3d320b)

4. Attempt to change temperature on first temperature control (`.bubble-temperature-container`)
5. See error
![image](https://github.com/user-attachments/assets/a81f97f3-b0fb-4db2-917b-c5ce15593c5b)

**Expected behavior**  
`.bubble-temperature-container` should not show, or should adjust temperature somehow.

**Screenshots**  
Included in `To Reproduce`

**YAML**  
```yaml
type: custom:bubble-card
card_type: climate
entity: climate.amana
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: false
    show_arrow: false
icon: mdi:home-thermometer-outline
card_layout: large
```

**Informations (please complete the following information):**  
 - OS: Linux, macOS 15.1, Windows 11
 - Browser/App: brave, chrome
 - Bubble Card version: [v2.3.0-beta.5](https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.5)
 - Home Assistant version: 2024.11.1

**Additional context**  
Workaround for hiding temperature control in auto mode:
```yaml
styles: |-
  .bubble-temperature-container {
    display: ${ hass.states['climate.amana'].state === 'auto' ? 'none' : 'inherit'  };
  }
```
