### ISSUE TITLE
v2.3.0-beta.6 Climate card HVAC Sub Button Icons doesn't change

### ISSUE THREAD

**Issue by NdR91** [Clooos/Bubble-Card#924]
First of all, as usual, I want to thanks @Clooos for this great card.
Your work is really appreciated.

**Describe the bug**  
When specifying the Icon of the HVAC sub button, the card seems to ignore it and keeping the default one (mdi:fire)

**To Reproduce**  
1. Create a new Popup
2. Add a Climate Bubble Card
3. Change the default sub-button icon

**Expected behavior**  
A changed icon based on the previous select.

**Screenshots**  
<img width="995" alt="SCR-20241116-jicr" src="https://github.com/user-attachments/assets/e0ec099b-0b53-43e0-b009-4037e7cd3e20">

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#climate"
    button_type: name
    name: Termostati
    icon: mdi:home-thermometer
  - type: custom:bubble-card
    card_type: climate
    entity: climate.piano_camere
    sub_button:
      - entity: switch.termostato_p1
        name: Stato
        icon: mdi:fire
      - name: HVAC modes menu
        select_attribute: hvac_modes
        state_background: false
        show_arrow: false
        icon: mdi:power
        show_icon: true
    icon: mdi:home-floor-1
    show_state: false
    show_attribute: true
    attribute: hvac_action
```

**Informations (please complete the following information):**  
 - OS: iOS, MacOS
 - Browser/App: Chrome, Safari
 - Bubble Card version: v2.3.0-beta.6
 - Home Assistant version: 2024.11.2

Thank you! 🍻
