### ISSUE TITLE
v2.3.0-beta.7 Climate card background no change between off and heat

### ISSUE THREAD

**Issue by nzottmann** [Clooos/Bubble-Card#933]
My thermostat only support the modes off and heat. In beta.6 the card looks like expected when in mode heat:
![image](https://github.com/user-attachments/assets/1a67cf70-4213-4f0c-ac0e-f2745241a957)

In beta.7 the background color does not change between off and heat:
off:
![image](https://github.com/user-attachments/assets/21607638-7d11-40af-bca9-d79b93bfdec4)
heat:
![image](https://github.com/user-attachments/assets/32d8f827-fdda-45bd-adf7-22e72807e35c)

**Comment by nzottmann** [comment]
Thank you for the reply. I removed the HACS-installed bubble card and used the downloaded .js from the link. Unfortunately, this does not change the behavior, the card is still not colored. Current temperature is 20°, target 23°:

![image](https://github.com/user-attachments/assets/6aba49e0-c8c3-4383-8348-56281757592a)

Here is the developer info, in case this helps:
```yaml
hvac_modes:
  - "off"
  - heat
min_temp: 8
max_temp: 28
preset_modes:
  - none
  - Energy heat
  - Full power
  - Manufacturer specific
current_temperature: 20
temperature: 23
preset_mode: none
friendly_name: "Bad Heizung "
supported_features: 401
```
