### ISSUE TITLE
entity_picture doesnt work

### ISSUE THREAD

**Issue by rmxs** [Clooos/Bubble-Card#939]
**Describe the bug**  
I have set in configuration file a custom image for my entity but doesnt work on Climate card.

**To Reproduce**  
Set a custom entity image .png
create a climate card and select the entity
the entity icon is the default icon set and not the image from the configuration file.

**Expected behavior**  

**Screenshots**  
![image](https://github.com/user-attachments/assets/386c7fa0-ff78-44c6-9f85-33f1fa7edd8f)

Code in configuration

```
homeassistant:

  customize:
    # Add an entry for each entity that you want to overwrite.
    climate.ac_livingroom:
      entity_picture: /local/icons/air-conditioner.png
    climate.ac_bedroom:

```

Code for the card

```
type: custom:bubble-card
card_type: climate
entity: climate.ac_livingroom
sub_button:
  - name: ""
    select_attribute: hvac_modes
    show_arrow: false
    show_attribute: false
    show_state: false
    show_background: true
    show_icon: true
    state_background: true
    show_name: false
  - entity: climate.ac_livingroom
    show_icon: true
    select_attribute: fan_modes
    show_arrow: false
    show_name: false
    show_state: false
force_icon: false
show_icon: true
show_attribute: true
attribute: current_temperature
card_layout: large
scrolling_effect: true
show_last_changed: false
show_state: false
icon: ""
show_name: true
```

**Informations (please complete the following information):**  
 - OS: Latest 11
 - Browser/App:Chrome
 - Bubble Card version: 2.3.0 B7
 - Home Assistant version: 2024.11.2

Using other climate card the custom image as icon works without any issue
![image](https://github.com/user-attachments/assets/40770760-d022-4e21-bac7-2961d16d8df0)

Thank you! 🍻
