### ISSUE TITLE
entity_state option has no impact

### ISSUE THREAD

**Issue by panhans** [Clooos/Bubble-Card#95]
Hey,

I just want to show the entity state but the option entity_state has no impact:

```
-  type: custom:bubble-card
   card_type: button
   button_type: slider
   tap_action:
     action: toggle
   entity: light.wohnzimmer_ambient_lights
   entity_state: true
```
