### ISSUE TITLE
2.3.0-Beta 8 climate card layout issue 

### ISSUE THREAD

**Issue by Daniel-dev22** [Clooos/Bubble-Card#972]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

When I click on the mode the selector is very small and difficult to navigate.

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

![Screenshot_20241129_181346_Home Assistant](https://github.com/user-attachments/assets/01483a1e-ba71-40c0-a9a6-2fd1338ba9a2)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: climate
entity: climate.hvac_thermostat
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    state_background: false
    show_arrow: false
show_icon: true
scrolling_effect: false
styles: |-
  .bubble-icon-container: {
    background-color: transparent;
  }
  .bubble-climate-container: {
    background-color: transparent;
  }
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻
