### ISSUE TITLE
Current temperature?

### ISSUE THREAD

**Issue by scargill** [Clooos/Bubble-Card#974]
Clim,ate card - as I can't use a template on the name I can't see how to show the current temperature - am I missing something?

**Comment by ianperrin** [comment]
I’m using displaying the current temperature below the name, using `show_attribute: true` and `attribute: current_temperature`

perhaps this might work for you?

```
  - type: custom:bubble-card
    card_type: climate
    entity: climate.kitchen
    card_layout: large
    show_attribute: true
    attribute: current_temperature
    show_state: false
```

**Comment by Clooos** [comment]
This is the best way indeed!

**Comment by scargill** [comment]
> I’m using displaying the current temperature below the name, using `show_attribute: true` and `attribute: current_temperature`
> 
> perhaps this might work for you?
> 
> ```
>   - type: custom:bubble-card
>     card_type: climate
>     entity: climate.kitchen
>     card_layout: large
>     show_attribute: true
>     attribute: current_temperature
>     show_state: false
> ```

Thank you so much - right - I now have the current temperature . Hopefully this will help others. Marvellous.
```
type: custom:bubble-card
name: Office aircon
card_type: climate
show_attribute: true
attribute: current_temperature
entity: climate.condizionatore
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    show_arrow: false
    state_background: true
hold_action:
  action: more-info
```
