### ISSUE TITLE
`${card.querySelector()} ` not working on initial page load, but works after a state change on any bubble card

### ISSUE THREAD

**Issue by quincarter** [Clooos/Bubble-Card#975]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
When the same `hass.states[].state` is used multiple times in a style template, the second time doesn't always resolve properly. For example when I try to listen to the do not disturb sensor on my phone, i want to change the bubble button color and set the text for the bubble name to say `Quin is on DND` - This works if i am already on the home assistant dashboard then it works fine, but when i reload the page, the color resolves but the text does not, and it shows my default name variable.

*****EDIT --- I think the bug has to do with the `card.querySelector()` and when it is going off. The element isn't selectable on the initial page load. That's why the colors are working but not the nested JS stuff. 

**Expected behavior**  
`*.querySelector()` should work on initial load so that button states and names can be resolved for anything custom that is being overwritten for customization

**Screenshots**  
<img width="1018" alt="Screenshot 2024-12-01 at 6 43 17 PM" src="https://github.com/user-attachments/assets/86b04a56-6318-4a4d-b78f-a394ed9d84e7">

**YAML**  
```css
.bubble-button-background {
    opacity: 0.5 !important;
    background-color: ${state === 'home' ? 'green' : 'red'} !important;
  }

.bubble-button-background {
    opacity: 0.5 !important;
    background-color: ${hass.states['sensor.quin_s_pixel_9_pro_xl_do_not_disturb_sensor'].state === 'priority_only' ? 'lightgrey' : ''} !important;
  }

.bubble-button-background {
    opacity: 0.5 !important;
    background-color: ${hass.states['binary_sensor.quin_s_pixel_9_pro_xl_android_auto'].state === 'on' ? 'rebeccapurple' : ''} !important;
  }

.bubble-sub-button {
    background-color: transparent !important;
  }

.bubble-sub-button-1 {
    display: ${(hass.states['sensor.quin_s_pixel_9_pro_xl_battery_state'].state === 'charging' || hass.states['sensor.quin_s_pixel_9_pro_xl_battery_state'].state === 'full')  && hass.states['binary_sensor.quin_s_pixel_9_pro_xl_android_auto'].state !== 'on' ? '' : 'none'} !important;
  }

.bubble-sub-button-2 {
    display: ${hass.states['binary_sensor.quin_s_pixel_9_pro_xl_android_auto'].state === 'on' ? '' : 'none'} !important;
  }

/* this one doesn't ever fire on initial load unless another change is fired */
${hass.states['sensor.quin_s_pixel_9_pro_xl_do_not_disturb_sensor'].state === 'priority_only' ? card.querySelector('.bubble-name').innerText = "Quin is on DND" : card.querySelector('.bubble-name').innerText = "Quin"}
```

### Full button code
```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: person.quin_carter
styles: >-
  .bubble-button-background {
      opacity: 0.5 !important;
      background-color: ${state === 'home' ? 'green' : 'red'} !important;
    }

  .bubble-button-background {
      opacity: 0.5 !important;
      background-color: ${hass.states['sensor.quin_s_pixel_9_pro_xl_do_not_disturb_sensor'].state === 'priority_only' ? 'lightgrey' : ''} !important;
    }

  .bubble-button-background {
      opacity: 0.5 !important;
      background-color: ${hass.states['binary_sensor.quin_s_pixel_9_pro_xl_android_auto'].state === 'on' ? 'rebeccapurple' : ''} !important;
    }

  .bubble-sub-button {
      background-color: transparent !important;
    }

  .bubble-sub-button-1 {
      display: ${(hass.states['sensor.quin_s_pixel_9_pro_xl_battery_state'].state === 'charging' || hass.states['sensor.quin_s_pixel_9_pro_xl_battery_state'].state === 'full')  && hass.states['binary_sensor.quin_s_pixel_9_pro_xl_android_auto'].state !== 'on' ? '' : 'none'} !important;
    }

  .bubble-sub-button-2 {
      display: ${hass.states['binary_sensor.quin_s_pixel_9_pro_xl_android_auto'].state === 'on' ? '' : 'none'} !important;
    }

  ${hass.states['sensor.quin_s_pixel_9_pro_xl_do_not_disturb_sensor'].state ===
  'priority_only' ? card.querySelector('.bubble-name').innerText = "Quin is on
  DND" : card.querySelector('.bubble-name').innerText = "Quin"}
name: ""
show_attribute: false
show_last_changed: true
sub_button:
  - entity: sensor.quin_s_pixel_9_pro_xl_battery_level
    show_state: true
    show_attribute: false
    show_last_changed: false
    show_name: false
    show_icon: true
    icon: ""
  - entity: binary_sensor.quin_s_pixel_9_pro_xl_android_auto
    icon: mdi:car
button_action:
  tap_action:
    action: navigate
    navigation_path: "#person-quin"
card_layout: large

```

**Informations (please complete the following information):**  
 - OS: Android and MacOS on Chrome
 - Browser/App: Chrome
 - Bubble Card version: 2.3.0
 - Home Assistant versions

| Module    | Version |
| -------- | ------- |
| Core  | 2024.11.3    |
| Supervisor | 2024.11.4    |
| Operating System | 13.2   |
| Frontend | 20241106.2   |

**Comment by quincarter** [comment]
Followup question. Can i set JS variables in the style template and reuse them?

**Comment by quincarter** [comment]
If i manually fire off a state change of some kind after the elements are on the screen, the items update. I think there is something wrong with how the styles are appended and looking for the `card.querySelector()` - i think it is returning null or undefined because the element isn't loaded quite yet. In LitElement i would just do everything in `firstUpdated()` and wait for the items to be appended to the screen. But looks like everything here is in connectedCallback because it is just an HTMLElement. So i think the solution would be to wait for the element to be available for the `querySelector` to work properly on the initial load.

**Comment by quincarter** [comment]
Video demo showing what is happening:
https://drive.google.com/file/d/1Jgd185XdMphV8jw1n9dS7wTdALtPFJjs/view?usp=sharing

**Comment by quincarter** [comment]
Update - when i only try to update the `.bubble-name` innerText on a single test button, i get this error:

<img width="489" alt="image" src="https://github.com/user-attachments/assets/62d113eb-30b4-4817-86c6-3fbfdf90f3af">


## My YAML
```yaml
type: custom:bubble-card
card_type: button
entity: light.my_custom_lamp
icon: mdi:lamp
show_state: true
show_last_changed: true
styles: |
  ${card.querySelector('.button-name').innerText = 'Testing123'}

```
