### ISSUE TITLE
Custom tap_action on sub-button not working

### ISSUE THREAD

**Issue by TechHutTV** [Clooos/Bubble-Card#997]
Hey I've been at this for a bit, not sure if it's a bug or just not a possible function. Trying to make buttons with preset cover positions. I press the button and nothing happens.

https://www.home-assistant.io/integrations/cover/

```
type: custom:bubble-card
card_type: cover
entity: cover.bedroom_window_shade
name: Bedroom
icon_open: mdi:roller-shade
icon_close: mdi:roller-shade-closed
show_state: false
show_last_changed: false
show_attribute: true
attribute: current_position
card_layout: large-2-rows
hold_action: {}
rows: 1
sub_button:
  - entity: cover.bedroom_window_shade
    name: "50"
    show_name: true
    show_icon: false
    tap_action:
      action: cover.set_cover_position
      target:
        entity_id: cover.bedroom_window_shade
      data:
        position: 50
```

**Comment by TechHutTV** [comment]
Sorry, figured it out!

```
sub_button:
  - entity: cover.bedroom_window_shade
    name: "50"
    show_icon: false
    show_name: true
    tap_action:
      action: call-service
      target:
        entity_id: cover.bedroom_window_shade
      data:
        position: 50
      service: cover.set_cover_position
```
